<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Unidad 6 Análisis Descriptivo inicial | Modelos Estadísticos</title>
  <meta name="description" content="Unidad 6 Análisis Descriptivo inicial | Modelos Estadísticos" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Unidad 6 Análisis Descriptivo inicial | Modelos Estadísticos" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Unidad 6 Análisis Descriptivo inicial | Modelos Estadísticos" />
  
  
  



<meta name="date" content="2022-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="procesado-inicial.html"/>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>
<li><a href="./">J. Morales y A.M. Mayoral</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html"><i class="fa fa-check"></i>Antes de empezar</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#conceptos-básicos-del-diseño-experimental"><i class="fa fa-check"></i>Conceptos básicos del diseño experimental</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#objetivo-del-diseño-experimental"><i class="fa fa-check"></i>Objetivo del diseño experimental</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#población-y-muestra"><i class="fa fa-check"></i>Población y muestra</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#medidas-y-escalas-de-medida"><i class="fa fa-check"></i>Medidas y escalas de medida</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#parámetros-poblacionales-y-estadísticos"><i class="fa fa-check"></i>Parámetros poblacionales y estadísticos</a></li>
</ul></li>
<li><a href="antes-de-empezar.html#primeros-pasos-con-r-y-rstudio">Primeros pasos con <code>R</code> y <code>RStudio</code></a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#instalación-y-puesta-en-marcha"><i class="fa fa-check"></i>Instalación y puesta en marcha</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#informes-prediseñados"><i class="fa fa-check"></i>Informes prediseñados</a></li>
<li><a href="antes-de-empezar.html#librerías-de-r-necesarías">Librerías de <code>R</code> necesarías</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#conceptos-básicos"><i class="fa fa-check"></i><b>1.1</b> Conceptos básicos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#objetivo-del-diseño-experimental-1"><i class="fa fa-check"></i><b>1.1.1</b> Objetivo del diseño experimental</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#población-y-muestra-1"><i class="fa fa-check"></i><b>1.1.2</b> Población y muestra</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#medidas-y-escalas-de-medida-1"><i class="fa fa-check"></i><b>1.1.3</b> Medidas y escalas de medida</a></li>
<li class="chapter" data-level="1.1.4" data-path="intro.html"><a href="intro.html#parámetros-poblacionales-y-estadísticos-1"><i class="fa fa-check"></i><b>1.1.4</b> Parámetros poblacionales y estadísticos</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>1.2</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="aed.html"><a href="aed.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos</a></li>
<li class="chapter" data-level="3" data-path="objetivos.html"><a href="objetivos.html"><i class="fa fa-check"></i><b>3</b> Objetivos</a></li>
<li class="chapter" data-level="4" data-path="variabilidad.html"><a href="variabilidad.html"><i class="fa fa-check"></i><b>4</b> Variabilidad</a></li>
<li class="chapter" data-level="5" data-path="procesado-inicial.html"><a href="procesado-inicial.html"><i class="fa fa-check"></i><b>5</b> Procesado inicial</a>
<ul>
<li class="chapter" data-level="5.1" data-path="procesado-inicial.html"><a href="procesado-inicial.html#operaciones-con-sujetos"><i class="fa fa-check"></i><b>5.1</b> Operaciones con sujetos</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="procesado-inicial.html"><a href="procesado-inicial.html#filtrado"><i class="fa fa-check"></i><b>5.1.1</b> Filtrado</a></li>
<li class="chapter" data-level="5.1.2" data-path="procesado-inicial.html"><a href="procesado-inicial.html#ordenación"><i class="fa fa-check"></i><b>5.1.2</b> Ordenación</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="procesado-inicial.html"><a href="procesado-inicial.html#trabajando-con-variables"><i class="fa fa-check"></i><b>5.2</b> Trabajando con variables</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="procesado-inicial.html"><a href="procesado-inicial.html#selección"><i class="fa fa-check"></i><b>5.2.1</b> Selección</a></li>
<li class="chapter" data-level="5.2.2" data-path="procesado-inicial.html"><a href="procesado-inicial.html#creación"><i class="fa fa-check"></i><b>5.2.2</b> Creación</a></li>
<li class="chapter" data-level="5.2.3" data-path="procesado-inicial.html"><a href="procesado-inicial.html#creación-de-factores"><i class="fa fa-check"></i><b>5.2.3</b> Creación de factores</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="procesado-inicial.html"><a href="procesado-inicial.html#reuniendo-los-datos"><i class="fa fa-check"></i><b>5.3</b> Reuniendo los datos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html"><i class="fa fa-check"></i><b>6</b> Análisis Descriptivo inicial</a>
<ul>
<li class="chapter" data-level="6.1" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#una-variable-factor"><i class="fa fa-check"></i><b>6.1</b> Una variable factor</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#resúmenes-numéricos"><i class="fa fa-check"></i><b>6.1.1</b> Resúmenes numéricos</a></li>
<li class="chapter" data-level="6.1.2" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#visualización-gráfica"><i class="fa fa-check"></i><b>6.1.2</b> Visualización gráfica</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#una-variable-numérica"><i class="fa fa-check"></i><b>6.2</b> Una variable numérica</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#resúmenes-numéricos-1"><i class="fa fa-check"></i><b>6.2.1</b> Resúmenes numéricos</a></li>
<li class="chapter" data-level="6.2.2" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#visualización-gráfica-1"><i class="fa fa-check"></i><b>6.2.2</b> Visualización gráfica</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#dos-variables-categóricas"><i class="fa fa-check"></i><b>6.3</b> Dos variables categóricas</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#resúmenes-numéricos-2"><i class="fa fa-check"></i><b>6.3.1</b> Resúmenes numéricos</a></li>
<li class="chapter" data-level="6.3.2" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#visualización-gráfica-2"><i class="fa fa-check"></i><b>6.3.2</b> Visualización gráfica</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#categórica-vs-numérica"><i class="fa fa-check"></i><b>6.4</b> Categórica vs Numérica</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#resúmenes-numéricos-3"><i class="fa fa-check"></i><b>6.4.1</b> Resúmenes numéricos</a></li>
<li class="chapter" data-level="6.4.2" data-path="análisis-descriptivo-inicial.html"><a href="análisis-descriptivo-inicial.html#visualización-gráfica-3"><i class="fa fa-check"></i><b>6.4.2</b> Visualización gráfica</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-descriptivo-inicial" class="section level1" number="6">
<h1><span class="header-section-number">Unidad 6</span> Análisis Descriptivo inicial</h1>
<p>Esta sección muestra los procedimientos de análisis estadístico descriptivo para el estudio de una o dos variables de tipo numérico y/o categórico. Las situaciones que se plantean son:</p>
<ul>
<li>Una variable de tipo factor.</li>
<li>Una variable de tipo numérico.</li>
<li>Dos variables categóricas.</li>
<li>Dos variables numéricas.</li>
<li>Una variable categórica y una variable numérica.</li>
</ul>
<p>Este es el primer paso del EDA y sirve al investigador para plantear o responder las primeras preguntas de interés sobre sus datos. Para ilustrar los procedimientos utilizaremos el conjunto de datos <code>storms</code> de la librería <code>nasaweather</code>. Estos datos son un subconjunto de la base de datos de la NASA sobre los huracanes en el Atlántico Norte (<a href="http://www.nhc.noaa.gov/data/#hurdat">NOAA</a>). Los datos incluyen las posiciones y atributos de 198 tormentas tropicales, medidas cada seis horas durante la vida de la tormenta. Las variables registradas son:</p>
<ul>
<li><code>name</code>: Nombre de la tormenta</li>
<li><code>year</code>, <code>month</code>, <code>day</code>: Año, mes y día del informe de la tormenta</li>
<li><code>hour</code>: Hora del informe (en UTC)</li>
<li><code>lat</code>, <code>long</code>: Latitud y longitud de la tormenta</li>
<li><code>pressure</code>: Presión atmosférica en el centro de la tormenta (en milibares)</li>
<li><code>wind</code>: Máxima velocidad sostenida de la tormenta (en nudos)</li>
<li><code>type</code>: Clasificación de la tormenta (Tropical Depression, Tropical Storm, or Hurricane)</li>
<li><code>seasday</code>: día de la temporada de tormentas</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="análisis-descriptivo-inicial.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nasaweather)</span>
<span id="cb61-2"><a href="análisis-descriptivo-inicial.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Guardamos los datos en un nuevo objeto</span></span>
<span id="cb61-3"><a href="análisis-descriptivo-inicial.html#cb61-3" aria-hidden="true" tabindex="-1"></a>storm <span class="ot">&lt;-</span> nasaweather<span class="sc">::</span>storms </span>
<span id="cb61-4"><a href="análisis-descriptivo-inicial.html#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Estructura de los datos</span></span>
<span id="cb61-5"><a href="análisis-descriptivo-inicial.html#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(storm)</span></code></pre></div>
<p>Dado que las variables <code>year</code> y <code>month</code> no vienen definidas como factores, el primer paso es convertirlas en factores. En este caso vamos a utilizar una versión diferente de la vista en el tema anterior para convertir varaibles enteras a factores.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="análisis-descriptivo-inicial.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Primero creamos el factor año</span></span>
<span id="cb62-2"><a href="análisis-descriptivo-inicial.html#cb62-2" aria-hidden="true" tabindex="-1"></a>storm<span class="sc">$</span>year_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(storm<span class="sc">$</span>year)</span>
<span id="cb62-3"><a href="análisis-descriptivo-inicial.html#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Asignamos los niveles</span></span>
<span id="cb62-4"><a href="análisis-descriptivo-inicial.html#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(storm<span class="sc">$</span>year_f) <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="dv">1995</span><span class="sc">:</span><span class="dv">2000</span>)</span>
<span id="cb62-5"><a href="análisis-descriptivo-inicial.html#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahora el factor mes</span></span>
<span id="cb62-6"><a href="análisis-descriptivo-inicial.html#cb62-6" aria-hidden="true" tabindex="-1"></a>storm<span class="sc">$</span>month_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(storm<span class="sc">$</span>month)</span>
<span id="cb62-7"><a href="análisis-descriptivo-inicial.html#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Asignamos los niveles</span></span>
<span id="cb62-8"><a href="análisis-descriptivo-inicial.html#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(storm<span class="sc">$</span>month_f) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;June&quot;</span>, <span class="st">&quot;July&quot;</span>, <span class="st">&quot;August&quot;</span>, <span class="st">&quot;September&quot;</span>, </span>
<span id="cb62-9"><a href="análisis-descriptivo-inicial.html#cb62-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">&quot;October&quot;</span>, <span class="st">&quot;November&quot;</span>, <span class="st">&quot;December&quot;</span>)</span>
<span id="cb62-10"><a href="análisis-descriptivo-inicial.html#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Veamos como queda el banco de datos</span></span>
<span id="cb62-11"><a href="análisis-descriptivo-inicial.html#cb62-11" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(storm)</span></code></pre></div>
<pre><code>## tibble [2,747 × 13] (S3: tbl_df/tbl/data.frame)
##  $ name    : chr [1:2747] &quot;Allison&quot; &quot;Allison&quot; &quot;Allison&quot; &quot;Allison&quot; ...
##  $ year    : int [1:2747] 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 ...
##  $ month   : int [1:2747] 6 6 6 6 6 6 6 6 6 6 ...
##  $ day     : int [1:2747] 3 3 3 3 4 4 4 4 5 5 ...
##  $ hour    : int [1:2747] 0 6 12 18 0 6 12 18 0 6 ...
##  $ lat     : num [1:2747] 17.4 18.3 19.3 20.6 22 23.3 24.7 26.2 27.6 28.5 ...
##  $ long    : num [1:2747] -84.3 -84.9 -85.7 -85.8 -86 -86.3 -86.2 -86.2 -86.1 -85.6 ...
##  $ pressure: int [1:2747] 1005 1004 1003 1001 997 995 987 988 988 990 ...
##  $ wind    : int [1:2747] 30 30 35 40 50 60 65 65 65 60 ...
##  $ type    : chr [1:2747] &quot;Tropical Depression&quot; &quot;Tropical Depression&quot; &quot;Tropical Storm&quot; &quot;Tropical Storm&quot; ...
##  $ seasday : int [1:2747] 3 3 3 3 4 4 4 4 5 5 ...
##  $ year_f  : Factor w/ 6 levels &quot;1995&quot;,&quot;1996&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ month_f : Factor w/ 7 levels &quot;June&quot;,&quot;July&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>A lo largo de cada una de las secciones siguientes se irán introduciendo las funciones y procedimientos necesarias para cada análisis en función de la variable o variables que se desean analizar.</p>
<div id="una-variable-factor" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Una variable factor</h2>
<p>En esta sección se considera cómo explorar la distribución de una variable categórica. Se presentan las descriptivas básicas y visualizaciones que son apropiadas para las variables categóricas. Para ejemplificar los procedimientos utilizaremos la variable <code>type</code> que identifica el tipo de tormenta.</p>
<p>Explorar variables categóricas es generalmente más simple que trabajar con variables numéricas porque tenemos menos respuestas posibles. La primera pregunta que nos debemos plantear es is la variables categórica es de tipo nominal u ordinal. Esto tiene un efecto relevante a la hora de presentar y visualizar la información. La variable <code>type</code> es una variable categórica de tipo ordinal debido a que las tormentas son clasificadas según su virulencia.</p>
<div id="resúmenes-numéricos" class="section level3" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Resúmenes numéricos</h3>
<p>Cuando calculamos resúmenes de variables categóricas, intentamos describir la distribución muestral de la variable mediante el recuento de ocurrencias de cada una de las posibles respuestas de la variable. Estos recuentos es lo que denominamos en estadística <strong>frecuencias absolutas</strong>. Necesitamos entender qué categorías son comunes y cuáles son raras. Asociado a dichas frecuencias absolutas podemos obtener las <strong>frecuencias relativas</strong>, o más frecuentemente los <strong>porcentajes</strong> de cada una de las posibles categorías de la variable.</p>
<p>Si <span class="math inline">\(F_i\)</span> es la frecuencia absoluta de la categoría <span class="math inline">\(i\)</span> de la variable y <span class="math inline">\(n\)</span> es el tamaño de la muestra, se define la frecuencia relativa de la categoría <span class="math inline">\(i\)</span> (<span class="math inline">\(f_i\)</span>) como:</p>
<p><span class="math display" id="eq:freqrel">\[\begin{equation} 
  f_i =\frac{F_i}{n}
  \tag{6.1}
\end{equation}\]</span></p>
<p>El porcentaje de la categoría <span class="math inline">\(i\)</span> es simplemente <span class="math inline">\(100 * f_i\)</span>. La forma más sencilla para obtener la tabla de frecuencias absoluta asociada con una variable categórica es la función <code>table()</code>.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="análisis-descriptivo-inicial.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(storm<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## 
##       Extratropical           Hurricane Tropical Depression      Tropical Storm 
##                 412                 896                 513                 926</code></pre>
<p>Para obtener los porcentajes en lugar de los conteos podemos utilizar le código siguiente</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="análisis-descriptivo-inicial.html#cb66-1" aria-hidden="true" tabindex="-1"></a>type_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(storm<span class="sc">$</span>type)</span>
<span id="cb66-2"><a href="análisis-descriptivo-inicial.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(type_counts <span class="sc">/</span> <span class="fu">sum</span>(type_counts),<span class="dv">2</span>) <span class="co"># Redondeamos a dos decimales</span></span></code></pre></div>
<pre><code>## 
##       Extratropical           Hurricane Tropical Depression      Tropical Storm 
##                0.15                0.33                0.19                0.34</code></pre>
<p>Sin embargo, hay otra opción un poco más compleja pero que nos servirá de utilidad para el resto de esta unidad y que pasamos a mostrar a continuación. Es una combinación del operador de anidamiento <code>%&gt;%</code>, de la función de agrupación (<code>group_by()</code>), de la función de resumen (<code>summarise()</code>), y de la función de conteos (<code>n()</code>).</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="análisis-descriptivo-inicial.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># banco de datos</span></span>
<span id="cb68-2"><a href="análisis-descriptivo-inicial.html#cb68-2" aria-hidden="true" tabindex="-1"></a>tabla_tipo <span class="ot">&lt;-</span> storm <span class="sc">%&gt;%</span>  <span class="co"># agrupamos por la variable factor</span></span>
<span id="cb68-3"><a href="análisis-descriptivo-inicial.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span>     <span class="co"># resumimos contando el número de casos de cada nivel del factor</span></span>
<span id="cb68-4"><a href="análisis-descriptivo-inicial.html#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>())       <span class="co"># Para calcular los porcentajes</span></span>
<span id="cb68-5"><a href="análisis-descriptivo-inicial.html#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(tabla_tipo,<span class="at">percent=</span><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>n<span class="sc">/</span><span class="fu">sum</span>(n),<span class="dv">2</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   type                    n percent
## * &lt;chr&gt;               &lt;int&gt;   &lt;dbl&gt;
## 1 Extratropical         412    15  
## 2 Hurricane             896    32.6
## 3 Tropical Depression   513    18.7
## 4 Tropical Storm        926    33.7</code></pre>
<p>Aunque esta forma es más costosa cuando tenemos únicamente una variable nos resultará de más utilidad cuando deseemos realizar análisis que involucren un mayor número de variables.</p>
<blockquote>
<p>Podemos ver que mayoritariamente se han producido Tormentas Tropicales (33.71%) y Huracanes (32.62%). Estos dos tipos suman más de dos tercios de los ecentos registrados. Por contra los eventos menos abundantes han sido las Depresiones Tropicales (18.67%) y las Extratropicales (15.00%).</p>
</blockquote>
<p>Las funciones más habituales que se utilizan con <code>summarise()</code> son:</p>
<ul>
<li>Localización: <code>mean()</code> (media), <code>median()</code> (mediana)</li>
<li>Escala: <code>sd()</code> (desviación típica), <code>IQR()</code> (rango intercuartílico)</li>
<li>Rango: <code>min()</code> (mínimo), <code>max()</code> (máximo), <code>quantile()</code> (cuantil)</li>
<li>Posición: <code>first()</code> (primero), <code>last()</code> (último), <code>nth()</code> (posición n-ésima)</li>
<li>Conteo: <code>n()</code> (número de casos), <code>n_distinct()</code> (número de casos distintos)</li>
</ul>
<p>La mayoría se usan exclusivamente para variables de tipo numérico.</p>
</div>
<div id="visualización-gráfica" class="section level3" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Visualización gráfica</h3>
<p>En este apartado veremos como representar los datos de los conteos de una variable categórica mediante la función ’ggplot`. Esta función permite realizar casi cualquier tipo de gráfico que podamos imaginar. En este punto vamos a ir presentando diferentes parámetros de dicha función para ir familiarizándonos con su uso.</p>
<div id="gráfico-barras" class="section level4" number="6.1.2.1">
<h4><span class="header-section-number">6.1.2.1</span> Gráfico barras</h4>
<p>La herramienta gráfica más común utilizada para resumir una variable categórica es un gráfico de barras. Un gráfico de barras (o gráfico de barras) es un gráfico que presenta resúmenes de datos agrupados con barras rectangulares. La longitud de las barras es proporcional a los valores que representan. Al resumir una sola variable categórica, la longitud de las barras debe mostrar los recuentos brutos o las proporciones de cada categoría.</p>
<p>Para realizar este gráfico con la función <code>ggplot</code>necesitamos identificar el conjunto de datos sobre el que vamos a trabajar y la variable que queremos representar:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="análisis-descriptivo-inicial.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuramos el gráfico identificando los datos y la variable de interés</span></span>
<span id="cb70-2"><a href="análisis-descriptivo-inicial.html#cb70-2" aria-hidden="true" tabindex="-1"></a>bar_plt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) </span>
<span id="cb70-3"><a href="análisis-descriptivo-inicial.html#cb70-3" aria-hidden="true" tabindex="-1"></a>bar_plt <span class="ot">&lt;-</span> bar_plt <span class="sc">+</span> <span class="fu">geom_bar</span>() <span class="co"># Seleccionamos el tipo gráfico</span></span>
<span id="cb70-4"><a href="análisis-descriptivo-inicial.html#cb70-4" aria-hidden="true" tabindex="-1"></a>bar_plt                         <span class="co"># Representamos el gráfico</span></span></code></pre></div>
<div class="figure"><span id="fig:aed006"></span>
<img src="libroSTAT_files/figure-html/aed006-1.png" alt="Gráfico de barras del tipo de tormenta." width="672" />
<p class="caption">
Figura 6.1: Gráfico de barras del tipo de tormenta.
</p>
</div>
<p>Podemos personalizar este gráfico de barras si es necesario con funciones como xlab y ylab, y configurando varias propiedades dentro de geom_bar. Por ejemplo:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="análisis-descriptivo-inicial.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retocamos las barras para que aparezcan en azul y con un ancho inferior</span></span>
<span id="cb71-2"><a href="análisis-descriptivo-inicial.html#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="co"># En este caso no almacenamos el gráfico sino que lo ejecutamos directamente</span></span>
<span id="cb71-3"><a href="análisis-descriptivo-inicial.html#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) <span class="sc">+</span> </span>
<span id="cb71-4"><a href="análisis-descriptivo-inicial.html#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb71-5"><a href="análisis-descriptivo-inicial.html#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de Tormenta&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Número de observaciones&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed007"></span>
<img src="libroSTAT_files/figure-html/aed007-1.png" alt="Gráfico de barras del tipo de tormenta (versión 2)." width="672" />
<p class="caption">
Figura 6.2: Gráfico de barras del tipo de tormenta (versión 2).
</p>
</div>
<p>Como podemos ver tanto en las tablas obtenidas como en los dos gráficos precedentes la escala del tipo de tormenta no está ordenada, es decir, no la tenemos graduada por la relevancia de la tormenta. Veamos como podemos hacer esto e integrarlo en el gráfico:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="análisis-descriptivo-inicial.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un vector con el orden predefinido</span></span>
<span id="cb72-2"><a href="análisis-descriptivo-inicial.html#cb72-2" aria-hidden="true" tabindex="-1"></a>ords <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Tropical Depression&quot;</span>, <span class="st">&quot;Extratropical&quot;</span>, <span class="st">&quot;Tropical Storm&quot;</span>, <span class="st">&quot;Hurricane&quot;</span>)</span>
<span id="cb72-3"><a href="análisis-descriptivo-inicial.html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generamos el gráfico indica que el eje x tiene escala dada por el vector ordenado</span></span>
<span id="cb72-4"><a href="análisis-descriptivo-inicial.html#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) <span class="sc">+</span> </span>
<span id="cb72-5"><a href="análisis-descriptivo-inicial.html#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb72-6"><a href="análisis-descriptivo-inicial.html#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb72-7"><a href="análisis-descriptivo-inicial.html#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de Tormenta&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Número de observaciones&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed008"></span>
<img src="libroSTAT_files/figure-html/aed008-1.png" alt="Gráfico de barras del tipo de tormenta (versión 3)." width="672" />
<p class="caption">
Figura 6.3: Gráfico de barras del tipo de tormenta (versión 3).
</p>
</div>
<p>Ahora el gráfico si está ordenado con la escala adecuada y resulta más fácil cuantificar la relevancia de las tormentas más importantes. También podemos intercambiar las filas por las columnas para una mejor visualización de las etiquetas de la variable categórica. Para ello utilizamos el parámetro <code>coord_flip()</code>:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="análisis-descriptivo-inicial.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) <span class="sc">+</span> </span>
<span id="cb73-2"><a href="análisis-descriptivo-inicial.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb73-3"><a href="análisis-descriptivo-inicial.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb73-4"><a href="análisis-descriptivo-inicial.html#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb73-5"><a href="análisis-descriptivo-inicial.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de Tormenta&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Número de observaciones&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed009"></span>
<img src="libroSTAT_files/figure-html/aed009-1.png" alt="Gráfico de barras del tipo de tormenta (versión 4)." width="672" />
<p class="caption">
Figura 6.4: Gráfico de barras del tipo de tormenta (versión 4).
</p>
</div>
<p>Por último utilizamos la función <code>theme_bw()</code> para configurar un fondo blanco para el gráfico. Otras posibilidades para los temas son <code>theme_classic()</code>, <code>theme_dark()</code>, <code>theme_grey()</code>, <code>theme_light()</code>.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="análisis-descriptivo-inicial.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) <span class="sc">+</span> </span>
<span id="cb74-2"><a href="análisis-descriptivo-inicial.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb74-3"><a href="análisis-descriptivo-inicial.html#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb74-4"><a href="análisis-descriptivo-inicial.html#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb74-5"><a href="análisis-descriptivo-inicial.html#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de Tormenta&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Número de observaciones&quot;</span>)<span class="sc">+</span></span>
<span id="cb74-6"><a href="análisis-descriptivo-inicial.html#cb74-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<div class="figure"><span id="fig:aed010"></span>
<img src="libroSTAT_files/figure-html/aed010-1.png" alt="Gráfico de barras del tipo de tormenta (versión 5)." width="672" />
<p class="caption">
Figura 6.5: Gráfico de barras del tipo de tormenta (versión 5).
</p>
</div>
<p>En lugar de representar los contesos podemos visualizar los porcentajes asociados a cada categoría en lugar de los conteos haciendo uso de la variable <code>..prop..</code> en la configuración de <code>geom_bar()</code>. Se debe modificar la escala de la varaible para indicar que estamos representando porcentajes (<code>labels = scales::percent</code>):</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="análisis-descriptivo-inicial.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type)) <span class="sc">+</span> </span>
<span id="cb75-2"><a href="análisis-descriptivo-inicial.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..prop.. , <span class="at">group =</span> <span class="dv">1</span>),<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb75-3"><a href="análisis-descriptivo-inicial.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb75-4"><a href="análisis-descriptivo-inicial.html#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb75-5"><a href="análisis-descriptivo-inicial.html#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de Tormenta&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Porcentaje&quot;</span>)<span class="sc">+</span></span>
<span id="cb75-6"><a href="análisis-descriptivo-inicial.html#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<div class="figure"><span id="fig:aed011"></span>
<img src="libroSTAT_files/figure-html/aed011-1.png" alt="Gráfico de barras del porcentaje de cada tipo de tormenta." width="672" />
<p class="caption">
Figura 6.6: Gráfico de barras del porcentaje de cada tipo de tormenta.
</p>
</div>
</div>
</div>
</div>
<div id="una-variable-numérica" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Una variable numérica</h2>
<p>En esta sección se considera cómo explorar la distribución de una variable numérica Se presentan las descriptivas básicas y visualizaciones que son apropiadas para las variables de este tipo. Para ejemplificar los procedimientos utilizaremos las variables <code>wind</code> y <code>pressure</code>.</p>
<div id="resúmenes-numéricos-1" class="section level3" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Resúmenes numéricos</h3>
<p>Hasta ahora hemos estado describiendo las propiedades de las distribuciones de muestra en términos muy generales, usando frases como “valores más comunes” y “el rango de los datos” sin decir realmente lo que queremos decir. Los estadísticos han ideado términos específicos para describir este tipo de propiedades, así como diferentes estadísticas descriptivas para cuantificarlas. Los dos que más importan son la tendencia central y la dispersión:</p>
<ul>
<li>Una <strong>medida de tendencia central</strong> describe un valor típico (‘central’) de una distribución de datos. La medida de localización más extendida es la media aritmética de una muestra. Hay muchas medidas diferentes de tendencia central, cada una con sus propios pros y contras. Entre estos, la mediana es la que se usa con mayor frecuencia en los análisis exploratorios ya que es le valor que nos divide la muestra de dos partes iguales situando el 50% de los datos a cada lado de ese valor.</li>
<li>Una <strong>medida de dispersión</strong> describe cómo se distribuye una distribución. Las medidas de dispersión cuantifican la variabilidad o dispersión de una variable con respecto al promedio de los datos. Si una distribución está más dispersa que otra, significa que, en cierto sentido, abarca una gama más amplia de valores. Lo que esto significa en la práctica depende del tipo de medida con la que estamos trabajando. Las medidas de dispersión más habituales son la varianza y su raíz cuadrada, la desviación estándar.</li>
</ul>
<div id="medidas-de-tendencia-central" class="section level4" number="6.2.1.1">
<h4><span class="header-section-number">6.2.1.1</span> Medidas de tendencia central</h4>
<p>Hay dos estadísticos que se utilizan generalmente para describir la tendencia central de la distribución de los datos muestrales de un variable numérica. De ahora en adelante denotamos por <span class="math inline">\(n\)</span> al tamaño muestral y <span class="math inline">\(x_1, x_2,...,x_n\)</span> los valores muestrales de la variable que deseamos estudiar.</p>
<p>La media muestral es la medida de tendencia muestral por excelencia. La definición matemática de la media muestral viene dada por:
<span class="math display" id="eq:samplemean">\[\begin{equation} 
  \bar{x} = \frac{\sum_{i=1}^n x_i}{n}
  \tag{6.2}
\end{equation}\]</span></p>
<p>Para obtener la media utilizamos la función <code>mean()</code></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="análisis-descriptivo-inicial.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(storm<span class="sc">$</span>wind)</span></code></pre></div>
<pre><code>## [1] 54.68329</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="análisis-descriptivo-inicial.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(storm<span class="sc">$</span>pressure)</span></code></pre></div>
<pre><code>## [1] 989.8238</code></pre>
<p>Esto nos dice que la media de la velocidad del viento es de 55 mph y que la media de la presión es de 989.82 milibares. ¿Como podemos interpretar esos resultados?</p>
<p>Una limitación de la media aritmética es que se ve afectada por la forma de la distribución de los datos. Es muy sensible a los extremos de una muestra. Esta es la razón por la cual, por ejemplo, no tiene mucho sentido mirar el ingreso medio de los trabajadores en un país para tener una idea de lo que gana una persona “típica.” La distribución del ingreso es muy asimétrica, y los pocos que tienen la suerte de ganar salarios muy buenos tienden a cambiar la media hacia arriba y superar cualquier cosa que sea realmente “típica.” La media de la muestra también se ve fuertemente afectada por la presencia de ‘valores atípicos’ o valores extremos, es decir, valores inusualmente grandes o pequeños en una muestra.</p>
<p>Debido a que la media muestral es sensible a la forma de una distribución y la presencia de valores atípicos, a menudo se prefiere una segunda medida de tendencia central: la mediana de la muestra. La mediana de una muestra es el número que separa los datos en dos subgrupos (la mitad superior de la mitad inferior). Podemos calcular la mediana muestral en R con la función <code>median()</code>:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="análisis-descriptivo-inicial.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(storm<span class="sc">$</span>wind)</span></code></pre></div>
<pre><code>## [1] 50</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="análisis-descriptivo-inicial.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(storm<span class="sc">$</span>pressure)</span></code></pre></div>
<pre><code>## [1] 995</code></pre>
<p>Estos resultados indican que el 50% de de los registros muestran una valor de viento inferior a 50 mph. De la misma forma el 50% de los datos muestran una valor de la presión inferior a 995 milibares.</p>
<p>Otras medidas de localización son el mínimo, el máximo y los percentiles. Los percentiles son los valores que dividen en la muestra según el valor del percentil solicitado. Si solicitamos el percentil 20, se separa la muestra en dos subconjuntos dejando el 20% en un grupo y e 80% en el otro. Los percentiles más habituales son lo denominados primer y tercer cuartil que corresponden a los percentiles 25 y 75 respectivamente. Para obtener el percentil asociado a una variable numérica podemos hacer uso de la función <code>quantile()</code>. Para ver como se debe utilizar es útil consultar la ayuda de dicha función <code>help(quantile)</code>.</p>
</div>
<div id="medidas-de-dispersión" class="section level4" number="6.2.1.2">
<h4><span class="header-section-number">6.2.1.2</span> Medidas de dispersión</h4>
<p>Hay muchas maneras de cuantificar la dispersión de un conjunto de datos muestrales de una variable numérica. Los valores más importantes desde el punto de vista estadístico son la varianza muestral y la desviación estándar. La varianza muestral <span class="math inline">\(s^2\)</span> es “la suma de las desviaciones cuadradas” (es decir, las diferencias) de cada observación con respecto a la media de la muestra, dividida por el tamaño de la muestra menos uno. La desviación típica es la raíz cuadrada de la varianza muestral. Las definiciones matemáticas de ambas cantidades son:
<span class="math display" id="eq:var">\[\begin{equation} 
  s^2 = \frac{\sum_{i=1}^n (x_i-\bar{x})^2}{n-1}
  \tag{6.3}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:sd">\[\begin{equation} 
  s = \sqrt{s^2}
  \tag{6.4}
\end{equation}\]</span></p>
<p>Las funciones de R para calcular ambas cantidades son <code>var()</code> para la varianza y <code>sd()</code> para la desviación típica.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="análisis-descriptivo-inicial.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(storm<span class="sc">$</span>wind);<span class="fu">sd</span>(storms<span class="sc">$</span>wind)</span></code></pre></div>
<pre><code>## [1] 668.1444</code></pre>
<pre><code>## [1] 25.84849</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="análisis-descriptivo-inicial.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(storm<span class="sc">$</span>pressure);<span class="fu">sd</span>(storms<span class="sc">$</span>pressure)</span></code></pre></div>
<pre><code>## [1] 349.4912</code></pre>
<pre><code>## [1] 18.69468</code></pre>
<p>¿Qué significa ese número en realidad? Las variaciones son siempre no negativas. Una pequeña varianza indica que las observaciones tienden a ser cercanas a la media (y una a la otra), mientras que una alta varianza indica que las observaciones están muy dispersas. Una varianza de cero solo ocurre si todos los valores son idénticos. Sin embargo, es difícil interpretar si una varianza muestral es realmente “pequeña” o “grande” porque el cálculo involucra desviaciones al cuadrado. Por ejemplo, cambiar la escala de medición de una variable por 10 implica un cambio de 100 veces (102) en la varianza.</p>
<p>La varianza es una cantidad importante en las estadísticas que aparece una y otra vez. Muchas herramientas estadísticas comunes usan cambios en la varianza para comparar formalmente qué tan bien diferentes modelos describen un conjunto de datos. Sin embargo, es muy difícil interpretar las variaciones, por lo que rara vez las utilizamos en el trabajo exploratorio. Para expresar la variabilidad en la misma escala de la variable original utilizamos la desviación típica. En este caso se puede observar una mayor variabilidad en la variable presión atmosférica (desviación típica de 25.84 milibares) que en la variable de viento (18.69 mph).</p>
<p>La desviación estándar de la muestra no está exenta de problemas. Al igual que la media muestral, es sensible a la forma de la distribución de los datos y a la presencia de valores atípicos. Una medida de dispersión más robusta para este tipo de características es el rango intercuartílico, definida como la diferencia entre el percentil 75 (tercer cuartil) y el percentil 25 (primer cuartil):</p>
<p><span class="math display" id="eq:iqr">\[\begin{equation} 
 IQR = Q_3 - Q_1
  \tag{6.5}
\end{equation}\]</span></p>
<p>Obviamente, cuanto más dispersos estén los datos, mayor será el IQR. La razón por la que preferimos usar IQR para medir la dispersión es que solo depende de los datos en el “medio” de una distribución de muestra. Esto lo hace robusto a la presencia de valores atípicos. Podemos usar la función <code>IQR()</code> para calcular el rango intercuartílico:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="análisis-descriptivo-inicial.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(storm<span class="sc">$</span>wind)</span></code></pre></div>
<pre><code>## [1] 35</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="análisis-descriptivo-inicial.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(storm<span class="sc">$</span>pressure)</span></code></pre></div>
<pre><code>## [1] 24</code></pre>
<p>La última medidad de dispersión que veremos es el coeficiente de variación. Esta medida es una de las más habituales y se obtiene a partir de la media y desviación típica muestral como:
<span class="math display" id="eq:cv">\[\begin{equation} 
 CV = \frac{s}{\bar{x}}
  \tag{6.6}
\end{equation}\]</span></p>
<p>Su fórmula expresa la desviación estándar como porcentaje de la media aritmética, mostrando una interpretación relativa del grado de variabilidad, independiente de la escala de la variable, a diferencia de la desviación típica o estándar. De esta forma, valores bajos del coeficiente de variación expresan menor variabilidad, lo que resulta de utilidad cuando deseamos comparar la variabilidad de dos muestras independeintemente de su media. El mayor problema es que sólo puede ser usado cuando la media muestral es positiva.</p>
</div>
<div id="resúmenes-conjuntos" class="section level4" number="6.2.1.3">
<h4><span class="header-section-number">6.2.1.3</span> Resúmenes conjuntos</h4>
<p>Aunque podemos ir calculando cada una de las medidas de localización y dispersión vistas anteriormente, en la práctica nos resulta más útil obtenerlas todas de una vez. Existen diferentes funciones que nos permiten obterner estos análisis descriptivos. La primera de ellas es la función <code>summary()</code> que nos porporciona el mínimo, máximo, media, mediana y los percentiles 25 y 75. Sin embargo, no nos porporciona ninguna de las medidas de varaibilidad usuales. En nuestro ejemplo</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="análisis-descriptivo-inicial.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(storm<span class="sc">$</span>wind)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   15.00   35.00   50.00   54.68   70.00  155.00</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="análisis-descriptivo-inicial.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(storm<span class="sc">$</span>pressure)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   905.0   980.0   995.0   989.8  1004.0  1019.0</code></pre>
<p>Se pude ver que el 25% de las observaciones muestran una valor de viento inferior a 35mph y un 25% un valor de viento superior a 70mph. Con respecto a la presión atmosférica tenemos que el 25% de las observaciones tienen un valor inferior a 980 milibares, y un 25% tienen un valor superior a 1004 milibares.</p>
<p>Otra función que nos porporciona medidas conjuntas es <code>estat()</code> de la librería <code>pubh</code>. Esta función nos porporciona el número de casos, el mínimo, el máximo, la media, la mediana, la desviación típica, y el coeficiente de variación.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="análisis-descriptivo-inicial.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Etiquetamos las variables</span></span>
<span id="cb98-2"><a href="análisis-descriptivo-inicial.html#cb98-2" aria-hidden="true" tabindex="-1"></a>storm <span class="ot">=</span> storm <span class="sc">%&gt;%</span> </span>
<span id="cb98-3"><a href="análisis-descriptivo-inicial.html#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">var_labels</span>(<span class="at">wind =</span> <span class="st">&#39;Wind speed (in knots)&#39;</span>, </span>
<span id="cb98-4"><a href="análisis-descriptivo-inicial.html#cb98-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">pressure =</span> <span class="st">&#39;Air pressure (in mbar)&#39;</span>)</span>
<span id="cb98-5"><a href="análisis-descriptivo-inicial.html#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis descriptivos</span></span>
<span id="cb98-6"><a href="análisis-descriptivo-inicial.html#cb98-6" aria-hidden="true" tabindex="-1"></a><span class="fu">estat</span>(<span class="sc">~</span> wind, <span class="at">data =</span> storm)</span></code></pre></div>
<pre><code>##                            N Min. Max.  Mean Median    SD   CV
## 1 Wind speed (in knots) 2747   15  155 54.68     50 25.85 0.47</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="análisis-descriptivo-inicial.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estat</span>(<span class="sc">~</span> pressure, <span class="at">data =</span> storm)</span></code></pre></div>
<pre><code>##                             N Min. Max.   Mean Median    SD   CV
## 1 Air pressure (in mbar) 2747  905 1019 989.82    995 18.69 0.02</code></pre>
</div>
</div>
<div id="visualización-gráfica-1" class="section level3" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Visualización gráfica</h3>
<p>En este apartado veremos como representar los datos de los conteos de una variable categórica mediante la función ’ggplot`. Esta función permite realizar casi cualquier tipo de gráfico que podamos imaginar. En este punto vamos a ir presentando diferentes parámetros de dicha función para ir familiarizándonos con su uso.</p>
<div id="gráfico-barras-1" class="section level4" number="6.2.2.1">
<h4><span class="header-section-number">6.2.2.1</span> Gráfico barras</h4>
<p>El gráfico por excelencia para una variable de tipo numérico es el denominado histograma. El histograma es una representación mediante barras de la distribución de los datos. Para construir las barras se divide el rango de la variable numérica en un conjunto fijo de intervalos disjuntos y se contabiliza el número de datos que quedan dentro de cada uno de ellos (altura del gráfico de barras). Es un gráfico muy interesante porque representa de forma bastante precisa, ajustando el número de intervalos, la distribución del conjunto de datos pudiéndose observar su dispersión y/o asimetria.</p>
<p>Para realizar este gráfico utilizamos parámetros específicos dentro de la función <code>ggplot()</code> a partir de <code>geom_histogram()</code>.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="análisis-descriptivo-inicial.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> pressure)) <span class="sc">+</span></span>
<span id="cb102-2"><a href="análisis-descriptivo-inicial.html#cb102-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_histogram</span>()</span></code></pre></div>
<div class="figure"><span id="fig:aed018"></span>
<img src="libroSTAT_files/figure-html/aed018-1.png" alt="Histograma de la presión atmosférica." width="672" />
<p class="caption">
Figura 6.7: Histograma de la presión atmosférica.
</p>
</div>
<p>Podemos ver que la mayoría de los datos se sitúan por encima de 915 milibares, hay una clara asimetría hacia los valores más grandes y existe una gran dispersión entre en el conjunto de valores observados.</p>
<p>Veamos como introducir diferentes parámetros en el gráfico anterior. el más importante es el que hace referencia a los intervalos asociado con el histograma (parámetro <code>binwith</code>)</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="análisis-descriptivo-inicial.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> pressure)) <span class="sc">+</span> </span>
<span id="cb103-2"><a href="análisis-descriptivo-inicial.html#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">8</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb103-3"><a href="análisis-descriptivo-inicial.html#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Air pressure (in mbar)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed019"></span>
<img src="libroSTAT_files/figure-html/aed019-1.png" alt="Histograma de la presión atmosférica (modificando binwidth)." width="672" />
<p class="caption">
Figura 6.8: Histograma de la presión atmosférica (modificando binwidth).
</p>
</div>
<p>Veamos ahora el histograma de la variable <code>wind</code></p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="análisis-descriptivo-inicial.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind)) <span class="sc">+</span> </span>
<span id="cb104-2"><a href="análisis-descriptivo-inicial.html#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">8</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb104-3"><a href="análisis-descriptivo-inicial.html#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed020"></span>
<img src="libroSTAT_files/figure-html/aed020-1.png" alt="Histograma de la velocidad del viento." width="672" />
<p class="caption">
Figura 6.9: Histograma de la velocidad del viento.
</p>
</div>
<p>El otro gráfico habitual para una variable de tipo numérico es el llamado gráfico de cajas. En este gráfico se representa mediante una caja la media (linea central de la caja), el percentil 75 (línea superior de la caja), y el percentil 25 (linea inferior de la caja). También se representan el valor máximo (percentil 75 + 1.5 IQR) y mínimo (percentil 25 - 1.5 IQR), así como los caracterizados como valores extremos (punto fuera de la caja).
Veamos como realizar este gráfico mediante el parámetro <code>geom_boxplot()</code>.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="análisis-descriptivo-inicial.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>),<span class="at">y =</span> pressure)) <span class="sc">+</span></span>
<span id="cb105-2"><a href="análisis-descriptivo-inicial.html#cb105-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<div class="figure"><span id="fig:aed021"></span>
<img src="libroSTAT_files/figure-html/aed021-1.png" alt="Gráfico de cajas de la presión atmosférica." width="672" />
<p class="caption">
Figura 6.10: Gráfico de cajas de la presión atmosférica.
</p>
</div>
<p>Añadimos parámetros (título de ejes, color caja, selección de valores extremos, y fondo blanco)</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="análisis-descriptivo-inicial.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>), <span class="at">y =</span> pressure)) <span class="sc">+</span></span>
<span id="cb106-2"><a href="análisis-descriptivo-inicial.html#cb106-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb106-3"><a href="análisis-descriptivo-inicial.html#cb106-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">&quot; &quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">&quot;Air pressure (in mbar)&quot;</span>) <span class="sc">+</span></span>
<span id="cb106-4"><a href="análisis-descriptivo-inicial.html#cb106-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:aed022"></span>
<img src="libroSTAT_files/figure-html/aed022-1.png" alt="Gráfico de cajas de la presión atmosférica (versión 2)." width="672" />
<p class="caption">
Figura 6.11: Gráfico de cajas de la presión atmosférica (versión 2).
</p>
</div>
<p>Podemos ver que la media se sitúa muy próxima a los 1000 mbar y la gran cantidad de valores extremos en la parte baja de la distribución. Además la caja es muy estrecha indicando la poca variabilidad en los datos, lo que viene corroborado también por la proximidad de los percentiles 25 y 75.</p>
<p>Ahora el gráfico para la variable <code>wind</code></p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="análisis-descriptivo-inicial.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>),<span class="at">y =</span> wind)) <span class="sc">+</span></span>
<span id="cb107-2"><a href="análisis-descriptivo-inicial.html#cb107-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>,<span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb107-3"><a href="análisis-descriptivo-inicial.html#cb107-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">&quot; &quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-4"><a href="análisis-descriptivo-inicial.html#cb107-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:aed023"></span>
<img src="libroSTAT_files/figure-html/aed023-1.png" alt="Gráfico de cajas de la velocidad del viento." width="672" />
<p class="caption">
Figura 6.12: Gráfico de cajas de la velocidad del viento.
</p>
</div>
<p>¿Cómo interpretamos este gráfico?</p>
</div>
</div>
</div>
<div id="dos-variables-categóricas" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Dos variables categóricas</h2>
<p>Explorar numéricamente las asociaciones entre pares de variables categóricas no es tan simple como el caso de una variable. La pregunta general que debemos abordar es, “¿las diferentes combinaciones de categorías parecen estar sub o sobre representadas?” Necesitamos entender qué combinaciones son comunes y cuáles son raras. Lo más simple que podemos hacer es construir una tabulación cruzada del número de ocurrencias de cada combinación de niveles de ambas variables. La tabla resultante se llama tabla de contingencia.</p>
<p>En cuanto a la representación gráfica la opción más habitual pasa por representar los conteos mediante gráficos de barras que representan de forma conjunta la información de ambas variables.</p>
<p>Para ejemplificar los cálculos y gráficos utilizaremos las variables <code>month_f</code> (mes como factor) y <code>type</code>. En primer lugar etiquetamos las variables.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="análisis-descriptivo-inicial.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Etiquetamos las variables</span></span>
<span id="cb108-2"><a href="análisis-descriptivo-inicial.html#cb108-2" aria-hidden="true" tabindex="-1"></a>storm <span class="ot">=</span> storm <span class="sc">%&gt;%</span> </span>
<span id="cb108-3"><a href="análisis-descriptivo-inicial.html#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">var_labels</span>(<span class="at">month_f =</span> <span class="st">&#39;Month&#39;</span>, </span>
<span id="cb108-4"><a href="análisis-descriptivo-inicial.html#cb108-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="st">&#39;Storm category&#39;</span>)</span></code></pre></div>
<div id="resúmenes-numéricos-2" class="section level3" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Resúmenes numéricos</h3>
<p>El resumen numérico habitual para este tipo de situación es la tabla de contigencia (tabla de doble entrada) que nos porporciona los conteos o coincidencias entre los niveles de cada factor. Obtener la tabla completa (frecuencias y porcentajes) puede ser una faena algo pesada utilizando las funciones habituales. En nuestro caso utilizaremos la función <code>cross_tab</code> de la librería <code>pubh</code>. Dicha función nos porpociona la tbala de doble entrada con los conteos y los porcentajes marginales por columnas. Veamos su uso en el banco de datos.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="análisis-descriptivo-inicial.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(storm<span class="sc">$</span>type, storm<span class="sc">$</span>month_f)</span></code></pre></div>
<pre><code>##                      
##                       June July August September October November December
##   Extratropical         27   38     23       149     129       42        4
##   Hurricane              3   31    300       383     152       25        2
##   Tropical Depression   22   59    150       156      84       42        0
##   Tropical Storm        31  123    247       259     204       61        1</code></pre>
<p>Esta tabla nos permite analizar las concidencias entres los fatores estudiados (conteos), así como la relevancia de cada tipo de tormenta a los largo de los meses estudiados (porcentajes marginales por columnas). Por ejemplo, podemos ver que el perido más activo de huracanes es el comprendido entre los meses de agosto a octubre.</p>
<p>En este caso los porcentajes marginales nos revelan que tipo de tormenta es más habitual dentro de cada mes de los analizados. Por ejemplo, en el mes de agosto el tipo de tormenta más habitual son los huracanes con un 40.1%, lo que representa casi la mitad de los observado durante ese mes.</p>
</div>
<div id="visualización-gráfica-2" class="section level3" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Visualización gráfica</h3>
<p>Los gráficos de barras se pueden usar para resumir la relación entre dos variables categóricas. La idea básica es producir una barra separada para cada combinación de categorías en las dos variables. La longitud de estas barras es proporcional a los valores que representan, que son los recuentos brutos o las proporciones en cada combinación de categorías. Esta es la misma información que se muestra en una tabla de contingencia. El uso de ggplot2 para mostrar esta información no es muy diferente de producir un gráfico de barras para resumir una única variable categórica.</p>
<p>Tomamos las variables <code>type</code> y <code>year_f</code> para mostrar su funcionamiento. Ordenamos la variable <code>type</code> para mostrar los gráficos por orden de importancia de la tormenta. En primer lugar realizamos el gráfico de barras apiladas.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="análisis-descriptivo-inicial.html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un vector con el orden predefinido</span></span>
<span id="cb111-2"><a href="análisis-descriptivo-inicial.html#cb111-2" aria-hidden="true" tabindex="-1"></a>ords <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Tropical Depression&quot;</span>, <span class="st">&quot;Extratropical&quot;</span>, <span class="st">&quot;Tropical Storm&quot;</span>, <span class="st">&quot;Hurricane&quot;</span>)</span>
<span id="cb111-3"><a href="análisis-descriptivo-inicial.html#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generamos el gráfico indica que el eje x tiene escala dada por el vector ordenado</span></span>
<span id="cb111-4"><a href="análisis-descriptivo-inicial.html#cb111-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">fill =</span> year_f)) <span class="sc">+</span> </span>
<span id="cb111-5"><a href="análisis-descriptivo-inicial.html#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb111-6"><a href="análisis-descriptivo-inicial.html#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb111-7"><a href="análisis-descriptivo-inicial.html#cb111-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Storm category&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequancy&quot;</span>) </span></code></pre></div>
<div class="figure"><span id="fig:aed027"></span>
<img src="libroSTAT_files/figure-html/aed027-1.png" alt="Gráfico de barras apiladas para tipo de tormenta versus año." width="672" />
<p class="caption">
Figura 6.13: Gráfico de barras apiladas para tipo de tormenta versus año.
</p>
</div>
<p>En este caso cada tipo de tormenta tiene su propia barra, y cada barra se ha dividido en diferentes segmentos de colores, cuya longitud está determinada por el número de observaciones asociadas con cada año. Podemos apreciar si para un mismo tipo de tormenta la ocurrencia de un tipo de tormenta es similar o no. Por ejemplo, para los huracanes podemos apreciar que los años 1996, 1998, 1999, y 2000 tienen un número similar de ocurrencias.</p>
<p>Un problema con este tipo de gráfico es que puede ser difícil detectar asociaciones entre las dos variables categóricas. Si queremos saber cómo están asociados, a menudo es mejor trazar los recuentos para cada combinación de categorías una al lado de la otra. Este gráfico se denomina gráfico de barras agrupado. Utilizamos la opción <code>dodge</code> en la función <code>geom_bar</code> para poder realizar esta versión:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="análisis-descriptivo-inicial.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">fill =</span> year_f)) <span class="sc">+</span> </span>
<span id="cb112-2"><a href="análisis-descriptivo-inicial.html#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span> </span>
<span id="cb112-3"><a href="análisis-descriptivo-inicial.html#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb112-4"><a href="análisis-descriptivo-inicial.html#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Storm category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frequancy&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Storm category&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed028"></span>
<img src="libroSTAT_files/figure-html/aed028-1.png" alt="Gráfico de barras agrupado para el tipo de tormenta versus año." width="672" />
<p class="caption">
Figura 6.14: Gráfico de barras agrupado para el tipo de tormenta versus año.
</p>
</div>
<p>¿Qué ventajas o desventajas aprecias en este gráfico frente al de barras apiladas?</p>
<p>Alternativamente podríamos realizar el gráfico de porcentahjes en lugar de los conteos. Hacemos uso de la función <code>..prop..</code> e indicamos la agrupación por la variable <code>year_f</code>:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="análisis-descriptivo-inicial.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">fill =</span> year_f)) <span class="sc">+</span> </span>
<span id="cb113-2"><a href="análisis-descriptivo-inicial.html#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..prop.. , <span class="at">group =</span> year_f),<span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span> </span>
<span id="cb113-3"><a href="análisis-descriptivo-inicial.html#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb113-4"><a href="análisis-descriptivo-inicial.html#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Storm category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Percent&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Storm category&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed029"></span>
<img src="libroSTAT_files/figure-html/aed029-1.png" alt="Gráfico de barras agrupado (porcentjes) para el tipo de tormenta versus año." width="672" />
<p class="caption">
Figura 6.15: Gráfico de barras agrupado (porcentjes) para el tipo de tormenta versus año.
</p>
</div>
<p>Otra opción es realizar un mapa de intensidad de cada una de las combinaciones e ambos factores. Utilizamos la función <code>geom_tile()</code> a partir los conteos conjuntos para ambas variables con la opción <code>count()</code> que se almacenan en la variable temporal <code>n</code>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="análisis-descriptivo-inicial.html#cb114-1" aria-hidden="true" tabindex="-1"></a>storm <span class="sc">%&gt;%</span></span>
<span id="cb114-2"><a href="análisis-descriptivo-inicial.html#cb114-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(type,year_f) <span class="sc">%&gt;%</span></span>
<span id="cb114-3"><a href="análisis-descriptivo-inicial.html#cb114-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> year_f)) <span class="sc">+</span> </span>
<span id="cb114-4"><a href="análisis-descriptivo-inicial.html#cb114-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_tile</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> n)) <span class="sc">+</span> </span>
<span id="cb114-5"><a href="análisis-descriptivo-inicial.html#cb114-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb114-6"><a href="análisis-descriptivo-inicial.html#cb114-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Storm type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed030"></span>
<img src="libroSTAT_files/figure-html/aed030-1.png" alt="Mapa de intensidad para el tipo de tormenta versus año." width="672" />
<p class="caption">
Figura 6.16: Mapa de intensidad para el tipo de tormenta versus año.
</p>
</div>
<p>En este caso las casillas en tonos más claros corresponden con las combinaciones de niveles con una mayor ocurrencia. Las más abundantes se concentran en 1995 y los tipos de tormenta más graves. Por otro lado el año 1997 es el que ha registrado menor número de tormentas.</p>
</div>
</div>
<div id="categórica-vs-numérica" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Categórica vs Numérica</h2>
<p>El objetivo en este tipo de situaciones es comparar cada una de las distribuciones de la variable numérica que surgen al segmentar los valores por cada uno de los niveles de la variable categórica. Tenemos tantas conjuntos de datos como niveles del facgor hemos observado.</p>
<div id="resúmenes-numéricos-3" class="section level3" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Resúmenes numéricos</h3>
<p>Los resúmenes numéricos se pueden construir tomando las diversas ideas que hemos explorado para las variables numéricas (medias, medianas, etc.) y aplicándolas a subconjuntos de datos definidos por los valores de la variable categórica. Sin embargo, podemos hacer uso de la función <code>estat()</code> para simplicar este trabajo. para ejemplificar su uso utilizamos la variable <code>type</code> como categórica y las variables <code>wind</code> y <code>pressure</code> como numéricas.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="análisis-descriptivo-inicial.html#cb115-1" aria-hidden="true" tabindex="-1"></a>storm<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(storm<span class="sc">$</span>type)</span>
<span id="cb115-2"><a href="análisis-descriptivo-inicial.html#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Simplificamos las etiquetas de las variables</span></span>
<span id="cb115-3"><a href="análisis-descriptivo-inicial.html#cb115-3" aria-hidden="true" tabindex="-1"></a>storm <span class="ot">=</span> storm <span class="sc">%&gt;%</span> </span>
<span id="cb115-4"><a href="análisis-descriptivo-inicial.html#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">var_labels</span>(<span class="at">wind =</span> <span class="st">&#39;Wind&#39;</span>, </span>
<span id="cb115-5"><a href="análisis-descriptivo-inicial.html#cb115-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">pressure =</span> <span class="st">&#39;Air pressure&#39;</span>)</span>
<span id="cb115-6"><a href="análisis-descriptivo-inicial.html#cb115-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis descriptivos</span></span>
<span id="cb115-7"><a href="análisis-descriptivo-inicial.html#cb115-7" aria-hidden="true" tabindex="-1"></a><span class="fu">estat</span>(<span class="sc">~</span> wind<span class="sc">|</span>type, <span class="at">data =</span> storm)</span></code></pre></div>
<pre><code>##                       type   N Min. Max.  Mean Median    SD   CV
## 1 Wind       Extratropical 412   15   80 40.06     40 13.25 0.33
## 2                Hurricane 896   65  155 84.66     80 18.79 0.22
## 3      Tropical Depression 513   20   30 27.36     30  3.52 0.13
## 4           Tropical Storm 926   35  120 47.32     45 11.09 0.23</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="análisis-descriptivo-inicial.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estat</span>(<span class="sc">~</span> pressure<span class="sc">|</span>type, <span class="at">data =</span> storm)</span></code></pre></div>
<pre><code>##                               type   N Min. Max.    Mean Median    SD   CV
## 1 Air pressure       Extratropical 412  950 1019  993.95    996 14.19 0.01
## 2                        Hurricane 896  905 1005  970.44    974 16.95 0.02
## 3              Tropical Depression 513  982 1015 1006.16   1007  3.90 0.00
## 4                   Tropical Storm 926  935 1013  997.70   1000  8.95 0.01</code></pre>
<p>Se puede ver como el tipo Huracanes tiene la media más alta de velocidad del viento y la más baja de presión atmosférica. Además en ambos casos la variabilidad observada es la mayor de todos los tipos de tormenta. La depresión tropical es justo el caso contrario. Evidentemente los datos observados corresponden con la clasificación de tormenta establecida desde el inicio. ¿Qué otras conclusiones podemos obtener? ¿qué tipo de tormenta muestra una mayor variabilidad?</p>
</div>
<div id="visualización-gráfica-3" class="section level3" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Visualización gráfica</h3>
<p>Para la visualización gráfica de las relaciones entre una variable categórica y una numérica tenemos diferentes opciones: gráfico de densidad, gráfico de cajas, y gráficos comparativos matriciales.</p>
<p>El gráfico de densidad representa la distribución del conjunto de datos muestrales. Con este gráfico se puede apreciar claramente el rango de valores y su concentración (altura de la curva de densidad). Para su obtención utilizamos la opción <code>geom_density()</code> donde sólo debemos fijar el parámetro de suavizado, <code>bw</code>, que nos indica el grado de información que debemos utilizar para obtener dicha densidad. Valores pequeños dan curvas poco suavizadas y valores grandes dan curva suavizadas. Siempre es necesario un pequeño ajuste para obtener el valor más adecuado. Con este gráfico resulta muy fácil comparar el comportamiento de los diferentes grupos.</p>
<p>Comenzamos con la variable <code>wind</code>:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="análisis-descriptivo-inicial.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind)) <span class="sc">+</span> </span>
<span id="cb119-2"><a href="análisis-descriptivo-inicial.html#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">colour =</span> type), <span class="at">bw =</span> <span class="dv">3</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb119-3"><a href="análisis-descriptivo-inicial.html#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Wind speed (in knots)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) </span></code></pre></div>
<div class="figure"><span id="fig:aed032"></span>
<img src="libroSTAT_files/figure-html/aed032-1.png" alt="Gráficos de densidades de la velocidad del viento por tipo de tormenta." width="672" />
<p class="caption">
Figura 6.17: Gráficos de densidades de la velocidad del viento por tipo de tormenta.
</p>
</div>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="análisis-descriptivo-inicial.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># la opción na.rm elimina los valores pérdidos.</span></span></code></pre></div>
<p>El resultado son cuatro curvas de densidad (una por cada top de tormenta) donde los más destacable es que el rango de valores posibles para la velocidad del viento es sólo diferente para el tipo huracanes, ya que su curva de densidad se encuentra desplazada respecto del resto de densidades. También se puede ver que las depresiones tropicales tienen una menor dispersión (menor rango de valores) los que provoca que su curva sea más puntiaguda. Cuanto mayor sea la dispersión mas amplia sera la densidad obtenida. Si la densidad es simétrica la media se sitúa en el punto medio, mientras que el valor asociado con el punto más alto de la densidad es lo que denominamos moda.</p>
<p>Ahora con la variable presión atmosférica:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="análisis-descriptivo-inicial.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> pressure)) <span class="sc">+</span> </span>
<span id="cb121-2"><a href="análisis-descriptivo-inicial.html#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">colour =</span> type), <span class="at">bw =</span> <span class="dv">3</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb121-3"><a href="análisis-descriptivo-inicial.html#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Air pressure (in knots)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) </span></code></pre></div>
<div class="figure"><span id="fig:aed033"></span>
<img src="libroSTAT_files/figure-html/aed033-1.png" alt="Gráficos de densidades de la presión atmosférica por tipo de tormenta." width="672" />
<p class="caption">
Figura 6.18: Gráficos de densidades de la presión atmosférica por tipo de tormenta.
</p>
</div>
<p>El comportamiento de la variable presión atmosférica es muy similar al de la velocidad del viento pero en la parte izquierda del rango de valores. Los huracanes tienen la menor presión atmosférica y se distinguen del resto de tipos de tormenta. También muestra una mayor variabilidad que el resto de tipos.</p>
<p>La visualización más común para explorar las relaciones entre una variable categórica y otra numérica es el diagrama de cajas. Cada diagrama de caja consiste en:</p>
<ul>
<li>Una casilla que se extiende desde el percentil 25 de la distribución hasta el percentil 75, una distancia conocida como rango intercuartílico (IQR). En el medio del recuadro hay una línea que muestra la mediana, es decir, el percentil 50 de la distribución. Estas tres líneas le dan una idea de la extensión de la distribución y si la distribución es simétrica o no respecto a la mediana o sesgada hacia un lado.</li>
<li>Puntos visuales que muestran observaciones que caen más de 1,5 veces el IQR desde cualquier borde de la caja. Estos puntos remotos son inusuales, por lo que se representan de forma individual.</li>
<li>Una línea (o bigote) que se extiende desde cada extremo de la caja y va al
el punto más lejano no atípico en la distribución.</li>
</ul>
<p>Veamos los ejemplos:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="análisis-descriptivo-inicial.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> wind)) <span class="sc">+</span> </span>
<span id="cb122-2"><a href="análisis-descriptivo-inicial.html#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb122-3"><a href="análisis-descriptivo-inicial.html#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb122-4"><a href="análisis-descriptivo-inicial.html#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Storm category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Wind speed (in knots)&quot;</span>) </span></code></pre></div>
<div class="figure"><span id="fig:aed034"></span>
<img src="libroSTAT_files/figure-html/aed034-1.png" alt="Gráficos de cajas de la velocidad del viento por tipo de tormenta." width="672" />
<p class="caption">
Figura 6.19: Gráficos de cajas de la velocidad del viento por tipo de tormenta.
</p>
</div>
<p>En este tipo de gráficos se esta interesado en dos aspecto fundamentales:
* Estudiar la variabilidad dentro de cada grupo viendo la altura de la caja (IQR).
* Comparar el comportamiento de cada grupo observando si las cajas quedan a alturas superpuestas.</p>
<p>En este caso podemos ver que la variabilidad más grande se produce en el tipo huracanes y la más pequeña en las depresiones tropicales. Se aprecian diferencias entre las variabilidades de los grupos. Por otro lado, las cajas correspondientes a las tormentas extra tropicales y tormentas tropicales quedan a una misma altura indicando que tienen valores similares para la velocidad del viento. Este gráfico nos da unas primeras indicaciones claras para los procedimientos de comparaciones de medias que estudiaremos más adelante.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="análisis-descriptivo-inicial.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> pressure)) <span class="sc">+</span> </span>
<span id="cb123-2"><a href="análisis-descriptivo-inicial.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb123-3"><a href="análisis-descriptivo-inicial.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> ords) <span class="sc">+</span></span>
<span id="cb123-4"><a href="análisis-descriptivo-inicial.html#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Storm category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Air pressure (in mbar)&quot;</span>) </span></code></pre></div>
<div class="figure"><span id="fig:aed035"></span>
<img src="libroSTAT_files/figure-html/aed035-1.png" alt="Gráficos de cajas de la presión atmosférica por tipo de tormenta." width="672" />
<p class="caption">
Figura 6.20: Gráficos de cajas de la presión atmosférica por tipo de tormenta.
</p>
</div>
<p>En este caso observamos que los tipos extra tropical y Huracanes muestran variabilidades similares, mientras que los otros dos tipos también muestran variabilidades similares. En cuanto a la comparación de los grupos se observa que el único con un comportamiento diferente son los huracanes. Los otros tres tipos muestran cajas que se podrías solapar mostrando una mayor igualdad en los valores de presión atmosférica.</p>
<p>Los gráficos matriciales o de facetas permiten representar mediante múltiples gráficos la información de una variable numéricas con respecto a los niveles de la variable categórica. Se pretende de esta forma comprobar la forma de la distribución de los datos de forma similar al gráfico de densidad pero realzando un gráfico para cada nivel. Aunque resultan más útiles cuando trabajamos con más de dos variables, se introducen aquí para ir conociendo su funcionamiento en ejemplos sencillos.</p>
<p>Comenzamos realizando un histograma independiente. Para que resulte más fácil visualizar el gráfico introducimos un orden asociado con los valores de la variable numérica, comenzando con el nivel que tiene valores en esa variable más pequeños, y finalizando con la que tiene los valores más grandes.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="análisis-descriptivo-inicial.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un nuevo factor ordenado de acuerdo a la variable que estamos midiendo</span></span>
<span id="cb124-2"><a href="análisis-descriptivo-inicial.html#cb124-2" aria-hidden="true" tabindex="-1"></a>storm<span class="sc">$</span>type2 <span class="ot">&lt;-</span> <span class="fu">reorder</span>(storm<span class="sc">$</span>type, storm<span class="sc">$</span>wind)</span>
<span id="cb124-3"><a href="análisis-descriptivo-inicial.html#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el gráfico</span></span>
<span id="cb124-4"><a href="análisis-descriptivo-inicial.html#cb124-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind))  <span class="sc">+</span></span>
<span id="cb124-5"><a href="análisis-descriptivo-inicial.html#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span> </span>
<span id="cb124-6"><a href="análisis-descriptivo-inicial.html#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span></span>
<span id="cb124-7"><a href="análisis-descriptivo-inicial.html#cb124-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb124-8"><a href="análisis-descriptivo-inicial.html#cb124-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> type2, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed036"></span>
<img src="libroSTAT_files/figure-html/aed036-1.png" alt="Gráficos matricial de velocidad del viento por tipo de tormenta" width="672" />
<p class="caption">
Figura 6.21: Gráficos matricial de velocidad del viento por tipo de tormenta
</p>
</div>
<p>También podríamos realizar el gráfico de densidad</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="análisis-descriptivo-inicial.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el gráfico</span></span>
<span id="cb125-2"><a href="análisis-descriptivo-inicial.html#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind))  <span class="sc">+</span></span>
<span id="cb125-3"><a href="análisis-descriptivo-inicial.html#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">bw =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb125-4"><a href="análisis-descriptivo-inicial.html#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span></span>
<span id="cb125-5"><a href="análisis-descriptivo-inicial.html#cb125-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb125-6"><a href="análisis-descriptivo-inicial.html#cb125-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> type2, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed037"></span>
<img src="libroSTAT_files/figure-html/aed037-1.png" alt="Gráficos matricial de velocidad del viento por tipo de tormenta" width="672" />
<p class="caption">
Figura 6.22: Gráficos matricial de velocidad del viento por tipo de tormenta
</p>
</div>
<p>En ambos casos las interpretaciones son similares a las que se hicieron con el gráfico conjunto de densidad.</p>
<p>Podemos cambiar la configuración cambiando el número de columnas:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="análisis-descriptivo-inicial.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el gráfico</span></span>
<span id="cb126-2"><a href="análisis-descriptivo-inicial.html#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind))  <span class="sc">+</span></span>
<span id="cb126-3"><a href="análisis-descriptivo-inicial.html#cb126-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">bw =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb126-4"><a href="análisis-descriptivo-inicial.html#cb126-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span></span>
<span id="cb126-5"><a href="análisis-descriptivo-inicial.html#cb126-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb126-6"><a href="análisis-descriptivo-inicial.html#cb126-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> type2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span id="fig:aed038"></span>
<img src="libroSTAT_files/figure-html/aed038-1.png" alt="Gráficos matricial de velocidad del viento por tipo de tormenta" width="672" />
<p class="caption">
Figura 6.23: Gráficos matricial de velocidad del viento por tipo de tormenta
</p>
</div>
<p>Aunque el gráfico se visualiza mejor también resulta más difícil la comparación entre todos los niveles.</p>
<p>Si deseamos cambiar la situación de las etiquetas del factor podemos utilizar la opción <code>facet_grid</code>.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="análisis-descriptivo-inicial.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el gráfico</span></span>
<span id="cb127-2"><a href="análisis-descriptivo-inicial.html#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(storm, <span class="fu">aes</span>(<span class="at">x =</span> wind))  <span class="sc">+</span></span>
<span id="cb127-3"><a href="análisis-descriptivo-inicial.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">bw =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb127-4"><a href="análisis-descriptivo-inicial.html#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Wind speed (in knots)&quot;</span>) <span class="sc">+</span></span>
<span id="cb127-5"><a href="análisis-descriptivo-inicial.html#cb127-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb127-6"><a href="análisis-descriptivo-inicial.html#cb127-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(type2 <span class="sc">~</span> .)</span></code></pre></div>
<div class="figure"><span id="fig:aed039"></span>
<img src="libroSTAT_files/figure-html/aed039-1.png" alt="Gráficos matricial (grid) de velocidad del viento por tipo de tormenta" width="672" />
<p class="caption">
Figura 6.24: Gráficos matricial (grid) de velocidad del viento por tipo de tormenta
</p>
</div>
<p>Esta opción nos resultará de mayor utilidad cuando tengamos que representar dos factores ya que se podrá situar en la filas uno de los factores y el otro en las columnas con la opción <code>facet_grid(factor1 ~ factor2)</code>.</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-BreDay80" class="csl-entry">
Breslow, N. E., and N. E. Day. 1980. <span>“The Analysis of Case-Control Studies.”</span> <em>Statistical Methods in Cancer Research</em> Volume 1.
</div>
<div id="ref-ChamCleKleTuk83" class="csl-entry">
Chambers, J. M., W. S. Cleveland, B. Kleiner, and P. A. Tukey. 1983. <em>Graphical Methods for Data Analysis</em>. Wadsworth.
</div>
<div id="ref-Daniel05" class="csl-entry">
Daniel, Wayne W. 2005. <em>Biostatistics</em>. Eighth Edition. Wiley.
</div>
<div id="ref-Krzanowski98" class="csl-entry">
Krzanowski, Wojtek J. 1998. <em>An Introduction to Statistical Modelling</em>. Arnold.
</div>
<div id="ref-HadleyGrolemund16" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science</em>. http://r4ds.had.co.nz/ ed. O’Reilly.
</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="procesado-inicial.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["libroSTAT.pdf", "libroSTAT.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
