<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Unidad 8 Modelos ANOVA | Modelos Estadísticos</title>
<meta name="description" content="Los modelos ANOVA surgen cuando la variable o variables predictoras son de tipo categórico, es decir, factores con diferentes niveles de clasificación, de forma que cada sujeto es medido (respecto...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Unidad 8 Modelos ANOVA | Modelos Estadísticos">
<meta property="og:type" content="book">
<meta property="og:description" content="Los modelos ANOVA surgen cuando la variable o variables predictoras son de tipo categórico, es decir, factores con diferentes niveles de clasificación, de forma que cada sujeto es medido (respecto...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Unidad 8 Modelos ANOVA | Modelos Estadísticos">
<meta name="twitter:description" content="Los modelos ANOVA surgen cuando la variable o variables predictoras son de tipo categórico, es decir, factores con diferentes niveles de clasificación, de forma que cada sujeto es medido (respecto...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="bs4_style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Modelos Estadísticos</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Bienvenidos</a></li>
<li><a class="" href="introlibro.html"><span class="header-section-number">1</span> Comenzamos</a></li>
<li><a class="" href="aed.html"><span class="header-section-number">2</span> Análisis exploratorio de datos</a></li>
<li><a class="" href="prob.html"><span class="header-section-number">3</span> Probabilidad</a></li>
<li><a class="" href="inferencia-b%C3%A1sica.html"><span class="header-section-number">4</span> Inferencia básica</a></li>
<li><a class="" href="modelstats.html"><span class="header-section-number">5</span> Modelos estadísticos</a></li>
<li><a class="" href="rls.html"><span class="header-section-number">6</span> Regresión Lineal Simple (RLS)</a></li>
<li><a class="" href="rlm.html"><span class="header-section-number">7</span> Regresión Lineal Múltiple y Polinómica</a></li>
<li><a class="active" href="anova.html"><span class="header-section-number">8</span> Modelos ANOVA</a></li>
<li><a class="" href="ancova.html"><span class="header-section-number">9</span> Modelos ANCOVA</a></li>
<li><a class="" href="smooth.html"><span class="header-section-number">10</span> Modelos aditivos lineales</a></li>
<li><a class="" href="mmixed.html"><span class="header-section-number">11</span> Modelos Lineales Mixtos</a></li>
<li><a class="" href="glm.html"><span class="header-section-number">12</span> Modelos Lineales Generalizados</a></li>
<li><a class="" href="glmbinomial.html"><span class="header-section-number">13</span> GLM respuesta binomial</a></li>
<li><a class="" href="glmpoisson.html"><span class="header-section-number">14</span> GLM Poisson</a></li>
<li><a class="" href="glmtablascont.html"><span class="header-section-number">15</span> GLM para tablas de contingencia</a></li>
<li><a class="" href="glmsuperv.html"><span class="header-section-number">16</span> GLM para datos de supervivencia</a></li>
<li><a class="" href="referencias.html">Referencias</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="anova" class="section level1" number="8">
<h1>
<span class="header-section-number">Unidad 8</span> Modelos ANOVA<a class="anchor" aria-label="anchor" href="#anova"><i class="fas fa-link"></i></a>
</h1>
<p>Los modelos ANOVA surgen cuando la variable o variables predictoras son de tipo categórico, es decir, factores con diferentes niveles de clasificación, de forma que cada sujeto es medido (respecto de la respuesta) para una combinación específica de los factores considerados. La variable respuesta sigue siendo de tipo numérico y el objetivo principal es el estudio de la media para los diferentes niveles del factor o combinaciones de los factores. No solo se está interesado en comparar los diferentes grupos, sino además en cuantificar numéricamente esas diferencias.</p>
<p>La principal diferencia con los modelos de regresión es que en este caso no modelizamos toda la respuesta observada sino la media observada del conjunto de observaciones para cada nivel del factor. Además, veremos como estos modelos pueden ser descritos en términos de un modelo lineal de regresión lo que nos permite utilizar parte de los procesos de descripción, análisis y diagnóstico utilizamos en los capítulos anteriores. En cada punto de este capítulo estudiaremos las similitudes y diferencias con los modelos de regresión.</p>
<div id="bancos-de-datos-1" class="section level2" number="8.1">
<h2>
<span class="header-section-number">8.1</span> Bancos de datos<a class="anchor" aria-label="anchor" href="#bancos-de-datos-1"><i class="fas fa-link"></i></a>
</h2>
<p>Si las variables explicativas son de tipo factor, el análisis preliminar se realiza mediante gráficos de cajas. Estos gráficos sirven para visualizar relaciones entre una variable continua y un factor. En estos casos, hablar de relación / asociación equivale a hablar de diferencias en la variable continua respecto de los niveles (categorías) del factor. Tales diferencias se detectan cuando los diagramas de cajas no muestran solapamientos en la escala de la variable respuesta. En los modelos de dos vías podremos realizar además un gráfico de interacción, que es un gráfico de líneas donde se representan las medias de las diferentes combinaciones de niveles del factor, y que nos permite establecer una primera conclusión sobre el comportamiento conjunto de ambos factores.</p>
<p>Veamos los diferentes bancos de datos que iremos analizando a lo largo de la unidad.</p>
<p><strong>Ejemplo 1. Datos de Insecticidas.</strong> Este ejemplo contiene los datos de un experimento agronómico para conocer el efecto de diferentes insecticidas (<code>spray</code>) sobre el número de insectos vivos (<code>count</code>) tras un periodo de tratamiento.</p>
<p>Cargamos los datos y realizamos el gráfico descriptivo:</p>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">InsectSprays</span><span class="op">)</span>
<span class="va">insecticidas</span> <span class="op">&lt;-</span> <span class="va">InsectSprays</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">insecticidas</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">spray</span>, y <span class="op">=</span> <span class="va">count</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/unnamed-chunk-1-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se aprecia como el número de insectos vivos es superior cuando usamos los sprays A, B, y F (con medias muy similares). El resto de sprays muestran (medias) una supervivencia inferior. Se observan como dos grupos de sprays, uno con medias altas y otro con medias bajas.</p>
<p><strong>Ejemplo 2. Datos de Envasado.</strong> Se desea estudiar la fabricación de cuatro tipos de máquinas automáticas (<code>maquina</code>) en el cortado de piezas de embutido para envasado. Para ello se toman datos del número de envases sin defecto (<code>produccion</code>) que produce cada máquina durante periodos de una hora.</p>
<p>Cargamos los datos y realizamos el gráfico descriptivo:</p>
<div class="sourceCode" id="cb388"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">maquina</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"M1"</span>, <span class="fl">4</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"M2"</span>, <span class="fl">4</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"M3"</span>, <span class="fl">4</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"M4"</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">produccion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">103</span>, <span class="fl">115</span>, <span class="fl">101</span>, <span class="fl">105</span>, <span class="fl">109</span>, <span class="fl">106</span>, <span class="fl">116</span>, <span class="fl">124</span>, <span class="fl">104</span>, <span class="fl">98</span>, <span class="fl">117</span>, 
                <span class="fl">99</span>, <span class="fl">128</span>, <span class="fl">117</span>, <span class="fl">121</span>, <span class="fl">130</span><span class="op">)</span>
<span class="va">envasado</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">maquina</span>, <span class="va">produccion</span><span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">envasado</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">maquina</span>, y <span class="op">=</span> <span class="va">produccion</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/unnamed-chunk-2-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Cada máquina muestra un nivel de envases sin defecto diferente. La máquina M4 es la que muestra mejores resultados y la M3 los peores.</p>
<p><strong>Ejemplo 3. Datos de venenos.</strong> Se ha realizado un experimento para comprobar la efectividad de diferentes antídotos (AA, AB, AC y AD) frente a diferentes venenos (VA, VB y VC). Para ello se recoge el tiempo de reacción (tiempo) que cada antídoto tarda en hacer efecto para cada veneno.</p>
<p>Cargamos los datos y realizamos el gráfico descriptivo:</p>
<div class="sourceCode" id="cb389"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tiempo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.31</span>, <span class="fl">0.45</span>, <span class="fl">0.46</span>, <span class="fl">0.43</span>, <span class="fl">0.36</span>, <span class="fl">0.29</span>, <span class="fl">0.4</span>, <span class="fl">0.23</span>, 
          <span class="fl">0.22</span>, <span class="fl">0.21</span>, <span class="fl">0.18</span>, <span class="fl">0.23</span>, <span class="fl">0.82</span>, <span class="fl">1.1</span>, <span class="fl">0.88</span>, <span class="fl">0.72</span>, <span class="fl">0.92</span>, <span class="fl">0.61</span>, <span class="fl">0.49</span>, 
          <span class="fl">1.24</span>, <span class="fl">0.3</span>, <span class="fl">0.37</span>, <span class="fl">0.38</span>, <span class="fl">0.29</span>, <span class="fl">0.43</span>, <span class="fl">0.45</span>, <span class="fl">0.63</span>, <span class="fl">0.76</span>, <span class="fl">0.44</span>, <span class="fl">0.35</span>, 
          <span class="fl">0.31</span>, <span class="fl">0.4</span>, <span class="fl">0.23</span>, <span class="fl">0.25</span>, <span class="fl">0.24</span>, <span class="fl">0.22</span>, <span class="fl">0.45</span>, <span class="fl">0.71</span>, <span class="fl">0.66</span>, <span class="fl">0.62</span>, <span class="fl">0.56</span>, 
          <span class="fl">1.02</span>, <span class="fl">0.71</span>, <span class="fl">0.38</span>, <span class="fl">0.3</span>, <span class="fl">0.35</span>, <span class="fl">0.31</span>, <span class="fl">0.33</span><span class="op">)</span>
<span class="va">antidoto</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, 
                     <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, 
                     <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span><span class="op">)</span>, 
                   labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"AA"</span>, <span class="st">"AB"</span>, <span class="st">"AC"</span>, <span class="st">"AD"</span><span class="op">)</span><span class="op">)</span>
<span class="va">veneno</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, 
                   <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, 
                   <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, 
                 labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"VA"</span>, <span class="st">"VB"</span>, <span class="st">"VC"</span><span class="op">)</span><span class="op">)</span>
<span class="va">venenos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">tiempo</span>, <span class="va">antidoto</span>, <span class="va">veneno</span><span class="op">)</span>
<span class="co"># Diagrama de cajas</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">venenos</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">antidoto</span>, y <span class="op">=</span> <span class="va">tiempo</span>, color <span class="op">=</span> <span class="va">veneno</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/unnamed-chunk-3-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb390"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de interacción de medias</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">venenos</span>, 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">antidoto</span>, y <span class="op">=</span> <span class="va">tiempo</span>, group <span class="op">=</span> <span class="va">veneno</span>, color <span class="op">=</span> <span class="va">veneno</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"point"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"line"</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/unnamed-chunk-3-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>En el gráfico de interacción se puede apreciar que antídoto es más efectivo para cada tipo de veneno. demás se puede ver que las curvas del tiempo de reacción (líneas de colores) no tiene el mismo comportamiento lo que indica habitualmente que hay cierto efecto de interacción entre los factores considerados, es decir, existe dos combinaciones antídoto - veneno que presentan resultados significativos (medias distintas).</p>
</div>
<div id="modelos-anova-1-vía" class="section level2" number="8.2">
<h2>
<span class="header-section-number">8.2</span> Modelos ANOVA 1 vía<a class="anchor" aria-label="anchor" href="#modelos-anova-1-v%C3%ADa"><i class="fas fa-link"></i></a>
</h2>
<p>El modelo ANOVA de una vía se plantea cuando tenemos una única variable predictora de tipo categórico y una respuesta de tipo numérico. Dicho modelo se puede describir de forma general, para una muestra de tamaño <span class="math inline">\(n\)</span>, como:</p>
<ul>
<li>Una variable respuesta, <span class="math inline">\(Y\)</span>, de tipo numérico con observaciones <span class="math inline">\(y_1, \ldots ,y_n\)</span>.</li>
<li>Una variable predictora, <span class="math inline">\(F\)</span>, de tipo categórico con <span class="math inline">\(I\)</span> grupos o niveles distintos de tamaños muestrales <span class="math inline">\(n_1, n_2, \ldots , n_I\)</span>, de forma que <span class="math inline">\(n = n_1 + n_2 + \ldots + n_I\)</span>, y el vector de observaciones de la respuesta se puede escribir como:</li>
</ul>
<p><span class="math display">\[
y_{11},\ldots,y_{1n_1},y_{21},\ldots,y_{2n_2},\ldots,y_{I1},\ldots,y_{In_I}
\]</span>
donde el primer subíndice indica el nivel del factor y el segundo la posición dentro del conjunto de datos de dicho nivel del factor.</p>
<ul>
<li>Conjunto <span class="math inline">\(\mu_i\)</span> de medias de todas las observaciones de la respuesta asociadas con el nivel <span class="math inline">\(i\)</span> del factor, es decir:</li>
</ul>
<p><span class="math display">\[
\mu_i = \frac{\sum_{j = 1}^{n_j} y_{ij}}{n_i}; \text{ i = 1, 2,..., I}
\]</span></p>
<ul>
<li>Media global de la respuesta, <span class="math inline">\(\mu\)</span>, que se puede obtener como:</li>
</ul>
<p><span class="math display">\[
\mu = \frac{\sum_{j = 1}^{I} \mu_{j}}{I}
\]</span></p>
<ul>
<li>Incrementos, <span class="math inline">\(\alpha_i\)</span>, de cada una de las medias de cada grupo con respecto a la media global, es decir:</li>
</ul>
<p><span class="math display">\[
\alpha_i= \mu - \mu_i; \text{ i = 1, 2,..., I}
\]</span></p>
<p>El objetivo básico en este tipo de modelos es la comparación de las medias <span class="math inline">\(\mu_i\)</span> para detectar posibles diferencias entre os niveles del factor, es decir, plateamos el contraste de comparación de medias:
<span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mu_1 = \mu_2 = \ldots = \mu_I\\
H_a: &amp; \mbox{Existen dos grupos al menos con medias distintas}
\end{array}
\right.
\]</span></p>
<p>Este contraste es equivalente al que se puede escribir en términos de los incrementos de las medias:
<span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \alpha_1 = \alpha_2 = \ldots = \alpha_I = 0\\
H_a: &amp; \mbox{Al menos hay un incremento distinto de cero}
\end{array}
\right.
\]</span></p>
<p>que tiene una estructura similar al test <span class="math inline">\(F\)</span> de la regresión, donde queremos contrastar si existe algún coeficiente distinto de cero. Esto implica que el modelo ANOVA se puede escribir en términos de un modelo lineal sin más que considerar un conjunto de variables ficticias <span class="math inline">\(X_1,...,X_{I}\)</span> que toman los valores siguientes:</p>
<p><span class="math display">\[
X_i= 
\left\{ 
\begin{array}{ll}
1 &amp; \mbox{si la respuesta pertenece al grupo i}\\
0 &amp; \mbox{en otro caso}
\end{array}
\right.
\]</span></p>
<p>y un efecto común para todos los niveles del factor que viene dado por <span class="math inline">\(\mu\)</span> que denotamos por <span class="math inline">\(\alpha_0\)</span>. La única diferencia entre ambas estructuras de comparación es que la referida a las medias <span class="math inline">\(\mu_i\)</span> tiene <span class="math inline">\(I\)</span> parámetros, mientras que la de los incrementos tiene <span class="math inline">\(I+1\)</span> parámetros. Para hacer equivalentes ambas estructuras añadimos la conocida como restricción de identificabilidad que establece de partida que uno de los incrementos debe ser igual a cero, es decir, que una media de un grupo coincide con la media global. Este es el nivel de referencia que utilizamos como base de comparación con el resto de niveles o grupos del factor.</p>
<p>En esta situación si consideramos <span class="math inline">\(Y_i = \{y_{i1},...,y_{in_i}\}\)</span>, <span class="math inline">\(1_{n_i} = \{1,...,1\}\)</span> un vector de <span class="math inline">\(n_i\)</span> unos, <span class="math inline">\(0_{n_i} = \{0,...,0\}\)</span> un vector de <span class="math inline">\(n_i\)</span> ceros, para cada uno de los niveles <span class="math inline">\(i\)</span> del factor, <span class="math inline">\(\mu = \alpha_0\)</span>, y la restricción de identificabilidad <span class="math inline">\(\alpha_I = 0\)</span> (podríamos elegir cualquier otro <span class="math inline">\(\alpha_j =0\)</span> y obtendríamos el mismo modelo), podemos escribir el modelo ANOVA como:</p>
<p><span class="math display">\[
Y = \left( 
\begin{array}{c}
   Y_1 \\
   Y_2 \\
   \ldots \\
   Y_I \\
\end{array}
\right)
=
\left( 
\begin{array}{ccccc}
   1_{n_1} &amp; 1_{n_1} &amp; 0_{n_1} &amp; \ldots &amp; 0_{n_1} \\
   1_{n_2} &amp; 0_{n_2} &amp; 1_{n_2} &amp; \ldots &amp; 0_{n_2} \\
   \ldots &amp; \ldots &amp; \ldots &amp; \ldots &amp; \ldots \\
   1_{n_I} &amp; 0_{n_I} &amp; 0_{n_I} &amp;\ldots &amp; 1_{n_I} \\
\end{array}
\right)
\left( 
\begin{array}{c}
   \alpha_0 \\
   \alpha_1 \\
  \alpha_2 \\
 \ldots \\
   \alpha_{I_1} \\
\end{array}
\right)
+
\left( 
\begin{array}{c}
   e_1 \\
   e_2 \\
   \ldots \\
   e_n \\
\end{array}
\right) = X\beta + \epsilon
\]</span>
o equivalentemente en términos de las medias como:</p>
<p><span class="math display" id="eq:aovonefac">\[\begin{equation}
\mu_i = \alpha_0 + \alpha_i + \epsilon_i, \text{ para } i = 1, 2,...,k, \text{ con } \alpha_k = 0
\tag{8.1}
\end{equation}\]</span></p>
<p>Las hipótesis de este modelo es que los errores se distribuyen de forma independiente mediante una distribución Normal de media cero y varianza constante <span class="math inline">\(\sigma^2\)</span> para cada uno de los grupos que determina la variable predictora. En esta situación el contraste sobre los incrementos es equivalente al test <span class="math inline">\(F\)</span> de regresión de los modelos RLM.</p>
<div id="especificacion-del-modelo-en-r" class="section level3" number="8.2.1">
<h3>
<span class="header-section-number">8.2.1</span> Especificacion del modelo en <code>R</code><a class="anchor" aria-label="anchor" href="#especificacion-del-modelo-en-r"><i class="fas fa-link"></i></a>
</h3>
<p>A continuación se presenta la especificación en <code>R</code> de los modelos anteriores y de todos los anidados que pueden surgir a partir de ellos, así como su interpretación en términos de contraste de hipótesis o coeficientes asociados a cada efecto presente en el modelo. La especificación en <code>R</code> del modelo dado en la ecuación @ref{eq:aovonefac} para su estimación se realiza a través de la expresión reducida del modelo dada por:
<span class="math display">\[
Y \sim F
\]</span></p>
<p>En este tipo de modelos se plantean varias situaciones de modelos anidados que deberemos estudiar:</p>
<ul>
<li>Modelo con efecto de <span class="math inline">\(F\)</span>:</li>
</ul>
<p><span class="math display" id="eq:modesatoneway">\[\begin{equation}
Y \sim F,
\tag{8.2}
\end{equation}\]</span></p>
<p>Si <span class="math inline">\(F\)</span> resulta significativo, tenemos que se detectan diferencias entre al menos dos medias para los niveles del factor <span class="math inline">\(F\)</span>.</p>
<ul>
<li>Modelo sin efectos:</li>
</ul>
<p><span class="math display" id="eq:modelredoneway">\[\begin{equation}
Y \sim 1
\tag{8.3}
\end{equation}\]</span></p>
<p>En este caso <span class="math inline">\(F\)</span> no resulta significativo y podmeos conluir que las medias de todos los niveles del factor se pueden considerar iguales.</p>
<p>En la práctica el ajuste de este tipo de modelos se puede plantear como una comparación entre los modelos <a href="anova.html#eq:modesatoneway">(8.2)</a> y <a href="anova.html#eq:modelredoneway">(8.3)</a>, dado que están anidados, de forma similar al proceso de comparación de modelos planteado en los modelos RLM y MP.</p>
</div>
</div>
<div id="modelos-anova-dos-vías" class="section level2" number="8.3">
<h2>
<span class="header-section-number">8.3</span> Modelos ANOVA dos vías<a class="anchor" aria-label="anchor" href="#modelos-anova-dos-v%C3%ADas"><i class="fas fa-link"></i></a>
</h2>
<p>El modelo ANOVA de dos vías se presenta cuando consideramos dos variables predictoras de tipo categórico. Si tenemos dos factores <span class="math inline">\(F_1\)</span> y <span class="math inline">\(F_2\)</span> con <span class="math inline">\(I\)</span> y <span class="math inline">\(J\)</span> niveles respectivamente (y utilizando lo visto en el punto anterior), el modelo expresado en términos de las medias de las combinaciones de los diferentes niveles de los factores considerados viene dado por:</p>
<p><span class="math display" id="eq:aovtwofac">\[\begin{equation}
\mu_{ij} = \alpha_0 + \alpha_i + \beta_j + \alpha\beta_{ij} + \epsilon_{ij}, \ \mbox{para} \ i = 1,\ldots,I; \ j = 1,\ldots,J \ \mbox{con} \ \alpha_1 = \beta_1 = \alpha\beta_{11} = 0
\tag{8.4}
\end{equation}\]</span></p>
<p>donde:</p>
<ul>
<li>
<span class="math inline">\(\mu_{ij}\)</span> es la media de la respuesta para el nivel <span class="math inline">\(i\)</span> de <span class="math inline">\(F_1\)</span> y el nivel <span class="math inline">\(j\)</span> de <span class="math inline">\(F_2\)</span>.</li>
<li>
<span class="math inline">\(\alpha_0\)</span> es el efecto común a todas las combinaciones de niveles para ambos factores.</li>
<li>
<span class="math inline">\(\alpha_i\)</span> son los incrementos asociados a cada uno de los niveles del factor <span class="math inline">\(F_1\)</span>.</li>
<li>
<span class="math inline">\(\beta_j\)</span> son los incrementos asociados a cada uno de los niveles del factor <span class="math inline">\(F_2\)</span>.</li>
<li>
<span class="math inline">\(\alpha\beta_{ij}\)</span> son los incrementos asociados a la combinación de los niveles <span class="math inline">\(i\)</span> de <span class="math inline">\(F_1\)</span> y <span class="math inline">\(j\)</span> de <span class="math inline">\(F_2\)</span>. Es lo que se denomina efecto de interacción que valora los cambios en las combinaciones de las medias para ambos factores. Si este efecto no es significativo, la media para una combinación de niveles de los factores se construye sumando los incrementos de cada nivel de forma independiente.</li>
</ul>
<p>Dado que tenemos dos factores se hace necesario añadir más restricciones de identificabildiad. Añadimos una por cada factor y la que aparece de forma inmediata en la interacción de los dos efectos que estamos tomando como cero.</p>
<p>En este caso no escribimos la matriz de diseño del modelo pero se puede escribir considerado la matriz de coeficientes de dimensiones <span class="math inline">\(IJ \times IJ\)</span> que surge para el modelo <a href="anova.html#eq:aovtwofac">(8.4)</a>. Bastará con sustituir los unos y ceros por vectores de unos y ceros de dimensiones adecuadas en función de los tamaños de cada uno de los niveles de los dos factores considerados. Dicha matriz de coeficientes se puede extraer a partir de las ecuaciones completas del modelo <a href="anova.html#eq:aovtwofac">(8.4)</a> (teniendo en cuenta las restricciones de identificabilidad) dadas por:</p>
<p><span class="math display">\[\begin{array}{lll} 
\mu_{11} &amp; = \alpha_0 + \alpha_{1} + \beta_{1} + \alpha\beta_{11} + \epsilon_{11}&amp; = \alpha_0 + \epsilon_{11}\\
\mu_{12} &amp; = \alpha_0 + \alpha_{1} + \beta_{2} + \alpha\beta_{12} + \epsilon_{12}&amp; = \alpha_0 + \beta_{2} + \alpha\beta_{12} + \epsilon_{12}\\
\ldots &amp; \ldots &amp;\ldots\\
\mu_{1J} &amp; = \alpha_0 + \alpha_{1} + \beta_{J} + \alpha\beta_{1J} + \epsilon_{1J}&amp; = \alpha_0 + \beta_{J} + \alpha\beta_{1J} + \epsilon_{1J}\\
\mu_{21} &amp; = \alpha_0 + \alpha_{2} + \beta_{1} + \alpha\beta_{21} + \epsilon_{21}&amp; = \alpha_0 + \alpha_{2} + \alpha\beta_{21} +\epsilon_{11}\\
\mu_{22} &amp; = \alpha_0 + \alpha_{2} + \beta_{2} + \alpha\beta_{22} + \epsilon_{22}&amp; = \alpha_0 +  \alpha_{2} + \beta_{2} + \alpha\beta_{22} + \epsilon_{22}\\
\ldots &amp; \ldots &amp;\ldots\\
\mu_{2J} &amp; = \alpha_0 + \alpha_{2} + \beta_{J} + \alpha\beta_{2J} + \epsilon_{2J}&amp; = \alpha_0 +  \alpha_{2} + \beta_{J} + \alpha\beta_{2J} + \epsilon_{2J}\\
\ldots &amp; \ldots &amp;\ldots\\
\ldots &amp; \ldots &amp;\ldots\\
\ldots &amp; \ldots &amp;\ldots\\
\mu_{I1} &amp; = \alpha_0 + \alpha_{I} + \beta_{1} + \alpha\beta_{I1} + \epsilon_{I1}&amp; = \alpha_0 +  \alpha_{I} +  \alpha\beta_{I1} + \epsilon_{I1}\\
\mu_{I2} &amp; = \alpha_0 + \alpha_{I} + \beta_{2} + \alpha\beta_{I2} + \epsilon_{I2}&amp; = \alpha_0 +  \alpha_{I} + \beta_{2} + \alpha\beta_{I2} + \epsilon_{I2}\\
\ldots &amp; \ldots &amp;\ldots\\
\mu_{IJ} &amp; = \alpha_0 + \alpha_{I} + \beta_{J} + \alpha\beta_{IJ} + \epsilon_{IJ}&amp; = \alpha_0 +  \alpha_{I} + \beta_{J} + \alpha\beta_{IJ} + \epsilon_{IJ}\\
\end{array}\]</span></p>
<p>En este caso el objetivo vuelve a ser la comparación de medias pero el contraste a resolver depende de la especificación del modelo considerado. Hay que tener en cuenta que en este caso no tenemos una única variable predictora, y además hay que valorar la posibilidad de la interacción entre ambos factores.</p>
<div id="especificacion-del-modelo-en-r-1" class="section level3" number="8.3.1">
<h3>
<span class="header-section-number">8.3.1</span> Especificacion del modelo en <code>R</code><a class="anchor" aria-label="anchor" href="#especificacion-del-modelo-en-r-1"><i class="fas fa-link"></i></a>
</h3>
<p>La especificación en <code>R</code> del modelo dado en la ecuación @ref{eq:aovtwofac} para su estimación se realiza a través de la expresión reducida del modelo dada por:</p>
<p><span class="math display" id="eq:modesattwoway">\[\begin{equation}
Y \sim F_1 + F_2 + F_1 : F_2,
\tag{8.5}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(F_1 : F_2\)</span> representa el efecto de interacción, y <span class="math inline">\(F_1\)</span> y <span class="math inline">\(F_2\)</span> son los denominados efectos principales asociados con los factores considerados. En este tipo de modelos se plantean varias situaciones de modelos anidados que deberemos estudiar para establecer cual es el tipo de contraste sobre las medias que estamos resolviendo. Alternativamente ese modelo se puede escribir de forma más reducida como <span class="math inline">\(Y \sim F_1*F_2\)</span>, que es un modelo con los efectos principales de cada factor y con la interacción.</p>
<ul>
<li>Modelo saturado o modelo con todos los factores y la interacción dado por:</li>
</ul>
<p><span class="math display" id="eq:modeltwoway">\[\begin{equation}
Y \sim F_1 + F_2 + F_1 : F_2
\tag{8.6}
\end{equation}\]</span></p>
<p>Si la interacción está presente en el modelo el contraste planteado es:
<span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mbox{No hay diferencias entre las medias conjuntas de ambos niveles del factor}\\
H_a: &amp; \mbox{Al menos hay dos combinaciones de ambos factores con medias distintas}
\end{array}
\right.
\]</span></p>
<p>que nos permite concluir sobre si el efecto de interacción es necesario para explicar el comportamiento de la respuesta. En caso de que dicho contraste resulte no significativo podemos plantear el modelo con ambos efectos principales.</p>
<ul>
<li>Modelo con ambos efectos principales:</li>
</ul>
<p><span class="math display">\[
Y \sim F_1 + F_2
\]</span></p>
<p>donde se parte de que la interacción es no significativa y se plantean dos contrastes (uno por cada factor)</p>
<p><span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mbox{No hay diferencias entre las medias de } F_1\\
H_a: &amp; \mbox{Al menos hay dos medias  de } F_1 \mbox{ distintas}
\end{array}
\right.
\]</span>
Si no rechazamos este contraste deberemos considerar que no hay diferencias en las medias de los niveles establecidos en <span class="math inline">\(F_1\)</span> y debemos considerar un modelo con efecto principal de <span class="math inline">\(F_2\)</span>.</p>
<p><span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mbox{No hay diferencias entre las medias de } F_2\\
H_a: &amp; \mbox{Al menos hay dos medias  de } F_2 \mbox{ distintas}
\end{array}
\right.
\]</span>
Si no rechazamos este contraste deberemos considerar que no hay diferencias en las medias de los niveles establecidos en <span class="math inline">\(F_2\)</span> y debemos considerar un modelo con efecto principal de <span class="math inline">\(F_1\)</span>.</p>
<p>Estos contrastes nos permiten concluir sobre cada factor de forma independiente (no hay interacción entre ellos).</p>
<ul>
<li>Modelo con efecto principal de <span class="math inline">\(F_1\)</span>:</li>
</ul>
<p><span class="math display">\[
Y \sim F_1
\]</span></p>
<p>donde se parte de que la interacción y el efecto principal de <span class="math inline">\(F_2\)</span> son no significativos y se plantea el contraste</p>
<p><span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mbox{No hay diferencias entre las medias de } F_1\\
H_a: &amp; \mbox{Al menos hay dos medias  de } F_1 \mbox{ distintas}
\end{array}
\right.
\]</span></p>
<p>Si no rechazamos este contraste deberemos considerar que no hay diferencias en las medias de los niveles establecidos en <span class="math inline">\(F_1\)</span> y nuestro modelo final no contiene ningún tipo de efecto predictivo.</p>
<ul>
<li>Modelo con efecto principal de <span class="math inline">\(F_2\)</span>:</li>
</ul>
<p><span class="math display">\[
Y \sim F_2
\]</span></p>
<p>donde se parte de que la interacción y el efecto principal de <span class="math inline">\(F_1\)</span> son no significativos y se plantea el contraste</p>
<p><span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: &amp; \mbox{No hay diferencias entre las medias de } F_2\\
H_a: &amp; \mbox{Al menos hay dos medias  de } F_2 \mbox{ distintas}
\end{array}
\right.
\]</span>
Si no rechazamos este contraste deberemos considerar que no hay diferencias en las medias de los niveles establecidos en <span class="math inline">\(F_2\)</span> y nuestro modelo final no contiene ningún tipo de efecto predictivo.</p>
<ul>
<li>Modelo sin efectos:</li>
</ul>
<p><span class="math display">\[
Y \sim 1
\]</span></p>
<p>donde concluimos que todas las medias consideradas son iguales, es decir, los niveles de los factores considerados no tienen efecto sobre la respuesta.</p>
<p>Esta combinación de modelos nos da una estructura secuencial de modelización (modelos alternativos) que deberemos estudiar para elegir el modelo con una mayor capacidad predictiva. Dicha estructura viene dada por:</p>
<p><span class="math display">\[\begin{array}{lll} 
M1: &amp; Y \sim F_1 + F_2 + F_1:F_2\\
M2: &amp; Y \sim F_1 + F_2 \\
M3.1: &amp; Y \sim F_1 \\
M3.2: &amp; Y \sim F_2 \\
M4: &amp; Y \sim 1\\
\end{array}\]</span></p>
<p>Más adelante veremos como llevar a cabo esta comparación secuencial y como interpretarla para determinar los efectos que finalmente están presentes en el modelo y los que no.</p>
</div>
</div>
<div id="estimación-y-bondad-de-ajuste-del-modelo" class="section level2" number="8.4">
<h2>
<span class="header-section-number">8.4</span> Estimación y bondad de ajuste del modelo<a class="anchor" aria-label="anchor" href="#estimaci%C3%B3n-y-bondad-de-ajuste-del-modelo"><i class="fas fa-link"></i></a>
</h2>
<p>Dado que los modelos ANOVA se pueden escribir como modelos lineales de regresión con una matriz de diseño que solo contiene unos y ceros, se pueden utilizar los procedimientos de estimación vistos en el capitulo anterior para estimar los par??metros del modelo. Podemos utilizar las ecuaciones normales para obtener los coeficientes del modelo que en este caso representarán los incrementos de cada nivel con respecto al de referencia (que hemos tomado como cero en la restricción de identificabilidad), que nos permiten obtener las estimaciones de las medias asociadas a cada nivel o niveles del factor o factores. Además, podemos obtener los intervalos de confianza de dichos coeficientes.</p>
<p>Sin embargo, en este caso no se pueden interpretar de forma directa las significatividades de cada coeficiente en el modelo, ya que al contrario de los que ocurría en los modelos de regresión, donde cada coeficiente representaba el efecto de una predictora, en los modelos ANOVA el efecto de la predictora va asociado con todos los coeficientes estimados con el factor o interacción de factores. Por eso es necesario proporcionar una medida de bondad de ajuste con dichas estimaciones que en este caso es el test F ANOVA que se obtiene como el test F de la regresión de los modelos de unidades anteriores. Este test nos permite extraer conclusiones directas sobre los efectos presentes en el modelo y no sobre los coeficientes estimados. En el punto siguiente veremos como utilizar el test F ANOVA para obtener el mejor modelo. En este caso no utilizaremos el <span class="math inline">\(R^2\)</span> como medida de bondad de ajusta ya que se encuentra diseñada para modelos de regresión donde las predictoras son de tipo numérico.</p>
<p>Para resolver la estimación y la bondad de ajuste en este tipo de modelos utilizaremos las funciones utilizadas en la unidad anterior. En algunos casos modificaremos la sintaxis para adaptarnos a las variables predictoras de tipo factor.</p>
<div id="ejemplos-9" class="section level3" number="8.4.1">
<h3>
<span class="header-section-number">8.4.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-9"><i class="fas fa-link"></i></a>
</h3>
<p>Pasamos a estudiar cada uno de los ejemplos ajustando el modelo saturado, es decir, aquel que contiene todos los efectos posibles en el modelo. Por defecto el programa <code>R</code> utiliza como restricción de identificabilidad que el incremento asociado con la primera categoría (por orden numérico o texto de los niveles del factor) es igual a cero, es decir, que la estimación de dicho incremento corresponde con la interceptación o efecto común del modelo.</p>
<p>En las tablas de estimaciones eliminamos el p-valor individual asociado a cada incremento, dado que en este caso esos efectos no deben interpretarse de forma individual.</p>
<div id="datos-de-insecticidas" class="section level4" number="8.4.1.1">
<h4>
<span class="header-section-number">8.4.1.1</span> Datos de Insecticidas<a class="anchor" aria-label="anchor" href="#datos-de-insecticidas"><i class="fas fa-link"></i></a>
</h4>
<p>Obtenemos el ajuste del modelo de ANOVA de un factor para el banco de datos de Insecticidas. La expresión del modelo viene dado por:</p>
<p><span class="math display">\[\mu_{spray,i}=\alpha_0+\alpha_{spray,i}+\epsilon_{spray,i}, \text{para }i=A,B,C,D,E ,F\]</span></p>
<p>donde la restricción de identificabilidad es fijar el incremento del spray A igual a cero, es decir, <span class="math inline">\(\alpha_{spray,A} = 0\)</span>.</p>
<div class="sourceCode" id="cb391"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fit.insecticidas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">count</span> <span class="op">~</span> <span class="va">spray</span>, data <span class="op">=</span> <span class="va">insecticidas</span><span class="op">)</span>
<span class="co"># Inferencia sobre los parámetros del modelo</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.insecticidas</span>, 
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span>, 
          show.p <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
count
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
14.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
12.24 – 16.76
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [B]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.83
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.36 – 4.03
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [C]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-12.42
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-15.61 – -9.22
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [D]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-9.58
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-12.78 – -6.39
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [E]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-11.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-14.20 – -7.80
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [F]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.03 – 5.36
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
72
</td>
</tr>
</table></div>
<p>Las ecuaciones de estimación de las medias del número de insectos vivos se pueden extraer a partir de la tabla de coeficientes estimados. Sin embargo, podemos obtener las estimaciones y representar las medias de todos los sprays haciendo uso de la función <code><a href="https://rdrr.io/r/stats/update.html">update()</a></code> quitando el término de interceptación del modelo. De esta forma se prescinde de la restricción de identificabilidad y se obtienen las medias directamente.</p>
<div class="sourceCode" id="cb392"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo sin interceptación</span>
<span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">fit.insecticidas</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">spray</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>
<span class="co"># Inferencia sin identificabilidad</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">m1</span>, show.r2 <span class="op">=</span> <span class="cn">FALSE</span>, show.p <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
count
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [A]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
14.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
12.24 – 16.76
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [B]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
15.33
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
13.07 – 17.59
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [C]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.18 – 4.34
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [D]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
4.92
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.66 – 7.18
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [E]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.24 – 5.76
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
spray [F]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
16.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
14.41 – 18.93
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
72
</td>
</tr>
</table></div>
<p>En esta tabla podemos ver tanto el valor estimado con el intervalo de confianza al 95% del número de insectos vivos con cada uno de los sprays. De esta forma os sprays A, B, y F son los menos efectivos (medias de insectos vivos más altas), mientras que los otros tres tienen medias significativamente más bajas. El spray C es el que se muestra más efectivo con una media de insectos vivos de 2 (redondeando a entero). Podemos ver gráficamente la solución obtenida mediante:</p>
<div class="sourceCode" id="cb393"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de medias estimadas</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">m1</span>, show.values <span class="op">=</span> <span class="cn">TRUE</span>, vline.color <span class="op">=</span> <span class="st">"yellow"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov002b-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En cuanto a las medidas de bondad de ajuste utilizaremos le test F de igual de medias para establecer si los diferentes sprays considerados tienen un comportamiento similar o al menos hay dos de ellos que se comportan de forma distinta.</p>
<div class="sourceCode" id="cb394"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">fit.insecticidas</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC deviance df.residual
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1     0.724         0.704  3.92      34.7 3.18e-17     5  -197.  409.  425.    1015.          66
## # … with 1 more variable: nobs &lt;int&gt;</code></pre>
<p>Podemos ver que el test F resulta significativo indicando que al menos hay dos medias distintas (algún incremento distinto de cero), lo que implica que al menos hay dos tipos de spray que se comportan de forma diferente con respecto al número de insectos vivos que quedan finalmente.</p>
<p>Dado que el factor considerado es significativo resulta necesario conocer que medias son realmente distintas y cuales podemos considerar iguales. Para realizar esta tarea utilizaremos los denominados tests de comparaciones múltiples que nos permiten comparar dos a dos todas las combinaciones del factor para determinar las que son significativamente distintas o no. En R podemos utilizar la función TukeyHSD que realiza el test de comparaciones múltiples de Tukey. La salida proporciona la diferencia estimada entre cada para de niveles del factor considerado, así como el p-valor asociado con dicha comparación.</p>
<div class="sourceCode" id="cb396"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Test de comparaciones múltiples</span>
<span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">fit.insecticidas</span><span class="op">)</span> </code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = x)
## 
## $spray
##            diff        lwr       upr     p adj
## B-A   0.8333333  -3.866075  5.532742 0.9951810
## C-A -12.4166667 -17.116075 -7.717258 0.0000000
## D-A  -9.5833333 -14.282742 -4.883925 0.0000014
## E-A -11.0000000 -15.699409 -6.300591 0.0000000
## F-A   2.1666667  -2.532742  6.866075 0.7542147
## C-B -13.2500000 -17.949409 -8.550591 0.0000000
## D-B -10.4166667 -15.116075 -5.717258 0.0000002
## E-B -11.8333333 -16.532742 -7.133925 0.0000000
## F-B   1.3333333  -3.366075  6.032742 0.9603075
## D-C   2.8333333  -1.866075  7.532742 0.4920707
## E-C   1.4166667  -3.282742  6.116075 0.9488669
## F-C  14.5833333   9.883925 19.282742 0.0000000
## E-D  -1.4166667  -6.116075  3.282742 0.9488669
## F-D  11.7500000   7.050591 16.449409 0.0000000
## F-E  13.1666667   8.467258 17.866075 0.0000000</code></pre>
<p>Para interpretar la tabla resultante nos debemos fijar en la columna p adj. Todos aquellos inferiores a 0.05 indican que las medias son distintas. Analizando todos los p-valores podemos establecer dos grupos de sprays, el formado por los tipos A, B y F y el formado por los tipos C, D, y E. Dentro de cada grupo no hay diferencias pero sin entres los sprays de grupos distintos.</p>
<p>También podemos representar gráficamente las comparaciones realizadas para que resulte más fácil su interpretación:</p>
<div class="sourceCode" id="cb398"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/plot.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">fit.insecticidas</span><span class="op">)</span>, las<span class="op">=</span><span class="fl">1</span>, tcl <span class="op">=</span> <span class="op">-</span><span class="fl">.3</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov003b-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Los intervalos de confianza que contienen al cero muestran aquellos pares de sprays que pueden considerarse iguales. Los intervalos de confianza a la izquierda de cero muestran las combinaciones de sprays donde el primer spray tiene un efecto menor que el segundo (media negativa), mientras que en la parte derecha tenemos las combinaciones donde el primer spray es superior al segundo. Por ejemplo, podemos concluir: los sprays A y B tienen comportamiento similar; los sprays A y C tienen comportamientos distintos con la media del número de supervivientes en A superior que en con el spray C; los sprays F y E tienen comportamientos distintos con la media del número de supervivientes en F superior que en con el spray E. ¿Qué otras conclusiones podemos extraer?</p>
</div>
<div id="datos-de-envasado" class="section level4" number="8.4.1.2">
<h4>
<span class="header-section-number">8.4.1.2</span> Datos de Envasado<a class="anchor" aria-label="anchor" href="#datos-de-envasado"><i class="fas fa-link"></i></a>
</h4>
<p>Ajustamos un modelo ANOVA de una vía para el conjunto de datos de envasado. En este caso la restricción de identificabilidad es fijar el incremento de Máquina M1 igual a cero, es decir, <span class="math inline">\(\alpha_{maquina,M1} = 0\)</span>.</p>
<p><span class="math display">\[\mu_{maquina,i}=\alpha_0+\alpha_{maquina,i}+\epsilon_{maquina,i}, \text{para }i=M1, M2, M3, M4\]</span>
donde la restricción de identificabilidad es fijar el incremento de Máquina M1 igual a cero, es decir, <span class="math inline">\(\alpha_{maquina,M1} = 0\)</span>.</p>
<div class="sourceCode" id="cb399"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fit.envasado</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span> <span class="va">produccion</span> <span class="op">~</span> <span class="va">maquina</span>, data <span class="op">=</span> <span class="va">envasado</span><span class="op">)</span>
<span class="co"># Inferencia sobre los parámetros del modelo</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.envasado</span>, 
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span>, 
          show.p <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
produccion
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
106.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
98.00 – 114.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M2]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7.75
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.57 – 19.07
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M3]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-12.82 – 9.82
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M4]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
18.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.68 – 29.32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
16
</td>
</tr>
</table></div>
<p>A la vista de los coeficientes la máquina el orden de las máquinas (de mejor a peor, es decir, de mayor número de envases sin defecto a menor) es <span class="math inline">\(M4 &gt; M2 &gt; M1 &gt; M3\)</span>, con media estimadas dadas por:</p>
<div class="sourceCode" id="cb400"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo sin interceptación</span>
<span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">fit.envasado</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">maquina</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>
<span class="co"># Inferencia sin identificabilidad</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">m1</span>, show.r2 <span class="op">=</span> <span class="cn">FALSE</span>, show.p <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
produccion
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M1]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
106.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
98.00 – 114.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M2]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
113.75
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
105.75 – 121.75
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M3]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
104.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
96.50 – 112.50
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
maquina [M4]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
124.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
116.00 – 132.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
16
</td>
</tr>
</table></div>
<p>Vemos la solución gráfica donde se aprecian comportamientos muy diferenciados entre las diferentes máquinas.</p>
<div class="sourceCode" id="cb401"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">m1</span>, show.values <span class="op">=</span> <span class="cn">TRUE</span>, vline.color <span class="op">=</span> <span class="st">"yellow"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov005b-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Con respecto a la bondad del ajuste podemos ver que el test <span class="math inline">\(F\)</span> resulta significativo indicando que al menos alguna de las medias es distinta del resto (algún incremento distinto de cero). Por tanto, existe un efecto del tipo de máquina en el número de envases sin defecto.</p>
<div class="sourceCode" id="cb402"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC deviance df.residual
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1     0.596         0.496  7.35      5.91  0.0102     3  -52.3  115.  118.     648.          12
## # … with 1 more variable: nobs &lt;int&gt;</code></pre>
<p>Realizamos las comparaciones múltiples para comparar todas las máquinas dos a dos.</p>
<div class="sourceCode" id="cb404"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span> </code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = x)
## 
## $maquina
##        diff        lwr       upr     p adj
## M2-M1  7.75  -7.673887 23.173887 0.4716327
## M3-M1 -1.50 -16.923887 13.923887 0.9911761
## M4-M1 18.00   2.576113 33.423887 0.0210561
## M3-M2 -9.25 -24.673887  6.173887 0.3283778
## M4-M2 10.25  -5.173887 25.673887 0.2508228
## M4-M3 19.50   4.076113 34.923887 0.0126965</code></pre>
<p>Tan sólo las combinaciones M4-M1 y M4-M3 muestran resultados significativos indicando que la máquina M4 es comparable con la M2, es decir, la media de envases sin defecto es igual para dichas máquinas, pero distintas de la M1 y M3 que también puede considerarse iguales. Veamos los resultados gráficamente:</p>
<div class="sourceCode" id="cb406"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/plot.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span>, las<span class="op">=</span><span class="fl">1</span>, tcl <span class="op">=</span> <span class="op">-</span><span class="fl">.3</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov006c-1.png" width="95%" style="display: block; margin: auto;"></div>
</div>
<div id="datos-de-venenos" class="section level4" number="8.4.1.3">
<h4>
<span class="header-section-number">8.4.1.3</span> Datos de Venenos<a class="anchor" aria-label="anchor" href="#datos-de-venenos"><i class="fas fa-link"></i></a>
</h4>
<p>Ajustamos un modelo ANOVA de dos vías con interacción entre veneno y antídoto para el conjunto de datos de venenos cuya expresión viene dada por (el índice i hace referencia al antídoto, y el j a los venenos):</p>
<p><span class="math display">\[\mu_{Antidoto:i,Veneno:j} = \alpha_0 + \alpha_{Antidoto:i} +\alpha_{Veneno:j} + \alpha\beta_{Antidoto:i,Veneno:j} + \epsilon_{Antidoto:i,Veneno:j}\]</span>
para <span class="math inline">\(i=AA,AB,AC,AD\)</span>, <span class="math inline">\(j=VA,VB,VC\)</span> con las restricciones de identificabilidad:</p>
<ul>
<li>
<span class="math inline">\(\alpha_{antidoto,AA} = 0\)</span>,</li>
<li>
<span class="math inline">\(\beta_{veneno,VA} = 0\)</span>,</li>
<li>
<span class="math inline">\(\alpha\beta_{Antidoto,AA; Veneno,VA} = 0\)</span>,</li>
</ul>
<p>de forma que el ajuste para este modelo viene dado por:</p>
<div class="sourceCode" id="cb407"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fit.venenos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span> <span class="va">tiempo</span> <span class="op">~</span> <span class="va">antidoto</span><span class="op">*</span><span class="va">veneno</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span>
<span class="co"># Inferencia sobre los parámetros del modelo</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.venenos</span>,
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span>, 
          show.p <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
tiempo
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.26 – 0.56
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.25 – 0.68
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.06 – 0.37
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.02 – 0.41
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.31 – 0.12
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.42 – 0.01
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.27 – 0.33
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.40 – 0.20
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.15 – 0.45
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.34
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.64 – -0.04
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43 – 0.17
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.39 – 0.22
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
48
</td>
</tr>
</table></div>
<p>Desde luego interpretar la tabla de coeficientes en este caso es más complicado, dada la gran cantidad de parámetros involucrados, por lo que resulta más fácil obtener las medias y el gráfico asociado. En este caso no podemos actualizar el modelo eliminando la interceptación dado que tenemos tres restricciones y no una. Modificamos la tabla de estimaciones y el gráfico para obtener todo el conjunto de medias. Además, como no hemos descartado el efecto de interacción, en el gráfico sólo representaremos las medias asociadas con dicho efecto. Para representar el efecto de interacción añadimos el parámetro <code>"int"</code> a la función <code>plot_model</code>.</p>
<div class="sourceCode" id="cb408"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Objeto gráfico</span>
<span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.venenos</span>, <span class="st">"int"</span>, 
           show.stat <span class="op">=</span> <span class="cn">TRUE</span>, 
           title <span class="op">=</span><span class="st">""</span><span class="op">)</span>
<span class="co"># Tabla de estimaciones</span>
<span class="va">p</span><span class="op">$</span><span class="va">data</span></code></pre></div>
<pre><code>## # Predicted values of tiempo
## 
## # veneno = VA
## 
## antidoto | Predicted | group_col |       95% CI
## -----------------------------------------------
##        1 |      0.41 |        VA | [0.27, 0.56]
##        2 |      0.88 |        VA | [0.73, 1.03]
##        3 |      0.57 |        VA | [0.42, 0.71]
##        4 |      0.61 |        VA | [0.46, 0.76]
## 
## # veneno = VB
## 
## antidoto | Predicted | group_col |       95% CI
## -----------------------------------------------
##        1 |      0.32 |        VB | [0.17, 0.47]
##        2 |      0.81 |        VB | [0.67, 0.96]
##        3 |      0.38 |        VB | [0.23, 0.52]
##        4 |      0.67 |        VB | [0.52, 0.81]
## 
## # veneno = VC
## 
## antidoto | Predicted | group_col |       95% CI
## -----------------------------------------------
##        1 |      0.21 |        VC | [0.06, 0.36]
##        2 |      0.33 |        VC | [0.19, 0.48]
##        3 |      0.24 |        VC | [0.09, 0.38]
##        4 |      0.32 |        VC | [0.18, 0.47]</code></pre>
<div class="sourceCode" id="cb410"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de interacción estimado</span>
<span class="va">p</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov008-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>A la vista de la tabla de estimaciones podemos concluir que:</p>
<ul>
<li>El antídoto AA es el menos tiempo tarda en hacer efecto sobre el veneno VA.</li>
<li>El antídoto AA es el menos tiempo tarda en hacer efecto sobre el veneno VB.</li>
<li>El antídoto AA es el menos tiempo tarda en hacer efecto sobre el veneno VC.</li>
</ul>
<p>De esta forma parece que el antídoto AA es el mejor funciona con cualquiera de los venenos pero será necesario estudiar la bondad de ajuste y realizar el proceso de selección para determinar que efectos deben aparecer el modelo, para poder concluir más precisamente sobre el comportamiento de los diferentes antídotos. En el gráfico de estimación del efecto de interacción podemos apreciar de forma más sencillo la relación entre ambos factores. Aunque el antídoto AA muestra los tiempos más bajos, también es cierto que los intervalos de confianza no son muy diferentes de los obtenidos para AC y AD.</p>
<p>Con respecto a la bondad del ajuste podemos ver que el test <span class="math inline">\(F\)</span> resulta significativo indicando que al menos alguna de las medias es distinta del resto (algún incremento distinto de cero). Por tanto, existe un efecto de interacción entre venenos y antídoto que proporciona un tiempo de reacción distinto.</p>
<div class="sourceCode" id="cb411"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">fit.venenos</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC deviance df.residual
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1     0.734         0.653 0.149      9.03 0.000000193    11   30.2 -34.3 -9.98    0.800          36
## # … with 1 more variable: nobs &lt;int&gt;</code></pre>
<p>El p-valor asociado con la interacción resulta no significativo, indicando que dicho efecto puede ser considerado nulo y no se debería considerarse en el modelo. Vemos aquí la diferencia entre la interpretación del test F para el modelo ANOVA de una vía y el ANOVA de dos vías. En este último caso es necesario el estudio de la tabla ANOVA para determinar los efectos significativos y no basta solo con la bondad del ajuste. En el punto siguiente vemos como realizar la selección del mejor modelo en este tipo de situaciones.</p>
</div>
</div>
</div>
<div id="comparación-y-selección-de-modelos-1" class="section level2" number="8.5">
<h2>
<span class="header-section-number">8.5</span> Comparación y selección de modelos<a class="anchor" aria-label="anchor" href="#comparaci%C3%B3n-y-selecci%C3%B3n-de-modelos-1"><i class="fas fa-link"></i></a>
</h2>
<p>La comparación de modelos se basa en determinar la capacidad explicativa de cada uno de los efectos presentes en el modelo. Mientras que en los modelos de regresión esos efectos van asociados con un único coeficiente del modelo (pendiente asociada a la predictora), en los modelos ANOVA el efecto de un factor va asociado con todos los incrementos establecidos. En realidad, tendremos un efecto significativo cuando detectemos diferencias entre al menos dos medias de la respuesta para los diferentes niveles del factor. Dado que el número de modelos que podemos construir en estas situaciones es limitado, podríamos construirlos todos ellos y compararlos de golpe para decidir el mejor modelo. Esto se puede hacer con el test F de comparación de modelos que es una versión del test F para un contraste especifico, o bien utilizar el criterio del AIC o BIC y quedarnos con aquel modelo que de un valor más pequeño. En modelos más complejos optaremos por un procedimiento automático por pasos empezando por el modelo saturado.</p>
<p>En los modelos ANOVA de una vía la selección del modelo se basa únicamente en el análisis de bondad de ajuste, ya que el test F que obtenemos es realmente la comparación entre los modelos que contienen el factor y el que no lo contiene, mientras que los modelos de más de una vía es necesario realizar el proceso de selección de efectos para determinar el modelo final.</p>
<p>A continuación presentamos las diferentes opciones con el banco de datos de venenos ya que en los otros dos casos ya hemos resulto la selección mediante el análisis de la bondad del ajuste.</p>
<div id="ejemplos-10" class="section level3" number="8.5.1">
<h3>
<span class="header-section-number">8.5.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-10"><i class="fas fa-link"></i></a>
</h3>
<p>Realizamos la selección le mejor modelo par el banco de datos de venenos. En primer lugar procederemos de forma manual considerando todos los posibles modelos con las combinaciones de los factores considerados:</p>
<ul>
<li>
<span class="math inline">\(tiempo ∼veneno∗antidoto\)</span>: Modelo con interacción, donde hay al menos una combinación de veneno y antídoto con tiempo de reacción medio distinto de otras combinaciones.</li>
<li>
<span class="math inline">\(tiempo∼veneno+antidoto\)</span>: Modelo sin interacción con efectos principales, donde el efecto del veneno y el antídoto tiene un efecto aditivo en e tiempo medio de reacción.</li>
<li>
<span class="math inline">\(tiempo∼veneno\)</span>: Modelo con efecto principal marginal del veneno, donde hay almenos un tipo de veneno con un tiempo medio de reacción distinto pero los antidotos no tienen efecto.</li>
<li>
<span class="math inline">\(tiempo∼antidoto\)</span>: Modelo con efecto principal marginal del antídoto, donde hay al menos un tipo de antídoto con un tiempo medio de reacción distinto pero los venenos no tienen efecto.</li>
<li>
<span class="math inline">\(tiempo∼1\)</span>: Modelo sin efectos, donde el tiempo de reacción no cambia con el antídoto y el tipo de veneno.</li>
</ul>
<p>En este caso la especificación de todos los posibles modelos así como su comparación resulta más costosa ya que están involucrados dos factores de clasificación. Los posibles modelos son:</p>
<ul>
<li>
<span class="math inline">\(tiempo \sim veneno * antidoto\)</span>: Modelo con interacción, donde hay al menos una combinación de veneno y antídoto con tiempo de reacción medio distinto de otras combinaciones.</li>
<li>
<span class="math inline">\(tiempo \sim veneno + antidoto\)</span>: Modelo sin interacción con efectos principales, donde el efecto del veneno y el antídoto tiene un efecto aditivo en e tiempo medio de reacción.</li>
<li>
<span class="math inline">\(tiempo \sim veneno\)</span>: Modelo con efecto principal marginal del veneno, donde hay almenos un tipo de veneno con un tiempo medio de reacción distinto pero los antidotos no tienen efecto.</li>
<li>
<span class="math inline">\(tiempo \sim antidoto\)</span>: Modelo con efecto principal marginal del antídoto, donde hay al menos un tipo de antídoto con un tiempo medio de reacción distinto pero los venenos no tienen efecto.</li>
<li>
<span class="math inline">\(tiempo \sim 1\)</span>: Modelo sin efectos, donde el tiempo de reacción no cambia con el antídoto y el tipo de veneno.</li>
</ul>
<p>Consideramos en primer lugar la comparación entre los modelos con y sin interacción para determinar si dicho efecto es relevante o no para explicar el comportamiento del tiempo medio de reacción. Obtenemos el contraste F parcial mediante:</p>
<div class="sourceCode" id="cb413"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo con interacción</span>
<span class="va">fit1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">tiempo</span> <span class="op">~</span> <span class="va">antidoto</span> <span class="op">+</span> <span class="va">veneno</span> <span class="op">+</span> <span class="va">antidoto</span><span class="op">:</span><span class="va">veneno</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span>
<span class="co"># Ajuste del modelo sin interacción</span>
<span class="va">fit2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">tiempo</span> <span class="op">~</span> <span class="va">antidoto</span> <span class="op">+</span> <span class="va">veneno</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span> 
<span class="co"># Comparación entre modelos</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit2</span>, <span class="va">fit1</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: tiempo ~ antidoto + veneno
## Model 2: tiempo ~ antidoto + veneno + antidoto:veneno
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     42 1.0504                           
## 2     36 0.8001  6   0.25027 1.8768 0.1118</code></pre>
<p>Dado que el p-valor no es significativo (p-valor &gt; 0.05) podemos concluir que ambos modelos pueden ser considerarse como iguales, es decir, el efecto de interacción no resulta significativo. Vamos a comparar las estimaciones de ambos modelos y representamos gráficamente el modelo sin interacción. En este caso obtendremos un gráfico por cada factor dado que no actúan de forma conjunta sino de forma aditiva. Utilizamos el parámetro “pred” para obtener las estimaciones de las medias asociadas a cada factor.</p>
<div class="sourceCode" id="cb415"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimaciones de ambos modelos</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit1</span>, <span class="va">fit2</span>, show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> </code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
tiempo
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
tiempo
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.26 – 0.56
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.34 – 0.57
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.25 – 0.68
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.36
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.23 – 0.49
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.06 – 0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.150
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.05 – 0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.232
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.02 – 0.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.069
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.35
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>0.002</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.31 – 0.12
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.386
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.07
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.19 – 0.04
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.198
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.42 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.063
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.34
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.45 – -0.23
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.27 – 0.33
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.855
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.40 – 0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.507
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD] * veneno<br>[VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.15 – 0.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.321
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.34
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.64 – -0.04
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.028</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43 – 0.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.389
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD] * veneno<br>[VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.39 – 0.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.572
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
48
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
48
</td>
</tr>
</table></div>
<div class="sourceCode" id="cb416"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico del modelo sin interacción</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit2</span>, <span class="st">"pred"</span><span class="op">)</span></code></pre></div>
<pre><code>## $antidoto</code></pre>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov017-1.png" width="95%" style="display: block; margin: auto;"></div>
<pre><code>## 
## $veneno</code></pre>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov017-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Como era de esperar, dado que la interacción no es significativa, los coeficientes estimados (incrementos respecto de las medias de referencia dadas por el antídoto AA y el veneno VA) no varían sustancialmente entre ambos modelos. En el gráfico podemos ver que el veneno con un tiempo de reacción más pequeño es el asociado con el veneno VC, mientras que si nos fijamos en el antídoto, el menor tiempo de reacción se da para el AA. Dado que no hay interacción el modelo sugiere que independientemente del veneno utilizado, el antídoto más efectivo es el AA, seguido por el AC, AD, y por último el AB. Se pueden obtener las estimaciones asociadas con el modelo sin interacción para verificar este hecho.</p>
<p>Este proceso manual resulta complicado de llevar a cabo cuando tenemos modelos más complejos (con más de dos vías de clasificación), por lo que es necesario utilizar procedimientos secuenciales automáticos para alcanzar el mejor modelo. A continuación se muestra como realizar esta selección:</p>
<div class="sourceCode" id="cb419"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Selección basada en test F</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_backward_p.html">ols_step_backward_p</a></span><span class="op">(</span><span class="va">fit.venenos</span>, prem <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## 
##                               Elimination Summary                               
## -------------------------------------------------------------------------------
##         Variable                         Adj.                                      
## Step        Removed        R-Square    R-Square     C(p)       AIC        RMSE     
## -------------------------------------------------------------------------------
##    1    antidoto:veneno      0.6508      0.6092    5.2608    -33.2407    0.1581    
## -------------------------------------------------------------------------------</code></pre>
<p>Como era de esperar el proceso determina que podemos prescindir del efecto de interacción.</p>
<p>Para utilizar el criterio AIC utilizamos la función <code><a href="https://rdrr.io/r/stats/step.html">step()</a></code> porque la función <code>ols_step_backward_aic</code> esta diseñada específicamente para trabajar con preditores numéricos y no con interacciones de factores lo que puede llevar a soluciones erróneas. Por tanto, la única opción pasa por evaluar todos los modelos con la función <code>ols_step_all_possible</code> y elegir el mejor de ellos teniendo en cuenta la construcción del modelo. Sin embargo, esta forma de proceder no será práctica en modelos más complejos.</p>
<div class="sourceCode" id="cb421"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Selección con función step y AIC</span>
<span class="fu">stats</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">fit.venenos</span>, direction <span class="op">=</span> <span class="st">"backward"</span><span class="op">)</span></code></pre></div>
<pre><code>## Start:  AIC=-172.52
## tiempo ~ antidoto * veneno
## 
##                   Df Sum of Sq    RSS     AIC
## &lt;none&gt;                         0.8001 -172.52
## - antidoto:veneno  6   0.25027 1.0504 -171.46</code></pre>
<pre><code>## 
## Call:
## lm(formula = tiempo ~ antidoto * veneno, data = venenos)
## 
## Coefficients:
##         (Intercept)           antidotoAB           antidotoAC           antidotoAD  
##              0.4125               0.4675               0.1550               0.1975  
##            venenoVB             venenoVC  antidotoAB:venenoVB  antidotoAC:venenoVB  
##             -0.0925              -0.2025               0.0275              -0.1000  
## antidotoAD:venenoVB  antidotoAB:venenoVC  antidotoAC:venenoVC  antidotoAD:venenoVC  
##              0.1500              -0.3425              -0.1300              -0.0850</code></pre>
<p>El proceso indica que no podemos descartar el efecto de interacción contradiciendo los resultados obtenidos con el test F, aunque la diferencia entre los valores de AIC es muy pequeña. Habitualmente para este tipo de modelos se suele utilizar el criterio basado en el test F, dado que ambos pueden llevar a soluciones distintas como ocurre en este caso.</p>
</div>
</div>
<div id="diagnóstico-1" class="section level2" number="8.6">
<h2>
<span class="header-section-number">8.6</span> Diagnóstico<a class="anchor" aria-label="anchor" href="#diagn%C3%B3stico-1"><i class="fas fa-link"></i></a>
</h2>
<p>Los procedimientos de diagnóstico son los mismos que en los modelos de regresión salvo por el hecho de que la igualdad de varianzas de los residuos se debe cumplir para cada uno de los grupos determinados por los niveles de los factores, es decir, varianzas residuales iguales. Para este tipo de modelos utilizaremos el test de Kolmogorov-Smirnov para el test de normalidad y el de Levene para la homogeneidad de varianzas</p>
<p>También se pueden realizar los diagnósticos gráficos de residuos para cada hipótesis pero en estos modelos sólo tiene sentido realizar los diagramas de cajas de residuos versus niveles del factor para valorar linealidad y varianza constante, dado que en este tipo de modelos tenemos un único valor ajustado (media) para todos los sujetos de un mismo nivel del factor, y por tanto un mismo residuo para todos los sujetos de un mismo grupo. En cuanto al estudio de influencia, nos centraremos principalmente en la distancia de Cook dado que no tiene sentido considerar la influencia sobre los coeficientes del modelo ni sobre los valores ajustados dada la estructura agrupada del banco de datos a analizar, es decir, cada coeficiente no representa una variable sino que debemos considerar el conjunto de ellos que representan el efecto de un factor.</p>
<p>Para realizar el diagnóstico partiremos del modelo ajustado en el apartado anterior para cada banco de datos.</p>
<div id="ejemplos-11" class="section level3" number="8.6.1">
<h3>
<span class="header-section-number">8.6.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-11"><i class="fas fa-link"></i></a>
</h3>
<p>Para realizar el diagnóstico partiremos del modelo ajustado en el apartado anterior para cada banco de datos. En caso de detectar algún problema con las hipótesis del modelo deberemos ajustar un nuevo modelo y verificar que cumple las hipótesis.</p>
<div id="datos-de-insecticidas-1" class="section level4" number="8.6.1.1">
<h4>
<span class="header-section-number">8.6.1.1</span> Datos de insecticidas<a class="anchor" aria-label="anchor" href="#datos-de-insecticidas-1"><i class="fas fa-link"></i></a>
</h4>
<p>Obtenemos los valores de diagnóstico y realizamos los correspondientes tests de hipótesis y análisis de influencia para el banco de datos de insecticidas. En primer lugar realizamos el gráfico cajas de residuos versus niveles del factor para valorar la hipótesis de linealidad y varianza constante.</p>
<div class="sourceCode" id="cb424"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Valores de diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.insecticidas</span><span class="op">)</span>
<span class="co"># Gráfico de residuos vs factor</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">diagnostico</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">spray</span>, y <span class="op">=</span> <span class="va">.stdresid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov021-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En el gráfico se observa como la variabilidad dentro de cada nivel del factor parece diferente, aunque los residuos parecen tener un comportamiento lineal alrededor del cero.</p>
<div class="sourceCode" id="cb425"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de normalidad</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_test_normality.html">ols_test_normality</a></span><span class="op">(</span><span class="va">fit.insecticidas</span><span class="op">)</span> </code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9601         0.0223 
## Kolmogorov-Smirnov        0.1301         0.1747 
## Cramer-von Mises          6.6076         0.0000 
## Anderson-Darling          1.2015         0.0037 
## -----------------------------------------------</code></pre>
<p>El test de Kolmogorov-Smirnov resulta no significativo indicando el cumplimiento de la hipótesis de Normalidad de los residuos.</p>
<div class="sourceCode" id="cb427"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de homogeneidad de varianzas</span>
<span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">.stdresid</span> <span class="op">~</span> <span class="va">spray</span>, data <span class="op">=</span> <span class="va">diagnostico</span><span class="op">)</span> </code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value   Pr(&gt;F)   
## group  5  3.8214 0.004223 **
##       66                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>El test resulta significativo (p-valor inferior a 0.05) indicando que no se verifica la hipótesis de varianza constante, como ya sospechábamos del gráfico de los residuos. Podemos ver si el incumplimiento es debido a algún valor influyente, pero sino es así deberemos plantear alguna transformación de la respuesta para tratar de corregir los problemas de diagnóstico. Se puede verificar que el análisis de la distancia de Cook no presenta ninguna observación influyente, por lo que lo ideal sería plantear la transformación de Box-Cox para encontrar una solución a esta situación pero dado que tenemos valores de cero en la respuesta esto no resulta posible. Sin embargo puesto que la respuesta son datos de conteos podemos utilizar la función logaritmo añadiendo un uno a los valores de la respuesta para evitar problemas en la transformación.</p>
<div class="sourceCode" id="cb429"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculamos la nueva variable</span>
<span class="va">insecticidas</span> <span class="op">&lt;-</span> <span class="va">insecticidas</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>lcount <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">count</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>¿qué ajuste tenemos con esa nueva variable? ¿Cómo es la bondad del ajuste?¿se verifican ahora las hipótesis del modelo?</p>
</div>
<div id="datos-de-envasado-1" class="section level4" number="8.6.1.2">
<h4>
<span class="header-section-number">8.6.1.2</span> Datos de envasado<a class="anchor" aria-label="anchor" href="#datos-de-envasado-1"><i class="fas fa-link"></i></a>
</h4>
<p>Obtenemos los valores de diagnóstico y realizamos los correspondientes tests de hipótesis y análisis de influencia.</p>
<div class="sourceCode" id="cb430"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Valores de diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span>
<span class="co"># Gráfico</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">diagnostico</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">maquina</span>, y <span class="op">=</span> <span class="va">.stdresid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov027-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb431"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de hipótesis</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_test_normality.html">ols_test_normality</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span></code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9074         0.1058 
## Kolmogorov-Smirnov        0.176          0.6420 
## Cramer-von Mises          1.5833         0.0000 
## Anderson-Darling          0.5552         0.1269 
## -----------------------------------------------</code></pre>
<div class="sourceCode" id="cb433"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">.stdresid</span> <span class="op">~</span> <span class="va">maquina</span>, data <span class="op">=</span> <span class="va">diagnostico</span><span class="op">)</span></code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  3  0.2091 0.8882
##       12</code></pre>
<div class="sourceCode" id="cb435"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Análisis de influencia</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_plot_cooksd_chart.html">ols_plot_cooksd_chart</a></span><span class="op">(</span><span class="va">fit.envasado</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov027-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Los tests de hipótesis resultan no significativos indicando que el modelo propuesto verifica dichas hipótesis. No se detectan además observaciones influyentes, con lo que el modelo propuesto y que fue analizado en la sección de estimación es el modelo final para este banco de datos.</p>
</div>
<div id="datos-de-venenos-1" class="section level4" number="8.6.1.3">
<h4>
<span class="header-section-number">8.6.1.3</span> Datos de venenos<a class="anchor" aria-label="anchor" href="#datos-de-venenos-1"><i class="fas fa-link"></i></a>
</h4>
<p>Utilizamos el modelo sin interacción que hemos obtenido tras el proceso de selección de efectos tratada en la sección anterior.</p>
<div class="sourceCode" id="cb436"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo</span>
<span class="va">fit.venenos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">tiempo</span> <span class="op">~</span> <span class="va">veneno</span> <span class="op">+</span> <span class="va">antidoto</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span>
<span class="co"># Valores de diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.venenos</span><span class="op">)</span>
<span class="co"># Tests de hipótesis</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_test_normality.html">ols_test_normality</a></span><span class="op">(</span><span class="va">fit.venenos</span><span class="op">)</span></code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9221         0.0035 
## Kolmogorov-Smirnov        0.113          0.5353 
## Cramer-von Mises         12.0813         0.0000 
## Anderson-Darling          0.8952         0.0205 
## -----------------------------------------------</code></pre>
<p>El test de Kolmogorov-Smirnov resulta no significativo indicando el cumplimiento de la hipótesis de normalidad.</p>
<div class="sourceCode" id="cb438"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">.stdresid</span> <span class="op">~</span> <span class="va">veneno</span><span class="op">*</span><span class="va">antidoto</span>, data <span class="op">=</span> <span class="va">diagnostico</span><span class="op">)</span></code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value    Pr(&gt;F)    
## group 11  4.1582 0.0005539 ***
##       36                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>El test de Leven resulta significativo indicando que no se cumple la hipótesis de varianza constante. Se plantea utilizar Box-Cox para obtener una posible transformación de la respuesta que permita verificar las hipótesis del modelo.</p>
<div class="sourceCode" id="cb440"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/boxcox.html">boxcox</a></span><span class="op">(</span><span class="va">fit.venenos</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov030-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se puede ver que el intervalo de confianza para la transformación contiene el valor de -1. Esto nos da indicios de que podríamos utilizar la transformación inversa para corregir los problemas detectados de homogeneidad de varianzas. En ese caso habrá que tener en cuenta que todas nuestras conclusiones se basarán en dicha transformación. Comenzamos de nuevo con la construcción del modelo.</p>
<div class="sourceCode" id="cb441"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Creamos la variable transformada</span>
<span class="va">venenos</span> <span class="op">&lt;-</span> <span class="va">venenos</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>tiempoinv <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">tiempo</span><span class="op">)</span>
<span class="co"># Ajustamos el modelo de nuevo</span>
<span class="va">fit.venenos.inv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">tiempoinv</span> <span class="op">~</span> <span class="va">antidoto</span><span class="op">*</span><span class="va">veneno</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span>
<span class="co"># Selección utilizando el test F</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_backward_p.html">ols_step_backward_p</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span>, prem <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## 
##                              Elimination Summary                               
## ------------------------------------------------------------------------------
##         Variable                         Adj.                                     
## Step        Removed        R-Square    R-Square     C(p)       AIC       RMSE     
## ------------------------------------------------------------------------------
##    1    antidoto:veneno      0.8454       0.827    0.4181    75.5483    0.4911    
## ------------------------------------------------------------------------------</code></pre>
<p>El modelo resultante es aquel que no contiene la interacción. Obtenemos los coeficientes de ese modelo, así como las medias estimadas para la combinación de veneno-antídoto. Expresamos las medias con la transformación propuesta.</p>
<div class="sourceCode" id="cb443"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo sin interacción</span>
<span class="va">fit.venenos.inv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">tiempoinv</span> <span class="op">~</span> <span class="va">antidoto</span> <span class="op">+</span> <span class="va">veneno</span>, data <span class="op">=</span> <span class="va">venenos</span><span class="op">)</span>
<span class="co"># Estimaciones de ambos modelos</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span>, show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
tiempoinv
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.70
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.35 – 3.05
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.66
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.06 – -1.25
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.57
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.98 – -0.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.007</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
antidoto [AD]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.35
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.76 – -0.95
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VB]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.12 – 0.82
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.010</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
veneno [VC]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.65 – 2.35
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
48
</td>
</tr>
</table></div>
<p>Las ecuaciones de estimación son:</p>
<p><span class="math display">\[\begin{array}{lll} 
1/\mu_{AA,VA} &amp; = \alpha_0 + \alpha_{AA} + \beta_{VA} &amp; = 2.70 + 0 + 0 = 2.70\\
1/\mu_{AA,VB} &amp; = \alpha_0 + \alpha_{AA} + \beta_{VB} &amp; = 2.70 + 0 + 0.47 = 3.17\\
1/\mu_{AA,VC} &amp; = \alpha_0 + \alpha_{AA} + \beta_{VC} &amp; = 2.70 + 0 + 2.00 = 4.70\\
1/\mu_{AB,VA} &amp; = \alpha_0 + \alpha_{AB} + \beta_{VA} &amp; = 2.70 - 1.66 + 0 = 1.04\\
1/\mu_{AB,VB} &amp; = \alpha_0 + \alpha_{AB} + \beta_{VB} &amp; = 2.70 - 1.66 + 0.47 = 1.51\\
1/\mu_{AB,VC} &amp; = \alpha_0 + \alpha_{AB} + \beta_{VC} &amp; = 2.70 - 1.66 + 2.00 = 3.04\\
1/\mu_{AC,VA} &amp; = \alpha_0 + \alpha_{AC} + \beta_{VA} &amp; = 2.70 - 0.57 + 0 = 2.13\\
1/\mu_{AC,VB} &amp; = \alpha_0 + \alpha_{AC} + \beta_{VB} &amp; = 2.70 - 0.57 + 0.47 = 2.60\\
1/\mu_{AC,VC} &amp; = \alpha_0 + \alpha_{AC} + \beta_{VC} &amp; = 2.70 - 0.57 + 2.00 = 4.13\\
1/\mu_{AD,VA} &amp; = \alpha_0 + \alpha_{AD} + \beta_{VA} &amp; = 2.70 - 1.35 + 0 = 1.35\\
1/\mu_{AD,VB} &amp; = \alpha_0 + \alpha_{AD} + \beta_{VB} &amp; = 2.70 - 1.35 + 0.47 = 1.82\\
1/\mu_{AD,VC} &amp; = \alpha_0 + \alpha_{AD} + \beta_{VC} &amp; = 2.70 - 1.35 + 2.00 = 3.35\\
\end{array}\]</span></p>
<p>Veamos si se verifican las hipótesis del modelo:</p>
<div class="sourceCode" id="cb444"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Valores de diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span><span class="op">)</span>
<span class="co"># Tests de hipótesis</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_test_normality.html">ols_test_normality</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span><span class="op">)</span></code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9789         0.5339 
## Kolmogorov-Smirnov        0.1057         0.6192 
## Cramer-von Mises          6.0617         0.0000 
## Anderson-Darling          0.2948         0.5834 
## -----------------------------------------------</code></pre>
<div class="sourceCode" id="cb446"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">.stdresid</span> <span class="op">~</span> <span class="va">veneno</span><span class="op">*</span><span class="va">antidoto</span>, data <span class="op">=</span> <span class="va">diagnostico</span><span class="op">)</span></code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group 11  1.1672 0.3429
##       36</code></pre>
<div class="sourceCode" id="cb448"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Análisis de influencia</span>
<span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_plot_cooksd_chart.html">ols_plot_cooksd_chart</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov032-2-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se verifican las hipótesis del modelo. La transformación planteada permite obtener un modelo válido para la fase de predicción, y nos permite extraer conclusiones sobre la relación entre veneno y antídoto con el tiempo de reacción.</p>
</div>
</div>
</div>
<div id="predicción-1" class="section level2" number="8.7">
<h2>
<span class="header-section-number">8.7</span> Predicción<a class="anchor" aria-label="anchor" href="#predicci%C3%B3n-1"><i class="fas fa-link"></i></a>
</h2>
<p>El proceso de predicción en este tipo de modelos es muy simple ya que los posibles valores de las predictoras coincide con las medias de los posibles niveles o combinación de los niveles del factor o factores que aparezcan en el modelo final. En este caso solo tiene sentido predecir los valores de la media ya que nuestro objetivo es el estudio de dichas medias. Veremos además como representar gráficamente los resultados de la predicción.</p>
<div id="ejemplos-12" class="section level3" number="8.7.1">
<h3>
<span class="header-section-number">8.7.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-12"><i class="fas fa-link"></i></a>
</h3>
<p>Obtenemos las tablas de medias estimadas para cada uno de los ejemplos tratados en esta unidad.</p>
<div id="datos-de-insecticidas-2" class="section level4" number="8.7.1.1">
<h4>
<span class="header-section-number">8.7.1.1</span> Datos de insecticidas<a class="anchor" aria-label="anchor" href="#datos-de-insecticidas-2"><i class="fas fa-link"></i></a>
</h4>
<p>Estamos interesados en predcir el número de insectos muertos en función del tipo de insecticida utilizado. Podemos obtener la tabla de predicción y el gráfico asociado con el código siguiente:</p>
<div class="sourceCode" id="cb449"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Objeto gráfico</span>
<span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.insecticidas</span>, <span class="st">"pred"</span>, terms <span class="op">=</span> <span class="st">"spray"</span>,
           show.stat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co"># Tabla de estimaciones</span>
<span class="va">p</span><span class="op">$</span><span class="va">data</span></code></pre></div>
<pre><code>## # Predicted values of count
## 
## spray | Predicted | group_col |         95% CI
## ----------------------------------------------
##     1 |     14.50 |         1 | [12.28, 16.72]
##     2 |     15.33 |         1 | [13.11, 17.55]
##     3 |      2.08 |         1 | [-0.14,  4.30]
##     4 |      4.92 |         1 | [ 2.70,  7.14]
##     5 |      3.50 |         1 | [ 1.28,  5.72]
##     6 |     16.67 |         1 | [14.45, 18.89]</code></pre>
<p>Para obtener el verdadero valor de la media debemos deshacer la transformación utilizada para el ajuste del modelo. Representamos la media predicha así como un intervalo de predicción para ella. Ordenamos los valores obtenidos de mayor a menor predicción para una mejor visualización.</p>
<div class="sourceCode" id="cb451"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Secuencia de valores de predicción</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>spray <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">insecticidas</span><span class="op">$</span><span class="va">spray</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Predicción para la media de la respuesta</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">newdata</span>, 
            <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">fit.insecticidas</span>, <span class="va">newdata</span>, interval <span class="op">=</span> <span class="st">"confidence"</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Deshacemos la transformación</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="va">newdata</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prediccion <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span>,
                              lower <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">lwr</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span>, 
                              upper <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">upr</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>
<span class="co"># Gráfico ordenado del menor al mayor valor en función del tipo de spray</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">newdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_reorder.html">fct_reorder</a></span><span class="op">(</span><span class="va">spray</span>, <span class="va">prediccion</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">prediccion</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">lower</span>, ymax <span class="op">=</span> <span class="va">upper</span><span class="op">)</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Spray"</span>, y <span class="op">=</span> <span class="st">"Conteo"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov033b-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>¿Qué podemos decir del gráfico de predicción de medias obtenido? ¿ Qué insecticida es más efectivo y cual menos?</p>
</div>
<div id="datos-de-envasado-2" class="section level4" number="8.7.1.2">
<h4>
<span class="header-section-number">8.7.1.2</span> Datos de envasado<a class="anchor" aria-label="anchor" href="#datos-de-envasado-2"><i class="fas fa-link"></i></a>
</h4>
<p>Podemos obtener la tabla de predicción y el gráfico asociado con el código siguiente:</p>
<div class="sourceCode" id="cb452"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Objeto gráfico</span>
<span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.envasado</span>, <span class="st">"pred"</span>, terms <span class="op">=</span> <span class="st">"maquina"</span>,
           show.stat <span class="op">=</span> <span class="cn">TRUE</span>, 
           title <span class="op">=</span> <span class="st">" "</span><span class="op">)</span>
<span class="co"># Tabla de estimaciones</span>
<span class="va">p</span><span class="op">$</span><span class="va">data</span></code></pre></div>
<pre><code>## # Predicted values of produccion
## 
## maquina | Predicted | group_col |           95% CI
## --------------------------------------------------
##       1 |    106.00 |         1 | [ 98.80, 113.20]
##       2 |    113.75 |         1 | [106.55, 120.95]
##       3 |    104.50 |         1 | [ 97.30, 111.70]
##       4 |    124.00 |         1 | [116.80, 131.20]</code></pre>
<div class="sourceCode" id="cb454"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico</span>
<span class="va">p</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov034-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Podemos ver como la predicción para la máquina 4 es diferente de las predicciones para las máquinas 1 y 3 (sus intervalos de confianza no se solapan). No hay diferencia entre la M4 y la M2, ni entre la M2 y la M1 o M3. La máquina que podemos indicar como más efectiva es la M4 ya que es la que produce un mayor número de envases sin defectos.</p>
</div>
<div id="datos-de-venenos-2" class="section level4" number="8.7.1.3">
<h4>
<span class="header-section-number">8.7.1.3</span> Datos de venenos<a class="anchor" aria-label="anchor" href="#datos-de-venenos-2"><i class="fas fa-link"></i></a>
</h4>
<p>Comenzaremos obteniendo la predicción para el modelo estimado y posteriormente lo haremos para la variable respuesta en la escala original.</p>
<div class="sourceCode" id="cb455"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Objeto gráfico</span>
<span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span>, <span class="st">"pred"</span>, terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"veneno"</span>,<span class="st">"antidoto"</span><span class="op">)</span>,
           show.stat <span class="op">=</span> <span class="cn">TRUE</span>, 
           title <span class="op">=</span><span class="st">""</span><span class="op">)</span>
<span class="co"># Tabla de estimaciones en términos de la inversa</span>
<span class="va">p</span><span class="op">$</span><span class="va">data</span></code></pre></div>
<pre><code>## # Predicted values of tiempoinv
## 
## # antidoto = AA
## 
## veneno | Predicted | group_col |       95% CI
## ---------------------------------------------
##      1 |      2.70 |        AA | [2.36, 3.04]
##      2 |      3.16 |        AA | [2.82, 3.50]
##      3 |      4.70 |        AA | [4.36, 5.04]
## 
## # antidoto = AB
## 
## veneno | Predicted | group_col |       95% CI
## ---------------------------------------------
##      1 |      1.04 |        AB | [0.70, 1.38]
##      2 |      1.51 |        AB | [1.17, 1.85]
##      3 |      3.04 |        AB | [2.70, 3.38]
## 
## # antidoto = AC
## 
## veneno | Predicted | group_col |       95% CI
## ---------------------------------------------
##      1 |      2.12 |        AC | [1.78, 2.46]
##      2 |      2.59 |        AC | [2.25, 2.93]
##      3 |      4.13 |        AC | [3.78, 4.47]
## 
## # antidoto = AD
## 
## veneno | Predicted | group_col |       95% CI
## ---------------------------------------------
##      1 |      1.34 |        AD | [1.00, 1.68]
##      2 |      1.81 |        AD | [1.47, 2.15]
##      3 |      3.35 |        AD | [3.01, 3.69]</code></pre>
<div class="sourceCode" id="cb457"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de interacción estimado</span>
<span class="va">p</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov035-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Dado que hemos utilizado la transformación inversa para encontrar el antídoto que mejor funciona para cada veneno debemos buscar el valor más alto de valor predicho. El antídoto AA es que le muestra valores predichos más altos para cualquier tipo de venenos por lo que resulta el más efectivo. Podemos ver el resultado gráficamente:</p>
<div class="sourceCode" id="cb458"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de interacción estimado</span>
<span class="va">p</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov035b-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>¿Cómo podemos interpretar los intervalos de confianza para la predicción que hemos obtenido? ¿Cómo se comportan los antídotos con cada veneno? ¿Este resultado es esperable en función del modelo ajustado?</p>
<p>Obtenemos y representamos los valores de predicción en la escala original de la variable respuesta.</p>
<div class="sourceCode" id="cb459"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Creamos la combinación de grupos con ambos factores</span>
<span class="va">f1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">venenos</span><span class="op">$</span><span class="va">antidoto</span><span class="op">)</span>
<span class="va">f2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">venenos</span><span class="op">$</span><span class="va">veneno</span><span class="op">)</span>
<span class="co"># Generamos todas las posibles combinaciones de niveles</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span><span class="va">f1</span>, <span class="va">f2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">newdata</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"antidoto"</span>, <span class="st">"veneno"</span><span class="op">)</span>
<span class="co"># Predicción para la media de la respuesta</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">newdata</span>, <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">fit.venenos.inv</span>, 
                               <span class="va">newdata</span>, 
                               interval<span class="op">=</span><span class="st">"confidence"</span><span class="op">)</span><span class="op">)</span> 
<span class="co"># Deshacemos la transformación inversa</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="va">newdata</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
             <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prediccion <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">fit</span>,
                    lower <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">lwr</span>, 
                    upper <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">upr</span><span class="op">)</span>
<span class="co"># Presentamos los datos en la escala transformada y la original</span>
<span class="va">newdata</span></code></pre></div>
<pre><code>##    antidoto veneno      fit       lwr      upr prediccion     lower     upper
## 1        AA     VA 2.696003 2.3455815 3.046425  0.3709194 0.4263335 0.3282536
## 2        AB     VA 1.038601 0.6881791 1.389022  0.9628339 1.4531102 0.7199308
## 3        AC     VA 2.123868 1.7734460 2.474289  0.4708391 0.5638739 0.4041564
## 4        AD     VA 1.344279 0.9938569 1.694700  0.7438934 1.0061810 0.5900748
## 5        AA     VB 3.164644 2.8142227 3.515066  0.3159913 0.3553379 0.2844897
## 6        AB     VB 1.507242 1.1568203 1.857664  0.6634635 0.8644385 0.5383106
## 7        AC     VB 2.592509 2.2420873 2.942931  0.3857267 0.4460130 0.3397973
## 8        AD     VB 1.812920 1.4624982 2.163342  0.5515964 0.6837615 0.4622479
## 9        AA     VC 4.697388 4.3469667 5.047810  0.2128842 0.2300455 0.1981057
## 10       AB     VC 3.039986 2.6895643 3.390408  0.3289489 0.3718074 0.2949498
## 11       AC     VC 4.125253 3.7748312 4.475675  0.2424094 0.2649125 0.2234300
## 12       AD     VC 3.345664 2.9952422 3.696086  0.2988943 0.3338628 0.2705565</code></pre>
<p>Realizamos el gráfico de predicción en la escala original de la variable respuesta ordenando los intervalos de confianza desde el tiempo de reacción más pequeño al más grande, para así determinar las combinaciones antídoto-veneno más efectivas.</p>
<div class="sourceCode" id="cb461"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Variable de combinaciones de factores</span>
<span class="va">newdata</span> <span class="op">&lt;-</span> <span class="va">newdata</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>grupo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">antidoto</span>,<span class="va">veneno</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Gráfico</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">newdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_reorder.html">fct_reorder</a></span><span class="op">(</span><span class="va">grupo</span>,<span class="va">fit</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">fit</span>, colour <span class="op">=</span> <span class="va">veneno</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">lwr</span>, ymax <span class="op">=</span> <span class="va">upr</span><span class="op">)</span>, width<span class="op">=</span><span class="fl">.1</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Tiempo"</span>, x <span class="op">=</span> <span class="st">"Antidoto-Veneno"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="08-lmANOVA_files/figure-html/aov035d-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Las conclusiones que podemos extraer son:</p>
<ul>
<li>Para el veneno VA los mejores antídotos son el AA y el AC con tiempos de reacción similares (intervalos de predicción no disjuntos), y distintos de los que proporcionan el antídoto AD y el AB.</li>
<li>Para el veneno VB los mejores antídotos son el AA y el AC con tiempos de reacción similares, y distintos de los que proporcionan el antídoto AD y el AB.</li>
<li>Para el veneno VC los mejores antídotos son el AA y el AC con tiempos de reacción similares, y distintos de los que proporcionan el antídoto AD y el AB.</li>
</ul>
<p>A la hora de elegir deberíamos hacerlo entre AA y AC para cualquiera de los venenos. Además, podemos ver que el veneno VC es el más resistente a los antídotos ya que tiene mayores tiempos de reacción (sitúa más intervalos de predicción en la zona alta). El menos resistente sería el veneno VA (mayor número de intervalos de predicción en la parte inferior).</p>
</div>
</div>
</div>
<div id="ejercicios-1" class="section level2" number="8.8">
<h2>
<span class="header-section-number">8.8</span> Ejercicios<a class="anchor" aria-label="anchor" href="#ejercicios-1"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Ejercicio 1.</strong> Se realiza una investigación para conocer los niveles de fosfato inorgánico en plasma (mg / dl) una hora después de una prueba de tolerancia a la glucosa estándar para sujetos obesos, con o sin hiperinsulinemia, y controles. Los datos corresponden con la tabla 6.18 de Dobson (2002).</p>
<div class="sourceCode" id="cb462"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Lectura de datos</span>
<span class="va">ejer01</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/3L4EtK"</span>, col_types <span class="op">=</span> <span class="st">"cd"</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 2.</strong> Se lleva a cabo un estudio sobre el contenido promedio de grasa (en porcentaje) en la leche del ganado de cinco razas distintas canadienses. Para ello se consideran veinte ejemplares de pura raza (diez de dos años y diez maduras de más de cuatro años de cada una de cinco razas.</p>
<div class="sourceCode" id="cb463"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Lectura de datos</span>
<span class="va">ejer02</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/J2ZKWK"</span>, col_types <span class="op">=</span> <span class="st">"dcc"</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 3.</strong> Los datos que se presentan a continuación <span class="citation">[@Dobson02]</span> corresponden a un estudio en el que semillas genéticamente iguales son asignadas aleatoriamente, bien a un entorno enriquecido nutricionalmente (tratamiento), bien a condiciones estándar (control). Una vez han crecido todas las plantas, se recolectan, secan y pesan. El interés es investigar el efecto del tratamiento utilizado sobre le peso seco (en gramos) de las plantas en cuestión.</p>
<div class="sourceCode" id="cb464"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">peso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4.17</span>, <span class="fl">5.58</span>, <span class="fl">5.18</span>, <span class="fl">6.11</span>, <span class="fl">4.50</span>, <span class="fl">4.61</span>, <span class="fl">5.17</span>, <span class="fl">4.53</span>, <span class="fl">5.33</span>, <span class="fl">5.14</span>, <span class="fl">4.81</span>, <span class="fl">4.17</span>, 
          <span class="fl">4.41</span>, <span class="fl">3.59</span>, <span class="fl">5.87</span>, <span class="fl">3.83</span>, <span class="fl">6.03</span>, <span class="fl">4.89</span>, <span class="fl">4.32</span>, <span class="fl">4.69</span><span class="op">)</span>
<span class="va">entorno</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"tratamiento"</span>,<span class="fl">10</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"control"</span>,<span class="fl">10</span><span class="op">)</span><span class="op">)</span>
<span class="va">ejercicio03</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">peso</span>,<span class="va">entorno</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 4.</strong> Se realiza un estudio experimental para estudiar el rendimiento de un proceso químico en función de la concentración del compuesto base (A, B, C y D), el catalizador usado (C1, C2, y C3), y la temperatura usada en el proceso (T1, T2). Se quiere estudiar como afectan estos factores en el rendimiento del proceso.</p>
<div class="sourceCode" id="cb465"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio04</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://bit.ly/2GhFsl7"</span>, col_types <span class="op">=</span> <span class="st">"dccc"</span><span class="op">)</span>
<span class="va">ejercicio04</span> <span class="op">&lt;-</span> <span class="va">ejercicio04</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
   <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">ejercicio04</span>,<span class="va">is.character</span><span class="op">)</span>,<span class="va">as.factor</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 5.</strong> Se quiere evaluar la eficacia de distintas dosis de un fármaco contra la hipertensión arterial, comparándola con la de una dieta sin sal. Para ello se seleccionan al azar 25 hipertensos y se distribuyen aleatoriamente en 5 grupos. Al primero de ellos no se le suministra ningún tratamiento (<code>T1</code>), al segundo una dieta con un contenido pobre en sal (<code>T2</code>), al tercero una dieta sin sal (<code>T3</code>), al cuarto el fármaco a una dosis determinada (<code>T4</code>) y al quinto el mismo fármaco a otra dosis (<code>T5</code>). Las presiones arteriales (<code>Presion</code>) sistólicas de los 25 sujetos al finalizar los tratamientos son:</p>
<div class="sourceCode" id="cb466"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">presion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">180</span>, <span class="fl">173</span>, <span class="fl">175</span>, <span class="fl">182</span>, <span class="fl">181</span>, <span class="fl">172</span>, <span class="fl">158</span>, <span class="fl">167</span>, <span class="fl">160</span>,
             <span class="fl">175</span>, <span class="fl">163</span>, <span class="fl">170</span>, <span class="fl">158</span>, <span class="fl">162</span>, <span class="fl">170</span>, <span class="fl">158</span>, <span class="fl">146</span>, <span class="fl">160</span>,
             <span class="fl">171</span>, <span class="fl">155</span>, <span class="fl">147</span>, <span class="fl">152</span>, <span class="fl">143</span>, <span class="fl">155</span>, <span class="fl">160</span><span class="op">)</span>
<span class="va">tratamiento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T1"</span>,<span class="fl">5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T2"</span>,<span class="fl">5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T3"</span>,<span class="fl">5</span><span class="op">)</span>,
                 <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T4"</span>,<span class="fl">5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T5"</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span>
<span class="va">ejercicio05</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">presion</span>, <span class="va">tratamiento</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 6.</strong> La convección es una forma de transferencia de calor por los fluidos debido a sus variaciones de densidad por la temperatura; las partes calientes ascienden y las frías descienden formando las corrientes de convección que hacen uniforme la temperatura del fluido. Se ha realizado un experimento para determinar las modificaciones de la densidad de fluido al elevar la temperatura en una determinada zona. Los resultados obtenidos han sido los siguientes:</p>
<div class="sourceCode" id="cb467"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">densidad</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">21.8</span>, <span class="fl">21.9</span>, <span class="fl">21.7</span>, <span class="fl">21.6</span>, <span class="fl">21.7</span>, <span class="fl">21.7</span>, <span class="fl">21.4</span>, <span class="fl">21.5</span>, <span class="fl">21.4</span>,
              <span class="fl">21.9</span>, <span class="fl">21.8</span>, <span class="fl">21.8</span>, <span class="fl">21.6</span>, <span class="fl">21.5</span>, <span class="fl">21.9</span>, <span class="fl">22.1</span>, <span class="fl">21.85</span>, <span class="fl">21.9</span><span class="op">)</span>
<span class="va">temperatura</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T100"</span>,<span class="fl">5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T125"</span>,<span class="fl">4</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T150"</span>,<span class="fl">5</span><span class="op">)</span>,
                 <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"T175"</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">ejercicio06</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">densidad</span>, <span class="va">temperatura</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 7.</strong> Un laboratorio de reciclaje controla la calidad de los plásticos utilizados en bolsas. Se desea contrastar si existe variabilidad en la calidad de los plásticos que hay en el mercado. Para ello, se eligen al azar cuatro plásticos y se les somete a una prueba para medir el grado de resistencia a la degradación ambiental. De cada plástico elegido se han seleccionado ocho muestras y los resultados de la variable que mide la resistencia son los de la tabla adjunta.</p>
<div class="sourceCode" id="cb468"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resistencia</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">135</span>, <span class="fl">175</span>, <span class="fl">97</span>, <span class="fl">169</span>, <span class="fl">213</span>, <span class="fl">171</span>, <span class="fl">115</span>, <span class="fl">143</span>,
                 <span class="fl">275</span>, <span class="fl">170</span>, <span class="fl">154</span>, <span class="fl">133</span>, <span class="fl">219</span>, <span class="fl">187</span>, <span class="fl">220</span>, <span class="fl">185</span>,
                 <span class="fl">169</span>, <span class="fl">239</span>, <span class="fl">184</span>, <span class="fl">222</span>, <span class="fl">253</span>, <span class="fl">179</span>, <span class="fl">280</span>, <span class="fl">193</span>,
                 <span class="fl">115</span>, <span class="fl">105</span>, <span class="fl">93</span>, <span class="fl">85</span>, <span class="fl">120</span>, <span class="fl">74</span>, <span class="fl">87</span>, <span class="fl">63</span><span class="op">)</span>
<span class="va">plastico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"PA"</span>,<span class="fl">8</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"PB"</span>,<span class="fl">8</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"PC"</span>,<span class="fl">8</span><span class="op">)</span>,
                 <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"PD"</span>,<span class="fl">8</span><span class="op">)</span><span class="op">)</span>
<span class="va">ejercicio07</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">resistencia</span>, <span class="va">plastico</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 8.</strong> Se realiza un estudio sobre el efecto que produce la descarga de aguas residuales de un planta sobre la ecología del agua natural de un río. En el estudio se utilizaron dos lugares de muestreo. Un lugar está aguas arriba del punto en el que la planta introduce aguas residuales en la corriente; el otro está aguas abajo. Se tomaron muestras durante un periodo de cuatro semanas y se obtuvieron los datos sobre el número de diatomeas halladas. Los datos se muestran en la tabla adjunta:</p>
<div class="sourceCode" id="cb469"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">diatomeas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">78</span>, <span class="fl">94</span>, <span class="fl">43</span>, <span class="fl">58</span>, <span class="fl">620</span>, <span class="fl">760</span>, <span class="fl">420</span>, <span class="fl">913</span>, <span class="fl">204</span>, <span class="fl">333</span>, <span class="fl">98</span>, <span class="fl">89</span>,
               <span class="fl">890</span>, <span class="fl">655</span>, <span class="fl">763</span>, <span class="fl">562</span>, <span class="fl">79</span>, <span class="fl">87</span>, <span class="fl">145</span>, <span class="fl">522</span>, <span class="fl">546</span>, <span class="fl">652</span>, <span class="fl">76</span>, <span class="fl">94</span>,
               <span class="fl">45</span>, <span class="fl">69</span>, <span class="fl">59</span>, <span class="fl">62</span>, <span class="fl">254</span>, <span class="fl">86</span>, <span class="fl">789</span>, <span class="fl">267</span><span class="op">)</span>
<span class="va">semana</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S1"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S2"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S3"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S4"</span>,<span class="fl">4</span><span class="op">)</span>,
            <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S1"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S2"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S3"</span>,<span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"S4"</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">lugar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Aguas arriba"</span>,<span class="fl">16</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Aguas abajo"</span>,<span class="fl">16</span><span class="op">)</span><span class="op">)</span>
<span class="va">ejercicio08</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">diatomeas</span>, <span class="va">semana</span>, <span class="va">lugar</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 9.</strong> (Estos datos corresponden a modelos ANOVA) Un fabricante de ropa que suministra uniformes militares debe cortar chaquetas, camisas, pantalones (variable <code>Prenda</code>) y otros complementos (en muchas tallas diferentes), de rollos de tela. La tela es cara, de modo que el desperdicio (<code>Desperdicio</code>) tiene un efecto muy grande en los beneficios. El fabricante tiene que elegir entre tres máquinas (<code>Maquina</code>) cortadoras asistidas por computadora: A, B y C. El fabricante decide experimentar haciendo que cada máquina corte varios lotes de chaquetas, varios más de camisas otros más de pantalones y complementos para determinar que máquina es más eficiente en cada caso, es decir, tratamos de conocer el desperdicio que se producirá para cada prenda y máquina.</p>
<div class="sourceCode" id="cb470"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Lectura de datos</span>
<span class="va">ejer09</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://bit.ly/2GcVn3R"</span>, col_types <span class="op">=</span> <span class="st">"ccd"</span><span class="op">)</span>
<span class="va">ejer09</span> <span class="op">&lt;-</span> <span class="va">ejer09</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">ejer09</span>,<span class="va">is.character</span><span class="op">)</span>,<span class="va">as.factor</span><span class="op">)</span></code></pre></div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="rlm.html"><span class="header-section-number">7</span> Regresión Lineal Múltiple y Polinómica</a></div>
<div class="next"><a href="ancova.html"><span class="header-section-number">9</span> Modelos ANCOVA</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#anova"><span class="header-section-number">8</span> Modelos ANOVA</a></li>
<li><a class="nav-link" href="#bancos-de-datos-1"><span class="header-section-number">8.1</span> Bancos de datos</a></li>
<li>
<a class="nav-link" href="#modelos-anova-1-v%C3%ADa"><span class="header-section-number">8.2</span> Modelos ANOVA 1 vía</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#especificacion-del-modelo-en-r"><span class="header-section-number">8.2.1</span> Especificacion del modelo en R</a></li></ul>
</li>
<li>
<a class="nav-link" href="#modelos-anova-dos-v%C3%ADas"><span class="header-section-number">8.3</span> Modelos ANOVA dos vías</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#especificacion-del-modelo-en-r-1"><span class="header-section-number">8.3.1</span> Especificacion del modelo en R</a></li></ul>
</li>
<li>
<a class="nav-link" href="#estimaci%C3%B3n-y-bondad-de-ajuste-del-modelo"><span class="header-section-number">8.4</span> Estimación y bondad de ajuste del modelo</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-9"><span class="header-section-number">8.4.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#comparaci%C3%B3n-y-selecci%C3%B3n-de-modelos-1"><span class="header-section-number">8.5</span> Comparación y selección de modelos</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-10"><span class="header-section-number">8.5.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#diagn%C3%B3stico-1"><span class="header-section-number">8.6</span> Diagnóstico</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-11"><span class="header-section-number">8.6.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#predicci%C3%B3n-1"><span class="header-section-number">8.7</span> Predicción</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-12"><span class="header-section-number">8.7.1</span> Ejemplos</a></li></ul>
</li>
<li><a class="nav-link" href="#ejercicios-1"><span class="header-section-number">8.8</span> Ejercicios</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modelos Estadísticos</strong>" was written by true, true. It was last built on 2022-03-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
