<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Unidad 13 GLM respuesta binomial | Modelos Estadísticos</title>
<meta name="description" content="Consideramos en este tema la modelización de variables respuesta de tipo binario, es decir, para cada individuo, la variable respuesta para cada uno de los sujetos puede tomar únicamente dos...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Unidad 13 GLM respuesta binomial | Modelos Estadísticos">
<meta property="og:type" content="book">
<meta property="og:description" content="Consideramos en este tema la modelización de variables respuesta de tipo binario, es decir, para cada individuo, la variable respuesta para cada uno de los sujetos puede tomar únicamente dos...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Unidad 13 GLM respuesta binomial | Modelos Estadísticos">
<meta name="twitter:description" content="Consideramos en este tema la modelización de variables respuesta de tipo binario, es decir, para cada individuo, la variable respuesta para cada uno de los sujetos puede tomar únicamente dos...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="bs4_style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Modelos Estadísticos</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Bienvenidos</a></li>
<li><a class="" href="introlibro.html"><span class="header-section-number">1</span> Comenzamos</a></li>
<li><a class="" href="aed.html"><span class="header-section-number">2</span> Análisis exploratorio de datos</a></li>
<li><a class="" href="prob.html"><span class="header-section-number">3</span> Probabilidad</a></li>
<li><a class="" href="inferencia-b%C3%A1sica.html"><span class="header-section-number">4</span> Inferencia básica</a></li>
<li><a class="" href="modelstats.html"><span class="header-section-number">5</span> Modelos estadísticos</a></li>
<li><a class="" href="rls.html"><span class="header-section-number">6</span> Regresión Lineal Simple (RLS)</a></li>
<li><a class="" href="rlm.html"><span class="header-section-number">7</span> Regresión Lineal Múltiple y Polinómica</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">8</span> Modelos ANOVA</a></li>
<li><a class="" href="ancova.html"><span class="header-section-number">9</span> Modelos ANCOVA</a></li>
<li><a class="" href="smooth.html"><span class="header-section-number">10</span> Modelos aditivos lineales</a></li>
<li><a class="" href="mmixed.html"><span class="header-section-number">11</span> Modelos Lineales Mixtos</a></li>
<li><a class="" href="glm.html"><span class="header-section-number">12</span> Modelos Lineales Generalizados</a></li>
<li><a class="active" href="glmbinomial.html"><span class="header-section-number">13</span> GLM respuesta binomial</a></li>
<li><a class="" href="glmpoisson.html"><span class="header-section-number">14</span> GLM Poisson</a></li>
<li><a class="" href="glmtablascont.html"><span class="header-section-number">15</span> GLM para tablas de contingencia</a></li>
<li><a class="" href="glmsuperv.html"><span class="header-section-number">16</span> GLM para datos de supervivencia</a></li>
<li><a class="" href="referencias.html">Referencias</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="glmbinomial" class="section level1" number="13">
<h1>
<span class="header-section-number">Unidad 13</span> GLM respuesta binomial<a class="anchor" aria-label="anchor" href="#glmbinomial"><i class="fas fa-link"></i></a>
</h1>
<p>Consideramos en este tema la modelización de variables respuesta de tipo binario, es decir, para cada individuo, la variable respuesta para cada uno de los sujetos puede tomar únicamente dos posibles valores, que denotaremos por 0 (fracaso) y 1 (éxito),</p>
<p><span class="math display">\[Pr(Y_i = 0) = 1 - \pi_i; \text{ } Pr(Y_i = 1) = \pi_i\]</span></p>
<p>Si además se han observado una serie de covariables continuas o de tipo factor, el objetivo del análisis con el modelo lineal generalizado será predecir la probabilidad asociada al éxito, <span class="math inline">\(\widehat{\pi_i}\)</span>, (o equivalentemente el fracaso), en función de dichas covariables.</p>
<div id="tipos-de-datos-binomiales" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Tipos de datos binomiales<a class="anchor" aria-label="anchor" href="#tipos-de-datos-binomiales"><i class="fas fa-link"></i></a>
</h2>
<p>Existen dos formas habituales en las que se presenta o se recoge la información experimental sobre variables que miden éxito o fracaso. A continuación detallamos dichas situaciones experimentales y vemos un ejemplo de cada una de ellas.</p>
<div id="información-individualizada-por-sujeto" class="section level3" number="13.1.1">
<h3>
<span class="header-section-number">13.1.1</span> Información individualizada por sujeto<a class="anchor" aria-label="anchor" href="#informaci%C3%B3n-individualizada-por-sujeto"><i class="fas fa-link"></i></a>
</h3>
<p>En este caso el banco de datos recoge la información de cada sujeto de la muestra con una variable que indica el éxito o el fracaso. Dicha variable se suele codificar 1 (éxito) y 0 (fracaso). Asociada con esta variable binaria se pueden recoger variables predictoras, en cada uno de los sujetos, para tratar de explicar el comportamiento de la respuesta.</p>
<div id="datos-de-kifosis" class="section level4" number="13.1.1.1">
<h4>
<span class="header-section-number">13.1.1.1</span> Datos de Kifosis<a class="anchor" aria-label="anchor" href="#datos-de-kifosis"><i class="fas fa-link"></i></a>
</h4>
<p>En este banco de datos aparecen los datos de 81 niños que fueron intervenidos quirúrgicamente para corregirles problemas en la columna vertebral. La variable binaria <code>kifosis</code> indica la presencia o ausencia de una deformidad postoperatoria en la columna, denominada kifosis. Las otras tres variables son <code>Age</code>, edad del niñoo en meses, <code>Number</code>, número de vértebras intervenidas en la operación, y <code>Start</code>, que define la primera vértebra involucrada en la operación. Es de interés en el análisis investigar cómo están relacionadas dichas variables a la hora de predecir la incidencia de la kifosis en el postoperatorio. En este caso todas las variables predictoras son de tipo numérico.</p>
<p>En este caso la variable respuesta se puede representar mediante el modelo <span class="math inline">\(Y_i \sim Bi(n = 1, \pi_i)\)</span>, dado que cada observación corresponde a un único sujeto con <span class="math inline">\(\pi_i\)</span> la probabilidad de sufrir una deformidad postoperatoria para el sujeto <span class="math inline">\(i\)</span>.</p>
<p>Cargamos los datos a partir de la librería <code>rpart</code> y los representamos gráficamente. En este caso realizamos diagramas de caja para cada variable predictora. La variable respuesta viene codificada con las opciones <code>absent</code> y <code>present</code>, por lo que al cargar los datos codificaremos dichos valores como 0 y 1. En este caso el éxito viene marcado por tener la enfermedad.</p>
<div class="sourceCode" id="cb681"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Kyphosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2L</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>,  <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, 
                     <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, 
                     <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, 
                     <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, 
                     <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, 
                     <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, 
                     <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, 
                     <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"absent"</span>, <span class="st">"present"</span><span class="op">)</span><span class="op">)</span>
<span class="va">Age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">71</span>, <span class="fl">158</span>, <span class="fl">128</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">61</span>, <span class="fl">37</span>, <span class="fl">113</span>, <span class="fl">59</span>, <span class="fl">82</span>, <span class="fl">148</span>, 
         <span class="fl">18</span>, <span class="fl">1</span>, <span class="fl">168</span>, <span class="fl">1</span>, <span class="fl">78</span>, <span class="fl">175</span>, <span class="fl">80</span>, <span class="fl">27</span>, <span class="fl">22</span>, <span class="fl">105</span>, <span class="fl">96</span>, <span class="fl">131</span>, 
         <span class="fl">15</span>, <span class="fl">9</span>, <span class="fl">8</span>, <span class="fl">100</span>, <span class="fl">4</span>, <span class="fl">151</span>, <span class="fl">31</span>, <span class="fl">125</span>, <span class="fl">130</span>, <span class="fl">112</span>, <span class="fl">140</span>, <span class="fl">93</span>, 
         <span class="fl">1</span>, <span class="fl">52</span>, <span class="fl">20</span>, <span class="fl">91</span>, <span class="fl">73</span>, <span class="fl">35</span>, <span class="fl">143</span>, <span class="fl">61</span>, <span class="fl">97</span>, <span class="fl">139</span>, <span class="fl">136</span>, <span class="fl">131</span>, 
         <span class="fl">121</span>, <span class="fl">177</span>, <span class="fl">68</span>, <span class="fl">9</span>, <span class="fl">139</span>, <span class="fl">2</span>, <span class="fl">140</span>, <span class="fl">72</span>, <span class="fl">2</span>, <span class="fl">120</span>, <span class="fl">51</span>, <span class="fl">102</span>, 
         <span class="fl">130</span>, <span class="fl">114</span>, <span class="fl">81</span>, <span class="fl">118</span>, <span class="fl">118</span>, <span class="fl">17</span>, <span class="fl">195</span>, <span class="fl">159</span>, <span class="fl">18</span>, <span class="fl">15</span>, <span class="fl">158</span>, 
         <span class="fl">127</span>, <span class="fl">87</span>, <span class="fl">206</span>, <span class="fl">11</span>, <span class="fl">178</span>, <span class="fl">157</span>, <span class="fl">26</span>, <span class="fl">120</span>, <span class="fl">42</span>, <span class="fl">36</span><span class="op">)</span> 
<span class="va">Number</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">6</span>, <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">6</span>, 
            <span class="fl">5</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">2</span>, <span class="fl">6</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">7</span>, <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">3</span>, 
            <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">5</span>, <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">9</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">5</span>, 
            <span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">2</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">7</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">2</span>, <span class="fl">4</span>, 
            <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">7</span>, <span class="fl">2</span>, <span class="fl">7</span>, <span class="fl">4</span><span class="op">)</span> 
<span class="va">Start</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">14</span>, <span class="fl">5</span>, <span class="fl">1</span>, <span class="fl">15</span>, <span class="fl">16</span>, <span class="fl">17</span>, <span class="fl">16</span>, <span class="fl">16</span>, <span class="fl">12</span>, <span class="fl">14</span>, <span class="fl">16</span>, <span class="fl">2</span>, <span class="fl">12</span>, 
           <span class="fl">18</span>, <span class="fl">16</span>, <span class="fl">15</span>, <span class="fl">13</span>, <span class="fl">16</span>, <span class="fl">9</span>, <span class="fl">16</span>, <span class="fl">5</span>, <span class="fl">12</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">13</span>, <span class="fl">6</span>, <span class="fl">14</span>, 
           <span class="fl">16</span>, <span class="fl">16</span>, <span class="fl">16</span>, <span class="fl">11</span>, <span class="fl">13</span>, <span class="fl">16</span>, <span class="fl">11</span>, <span class="fl">16</span>, <span class="fl">9</span>, <span class="fl">6</span>, <span class="fl">9</span>, <span class="fl">12</span>, <span class="fl">1</span>, <span class="fl">13</span>, 
           <span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">16</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">13</span>, <span class="fl">3</span>, <span class="fl">14</span>, <span class="fl">10</span>, <span class="fl">17</span>, <span class="fl">6</span>, <span class="fl">17</span>, <span class="fl">15</span>, <span class="fl">15</span>, 
           <span class="fl">13</span>, <span class="fl">8</span>, <span class="fl">9</span>, <span class="fl">13</span>, <span class="fl">1</span>, <span class="fl">8</span>, <span class="fl">1</span>, <span class="fl">16</span>, <span class="fl">16</span>, <span class="fl">10</span>, <span class="fl">17</span>, <span class="fl">13</span>, <span class="fl">11</span>, <span class="fl">16</span>, 
           <span class="fl">14</span>, <span class="fl">12</span>, <span class="fl">16</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">15</span>, <span class="fl">13</span>, <span class="fl">13</span>, <span class="fl">13</span>, <span class="fl">6</span>, <span class="fl">13</span><span class="op">)</span>
<span class="va">kyphosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">Kyphosis</span>, <span class="va">Age</span>, <span class="va">Number</span>, <span class="va">Start</span><span class="op">)</span>
<span class="co"># Recodificación a 0 - 1</span>
<span class="va">kyphosisb</span> <span class="op">=</span> <span class="va">kyphosis</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Kyphosis <span class="op">=</span> <span class="fl">1</span><span class="op">*</span><span class="op">(</span><span class="va">Kyphosis</span><span class="op">==</span><span class="st">"present"</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Gráficos de predictoras y variable</span>
<span class="va">datacomp</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">kyphosis</span>, id.vars<span class="op">=</span><span class="st">'Kyphosis'</span><span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">datacomp</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">Kyphosis</span>,<span class="va">value</span>, colour<span class="op">=</span><span class="va">variable</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">variable</span>, scales <span class="op">=</span><span class="st">"free_y"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">""</span>, y <span class="op">=</span> <span class="st">"Kyphosis"</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom001-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En dichos gráficos podemos ver como hay más incidencia de la enfermedad para los bebes más grandes y cuando el número de vértebras intervenidas es inferior, mientras que disminuye cuando la primera vértebra involucrada en la operación tiene un valor más bajo, es decir, se sitúa más arriba en la columna vertebral.</p>
</div>
</div>
<div id="información-agrupada-por-sujetos" class="section level3" number="13.1.2">
<h3>
<span class="header-section-number">13.1.2</span> Información agrupada por sujetos<a class="anchor" aria-label="anchor" href="#informaci%C3%B3n-agrupada-por-sujetos"><i class="fas fa-link"></i></a>
</h3>
<p>Los bancos de datos de este tipo suelen identificar por fila el “tratamiento” al que se ven sometidos un grupo de sujetos, registrándose el número total de sujetos en esa combinación y el número de éxitos (en algunos casos se recogen los éxitos y fracasos para dicha combinación). El “tratamiento” puede ser la combinación de una o más predictoras. Estos bancos de datos son muy habituales en ensayos de dosis-repuesta donde únicamente queremos valorar eficacia, ya que no es necesario recoger una información exhaustiva sobre los sujetos bajo estudio. En estos casos no estimamos la probabilidad de éxito individual sino del grupo de sujetos que se ven sometidos al mismo tratamiento. La información muestral debe recoger la probabilidad de éxito asociada a cada combinación.</p>
<div id="datos-dosis-respuesta" class="section level4" number="13.1.2.1">
<h4>
<span class="header-section-number">13.1.2.1</span> Datos dosis-respuesta<a class="anchor" aria-label="anchor" href="#datos-dosis-respuesta"><i class="fas fa-link"></i></a>
</h4>
<p>Collet (1991) presenta un experimento sobre la toxicidad de distintas dosis (en microgramos) del piretroide trnas-cipemetrín en los capullos de gusano del tabaco. Se había comenzado a detectar resistencia de esas polillas a dicho tóxico. El experimento consistía en exponer, durante tres días y a distintas dosis de tóxico, a series de 20 polillas de cada sexo (<code>total</code>). Se anotaron el número de polillas muertas en cada serie (<code>dead</code>). Es de interés en el análisis investigar si efectivamente se demostraba tal resistencia al tóxico en función del sexo de la polilla (<code>sex</code>) y a partir de qué dosis (<code>dosis</code>). También se desea determinar la dosis a la cual es posible garantizar el exterminio del 50% de los insectos.</p>
<p>En este caso tenemos un modelo <span class="math inline">\(Y_i \sim Bi(n = 20, \pi_i)\)</span>, con <span class="math inline">\(\pi_i\)</span> la probabilidad de morir para una polilla en la combinación dosis-sexo.</p>
<p>Veamos los datos para este experimento y la representación gráfica. Utilizamos la variable <code>log(dosis)</code> como es habitual en este tipo de experimentos para linealizar la relación entre probabilidad de éxito y dosis .</p>
<div class="sourceCode" id="cb682"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Dosis</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/w23RGz"</span>, col_types <span class="op">=</span> <span class="st">"cdii"</span><span class="op">)</span>
<span class="va">Dosis</span></code></pre></div>
<pre><code>## # A tibble: 12 × 4
##    sex   dosis total  dead
##    &lt;chr&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
##  1 M         1    20     1
##  2 M         2    20     4
##  3 M         4    20     9
##  4 M         8    20    13
##  5 M        16    20    18
##  6 M        32    20    20
##  7 F         1    20     0
##  8 F         2    20     2
##  9 F         4    20     6
## 10 F         8    20    10
## 11 F        16    20    12
## 12 F        32    20    16</code></pre>
<div class="sourceCode" id="cb684"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculamos los vivos, la probabilidad de morir, y el </span>
<span class="co"># logaritmo de dosis que es la forma habitual de medir </span>
<span class="co"># en este tipo de situaciones</span>
<span class="va">Dosis</span> <span class="op">=</span> <span class="va">Dosis</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>alive <span class="op">=</span> <span class="va">total</span> <span class="op">-</span> <span class="va">dead</span>, probabilidad <span class="op">=</span> <span class="va">dead</span><span class="op">/</span><span class="va">total</span>, ldosis <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">dosis</span><span class="op">)</span><span class="op">)</span>
<span class="va">Dosis</span></code></pre></div>
<pre><code>## # A tibble: 12 × 7
##    sex   dosis total  dead alive probabilidad ldosis
##    &lt;chr&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;  &lt;dbl&gt;
##  1 M         1    20     1    19         0.05  0    
##  2 M         2    20     4    16         0.2   0.693
##  3 M         4    20     9    11         0.45  1.39 
##  4 M         8    20    13     7         0.65  2.08 
##  5 M        16    20    18     2         0.9   2.77 
##  6 M        32    20    20     0         1     3.47 
##  7 F         1    20     0    20         0     0    
##  8 F         2    20     2    18         0.1   0.693
##  9 F         4    20     6    14         0.3   1.39 
## 10 F         8    20    10    10         0.5   2.08 
## 11 F        16    20    12     8         0.6   2.77 
## 12 F        32    20    16     4         0.8   3.47</code></pre>
<div class="sourceCode" id="cb686"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Representamos la probabilidad de morir en función de </span>
<span class="co"># las covariables sex y ldosis</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Dosis</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ldosis</span>, y <span class="op">=</span> <span class="va">probabilidad</span>, color <span class="op">=</span> <span class="va">sex</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Logaritmo Dosis"</span>, y <span class="op">=</span> <span class="st">"Probabilidad de morir"</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom002-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se observa que para la misma dosis la probabilidad de morir en las hembras es menor que en los machos. Además, hay una tendencia creciente con la dosis, es decir, cuanto aumenta la dosis aumenta la probabilidad de morir.</p>
</div>
</div>
</div>
<div id="especificación-e-hipótesis-de-modelo" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Especificación e hipótesis de modelo<a class="anchor" aria-label="anchor" href="#especificaci%C3%B3n-e-hip%C3%B3tesis-de-modelo"><i class="fas fa-link"></i></a>
</h2>
<p>Las hipótesis que debe verificar los modelos de este tipo son:</p>
<ul>
<li>independencia entre las observaciones</li>
<li>linealidad entre transformaciones de la proporción de éxitos y de las variables explicativas continuas (función link)</li>
<li>consistencia entre la modelización y la interpretación física.</li>
</ul>
<p>Si <span class="math inline">\(\pi_i\)</span> es la probabilidad de éxito asociado al i-ésimo experimento binomial con respuesta <span class="math inline">\(Y_i\)</span>, y condiciones de experimentación observadas en las variables predictoras <span class="math inline">\(X_1;X_2,...,X_p\)</span>, la formulación del GLM viene dada por:</p>
<p><span class="math display">\[g(\pi_i) = \eta_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip}\]</span></p>
<p>donde <span class="math inline">\(g()\)</span> es la función link asociada con este tipo de datos. En este tipo de modelos los coeficientes <span class="math inline">\(\beta_i\)</span> representan el incremento o decremento sobre la función de enlace que nos permite linealizar la relación entre la probabilidad de éxito y las variables predictora o predictor lineal.</p>
<p>A continuación, presentamos las diferentes posibilidades de funciones link para este tipo de datos.</p>
<div id="funciones-link" class="section level3" number="13.2.1">
<h3>
<span class="header-section-number">13.2.1</span> Funciones link<a class="anchor" aria-label="anchor" href="#funciones-link"><i class="fas fa-link"></i></a>
</h3>
<p>En este tipo de modelos se contemplan diferentes funciones link. De forma habitual se suelen ajustar los modelos obtenidos para función de enlace, y nos quedamos con aquel modelo, y por tanto función de enlace, con mejor capacidad explicativa.</p>
<div id="link-logit" class="section level4" number="13.2.1.1">
<h4>
<span class="header-section-number">13.2.1.1</span> link logit<a class="anchor" aria-label="anchor" href="#link-logit"><i class="fas fa-link"></i></a>
</h4>
<p>El link logit proporciona los comúnmente conocidos como modelos de regresión logística y su expresión viene dada por:</p>
<p><span class="math display">\[g(\pi_i) = log\left( \frac{\pi_i}{1-\pi_i}\right) = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip}\]</span></p>
<p>En esta situación la probabilidad de éxito se puede escribir en términos de las variables predictoras (despejando de la ecuación anterior) como:</p>
<p><span class="math display">\[\pi_i = \frac{exp(\beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip})}{1+exp(\beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip})} \]</span></p>
<p>Si <span class="math inline">\(\pi_i (x_1)\)</span> y <span class="math inline">\(\pi_i (x_2)\)</span> denotan las probabilidades de éxito para dos valores de la predictora (<span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span>), el cociente <span class="math inline">\((\pi_i (x_1)/(1-\pi_i (x_1))) / (\pi_i (x_2)/(1-\pi_i (x_2)))\)</span> se denomina odds ratio y valora la relación entre probabilidad de éxito y fracaso para dos valores de la covaraible, de forma que:</p>
<ul>
<li>un valor mayor que 1 indica un aumento de la probabilidad de éxito en <span class="math inline">\(x_1\)</span> con respecto a <span class="math inline">\(x_2\)</span>,</li>
<li>un valor menor que 1 indica un decremento de la probabilidad de éxito en <span class="math inline">\(x_1\)</span> con respecto a <span class="math inline">\(x_2\)</span>.</li>
</ul>
<p>En términos del modelo ajustado se puede valorar el incremento o decremento del odds ratio con el valor de <span class="math inline">\(exp(\beta_i)\)</span>, para cada uno de los efectos (variables numéricas o niveles de un factor) presentes en el modelo. Valores negativos de <span class="math inline">\(\beta_i\)</span> dan lugar a odds ratios menores que 1, mientras que valores de <span class="math inline">\(\beta_i\)</span> positivos dan odds ratios positivos.</p>
<p>De hecho, esta propiedad es la que motiva que esta función de enlace sea la más utilizada en este tipo de modelos.</p>
<p>En <code>R</code> podemos obtener el valor de la función enlace para cualquier probabilidad con la sentencia</p>
<div class="sourceCode" id="cb687"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span><span class="op">$</span><span class="fu">linlfun</span><span class="op">(</span><span class="va">probabilidad</span><span class="op">)</span></code></pre></div>
<p>y el valor de la probabilidad de éxito a partir del valor del predictor lineal con</p>
<div class="sourceCode" id="cb688"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span><span class="op">$</span><span class="fu">linlinv</span><span class="op">(</span><span class="va">predictor</span><span class="op">)</span></code></pre></div>
</div>
<div id="link-probit" class="section level4" number="13.2.1.2">
<h4>
<span class="header-section-number">13.2.1.2</span> link probit<a class="anchor" aria-label="anchor" href="#link-probit"><i class="fas fa-link"></i></a>
</h4>
<p>El link probit proporciona los comúnmente conocidos como modelos de regresión probit y su expresión viene dada por:</p>
<p><span class="math display">\[g(\pi_i) = \Phi^{-1}(\pi_i) = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip}\]</span>
donde <span class="math inline">\(\Phi^{-1}\)</span> es la función inversa de la función de distribución Normal estándar. En esta situación la probabilidad de éxito se puede escribir en términos de las variables predictoras (despejando de la ecuación anterior) como:</p>
<p><span class="math display">\[\pi_i = \Phi(\beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} + ... + \beta_p x_{ip})\]</span>
donde <span class="math inline">\(\Phi\)</span> es la función de distribución Normal estándar.</p>
</div>
<div id="link-cloglog" class="section level4" number="13.2.1.3">
<h4>
<span class="header-section-number">13.2.1.3</span> link cloglog<a class="anchor" aria-label="anchor" href="#link-cloglog"><i class="fas fa-link"></i></a>
</h4>
<p>El link cloglog es el menos habitual en la práctica y su expresión viene dada por:</p>
<p><span class="math display">\[g(\pi_i) = log(-log(1-\pi_i)) = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{21} +...+\beta_p x_{ip}\]</span>
¿Cuál es la probabilidad de éxito en este caso?</p>
<p>La diferencia entre un link y otro hace referencia a como modelizamos las probabilidades más extremas, es decir, las muy bajas o muy altas, pero en la práctica proporcionan resultados muy similares. Por eso casi siempre el modelo utilizado es el de regresión logística.</p>
</div>
</div>
<div id="representación-de-las-funciones-link" class="section level3" number="13.2.2">
<h3>
<span class="header-section-number">13.2.2</span> Representación de las funciones link<a class="anchor" aria-label="anchor" href="#representaci%C3%B3n-de-las-funciones-link"><i class="fas fa-link"></i></a>
</h3>
<p>Para poder comparar los diferentes links presentados veamos cual es su comportamiento en función de la probabilidad de éxito, lo que se denomina en los modelos de dosis-respuesta función de tolerancia. Respectivamente se representan el link logit (línea continua), link probit (línea discontinua), link cloglog (puntos):</p>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom003-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En este gráfico se puede apreciar las pequeñas diferencias entre las funciones de enlace. Podemos ver que para un valor del predictor lineal de 2.5 la probabilidad de éxito en los modelos probit y cloglog es 1 mientras que para el modelo logit está próxima a 0.9. La elección de un tipo de enlace u otro dependerá por tanto del comportamiento de los datos observados.</p>
<p>Representamos a continuación las diferentes funciones link para los datos de dosis-respuesta. Este gráfico sólo se puede hacer para datos en formato agrupado.</p>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom004-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se aprecia como las tres funciones de enlace tienen un comportamiento muy similar. En el resto de esta unidad mostraremos los resultados correspondientes al modelo de regresión logística (link logit), e indicaremos como obtener los modelos para el resto de funciones link.</p>
</div>
</div>
<div id="estimación-y-bondad-de-ajuste" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Estimación y bondad de ajuste<a class="anchor" aria-label="anchor" href="#estimaci%C3%B3n-y-bondad-de-ajuste"><i class="fas fa-link"></i></a>
</h2>
<p>Para la estimación utilizamos la función <code>glm</code> con las especificaciones siguientes:</p>
<div class="sourceCode" id="cb689"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo de regresión logística</span>
<span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">modelo</span>,family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,<span class="va">data_set</span><span class="op">)</span>
<span class="co"># Modelo de regresión probit</span>
<span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">modelo</span>,family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">probit</span><span class="op">)</span>,<span class="va">data_set</span><span class="op">)</span>
<span class="co"># Modelo cloglog</span>
<span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">modelo</span>,family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">cloglog</span><span class="op">)</span>,<span class="va">data_set</span><span class="op">)</span></code></pre></div>
<p>Sin embargo, la especificación del modelo varía en función del tipo de datos (individualizados o conteos). En el caso de nuestro banco de datos contenga información individualizada para cada sujeto la variable respuesta se debe codificar con un 1 para el éxito y 0 para el fracaso, y el modelo se especifica como:</p>
<div class="sourceCode" id="cb690"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">respuesta</span> <span class="op">~</span> <span class="va">predictoras</span></code></pre></div>
<p>En el caso de disponer del número de éxitos y fracasos el modelo se especifica e la forma siguiente:</p>
<div class="sourceCode" id="cb691"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">exitos</span>,<span class="va">fracasos</span><span class="op">)</span> <span class="op">~</span> <span class="va">predictoras</span></code></pre></div>
<div id="ejemplos-14" class="section level3" number="13.3.1">
<h3>
<span class="header-section-number">13.3.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-14"><i class="fas fa-link"></i></a>
</h3>
<p>Estudiamos ahora el proceso de estimación del modelo completo (con todos los efectos posibles) para cada uno de los ejemplos. Utilizamos la función <code><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model()</a></code> con diferentes especificaciones para obtener las estimaciones de los parámetros del modelo (predictor lineal) y de los odds ratios.</p>
<div id="kyphosis" class="section level4" number="13.3.1.1">
<h4>
<span class="header-section-number">13.3.1.1</span> Kyphosis<a class="anchor" aria-label="anchor" href="#kyphosis"><i class="fas fa-link"></i></a>
</h4>
<p>En este caso ya hemos creado un variable para identificar el éxito (tener malformación postoperatoria) o el fracaso (no tener malformación) para cada sujeto de la muestra. El banco de datos es <code>kyphosisb</code> con variable respuesta <code>Kyphosis</code> y con tres posibles variables predictoras de tipo numérico: <code>Age</code>, <code>Number</code>, <code>Start</code>.
Para ajustar el modelo de regresión logística escribimos:</p>
<div class="sourceCode" id="cb692"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit.kyphosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Kyphosis</span>  <span class="op">~</span> <span class="va">Age</span> <span class="op">+</span> <span class="va">Number</span> <span class="op">+</span> <span class="va">Start</span>,
          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,
          data <span class="op">=</span> <span class="va">kyphosisb</span><span class="op">)</span></code></pre></div>
<p>Veamos las estimaciones del modelo ajustado:</p>
<div class="sourceCode" id="cb693"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, 
          transform <span class="op">=</span> <span class="cn">NULL</span>, 
          string.est <span class="op">=</span> <span class="st">"Estimate"</span>,
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Kyphosis
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimate
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.04
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-5.11 – 0.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.160
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.00 – 0.02
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.090
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Number
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00 – 0.90
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.068
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Start
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.35 – -0.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.002</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
81
</td>
</tr>
</table></div>
<div class="sourceCode" id="cb694"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, 
           transform <span class="op">=</span> <span class="cn">NULL</span>, 
           axis.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Estimate"</span>,<span class="st">""</span><span class="op">)</span>,
           show.values <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom009-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>A la vista de los coeficientes estimados se desprende que la única preditora que parece tener influencia en la probabilidad de observar una malformación es la variable <code>Start</code>. Dado que el coeficiente es negativo dicha probabilidad disminuye cuando aumenta dicha variable. La ecuación del modelo viene dada por:</p>
<p><span class="math display">\[log\left( \frac{\hat{\pi}_i}{1-\hat{\pi}_i}\right) = -2.04 + 0.01 *Age_{i} + 0.41 *Number_{1} - 0.21 *Start_{i}\]</span></p>
<p>donde la probabilidad de éxito es:</p>
<p><span class="math display">\[\pi_i = \frac{exp(-2.04 + 0.01 * Age_{i} + 0.41* Number_{i} - 0.21* Start_{i})}{1 -exp(2.04 + 0.01* Age_{i} + 0.41* Number_{i} - 0.21* Start_{i})}\]</span></p>
<p>Los odds ratios asociados a cada variable presente en el modelo vienen dados por</p>
<p><span class="math display">\[
\begin{array}{ll}
odds(Age) = &amp; exp(0.01) = 1.01\\
odds(Number) = &amp; exp(0.41) = 1.51\\
odds(Start) = &amp; exp(-0.21) = 0.81\\
\end{array}
\]</span></p>
<p>En términos de los odds ratios podemos ver que la probabilidad de sufrir una malformación aumenta 1.01 y 1.51 al aumentar respectivamente las variables <code>Age</code> y <code>Number</code>, es decir, la probabilidad de sufrir una malformación al incrementar en una unidad el número de vértebras intervenidas es 1.5 (odds ratio) veces superior que de no padecerla. Con la variable <code>Start</code> podemos ver que la relación entre sufrir la malformación es 0.81 veces la probabilidad de no sufrirla, es decir, disminuye al aumentar la vértebra de inicio.</p>
<p>Con la formulación siguiente podemos obtener y representar de forma directa los odds ratios asociados al modelo analizado:</p>
<div class="sourceCode" id="cb695"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, 
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Kyphosis
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 1.95
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.160
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.00 – 1.02
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.090
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Number
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.00 – 2.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.068
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Start
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.81
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.71 – 0.92
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.002</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
81
</td>
</tr>
</table></div>
<div class="sourceCode" id="cb696"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, 
           show.values <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom010-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>De todas formas hay que ser cautelosos en la interpretación dado que todavía no hemos validado el modelo ni hemos realizado el proceso de selección de efectos relevantes en el modelo.</p>
<p>Para realizar la bondad de ajuste del modelo obtenemos los estadísticos asociados (función <code>glance</code>) y el contraste de bondad de ajuste utilizando la deviance explicada y sus grados de libertad asociados utilizando el test <span class="math inline">\(\chi^2\)</span>.</p>
<div class="sourceCode" id="cb697"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># P-valor del contraste</span>
<span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">fit.kyphosis</span><span class="op">$</span><span class="va">deviance</span>,<span class="va">fit.kyphosis</span><span class="op">$</span><span class="va">df.residual</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.9033442</code></pre>
<div class="sourceCode" id="cb699"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Bondad del ajuste</span>
<span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">fit.kyphosis</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
##           &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
## 1          83.2      80  -30.7  69.4  79.0     61.4          77    81</code></pre>
<p>El p-valor obtenido es superior a 0.05 indicando que el modelo considerado tiene una buena capacidad explicativa. En el punto siguiente estudiaremos la selección de variables para quedarnos con el mejor modelo posible.</p>
</div>
<div id="dosis-respuesta" class="section level4" number="13.3.1.2">
<h4>
<span class="header-section-number">13.3.1.2</span> Dosis-Respuesta<a class="anchor" aria-label="anchor" href="#dosis-respuesta"><i class="fas fa-link"></i></a>
</h4>
<p>En este caso trabajamos con datos agrupados que contabilizan los éxitos (número de polillas muertas) y los fracasos (número de polillas vivas) para cada combinación considerada en el diseño experimental. Se consideran las variables predictoras <code>sex</code> (categórica) y <code>dosis</code> (numérica).</p>
<p>El banco de datos es <code>Dosis</code> y contiene además las polillas totales, muertas y vivas (calculadas como muertas - vivas), y el logaritmo de la dosis suministrada, ya que de forma habitual en este tipo de modelos se suele trabajar en dicha escala logarítmica. Para ajustar el modelo de regresión logística consideramos los efectos asociados con cada predictora, así como la posible interacción entre ambos:</p>
<div class="sourceCode" id="cb701"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Yres</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">Dosis</span><span class="op">$</span><span class="va">dead</span>,<span class="va">Dosis</span><span class="op">$</span><span class="va">alive</span><span class="op">)</span>
<span class="va">fit.dosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Yres</span>  <span class="op">~</span> <span class="va">sex</span> <span class="op">*</span> <span class="va">ldosis</span>,
          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,
          data <span class="op">=</span> <span class="va">Dosis</span><span class="op">)</span></code></pre></div>
<p>Analizamos el modelo obtenido:</p>
<div class="sourceCode" id="cb702"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>, 
          transform <span class="op">=</span> <span class="cn">NULL</span>,
          string.est <span class="op">=</span> <span class="st">"Estimate"</span>,
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Yres
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimate
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.99
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-4.19 – -2.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex [M]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.37 – 1.72
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.822
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ldosis
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.31
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.87 – 1.82
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex [M] * ldosis
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.24 – 1.31
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.191
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
12
</td>
</tr>
</table></div>
<div class="sourceCode" id="cb703"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>, 
           transform <span class="op">=</span> <span class="cn">NULL</span>, 
           axis.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Estimate"</span>,<span class="st">""</span><span class="op">)</span>,
           show.values <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom013-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>De los resultados obtenidos parece desprenderse que no existe efecto de interacción entre sexo y dosis. Antes de tratar de explicar el resto de efectos deberemos estudiar la posibilidad de eliminar dicho efecto del modelo. Las ecuaciones de este modelo vienen dadas por:</p>
<p><span class="math display">\[
log\left(\frac{\widehat{\pi_i}}{1-\widehat{\pi_i}}\right)_{Machos} = -2.82 + 1.82 * ldosis_{i} 
\]</span></p>
<p><span class="math display">\[
log\left(\frac{\widehat{\pi_i}}{1-\widehat{\pi_i}}\right)_{Hembras} = -2.99 + 1.31 * ldosis_{i}
\]</span></p>
<p>En el punto siguiente seleccionaremos el mejor modelo e interpretaremos con detalle los coeficientes y los odds-ratios estimados.</p>
<p>Por otro lado, el p-valor para valorar la bondad del ajuste:</p>
<div class="sourceCode" id="cb704"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">fit.dosis</span><span class="op">$</span><span class="va">deviance</span>,<span class="va">fit.dosis</span><span class="op">$</span><span class="va">df.residual</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.7582464</code></pre>
<p>parece indicar que el ajuste obtenido es bueno, dado que es superior a 0.05.</p>
</div>
</div>
</div>
<div id="selección-del-modelo" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Selección del modelo<a class="anchor" aria-label="anchor" href="#selecci%C3%B3n-del-modelo"><i class="fas fa-link"></i></a>
</h2>
<p>Para la construcción del mejor modelo utilizaremos los mismos procedimientos secuenciales de selección de efectos que vimos en unidades anteriores. En este caso disponemos del criterio Deviance, del AIC y del test <span class="math inline">\(\chi^2\)</span> (p-valor significativo o no) para valorar los efectos del modelo. En este caso utilizaremos el AIC dado que los p-valores son aproximados en este tipo de modelos, y tienen que ser interpretados con mucha cautela.</p>
<p>Para realizar la selección del modelo utilizaremos el procedimiento:</p>
<div class="sourceCode" id="cb706"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">modelo.final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></code></pre></div>
<div id="ejemplos-15" class="section level3" number="13.4.1">
<h3>
<span class="header-section-number">13.4.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-15"><i class="fas fa-link"></i></a>
</h3>
<p>Estudiamos a continuación cada uno de los ejemplos.</p>
<div id="kyphosis-1" class="section level4" number="13.4.1.1">
<h4>
<span class="header-section-number">13.4.1.1</span> Kyphosis<a class="anchor" aria-label="anchor" href="#kyphosis-1"><i class="fas fa-link"></i></a>
</h4>
<p>Realizamos la selección del modelo:</p>
<div class="sourceCode" id="cb707"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">stats</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">fit.kyphosis</span><span class="op">)</span></code></pre></div>
<pre><code>## Start:  AIC=69.38
## Kyphosis ~ Age + Number + Start
## 
##          Df Deviance    AIC
## &lt;none&gt;        61.380 69.380
## - Age     1   64.536 70.536
## - Number  1   65.299 71.299
## - Start   1   71.627 77.627</code></pre>
<pre><code>## 
## Call:  glm(formula = Kyphosis ~ Age + Number + Start, family = binomial(link = logit), 
##     data = kyphosisb)
## 
## Coefficients:
## (Intercept)          Age       Number        Start  
##    -2.03693      0.01093      0.41060     -0.20651  
## 
## Degrees of Freedom: 80 Total (i.e. Null);  77 Residual
## Null Deviance:       83.23 
## Residual Deviance: 61.38     AIC: 69.38</code></pre>
<p>El proceso de selección de efectos indica que no podemos eliminar ninguna variable del modelo (todos los AIC asociados con las predictoras aumentan al eliminarlas). Los valores de Deviance siempre aumentan (deviance asociada a cada variable) cuando eliminamos cualquiera de las variables con respecto a la del modelo que se queda con todas ellas (<code>&lt;none&gt;</code>). Lo mismo ocurre con el estadístico AIC.</p>
<p>Por tanto, el modelo final es el obtenido en el punto anterior. Todo el análisis de los coeficientes y de los odds ratios ya fue detallado y no se repite aquí.</p>
</div>
<div id="dosis-respuesta-1" class="section level4" number="13.4.1.2">
<h4>
<span class="header-section-number">13.4.1.2</span> Dosis-respuesta<a class="anchor" aria-label="anchor" href="#dosis-respuesta-1"><i class="fas fa-link"></i></a>
</h4>
<p>Realizamos la selección para el modelo de dosis-respuesta:</p>
<div class="sourceCode" id="cb710"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">stats</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">fit.dosis</span><span class="op">)</span></code></pre></div>
<pre><code>## Start:  AIC=43.1
## Yres ~ sex * ldosis
## 
##              Df Deviance    AIC
## - sex:ldosis  1   6.7571 42.867
## &lt;none&gt;            4.9937 43.104
## 
## Step:  AIC=42.87
## Yres ~ sex + ldosis
## 
##          Df Deviance     AIC
## &lt;none&gt;         6.757  42.867
## - sex     1   16.984  51.094
## - ldosis  1  118.799 152.909</code></pre>
<pre><code>## 
## Call:  glm(formula = Yres ~ sex + ldosis, family = binomial(link = logit), 
##     data = Dosis)
## 
## Coefficients:
## (Intercept)         sexM       ldosis  
##      -3.473        1.101        1.535  
## 
## Degrees of Freedom: 11 Total (i.e. Null);  9 Residual
## Null Deviance:       124.9 
## Residual Deviance: 6.757     AIC: 42.87</code></pre>
<p>El proceso de selección indica que no debemos considerar el efecto de interacción ya que el valor de deviance es inferior cuando está presente que cuando lo eliminamos, el AIC aumenta al eliminarlo. El resto de efectos del modelo no pueden ser eliminados. Esto implica que al no haber efecto de interacción la probabilidad de morir se puede obtener mediante comportamientos paralelos para machos y hembras.</p>
<p>Ajustamos el modelo sin interacción y realizamos el análisis de dicho modelo:</p>
<div class="sourceCode" id="cb713"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit.dosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Yres</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">ldosis</span>,
                 family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,
                 data <span class="op">=</span> <span class="va">Dosis</span><span class="op">)</span></code></pre></div>
<p>La inferencia sobre el modelo viene dada por:</p>
<div class="sourceCode" id="cb714"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>, 
          transform <span class="op">=</span> <span class="cn">NULL</span>,
          string.est <span class="op">=</span> <span class="st">"Estimate"</span>,
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Yres
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimate
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-4.46 – -2.61
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex [M]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.42 – 1.82
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.002</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ldosis
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.54
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.19 – 1.93
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
12
</td>
</tr>
</table></div>
<p>de forma que podemos escribir el predictor lineal mediante las expresiones siguientes (atendiendo a los diferentes valores de <code>sex</code>):</p>
<p><span class="math display">\[
log\left(\frac{\widehat{\pi_i}}{1-\widehat{\pi_i}}\right)_{Machos} = -2.37 + 1,54* ldosis_{i}
\]</span></p>
<p><span class="math display">\[
log\left(\frac{\widehat{\pi_i}}{1-\widehat{\pi_i}}\right)_{Hembras} = -3.47 + 1.54* ldosis_{i}
\]</span></p>
<p>donde <span class="math inline">\(\pi_i\)</span> es la probabilidad de muerte de la polilla. Dado que la interceptación es más pequeña para las hembras que para los machos tenemos un indicador de que las hembras son más resistentes que los machos. La pendiente positiva refleja que la probabilidad de muerte aumenta cuando lo hace la dosis.</p>
<p>En términos de los odds ratios:</p>
<div class="sourceCode" id="cb715"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>, 
          show.r2 <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Yres
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.07
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex [M]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.52 – 6.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.002</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ldosis
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
4.64
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.28 – 6.90
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
12
</td>
</tr>
</table></div>
<p>podemos ver que el odds ratio de los machos frente a las hembras es 3.01 veces (coeficiente de sexo) superior, y es 4.64 veces mayor (coeficiente de log(dosis)) cuando aumentamos en una unidad el logaritmo de la dosis.</p>
<p>El odds ratio por sexo se obtiene como:
<span class="math display">\[
\frac{\left(\widehat{\pi_i}/(1-\widehat{\pi_i})\right)_{Machos}}{\left(\widehat{\pi_i}/(1-\widehat{\pi_i})\right)_{Hembras}} = \frac{exp(-2.37 + 1,54 * ldosis_{i})}{exp(-3.47 + 1.54 * ldosis_{i})} = exp(3.47 - 2.37) = exp(1.1)
\]</span></p>
<p>mientras que el odds ratio por ldosis, tanto para machos como para hembras, se obtiene como (tomamos los machos):
<span class="math display">\[
\frac{\left(\widehat{\pi_i}/(1-\widehat{\pi_i})\right)_{Machos}}{\left(\widehat{\pi_i}/(1-\widehat{\pi_i})\right)_{Machos}} = \frac{exp(-2.37 + 1,54 * (ldosis_{i}+1))}{exp(-2.37 + 1.54 * ldosis_{i})} = exp(1.54) 
\]</span></p>
<p>La bondad de ajuste de este modelo:</p>
<div class="sourceCode" id="cb716"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">fit.dosis</span><span class="op">$</span><span class="va">deviance</span>,<span class="va">fit.dosis</span><span class="op">$</span><span class="va">df.residual</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.6623957</code></pre>
<p>muestra que el ajuste obtenido puede considerarse como bueno dado que el p-valor resulta no significativo.</p>
<p>Para verificar el efecto de la dosis por sexo podemos calcular cuál es la dosis necesaria aplicar a cada sexo para conseguir una probabilidad de muerte del 50%, o como habitualmente se conoce con el nombre de dosis letal al 50% (LD50). Para ello basta con sustituir en las ecuaciones anteriores el valor de <span class="math inline">\(\pi_i\)</span> por 0.5 y despejar el valor de ldosis:</p>
<p><span class="math display">\[ldosis50_{Machos} = \frac{2.372}{1.535} = 1.54277 \to dosis50_{Machos} = exp(1.54277) = 4.69 \]</span>
<span class="math display">\[ldosis50_{Hembras} = \frac{3.473}{1.535} = 2.262541 \to dosis50_{Hembras} = exp(1.54277) = 9.61 \]</span></p>
<p>De los resultados obtenidos podemos ver que hay que aplicar el doble de dosis en las hembras para conseguir la misma probabilidad de muerte del 50%.</p>
<p>Para conseguir cualquier otra dosis letal basta con sustituir <span class="math inline">\(\pi_i\)</span> por la correspondiente probabilidad y despejar en las ecuaciones obtenidas, o utilizar el código siguiente para obtener la dosis letal a una probabilidad “prob”:</p>
<div class="sourceCode" id="cb718"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># prob = Probabilidad buscada</span>
<span class="va">predictor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span><span class="op">$</span><span class="fu">linkfun</span><span class="op">(</span><span class="va">prob</span><span class="op">)</span>
<span class="va">machos</span> <span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">(</span><span class="va">predictor</span><span class="op">+</span><span class="fl">2.372</span><span class="op">)</span><span class="op">/</span><span class="fl">1.535</span><span class="op">)</span>
<span class="va">hembras</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">(</span><span class="va">predictor</span><span class="op">+</span><span class="fl">3.473</span><span class="op">)</span><span class="op">/</span><span class="fl">1.535</span><span class="op">)</span></code></pre></div>
<p>Utilizamos el código anterior para representar y estudiar las curvas de dosis letales para ambos sexos (machos = azul, hembras = rojo):</p>
<div class="sourceCode" id="cb719"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.05</span>,<span class="fl">0.95</span>,<span class="fl">0.01</span><span class="op">)</span>
<span class="co"># Trabajamos con dosis </span>
<span class="va">predictor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span><span class="op">$</span><span class="fu">linkfun</span><span class="op">(</span><span class="va">prob</span><span class="op">)</span>
<span class="va">machos</span> <span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">(</span><span class="va">predictor</span> <span class="op">+</span> <span class="fl">2.372</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1.535</span><span class="op">)</span>
<span class="va">hembras</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">(</span><span class="va">predictor</span> <span class="op">+</span> <span class="fl">3.473</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1.535</span><span class="op">)</span>
<span class="va">dosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">prob</span>, <span class="va">machos</span>, <span class="va">hembras</span><span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dosis</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">prob</span>, y <span class="op">=</span> <span class="va">machos</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">prob</span>, y <span class="op">=</span> <span class="va">hembras</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0.05</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">70</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Probabilidad de muerte"</span>, y <span class="op">=</span> <span class="st">"Dosis"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom023-1.png" width="95%" style="display: block; margin: auto;"></div>
</div>
</div>
</div>
<div id="diagnóstico-4" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> Diagnóstico<a class="anchor" aria-label="anchor" href="#diagn%C3%B3stico-4"><i class="fas fa-link"></i></a>
</h2>
<p>Antes de comenzar el proceso de diagnóstico hay que recordar que en este tipo de modelos tenemos dos tipos de valores ajustados y dos tipos de residuos:</p>
<ul>
<li>Los correspondientes al predictor lineal obtenidos con las estimaciones de los parámetros del modelo.</li>
<li>Los correspondientes a los valores originales que se obtienen al deshacer la transformación de la función de enlace.</li>
</ul>
<p>El diagnóstico de los GLM se basa en los procedimientos gráficos, que vimos en temas anteriores, aplicado a los residuos deviance obtenidos a partir del predictor lineal considerado (<span class="math inline">\(X\widehat{\beta}\)</span>). Tanto para obtener los valores ajustados y residuos del predictor lineal utilizaremos la función <code>fortify</code>. Al resultado de dicha función podemos añadir sin muchos problemas los residuos entre valores originales de la respuesta y predichos. En el caso del modelo de regresión logística el código necesario viene dado por:</p>
<div class="sourceCode" id="cb720"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Sólo hay que sustituir "modelo" por el modelo ajustado a nuestros datos</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="st">"modelo"</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">fitoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.glm.html">predict.glm</a></span><span class="op">(</span><span class="st">"modelo"</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">residoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.summaries.html">residuals.glm</a></span><span class="op">(</span><span class="st">"modelo"</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></code></pre></div>
<p>Los gráficos de diagnóstico que vamos a utilizar son:</p>
<ul>
<li>Residuos vs Ajustados (predictor lineal)</li>
<li>Residuos vs variables en el modelo (predictor lineal)</li>
<li>Valores influyentes</li>
</ul>
<div id="ejemplos-16" class="section level3" number="13.5.1">
<h3>
<span class="header-section-number">13.5.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-16"><i class="fas fa-link"></i></a>
</h3>
<p>Pasamos a analizar cada uno de los ejemplos.</p>
<div id="kyphosis-2" class="section level4" number="13.5.1.1">
<h4>
<span class="header-section-number">13.5.1.1</span> Kyphosis<a class="anchor" aria-label="anchor" href="#kyphosis-2"><i class="fas fa-link"></i></a>
</h4>
<p>Obtenemos todas las cantidades de interés del modelo</p>
<div class="sourceCode" id="cb721"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Obtención de valores para el diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.kyphosis</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">fitoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.glm.html">predict.glm</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">residoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.summaries.html">residuals.glm</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></code></pre></div>
<p>Realizamos los gráficos de diagnóstico</p>
<div class="sourceCode" id="cb722"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#Gráfico de residuos vs ajustados (predictor lineal)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">diagnostico</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.stdresid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method<span class="op">=</span><span class="va">loess</span>, se<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Ajustados"</span>, y <span class="op">=</span> <span class="st">"Residuos"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom026-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Como se puede observar en el gráfico de ajustados versus residuos la interpretación en este tipo de modelos se hace bastante complicada. Esto es debido a que la variable respuesta sólo toma valores 0 y 1, lo que motiva que el gráfico tenga esa pinta tan extraña. Si valoraros las distancias de Cook obtenidas (<code>diagnostico$.cooksd</code>) podemos ver que no hay ninguna superior a 1, y por tanto no tenemos ninguna observación influyente.</p>
<div class="sourceCode" id="cb723"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráficos de residuos vs predictoras (preditor lineal)</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>, type <span class="op">=</span> <span class="st">"resid"</span>,
           show.data <span class="op">=</span> <span class="cn">TRUE</span>,
           ci.lvl <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom027-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En cuanto a los gráficos con respecto a las variables predictoras parece apreciarse ciertas tendencias con respecto a ellas. Este comportamiento parece más evidente con la variable edad donde se ve una parábola indicando la posible existencia de un efecto polinómico de grado 2 con respecto a ella. En las otras dos predictoras el efecto es menos apreciable.</p>
<p>Para solucionar este problema la opción más habitual sería ajustar un nuevo modelo indicando dicha tendencia de grado 2 (modelo polinómico con <code>Age</code>), pero se podría optar también por la inclusión de efectos de suavizado sobre cada una de ellas para evitar esas tendencias observadas. Utilizamos esta última opción y optamos por incluir efectos de suavizado para <code>Age</code> y <code>Start</code> (ambos con tendencias parabólicas) y comparamos con en el modelo sin suavizado.</p>
<p>A pesar de que la respuesta no es numérica pode os utilizar la función <code>gam</code> sin más que identificar el tipo de respuesta y la función de enlace a utilizar. Veamos el ajuste y la comparación entre ambos modelos:</p>
<div class="sourceCode" id="cb724"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo con suavizado en edad y start</span>
<span class="va">fit.kyphosis.gam</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">Kyphosis</span>  <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Age</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>  <span class="op">+</span> 
                          <span class="va">Number</span> <span class="op">+</span> 
                          <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Start</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>,
                        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,<span class="va">kyphosisb</span><span class="op">)</span>
<span class="co"># Comparamos utilizando el estadístico AIC</span>
<span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">fit.kyphosis</span>,<span class="va">fit.kyphosis.gam</span><span class="op">)</span></code></pre></div>
<pre><code>##                        df      AIC
## fit.kyphosis     4.000000 69.37993
## fit.kyphosis.gam 6.107437 62.71679</code></pre>
<p>El menor valor de AIC indica que el modelo con efectos de suavizado es preferible al que no los tiene. Estudiamos con un poco más detalle dicho modelo:</p>
<div class="sourceCode" id="cb726"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Resumen del predictor lineal</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit.kyphosis.gam</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Family: binomial 
## Link function: logit 
## 
## Formula:
## Kyphosis ~ s(Age, k = 10, m = 2, bs = "ps") + Number + s(Start, 
##     k = 10, m = 2, bs = "ps")
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  -3.6011     1.1482  -3.136  0.00171 **
## Number        0.3333     0.2324   1.434  0.15160   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##            edf Ref.df Chi.sq p-value  
## s(Age)   2.151  2.671  6.345  0.0699 .
## s(Start) 1.956  2.409  9.747  0.0130 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  0.354   Deviance explained = 39.3%
## UBRE = -0.22572  Scale est. = 1         n = 81</code></pre>
<p>En los efectos paramétricos se comprueba que el efecto asociado con <code>Number</code> no resulta significativo, mientras que en los no paramétricos vemos que el suavizado con edad no resulta significativo al 95%. Construimos todos los posibles modelos y valoramos cual de ellos es el mejor:</p>
<div class="sourceCode" id="cb728"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Modelo con suavizados y number</span>
<span class="va">M1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">Kyphosis</span>  <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Age</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>  <span class="op">+</span> 
            <span class="va">Number</span> <span class="op">+</span> 
            <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Start</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>,
          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,<span class="va">kyphosisb</span><span class="op">)</span>
<span class="co"># Modelo con suavizados y sin number</span>
<span class="va">M2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">Kyphosis</span>  <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Age</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span> <span class="op">+</span> 
            <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Start</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>,
          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,<span class="va">kyphosisb</span><span class="op">)</span>
<span class="co"># Modelo con suavizados con Start unicamente</span>
<span class="va">M3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">Kyphosis</span>  <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">Start</span>, k <span class="op">=</span> <span class="fl">10</span>, m <span class="op">=</span> <span class="fl">2</span>, bs <span class="op">=</span> <span class="st">"ps"</span><span class="op">)</span>,
          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="va">logit</span><span class="op">)</span>,<span class="va">kyphosisb</span><span class="op">)</span>
<span class="co"># Valores de AIC</span>
<span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">M1</span>,<span class="va">M2</span>,<span class="va">M3</span><span class="op">)</span></code></pre></div>
<pre><code>##          df      AIC
## M1 6.107437 62.71679
## M2 5.237969 62.98679
## M3 3.066073 68.34242</code></pre>
<div class="sourceCode" id="cb730"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Valores de GCV</span>
<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">M1</span><span class="op">$</span><span class="va">gcv.ubre</span>,<span class="va">M2</span><span class="op">$</span><span class="va">gcv.ubre</span>,<span class="va">M3</span><span class="op">$</span><span class="va">gcv.ubre</span><span class="op">)</span></code></pre></div>
<pre><code>##     GCV.Cp     GCV.Cp     GCV.Cp 
## -0.2257187 -0.2223853 -0.1562664</code></pre>
<p>El menor valor de AIC corresponde al modelo con los dos suavizados y la variable <code>Number</code>. Hay que tener en cuenta que las significatividades que parecen en las tablas son aproximaciones asintóticas, y por tanto siempre se deben tomar con cautela y proceder con otro tipo de comparación. El estadístico GCV también proporciona la misma conclusión.</p>
<p>Por tanto, el modelo final ajustado viene dado por:</p>
<p><span class="math display">\[log\left(\frac{\pi_i}{1-\pi_i}\right) = -3.60 + 0.33 * Number_i + s(Age_i) + s(Start_i)\]</span></p>
<p>Realizamos el diagnóstico del modelo de suavizado utilizando los procedimientos vistos en dicha unidad.</p>
<div class="sourceCode" id="cb732"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráficos de diagnóstico</span>
<span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.check.html">gam.check</a></span><span class="op">(</span><span class="va">fit.kyphosis.gam</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom031-1.png" width="95%" style="display: block; margin: auto;"></div>
<pre><code>## 
## Method: UBRE   Optimizer: outer newton
## full convergence after 4 iterations.
## Gradient range [-5.641377e-09,6.154328e-08]
## (score -0.2257187 &amp; scale 1).
## Hessian positive definite, eigenvalue range [0.007746516,0.01021528].
## Model rank =  20 / 20 
## 
## Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
## indicate that k is too low, especially if edf is close to k'.
## 
##            k'  edf k-index p-value
## s(Age)   9.00 2.15    1.11    0.83
## s(Start) 9.00 1.96    1.14    0.90</code></pre>
<p>Ningún p-valor resulta significativo indicando que el suavizado utilizado es adecuado. Además, los gráficos de diagnóstico no reportan ninguna incidencia.</p>
</div>
<div id="dosis---respuesta" class="section level4" number="13.5.1.2">
<h4>
<span class="header-section-number">13.5.1.2</span> Dosis - respuesta<a class="anchor" aria-label="anchor" href="#dosis---respuesta"><i class="fas fa-link"></i></a>
</h4>
<p>Realizamos ahora el diagnóstico para el modelo de dosis-respuesta a partir del modelo sin interacción obtenido en el apartado de selección del modelo. Obtenemos las cantidades de interés y realizamos los gráficos correspondientes.</p>
<p>Obtenemos todas las cantidades de interés del modelo</p>
<div class="sourceCode" id="cb734"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Obtención de valores para el diagnóstico</span>
<span class="va">diagnostico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/fortify.html">fortify</a></span><span class="op">(</span><span class="va">fit.dosis</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">fitoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.glm.html">predict.glm</a></span><span class="op">(</span><span class="va">fit.dosis</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>
<span class="va">diagnostico</span><span class="op">$</span><span class="va">residoriginal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.summaries.html">residuals.glm</a></span><span class="op">(</span><span class="va">fit.dosis</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></code></pre></div>
<p>Realizamos el gráfico de residuos versus ajustados identificando por el factor:</p>
<div class="sourceCode" id="cb735"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#Gráfico de residuos vs ajustados (predictor lineal)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">diagnostico</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.stdresid</span>, color <span class="op">=</span> <span class="va">sex</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Ajustados"</span>, y <span class="op">=</span> <span class="st">"Residuos"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom033-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En este caso no hemos ajustado las tendencias, ya que dado el tamaño de muestra tan pequeño en cada uno de los grupos, los resultados podrían mostrar tendencias ficticias que nos podrían hacer dudar de la validez del modelo. En este caso no se puede afirmar que exista ningún tipo de tendencia destacable. Tampoco se registra ninguna observación influyente.</p>
<p>En los gráficos de residuos versus predictoras ocurre algo similar, ya que el número de observaciones es tan bajo que las posibles tendencias observadas no implican una modificación del modelo planteado. Dado el número tan bajo de observaciones el planteamiento de modelos con suavizado sobre dosis no resulta una opción.</p>
<div class="sourceCode" id="cb736"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráficos de residuos vs predictoras (preditor lineal)</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>, type <span class="op">=</span> <span class="st">"resid"</span>,
           show.data <span class="op">=</span> <span class="cn">TRUE</span>,
           ci.lvl <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom034-1.png" width="95%" style="display: block; margin: auto;"></div>
</div>
</div>
</div>
<div id="predicción-4" class="section level2" number="13.6">
<h2>
<span class="header-section-number">13.6</span> Predicción<a class="anchor" aria-label="anchor" href="#predicci%C3%B3n-4"><i class="fas fa-link"></i></a>
</h2>
<p>La predicción en este tipo de modelos se divide en dos fases: i) predicción del predictor lineal, y ii) predicción de la respuesta, aunque evidentemente la más interesante es la correspondiente a la respuesta.</p>
<p>Sin embargo, cuando la respuesta viene individualizada, la predicción obtenida es un valor comprendido entre 0 y 1, con lo que hay que definir una regla para clasificar finalmente al sujeto con un 1 o un 0, identificando el éxito o el fracaso. En esta situación se toma la regla:</p>
<ul>
<li>si la predicción es mayor o igual a 0.5 asignamos un éxito como resultado de la predicción</li>
<li>si la predicción es menor a 0.5 asignamos un fracaso como resultado de la predicción</li>
</ul>
<p>El resultado de la predicción es una tabla de doble entrada donde comparamos los valores observados frente a los predichos calculados con la regla anterior. En esta situación estamos interesados en el porcentaje de observaciones que son correctamente clasificadas como éxitos o fracasos.</p>
<p>Este problema no aparece cuando tenemos datos agrupados ya que la variable respuesta ya es un valor entre 0 y 1, ya que modelizamos directamente la probabilidad de éxito.</p>
<p>En los modelos de suavizado utilizaremos la función <code>gam.predict</code> para conseguir las predicciones.</p>
<div id="ejemplos-17" class="section level3" number="13.6.1">
<h3>
<span class="header-section-number">13.6.1</span> Ejemplos<a class="anchor" aria-label="anchor" href="#ejemplos-17"><i class="fas fa-link"></i></a>
</h3>
<p>A continuación, presentamos los procedimientos para obtener y representar la predicción de los modelos obtenidos en apartados anteriores.</p>
<div id="kyphosis-3" class="section level4" number="13.6.1.1">
<h4>
<span class="header-section-number">13.6.1.1</span> Kyphosis<a class="anchor" aria-label="anchor" href="#kyphosis-3"><i class="fas fa-link"></i></a>
</h4>
<p>Dado que en este caso tenemos datos individualizamos, en primer lugar calculamos la predicción de la respuesta y utilizamos la regla de clasificación presentada anteriormente, para obtener el porcentaje de clasificación correcta.</p>
<div class="sourceCode" id="cb737"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Obtención de predicción de la respuesta</span>
<span class="va">prediccion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/predict.gam.html">predict.gam</a></span><span class="op">(</span><span class="va">fit.kyphosis.gam</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>
<span class="co"># Clasificacmos a cada sujeto como éxito o fracaso</span>
<span class="va">clasificado</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">*</span><span class="op">(</span><span class="va">prediccion</span><span class="op">&gt;=</span><span class="fl">0.5</span><span class="op">)</span>
<span class="va">tabla</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">kyphosis</span><span class="op">$</span><span class="va">Kyphosis</span>,<span class="va">clasificado</span><span class="op">)</span>
<span class="va">tabla</span></code></pre></div>
<pre><code>##          clasificado
##            0  1
##   absent  60  4
##   present  7 10</code></pre>
<div class="sourceCode" id="cb739"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Porcentaje de clasificación correcta</span>
<span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">100</span><span class="op">*</span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">tabla</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">sum</a></span><span class="op">(</span><span class="va">tabla</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 86.42</code></pre>
<p>Tenemos un 86.42% de clasificar correctamente a un individuo como éxito o fracaso en función de las variables predictoras consideradas. El modelo construido tiene alta capacidad predictiva ya que identifica bastante bien a los sujetos clasificados como éxitos y como fracasos.</p>
<p>Estudiamos ahora los efectos marginales individuales de cada efecto presente en el modelo para valorar como influyen en la probabilidad de éxito, es decir, probabilidad de sufrir una malformación.</p>
<div class="sourceCode" id="cb741"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráficos marginales</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.kyphosis.gam</span>, <span class="st">"pred"</span><span class="op">)</span></code></pre></div>
<pre><code>## $Age</code></pre>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom036-1.png" width="95%" style="display: block; margin: auto;"></div>
<pre><code>## 
## $Number</code></pre>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom036-2.png" width="95%" style="display: block; margin: auto;"></div>
<pre><code>## 
## $Start</code></pre>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom036-3.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se observa la parábola que describe la variable <code>Age</code>, la función creciente con <code>Number</code> y la función decreciente con <code>Start</code>. En conclusión, la probabilidad de malformación:</p>
<ul>
<li>es más alta en valores de <code>Age</code> próximos a los 100 meses (probabilidad superior a 0.2).</li>
<li>crece conforme aumenta el número de vértebras involucradas hasta superar el 0.6 con 10 vértebras.</li>
<li>disminuye con la primera vértebra operada (si es a partir de la quinta) hasta hacerse prácticamente cero si empezamos en la vértebra 20.</li>
</ul>
<p>Construimos ahora los gráficos conjuntos para las tres predictoras mediante la creación de escenarios. Concretamente seleccionamos valores para <code>Start</code> y <code>Age</code>:</p>
<ul>
<li>Valores Start: 1, 5, 10, 15.</li>
<li>Valores Age: 0, 50, 100, 150, 200, 250, 300</li>
</ul>
<div class="sourceCode" id="cb745"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráficos marginales</span>
<span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.kyphosis.gam</span>, <span class="st">"pred"</span>, 
           terms <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Number"</span>, <span class="st">"Age [0, 50, 100, 150, 200, 250, 300]"</span>, <span class="st">"Start [1,5,10,15]"</span><span class="op">)</span>,
           ci.lvl <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom037-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Podemos ver el efecto de los escenarios con <code>Number</code> para predecir la probabilidad de malformación. No se aprecian muchas diferencias entre los perfiles de predicción para <code>Start</code> en los tres primeros niveles considerados, donde la probabilidad de malformación es muy similar, pero si se aprecian cambios cuando <code>Start = 15</code>. Esto implica directamente que cuando dicha variable toma valores más grandes la probabilidad de malformación disminuye drásticamente.</p>
</div>
<div id="dosis-respuesta-2" class="section level4" number="13.6.1.2">
<h4>
<span class="header-section-number">13.6.1.2</span> Dosis-respuesta<a class="anchor" aria-label="anchor" href="#dosis-respuesta-2"><i class="fas fa-link"></i></a>
</h4>
<p>Dado que los datos están en formato agrupado obtenemos los gráficos de predicción asociados a los efectos del modelo:</p>
<div class="sourceCode" id="cb746"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">fit.dosis</span>,<span class="st">"pred"</span>,
           terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ldosis"</span>,<span class="st">"sex"</span><span class="op">)</span>,
           title <span class="op">=</span> <span class="st">"Porcentaje de insectos muertos"</span>,
           axis.title  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Log(dosis)"</span>,<span class="st">""</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-GLMBinomial_files/figure-html/binom038-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En los perfiles obtenidos se aprecia claramente el paralelismo entre ambos sexos, mostrando que las hembras son más resistentes (probabilidad de morir más baja) para todos los niveles de dosis considerados, y que la probabilidad de morir aumenta con la dosis suministrada.</p>
</div>
</div>
</div>
<div id="ejercicios-3" class="section level2" number="13.7">
<h2>
<span class="header-section-number">13.7</span> Ejercicios<a class="anchor" aria-label="anchor" href="#ejercicios-3"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Ejercicio 1.</strong> En un experimento se sometió a cierto número de cucarachas (<code>number</code>) a cinco horas de exposición a disulfato de carbono gaseoso a varias concentraciones. Se pretendía investigar la relación existente entre la dosis (<code>dose</code>) de disulfato administrada y la resistencia de los insectos (<code>dead</code>); si existe tal relación, determinar la dosis a la cual es posible garantizar el exterminio del 50% de los insectos.</p>
<div class="sourceCode" id="cb747"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio01</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/E2MlSZ"</span>, col_types <span class="op">=</span> <span class="st">"dii"</span><span class="op">)</span>
<span class="co"># Calculamos los vivos para el ajuste de modelos</span>
<span class="va">ejercicio01</span> <span class="op">=</span> <span class="va">ejercicio01</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>alive <span class="op">=</span> <span class="va">number</span> <span class="op">-</span> <span class="va">dead</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 2.</strong> Se realiza un experimento in vitro para estimar el número de anteras embriogénicas de las especies de plantas Datura innoxia Mill bajo dos condiciones experimentales. El primer tratamiento consiste en almacenar a 3° C durante 48 horas, y el segundo consiste en un control donde no se aplica ningún tratamiento. Además se considera una variable que representa los tres valores de fuerza de centrifugación. Las variables registradas son <code>total</code>, <code>embryogenic</code>, <code>storage</code>, <code>centrifuge</code>. Es de interés en el análisis investigar si efectivamente se demostraba un mayor número de anteras para las diferentes condiciones experimentales.</p>
<div class="sourceCode" id="cb748"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio02</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/6P3zRr"</span>, col_types <span class="op">=</span> <span class="st">"iici"</span><span class="op">)</span>
<span class="co"># Recodificación del factor y variable de no embryogenic</span>
<span class="va">ejercicio02</span> <span class="op">=</span> <span class="va">ejercicio02</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>storage<span class="op">=</span><span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">storage</span>,<span class="st">"Control"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"treatment"</span> <span class="op">=</span> <span class="st">"2"</span><span class="op">)</span>,
         nembrig <span class="op">=</span> <span class="va">total</span> <span class="op">-</span> <span class="va">embryogenic</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 3.</strong> Se realiza un ensayo clínico para determinar en un grupo de personas mayores su estado psiquiátrico. Para cada sujeto se realiza un análisis completo y se clasifica cada uno en función de si muestra rasgos de senilidad (<code>senility</code>) (calificados como 1) o no (calificados como 0). Por otro lado se les pasa el test de escala de inteligencia de adultos (<code>score</code>) para saber si la puntuación obtenida puede ser un indicador de si la persona tiene rasgos de senilidad o no.</p>
<div class="sourceCode" id="cb749"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio03</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/6E8fhd"</span>, col_types <span class="op">=</span> <span class="st">"ic"</span><span class="op">)</span>
<span class="co"># Convertimos la respuesta para el ajuste de modelos</span>
<span class="va">ejercicio03</span> <span class="op">=</span> <span class="va">ejercicio03</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>senility <span class="op">=</span> <span class="fl">1</span><span class="op">*</span><span class="op">(</span><span class="va">senility</span><span class="op">==</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 4.</strong> Se realiza un estudio para conocer que el impacto de la bomba de hiroshima en al aparición de caso de leucemia. Para ello se registro para todos los sujetos que presentaron algún tipo de cáncer el grado de radiación al que fue sometida la persona. Las variables que aparecen son los conteos del número de casos de leucemia (<code>leukemia</code>) y de otros tipos de cáncer (<code>other</code>) para los diferentes niveles de radiación (<code>radiation</code>). Se contabilizan también el número total de casos de cáncer registrados (<code>total</code>). Es de interés en el análisis investigar la influencia del grado de radiación en la aparición de un mayor número de casos de leucemia.</p>
<div class="sourceCode" id="cb750"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio04</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/ZDIWVC"</span>, col_types <span class="op">=</span> <span class="st">"ciii"</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 5.</strong> La Oficina Europea de Patentes puede proteger una patente de la competencia durante un cierto período de tiempo. La Oficina de Patentes tiene la tarea de examinar las invenciones y declarar patentes si se cumplen ciertos requisitos previos. El requisito más importante es que la invención sea algo realmente nuevo. Con el fin de analizar las objeciones contra las patentes, se recopiló un conjunto de datos con 4,866 patentes de los sectores biotecnología / farmacia y semiconductor / computadora. Las variables inclinadas son: <code>opp</code> = oposición de patente; <code>biopharm</code> = Patente del sector biotecnológico / farmacéutico; <code>ustwin</code> = existe la patente gemela estadounidense; <code>patus</code> = titular de la patente de los Estados Unidos; <code>patgsgr</code> = titular de la patente de Alemania, Suiza o Gran Bretaña; año = Año de concesión; <code>ncit</code> = Número de citas de la patente; <code>ncountry</code> = Número de estados designados para la patente; <code>nclaims</code> = Número de declaraciones. ¿Cómo afecta cada una de las variables consideradas en la posible objeción a una patente?</p>
<div class="sourceCode" id="cb751"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ejercicio05</span> <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/2EygLk"</span>, col_types <span class="op">=</span> <span class="st">"ccccciiii"</span><span class="op">)</span>
<span class="co"># Recodificación de factores</span>
<span class="va">ejercicio05</span> <span class="op">=</span> <span class="va">ejercicio05</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>opp <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">opp</span>,<span class="st">"yes"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"no"</span> <span class="op">=</span> <span class="st">"0"</span><span class="op">)</span>, 
         biopharm<span class="op">=</span><span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">biopharm</span>,<span class="st">"yes"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"no"</span> <span class="op">=</span><span class="st">"0"</span><span class="op">)</span>,
         ustwin<span class="op">=</span><span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">ustwin</span>,<span class="st">"yes"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"no"</span> <span class="op">=</span> <span class="st">"0"</span><span class="op">)</span>,
         patus<span class="op">=</span><span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">patus</span>,<span class="st">"yes"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"no"</span> <span class="op">=</span> <span class="st">"0"</span><span class="op">)</span>,
         patgsgr<span class="op">=</span><span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">patgsgr</span>,<span class="st">"yes"</span> <span class="op">=</span> <span class="st">"1"</span>,<span class="st">"no"</span> <span class="op">=</span> <span class="st">"0"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 6.</strong> Los datos siguientes describen los patrones de comportamiento en el consumo de drogas psicotrópicas en una muestra de individuos del Oeste de Londres. Los investigadores se plantean las preguntas siguientes:</p>
<ul>
<li>¿Hay diferencias por <code>sexo</code> en el consumo de drogas? ¿Cómo influye la <code>edad</code> para explicar el consumo de psicotrópicos? ¿La edad influye igual en hombres y en mujeres?</li>
<li>Obtén la expresión y el valor de las predicciones sobre el consumo de psicotrópicos en hombres y en mujeres de 17 y 52 años con el modelo ajustado.</li>
</ul>
<p>Las variables <code>usa</code> y <code>nousa</code> contienen la información sobre el uso de drogas psicotrópicas.</p>
<div class="sourceCode" id="cb752"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sexo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"H"</span>,<span class="fl">4</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"M"</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">edad</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"16-29"</span>,<span class="st">"30-44"</span>,<span class="st">"45-64"</span>,<span class="st">"65-74"</span>,<span class="st">"16-29"</span>,<span class="st">"30-44"</span>,<span class="st">"45-64"</span>,<span class="st">"65-74"</span><span class="op">)</span>
<span class="va">usa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">21</span>,<span class="fl">32</span>,<span class="fl">70</span>,<span class="fl">43</span>,<span class="fl">46</span>,<span class="fl">89</span>,<span class="fl">169</span>,<span class="fl">51</span><span class="op">)</span>
<span class="va">nousa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">683</span>,<span class="fl">596</span>,<span class="fl">705</span>,<span class="fl">295</span>,<span class="fl">738</span>,<span class="fl">700</span>,<span class="fl">847</span>,<span class="fl">196</span><span class="op">)</span>
<span class="va">ejercicio06</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">sexo</span>, <span class="va">edad</span>, <span class="va">usa</span>, <span class="va">nousa</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 7.</strong> Se desea estudiar la sensibilidad de un test basado en el diagnóstico de la tuberculosis a través de una prueba basada en rayos X. la información registrdas viene agrupada para las variables <code>tuberculosis</code>, <code>total</code> y <code>rayosx</code>. En las dos primeras se registran los positivos y negativos detectados por rayox para los enfermos de tuberculosis y para todos los que se realziaron las pruebas.</p>
<div class="sourceCode" id="cb753"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tuberculosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">22</span>,<span class="fl">8</span><span class="op">)</span>
<span class="va">total</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">51</span>,<span class="fl">1739</span><span class="op">)</span>
<span class="va">rayosx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Positivo"</span>,<span class="st">"Negativo"</span><span class="op">)</span>
<span class="va">ejercicio07</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">tuberculosis</span>, <span class="va">total</span>, <span class="va">rayosx</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 8.</strong> En el Hospital de Yale-New Heaven, en Connecticut, se llevó a cabo un estudio para investigar la relación entre los nacimientos prematuros (el niño nazca antes de 37 semanas de gestación o su peso sea inferior a 2500 g.) y la edad de la madre. La población de estudio consistió en 175 madres de niños nacidos únicos y prematuros, y 303 madres de niños no prematuros. Los datos agrupados en función de la edad de la madre se presentan a continuación. ¿Hay alguna relación entre la edad de la madre y el hecho de que un niño nazca prematuro? ¿Cuál es el grupo de edad con mayor riesgo?</p>
<div class="sourceCode" id="cb754"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">edad</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"14-17"</span>,<span class="st">"18-19"</span>,<span class="st">"20-24"</span>,<span class="st">"25-29"</span>,<span class="st">"+30"</span><span class="op">)</span>
<span class="va">casos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">15</span>,<span class="fl">22</span>,<span class="fl">47</span>,<span class="fl">56</span>,<span class="fl">35</span><span class="op">)</span>
<span class="va">controles</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16</span>,<span class="fl">25</span>,<span class="fl">62</span>,<span class="fl">122</span>,<span class="fl">18</span><span class="op">)</span>
<span class="va">ejercicio08</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">edad</span>, <span class="va">casos</span>, <span class="va">controles</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 9.</strong> En el banco de datos siguiente se presentan los resultados de una encuesta realizada en 1998. A cada sujeto de una muestra de 300 adultos se le pidió que opinara sobre qué política consideraba adecuada implantar respecto al uso de tabaco en lugares públicos. Las opciones planteadas son:</p>
<ul>
<li>Opción 1: Sin restricciones</li>
<li>Opción 2: Fumar sólo en áreas exclusivas</li>
<li>Opción 3: No fumar nunca</li>
<li>Opción 4: No opina</li>
</ul>
<p>¿Hay alguna relación entre la actitud frente al tabaco y el nivel de estudios?</p>
<div class="sourceCode" id="cb755"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nivel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Est. Superiores"</span>, <span class="st">"Secundaria"</span>, <span class="st">"Primaria"</span><span class="op">)</span>
<span class="va">opt1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">15</span>,<span class="fl">15</span><span class="op">)</span>
<span class="va">opt2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">44</span>,<span class="fl">100</span>,<span class="fl">40</span><span class="op">)</span>
<span class="va">opt3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">23</span>,<span class="fl">30</span>,<span class="fl">10</span><span class="op">)</span>
<span class="va">opt4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">5</span>,<span class="fl">10</span><span class="op">)</span>
<span class="va">total</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">75</span>,<span class="fl">150</span>,<span class="fl">75</span><span class="op">)</span>
<span class="va">ejercicio09</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">nivel</span>, <span class="va">opt1</span>, <span class="va">opt2</span>, <span class="va">opt3</span>, <span class="va">opt4</span>, <span class="va">total</span><span class="op">)</span></code></pre></div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="glm.html"><span class="header-section-number">12</span> Modelos Lineales Generalizados</a></div>
<div class="next"><a href="glmpoisson.html"><span class="header-section-number">14</span> GLM Poisson</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#glmbinomial"><span class="header-section-number">13</span> GLM respuesta binomial</a></li>
<li>
<a class="nav-link" href="#tipos-de-datos-binomiales"><span class="header-section-number">13.1</span> Tipos de datos binomiales</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#informaci%C3%B3n-individualizada-por-sujeto"><span class="header-section-number">13.1.1</span> Información individualizada por sujeto</a></li>
<li><a class="nav-link" href="#informaci%C3%B3n-agrupada-por-sujetos"><span class="header-section-number">13.1.2</span> Información agrupada por sujetos</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#especificaci%C3%B3n-e-hip%C3%B3tesis-de-modelo"><span class="header-section-number">13.2</span> Especificación e hipótesis de modelo</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#funciones-link"><span class="header-section-number">13.2.1</span> Funciones link</a></li>
<li><a class="nav-link" href="#representaci%C3%B3n-de-las-funciones-link"><span class="header-section-number">13.2.2</span> Representación de las funciones link</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#estimaci%C3%B3n-y-bondad-de-ajuste"><span class="header-section-number">13.3</span> Estimación y bondad de ajuste</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-14"><span class="header-section-number">13.3.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#selecci%C3%B3n-del-modelo"><span class="header-section-number">13.4</span> Selección del modelo</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-15"><span class="header-section-number">13.4.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#diagn%C3%B3stico-4"><span class="header-section-number">13.5</span> Diagnóstico</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-16"><span class="header-section-number">13.5.1</span> Ejemplos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#predicci%C3%B3n-4"><span class="header-section-number">13.6</span> Predicción</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplos-17"><span class="header-section-number">13.6.1</span> Ejemplos</a></li></ul>
</li>
<li><a class="nav-link" href="#ejercicios-3"><span class="header-section-number">13.7</span> Ejercicios</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modelos Estadísticos</strong>" was written by true, true. It was last built on 2022-03-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
