<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Unidad 16 GLM para datos de supervivencia | Modelos Estadísticos</title>
<meta name="description" content="El análisis de supervivencia examina y modela el tiempo que tardan en producirse lo que denominamos “eventos” aleatorios. Habitualmente dicho evento se asocia con la muerte del sujeto bajo estudio...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Unidad 16 GLM para datos de supervivencia | Modelos Estadísticos">
<meta property="og:type" content="book">
<meta property="og:description" content="El análisis de supervivencia examina y modela el tiempo que tardan en producirse lo que denominamos “eventos” aleatorios. Habitualmente dicho evento se asocia con la muerte del sujeto bajo estudio...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Unidad 16 GLM para datos de supervivencia | Modelos Estadísticos">
<meta name="twitter:description" content="El análisis de supervivencia examina y modela el tiempo que tardan en producirse lo que denominamos “eventos” aleatorios. Habitualmente dicho evento se asocia con la muerte del sujeto bajo estudio...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="bs4_style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Modelos Estadísticos</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Bienvenidos</a></li>
<li><a class="" href="introlibro.html"><span class="header-section-number">1</span> Comenzamos</a></li>
<li><a class="" href="aed.html"><span class="header-section-number">2</span> Análisis exploratorio de datos</a></li>
<li><a class="" href="prob.html"><span class="header-section-number">3</span> Probabilidad</a></li>
<li><a class="" href="inferencia-b%C3%A1sica.html"><span class="header-section-number">4</span> Inferencia básica</a></li>
<li><a class="" href="modelstats.html"><span class="header-section-number">5</span> Modelos estadísticos</a></li>
<li><a class="" href="rls.html"><span class="header-section-number">6</span> Regresión Lineal Simple (RLS)</a></li>
<li><a class="" href="rlm.html"><span class="header-section-number">7</span> Regresión Lineal Múltiple y Polinómica</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">8</span> Modelos ANOVA</a></li>
<li><a class="" href="ancova.html"><span class="header-section-number">9</span> Modelos ANCOVA</a></li>
<li><a class="" href="smooth.html"><span class="header-section-number">10</span> Modelos aditivos lineales</a></li>
<li><a class="" href="mmixed.html"><span class="header-section-number">11</span> Modelos Lineales Mixtos</a></li>
<li><a class="" href="glm.html"><span class="header-section-number">12</span> Modelos Lineales Generalizados</a></li>
<li><a class="" href="glmbinomial.html"><span class="header-section-number">13</span> GLM respuesta binomial</a></li>
<li><a class="" href="glmpoisson.html"><span class="header-section-number">14</span> GLM Poisson</a></li>
<li><a class="" href="glmtablascont.html"><span class="header-section-number">15</span> GLM para tablas de contingencia</a></li>
<li><a class="active" href="glmsuperv.html"><span class="header-section-number">16</span> GLM para datos de supervivencia</a></li>
<li><a class="" href="referencias.html">Referencias</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="glmsuperv" class="section level1" number="16">
<h1>
<span class="header-section-number">Unidad 16</span> GLM para datos de supervivencia<a class="anchor" aria-label="anchor" href="#glmsuperv"><i class="fas fa-link"></i></a>
</h1>
<p>El análisis de supervivencia examina y modela el tiempo que tardan en producirse lo que denominamos “eventos” aleatorios. Habitualmente dicho evento se asocia con la muerte del sujeto bajo estudio lo que justifica su nombre como análisis de supervivencia. Sin embargo el ámbito de aplicación es mucho más amplio. Esencialmente, la misma metodología utilizada para el estudio de mortalidad se utiliza para el “análisis de eventos históricos” en sociología y el “análisis del tiempo de fallo” en ingeniería.</p>
<p>Cuando se toman datos sobre tiempos de supervivencia en un conjunto de sujetos, se toma como resultado de dicha variable:</p>
<ul>
<li>el tiempo en que acontece el suceso (el sujeto muere, la máquina falla, la enfermedad remite,etc…</li>
<li>o el tiempo transcurrido hasta la finalización del periodo de seguimiento del experimento.</li>
</ul>
<p>Tenemos por tanto, dos posibilidades para cada sujeto en función se si ocurre o no el evento de interés. Los sujetos en los que al finalizar el periodo bajo estudio no se ha registrado el evento de interés se denominan datos censurados o incompletos. Las observaciones censuradas aún contienen información importante. Se sabe que al final del período de observación, un individuo con dato censurado es un individuo sobre el que no ha ocurrido el evento de interés, es decir, un individuo cuyo tiempo de vida supera al tiempo del periodo de observación.</p>
<p>Los tipos de censura más habituales son:</p>
<ul>
<li>censura por tiempo, que ocurre cuando se deja de observar a los individuos una vez que ha transcurrido un intervalo fijo de tiempo. En consecuencia, no se sabe si actualmente a ocurrido el evento de interés o no. Es frecuente en estudios médicos.</li>
<li>censura por fallo: si a lo largo del período de estudio se “pierden” casos (pacientes que dejan ele asistir a las revisiones, etc.), a pesar ele que el estudio prosiga hasta conseguir información completa sobre un número fijo de casos. Es común en tests industriales, donde para modelizar el proceso de fallos se observa, en cada máquina, el tiempo transcurrido hasta que tienen un fallo; el objetivo en estos tests es predecir cada cuanto tiempo acontece un fallo.</li>
</ul>
<p>Sin embargo, los casos pueden desaparecer por razones no relacionadas con el estudio o más allá del control del investigador. Esto puede estar o no ligado a la respuesta o a las variables predictoras (por ejemplo, testando un fármaco, un paciente decide suspender el tratamiento debido a los efectos secundarios que le ha provocado).</p>
<p>Por tanto, el análisis de supervivencia se centra en estudiar la función de distribución del tiempo de supervivencia o tiempo hasta que ocurre el evento de interés. El caso más interesante aparece cunado disponemos de variables predictoras que pueden influir en el tiempo de supervivencia. En este tema estudiamos este tipo de modelos y más concretamente los conocidos como modelos de regresión de Cox.</p>
<p>A continuación se muestran los diferentes ejemplos que trabajaremos a lo largo del tema.</p>
<p><strong>Ejemplo Leucemia.</strong> <em>Los datos siguientes provienen de un estudio de supervivencia en pacientes con leucemia mielógena aguda. las variables consideradas son time (tiempo de supervivencia o censura en semanas), status (valor 1 cuando el paciente ha fallecido y 0 si el dato está censurado), y x que indica para cada sujeto si el ciclo estándar de quimioterapia debería extenderse (Maintained) para ciclos adicionales o no (Nonmaintained). La pregunta de interés es si el matenimiento de la quimioteapia mejora la supervivencia de los pacientes.</em></p>
<p><strong>Ejemplo Cáncer de pulmón.</strong> <em>Los datos siguientes provienen de un estudio de supervivencia en pacientes con cáncer de pulmón avanzado del North Central Cancer Treatment Group. A cada paicnete se le pasan diferentes test para medir su capacidad para desempeñarse habitualmente, así ocm variables asociadas con su alimentación. El conjunot de variable consideradas son: inst (código de la institución), time (tiempo de supervivencia en días), status (estado de la censura 1=censurado, 2=muerto), age (edad in años), sex (masculino=1 femenino=2), ph.ecog (puntuación del test ECOG (0=buen estado 5=muerto)), ph.karno (puntuación del test de Karnofsky (malo=0-bueno=100)), pat.karno (test de Karnofsky estandarizado por paciente), meal.cal (conusmo de calorias), wt.loss (peso pérdido en los últimos seis meses). Se desea estudiar la supervivencia de los pacientes en función de las variables registradas.</em></p>
<p><strong>Ejemplo Ratas.</strong> <em>Los datos siguientes provienen de un estudio de supervivencia en ratas. El experimneto consistía en estudiar el efecto de un nuevo tratamiento para un tumor cerebral. Se elegían tres ratas de cada una de 100 camadas y se les generaba un tumor cerebral. Las ratas eran divididas en dos grupos de forma que unas eran tratados con radioterapía y las otras no recibían ningún tratamiento. Las variables consideradas son: litter (camada de la que proviene la rata), rx (1 = radioterapia, 0 = control), time (supervivencia en días), status (0 = censurado, 1 = muerta), sex (f = femenino, m = masculino). El objetvo es estudiar la supervivencia de las ratas en función de las variables consideradas.</em></p>
<p><strong>Ejemplo Ovarian</strong> <em>Los datos siguientes provienen de un estudio de supervivencia en mujeres con cáncer de ovarios sometidas a dos tratamientos distintos. Las variables consideradas son: futime (tiempo de supervivencia en días), fustat (estado de la censura 0 = censurado, 1 = defunción), age (edad de la paciente), resid.ds (persistencia de la enfermedad tras el tratamiento 1 = No, 2 = Si), rx (tratamiento a la que es sometida la paciente), ecog.ps (puntuación del test ECOG 1= buen estado). El objetvo es estudiar la supervivencia de las pacientes en función de las variables consideradas.</em></p>
<p><strong>Ejemplo Retinopatia</strong> <em>Se realiza un ensayo clínico para estudiar la coagulacióncon láser como tratamiento para retrasar la retinopatía diabética. Los 197 pacientes en este conjunto de datos fueron una muestra aleatoria del 50% de los pacientes con retinopatía diabética de “alto riesgo” tal como se define en el Estudio de Retinopatía Diabética (DRS). Cada paciente tenía un ojo asignado al azar al tratamiento con láser y el otro ojo no recibió tratamiento, y tiene dos observaciones en el conjunto de datos. Para cada ojo, el evento de interés fue el tiempo desde el inicio del tratamiento hasta el momento en que la agudeza visual cayó por debajo de 5/200 dos visitas seguidas. Por lo tanto, hay un retraso incorporado de aproximadamente 6 meses (las visitas fueron cada 3 meses). Los tiempos de supervivencia en este conjunto de datos son el tiempo real de pérdida de la visión en meses, menos el tiempo mínimo posible para el evento (6,5 meses). Las variables consideradas son: id (identificación del sujeto), laser (tipo de láser usado xenon o argon), eye (que ojo se ha tratado: left, right ), age (edad al diagnóstico de diabetes), type (tipo de diabetes: juvenile adult), trt (0 = control eye, 1 = treated eye), futime (tiempo hasta de pérdida de visión o finalización del seguimiento), status (0 = censurado, 1 = pérdida de visión en el ojo), risk (un score de riesgo para el ojo, con un valor mayor que 6 indicando riesgo alto en al menos un ojo).</em></p>
<p><strong>Ejemplo Mieloma</strong> <em>Datos de mieloma múltiple extraídos de datos de expresión génica disponibles públicamente (ID GEO: GSE4581). Las variables consideradas son: molecular_group (grupo molecular de pacientes), chr1q21_status (estado de amplificación del cromosoma 1q21), treatment (tratamiento), event (estado de supervivencia 0 = censurado, 1 = muerto), time (tiempo de supervivencia en meses), CCND1, CRIM1, DEPDC1, IRF4, TP53, WHSC1 son las expresiones de los genes.</em></p>
<p><strong>Ejemplo Veteranos</strong> <em>Datos sobre un ensayo aleatorizado de dos regímenes de tratamiento para el cáncer de pulmón en veteranos de guerra. Las variables consideradas son: trt (tratamiento 1=standard 2=test), celltype (1=squamous, 2=smallcell, 3=adeno, 4=large), time (tiempo de supervivencia), status (estado censura 0=censurada), karno (puntuación del test de Karnofsky (100=good)), diagtime (meses desde el diagnóstico hasta la aleatorización), age (en años), prior (si se aplico una terapia anterior 0=no, 1=yes.)</em></p>
<div id="funciones-de-supervivencia" class="section level2" number="16.1">
<h2>
<span class="header-section-number">16.1</span> Funciones de supervivencia<a class="anchor" aria-label="anchor" href="#funciones-de-supervivencia"><i class="fas fa-link"></i></a>
</h2>
<p>Antes de presentar el modelos de regresión de Cox estableemos la notación y definiciones necesarias para el estudio de este tipo de modelos.</p>
<p>Si <span class="math inline">\(f(t)\)</span> denota a la función de densidad de probabilidad para la variable aleatoria <span class="math inline">\(T\)</span>, tiempo de supervivencia, y <span class="math inline">\(F(t)\)</span> a la correspondiente función de distribución, entonces se define la <strong>función de supervivencia</strong> <span class="math inline">\(S(t)\)</span> como la probabilidad de sobrevivir al menos hasta el instante <span class="math inline">\(t\)</span>, esto es,</p>
<p><span class="math display">\[S(t) = P(T &gt; t) = 1 - F(t)\]</span></p>
<p>Se define el riesgo instantáneo de morir o <strong>función hazard</strong>, <span class="math inline">\(h(t)\)</span>, como el cociente entre la función de densidad y la función de supervivencia, es decir:</p>
<p><span class="math display">\[h(t) = \frac{f(t)}{S(t)}\]</span></p>
<p>De hecho, <span class="math inline">\(h(t)dt\)</span> o incremento de la función hazard representa la intensidad del proceso de ocurrencia del evento, o lo que es lo mismo, la probabilidad de que ocurra el evento en un intervalo pequeño de tiempo <span class="math inline">\(dt\)</span> dado que el individuo no ha registrado el evento de interés hasta el instante <span class="math inline">\(t\)</span>.</p>
<p>Una distribución para los tiempos de supervivencia ha de tener una función hazard con buenas propiedades; por ejemplo, es de esperar que la función hazard no decrezca con <span class="math inline">\(t\)</span>, esto es, a más tiempo transcurrido, mayor riesgo de de que ocurra el evento de interés. Teniendo esto en cuenta, se define la <strong>función hazard acumulada</strong>, <span class="math inline">\(H(t)\)</span> como:</p>
<p><span class="math display">\[H(t) = - log S(t)\]</span></p>
<p>Una característica importante de la función de supervivencia es la denominada mediana de supervivencia que es el valor de <span class="math inline">\(t_{0.5}\)</span> de forma que:
<span class="math display">\[S(t_{0.5}) = 0.5\]</span>. Asociado con este valor se puede obtener un intervalo de confianza para la mediana de supervivencia.</p>
<p>Para la modelización de este tipo de datos necesitamos instalar las librerías <code>survival</code> y <code>survminer</code>.</p>
<div id="supervivencia-completa" class="section level3" number="16.1.1">
<h3>
<span class="header-section-number">16.1.1</span> Supervivencia completa<a class="anchor" aria-label="anchor" href="#supervivencia-completa"><i class="fas fa-link"></i></a>
</h3>
<p>En este caso estamos interesados en estimar la curva de supervivencia completa para todo el conjunto de sujetos. La estimación de dichas funciones de supervivencia se realizan mediante las funciones:</p>
<div class="sourceCode" id="cb908"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tiempo de supervivencia y estado de la censura</span>
<span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span>
<span class="co"># Estimación de la supervivencia sin variables predictoras</span>
<span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></code></pre></div>
<p>donde <code>time</code> identifica la variable con los tiempo de supervivencia, <code>status</code> es la variable que identifica si el dato está censurado o no, y <span class="math inline">\(~ 1\)</span> indica que obtenemos la curva de supervivencia completa. Habitualmente se usa la codificación 0-1 donde el cero indica que el tiempo está censurado y 1 cuando ha ocurrido el evento de interés. El resultado de esta función se puede representar para obtener una primera aproximación de la función de supervivencia o conocido como estimador de Kaplan-Meier.</p>
</div>
<div id="supervivencia-por-un-factor" class="section level3" number="16.1.2">
<h3>
<span class="header-section-number">16.1.2</span> Supervivencia por un factor<a class="anchor" aria-label="anchor" href="#supervivencia-por-un-factor"><i class="fas fa-link"></i></a>
</h3>
<p>La primera aproximación para la comparación de curvas de supervivencia es utilizar un factor que separa a la población de sujeto en grupos. En esta situación se puede estimar la curva de supervivencia para cada uno de los grupos. Este proceso se realiza mediante la función:</p>
<div class="sourceCode" id="cb909"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación de la supervivencia sin variables predictoras</span>
<span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">factor</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></code></pre></div>
<p>donde <code>factor</code> identifica la variable de clasificación.</p>
</div>
<div id="test-de-comparación" class="section level3" number="16.1.3">
<h3>
<span class="header-section-number">16.1.3</span> Test de comparación<a class="anchor" aria-label="anchor" href="#test-de-comparaci%C3%B3n"><i class="fas fa-link"></i></a>
</h3>
<p>Dadas dos o más curvas de supervivencia estas se pueden comparar a través de las funciones hazard asociadas a cada una de ellas. Si tenemos <span class="math inline">\(k\)</span> curvas de supervivencia y sus funciones hazard asociadas (<span class="math inline">\(h_1(t), h_2(t),...,h_k(t)\)</span>) el test de comparación viene dado por:</p>
<p><span class="math display">\[\begin{array}{ll}
H_0:&amp; h_1(t) = h_2(t) = ... = h_k(t)\\
H_1:&amp; \text{existen al menos dos } h_i(t) \text{ y } h_j(t) \text{ distintas}\\
\end{array}\]</span></p>
<p>La resolución de este contraste se basa en un test ji-cuadrado. Si rechazamos <span class="math inline">\(H_0\)</span> concluiremos que existen al menos dos curvas de supervivencia distintas. Si tenemos solamente dos curvas el contraste permite establecer si las consideramos iguales o distintas.</p>
</div>
</div>
<div id="análisis-preliminar-1" class="section level2" number="16.2">
<h2>
<span class="header-section-number">16.2</span> Análisis preliminar<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-preliminar-1"><i class="fas fa-link"></i></a>
</h2>
<p>En este análisis preliminar no nos preocupamos por el posible efecto que pueden tener las diferentes variables predictoras en la supervivencia, sino más bien en un estudio descriptivo de la supervivencia global o por un factor de clasificación. Mostramos los resultados para diferentes bancos de datos de los presentados al inicio de este tema. Todos los bancos de datos son accesibles directamente ya que se encuentran alojados dentro de la librería survival.</p>
<div id="leucemia" class="section level3" number="16.2.1">
<h3>
<span class="header-section-number">16.2.1</span> Leucemia<a class="anchor" aria-label="anchor" href="#leucemia"><i class="fas fa-link"></i></a>
</h3>
<p>Para este conjunto de datos obtenemos y representamos la estimación de la curva de supervivencia global así como la mediana de supervivencia.</p>
<div class="sourceCode" id="cb910"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">aml</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = aml)
## 
##       n events median 0.95LCL 0.95UCL
## [1,] 23     18     27      18      45</code></pre>
<div class="sourceCode" id="cb912"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = aml)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     5     23       2   0.9130  0.0588       0.8049        1.000
##     8     21       2   0.8261  0.0790       0.6848        0.996
##     9     19       1   0.7826  0.0860       0.6310        0.971
##    12     18       1   0.7391  0.0916       0.5798        0.942
##    13     17       1   0.6957  0.0959       0.5309        0.912
##    18     14       1   0.6460  0.1011       0.4753        0.878
##    23     13       2   0.5466  0.1073       0.3721        0.803
##    27     11       1   0.4969  0.1084       0.3240        0.762
##    30      9       1   0.4417  0.1095       0.2717        0.718
##    31      8       1   0.3865  0.1089       0.2225        0.671
##    33      7       1   0.3313  0.1064       0.1765        0.622
##    34      6       1   0.2761  0.1020       0.1338        0.569
##    43      5       1   0.2208  0.0954       0.0947        0.515
##    45      4       1   0.1656  0.0860       0.0598        0.458
##    48      2       1   0.0828  0.0727       0.0148        0.462</code></pre>
<div class="sourceCode" id="cb914"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia y mediana de supervivencia</span>
<span class="co"># conf.int: permite obtner el intervalo de confinaza para la curva de supervivencia</span>
<span class="co"># surv.median.line: permite represenatr la mediana de supervivencia </span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">aml</span>, 
           palette <span class="op">=</span> <span class="st">"blue"</span>, 
           conf.int <span class="op">=</span> <span class="cn">FALSE</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv010-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>La mediana de supervivencia se sitúa en 27 semanas con un intervalo de confianza del 95% entre 18 y 45 semanas. En el resumen podemos ver como evoluciona la supervivencia con el tiempo. A partir del gráfico podemos ver que la probabilidad de sobrevivir más de 40 semanas se sitúa por debajo de 0.25.</p>
<p>Realizamos ahora el análisis diferenciando por la variable ‘x’ que indica si el sujeto ha mantenido o no el ciclo de quimioterapia. Representamos las curvas de supervivencia, la mediana de supervivencia, y el pvalor del contraste de comparación de funciones hazard. Añadimos además el intervalo de confianza para la curva de supervivencia de cada grupo.</p>
<div class="sourceCode" id="cb915"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">x</span>, data <span class="op">=</span> <span class="va">aml</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ x, data = aml)
## 
##                  n events median 0.95LCL 0.95UCL
## x=Maintained    11      7     31      18      NA
## x=Nonmaintained 12     11     23       8      NA</code></pre>
<div class="sourceCode" id="cb917"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia y mediana de supervivencia</span>
<span class="co"># conf.int: permite obtner el intervalo de confinaza para la curva de supervivencia</span>
<span class="co"># surv.median.line: permite represenatr la mediana de supervivencia </span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">aml</span>, 
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>, 
           pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv011-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se observa como los sujetos que han mantenido el ciclo de quimioterapia muestran una mayor probabilidad de supervivencia que los que no lo han mantenido. Sin embargo, las medianas de supervivencia entre ambos grupos se diferencia únicamente en 8 meses, y el p-valor resulta no significativo. Tenemos evidencias para concluir que no hay evidencias estadísticas para concluir que las curvas de supervivencia son distintas para cada uno de los grupos considerados.</p>
</div>
<div id="veteranos" class="section level3" number="16.2.2">
<h3>
<span class="header-section-number">16.2.2</span> Veteranos<a class="anchor" aria-label="anchor" href="#veteranos"><i class="fas fa-link"></i></a>
</h3>
<p>Para este conjunto de datos obtenemos el resumen de la mediana de supervivencia para todo el conjunto de datos, y representamos la función de supervivencia y la mediana de supervivencia.</p>
<div class="sourceCode" id="cb918"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">veteran</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = veteran)
## 
##        n events median 0.95LCL 0.95UCL
## [1,] 137    128     80      52     105</code></pre>
<div class="sourceCode" id="cb920"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia e IC</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">veteran</span>, 
           palette <span class="op">=</span> <span class="st">"blue"</span>, 
           conf.int <span class="op">=</span> <span class="cn">FALSE</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv012-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>La mediana de supervivencia se sitúa en 80 semanas con un intervalo de confianza del 95% entre 52 y 105 semanas Realizamos ahora el análisis considerando la variable ‘trt’ que indica el tratamiento del sujeto. Representamos las curvas de supervivencia, la mediana de supervivencia, y el pvalor del contraste de comparación de funciones hazard.</p>
<div class="sourceCode" id="cb921"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">trt</span>, data <span class="op">=</span> <span class="va">veteran</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ trt, data = veteran)
## 
##        n events median 0.95LCL 0.95UCL
## trt=1 69     64  103.0      59     132
## trt=2 68     64   52.5      44      95</code></pre>
<div class="sourceCode" id="cb923"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia y mediana de supervivencia</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">veteran</span>, 
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>, 
           pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv013-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Podemos ver que no existen diferencias entre las curvas de supervivencia para los dos grupos considerados (p-valor superior a 0.05). Probamos ahora con la variable <code>celltype</code>. Como esta variable tiene cuatro grupos no representaremos los intervalos de confianza.</p>
<div class="sourceCode" id="cb924"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">celltype</span>, data <span class="op">=</span> <span class="va">veteran</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ celltype, data = veteran)
## 
##                     n events median 0.95LCL 0.95UCL
## celltype=squamous  35     31    118      82     314
## celltype=smallcell 48     45     51      25      63
## celltype=adeno     27     26     51      35      92
## celltype=large     27     26    156     105     231</code></pre>
<div class="sourceCode" id="cb926"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia y mediana de supervivencia</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">veteran</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>, 
           pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv014-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>En este caso podemos ver que si existen diferencias entre las curvas de supervivencia (p-valor inferior a 0.05). AL menos existen dos funciones de supervivencia que pueden ser consideradas distintas. El problema es que el test no nos permite conocer que grupos son los que son diferentes.</p>
</div>
<div id="cáncer-de-pulmón" class="section level3" number="16.2.3">
<h3>
<span class="header-section-number">16.2.3</span> Cáncer de pulmón<a class="anchor" aria-label="anchor" href="#c%C3%A1ncer-de-pulm%C3%B3n"><i class="fas fa-link"></i></a>
</h3>
<p>Para este conjunto de datos obtenemos el resumen de la mediana de supervivencia para todo el conjunto de datos, y representamos la función de supervivencia y la mediana de supervivencia. En este caso la variable status no está codificado con 0-1 y debemos construir una nueva variable. Además añadimos las etiquetas de los factores presentes en el banco de datos.</p>
<div class="sourceCode" id="cb927"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Creamos la nueva varaible</span>
<span class="va">lung</span> <span class="op">&lt;-</span> <span class="va">lung</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>censurado <span class="op">=</span> <span class="va">status</span> <span class="op">-</span> <span class="fl">1</span>,
         sex <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span>, <span class="st">"Male"</span> <span class="op">=</span> <span class="st">"1"</span>, <span class="st">"Female"</span> <span class="op">=</span> <span class="st">"2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Estimamos ahora la función de supervivencia</p>
<div class="sourceCode" id="cb928"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">censurado</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, censurado) ~ 1, data = lung)
## 
##        n events median 0.95LCL 0.95UCL
## [1,] 228    165    310     285     363</code></pre>
<div class="sourceCode" id="cb930"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia e IC</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">lung</span>, 
           palette <span class="op">=</span> <span class="st">"blue"</span>, 
           conf.int <span class="op">=</span> <span class="cn">FALSE</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv016-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>¿Cómo interpretamos esta función de supervivencia?</p>
<p>Utilizamos ahora la variable <code>sex</code></p>
<div class="sourceCode" id="cb931"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Estimación</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">censurado</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, censurado) ~ sex, data = lung)
## 
##              n events median 0.95LCL 0.95UCL
## sex=Male   138    112    270     212     310
## sex=Female  90     53    426     348     550</code></pre>
<div class="sourceCode" id="cb933"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfica de la función de supervivencia e IC</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span> <span class="va">lung</span>, 
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>, 
           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>, 
           pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv017-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>¿Cómo interpretamos estos resultados? ¿Podemos considerar las curvas de supervivencia iguales o distintas?</p>
</div>
</div>
<div id="modelos-de-supervivencia" class="section level2" number="16.3">
<h2>
<span class="header-section-number">16.3</span> Modelos de supervivencia<a class="anchor" aria-label="anchor" href="#modelos-de-supervivencia"><i class="fas fa-link"></i></a>
</h2>
<p>En las situaciones experimentales en las que deseamos estudiar la supervivencia de un conjunto de sujetos en función de un conjunto <span class="math inline">\(X = (X_1,...,X_p)\)</span> de variables predictoras, es decir, variables que pueden afectar o caracterizar su supervivencia, es necesario establecer modelos estadísticos capaces de analizar dichas relaciones. La construcción de este tipo de modelos que depende del tiempo y de las predictoras se hace a través el análisis de las función hazard asociada <span class="math inline">\(h(t;X)\)</span>. El modelo más habitual en esta situación es el <strong>modelo hazard proporcional</strong> que separa en dos componentes la función hazard, una correspondiente al tiempo de supervivencia y otra a las variables predictoras, de la forma siguiente:
<span class="math display">\[h(t;X) = h(t)exp(X\beta)\]</span></p>
<p>donde <span class="math inline">\(h(t)\)</span> es la función hazard base y describe el riesgo para individuos cuando las predictoras toman valor 0, es decir <span class="math inline">\(x = O\)</span>; <span class="math inline">\(exp(X\beta)\)</span> es el riesgo relativo, y representa la reducción o incremento del riesgo asociada con el conjunto de características <span class="math inline">\(X\)</span>, que es similar para todas las duraciones <span class="math inline">\(t\)</span>. La exponencial está justificada por la necesidad de positivista y la hipótesis de un efecto multiplicativo de las covariables en los hazards. Este modelo implica que el cociente de hazards (<span class="math inline">\(hr\)</span>) de dos individuos depende de la diferencia entre sus predictores lineales en cualquier instante t, es decir, si <span class="math inline">\(x\)</span> y <span class="math inline">\(x^*\)</span> denotan a los valores de las predictoras para ambos sujetos tendríamos que:
<span class="math display">\[hr(x,x^*) = \frac{h(t)exp(x\beta)}{h(t)exp(x^*\beta)} = exp((x-x^*)\beta)\]</span>
Si solo tenemos una variable predictora de tipo factor con posibles valores 0 o 1, tendríamos la expresión para la función hazard asociada a cada respuesta:
<span class="math display">\[h(t;X = 0) = h(t); \text{ y } h(t;X = 1) = h(t)exp(\beta)\]</span>
de forma que el el hazard rate viene dado por <span class="math inline">\(hr(x = 1,x = 0) = exp(\beta)\)</span>. Esto implica que dicho coeficiente representa el incremento en el logaritmo del hazard rate, esto es:</p>
<p><span class="math display">\[log(hr(x = 1, x = 0)) = \beta\]</span>
En este caso cuando <span class="math inline">\(exp(\beta)&gt;0\)</span> tenemos que <span class="math inline">\(hr &gt; 1\)</span> indicando que hay un incremento el riesgo, y por tanto una reducción de la supervivencia. Cuando <span class="math inline">\(exp(\beta) &lt; 0\)</span> tenemos que <span class="math inline">\(hr &lt; 1\)</span> indicando que hay un descenso en el riesgo, y por tanto un aumento de la supervivencia.</p>
<p>Si la variable predictora es de tipo continuo de forma que <span class="math inline">\(\delta = x -x^*\)</span> es la diferencia entre los valores para dos sujetos, el logaritmo del hazard rate nos da:</p>
<p><span class="math display">\[log(hr(x,x^*)) = \delta\beta\]</span>
Si el incremento entre los dos valores es de un unidad (<span class="math inline">\(\delta = 1\)</span>), <span class="math inline">\(\beta\)</span> representa el incremento en el hazard rate por cada unidad que aumentamos el valor de la variable predictora. La interpretación del <span class="math inline">\(hr\)</span> es igual que el caso de un factor. Si <span class="math inline">\(hr &gt; 1\)</span> aumenta el riesgo y si es menor que uno disminuye el riesgo</p>
<p>Para facilitar la interpretación de los coeficientes se plantea la modelización del logaritmo del hazard mediante la expresión:</p>
<p><span class="math display">\[log(h(t;X)) = log(h(t)) + X\beta\]</span>
donde queda claro que el efecto de las predictoras afecta de forma lineal a la función hazard. Esta formulación es muy similar a la de los modelos lineales generalizados con función de enlace <span class="math inline">\(log()\)</span> y con un offset dado por <span class="math inline">\(log(h(t))\)</span>. EL problema es que en muchas ocasiones desconocemos la forma de la función <span class="math inline">\(h\)</span>, y por tanto, no podemos determinar de forma exacta el offset asociado. Los modelos de regresión de Cox o de supervivencia no paramétrica no asumen una forma específica para <span class="math inline">\(h\)</span> al estilo de los modelos de suavizado.</p>
<p>La estimación de este tipo de modelos se hace mediante la función:</p>
<div class="sourceCode" id="cb934"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">modelo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>,<span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">predictoras</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></code></pre></div>
<p>Para el resumen del modelo utilizaremos las funciones <code>summary(modelo)</code> que nos proporciona el proceso de estimación del modelo, y <code>ggforest(modelo)</code> que nos proporciona un resumen gráfico del modelo ajustado (estimaciones del <span class="math inline">\(hr\)</span>, intervalos de confianza y p-valores asociados para cada variable predictora presente en el modelo).</p>
<p>Para representar le modelo ajustado utilizaremos la función <code>ggcoxadjustedcurves(modelo, dataset, variable)</code> que permite representar la función de supervivencia asociada con la variable de interés o con una factor creado a partir de una de las variables presente en el modelo ajustado.</p>
<div id="hipótesis-del-modelo" class="section level3" number="16.3.1">
<h3>
<span class="header-section-number">16.3.1</span> Hipótesis del modelo<a class="anchor" aria-label="anchor" href="#hip%C3%B3tesis-del-modelo"><i class="fas fa-link"></i></a>
</h3>
<p>Las hipótesis de este modelo son:</p>
<ul>
<li>Proporcionalidad en la función hazard</li>
<li>El efecto de las predictoras es lineal sobre el logaritmo de la función hazard (asumiendo que no hay interacciones entre las predictoras)</li>
</ul>
<p>Estas hipótesis deben verificarse una vez estimado el modelo de supervivencia a través de la obtención de los residuos del modelo. En este caso trabajamos con los residuos de Schoenfeld. El incumplimiento de alguna de estas hipótesis implicará el planteamiento de un nuevo modelo.</p>
<p>Para la verificación de las hipótesis utilizamos las funciones:</p>
<ul>
<li>
<code>cox.zph(modelo)</code> que permite verificar la hipótesis de hazards proporcionales mediante los residuos de Schoenfeld. La verificación gráfica se puede realizar mediante la función <code>ggcoxzph(modelo)</code> que representa para cada predictora el gráfico de residuos vs tiempo.</li>
<li>
<code>ggcoxdiagnostics(modelo)</code> que permite representar los residuos en función del tiempo, en función del predictor lineal o del tiempo para verificar la hipótesis de linealidad.</li>
</ul>
</div>
<div id="análisis-cáncer-de-pulmón" class="section level3" number="16.3.2">
<h3>
<span class="header-section-number">16.3.2</span> Análisis Cáncer de pulmón<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-c%C3%A1ncer-de-pulm%C3%B3n"><i class="fas fa-link"></i></a>
</h3>
<p>Procedemos en este punto a mostrar el análisis completo de los datos correspondientes al ejemplo de cáncer de pulmón. Realizaremos el análisis completo mostrando el uso de todas las funciones tanto para la estimación y diagnóstico del modelo de regresión de Cox aplicado en este caso.</p>
<p>En primer lugar recodificamos la variable de status para que coincida con una variable 0-1.</p>
<div class="sourceCode" id="cb935"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Creamos la nueva varaible</span>
<span class="va">lung</span> <span class="op">&lt;-</span> <span class="va">lung</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>censurado <span class="op">=</span> <span class="va">status</span> <span class="op">-</span> <span class="fl">1</span>,
         sex <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span>,<span class="st">"Male"</span> <span class="op">=</span> <span class="st">"1"</span>, <span class="st">"Female"</span> <span class="op">=</span> <span class="st">"2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div id="estimación-del-modelo" class="section level4" number="16.3.2.1">
<h4>
<span class="header-section-number">16.3.2.1</span> Estimación del modelo<a class="anchor" aria-label="anchor" href="#estimaci%C3%B3n-del-modelo"><i class="fas fa-link"></i></a>
</h4>
<p>Por el momento plateamos un modelo en el que solo tenemos una variable predictora. Consideremos la variable <code>sex</code> dado que ya pudimos ver en el análisis preliminar que se apreciaban diferencias en la supervivencia por este factos.</p>
<div class="sourceCode" id="cb936"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="co"># Resumen del modelo ajustado</span>
<span class="va">fit</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex, data = lung)
## 
##              coef exp(coef) se(coef)      z       p
## sexFemale -0.5310    0.5880   0.1672 -3.176 0.00149
## 
## Likelihood ratio test=10.63  on 1 df, p=0.001111
## n= 228, number of events= 165</code></pre>
<p>El hazard rate asociado con le factor (columna exp(coef)) es menor que 1 lo que indica que las mujeres tienen más supervivencia que los hombres. Además el test de bondad de ajuste del modelo (“likelihood ratio test”) resulta significativo indicando que el sexo contribuye claramente a explicar la supervivencia de los sujetos del estudio. A continuación se muestran gráficamente los intervalos de confianza y pvalores asociados con le modelo estimado.</p>
<div class="sourceCode" id="cb938"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de la relevancia de los coeficientes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggforest.html">ggforest</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv021-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Como podemos ver se usa la categoría “Male” como referencia para la estimación de efectos del modelo. El hazard ratio asociado con las mujeres se sitúa en 0.58, lo que indica una fuerte relación entre el sexo de los pacientes y la disminución del riesgo de muerte.Por tanto, ser mujer reduce el riesgo de muerte por un factor de 0,58 o equivalentemente un 42% (100*(1-0.58)). Concluimos que ser mujer se asocia con buen pronóstico. El intervalo de confianza para el hazard ratio en las mujeres se sitúa entre 0.42 y 0.82 indicando una reducción del riesgo de entre el 18% y el 58%.</p>
<div class="sourceCode" id="cb939"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de supervivencia</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fit</span>, data <span class="op">=</span><span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"sex"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv022-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb940"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico con intervalos de confianza</span>
<span class="va">sex.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">lung</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">fit</span>,newdata <span class="op">=</span> <span class="va">sex.df</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span>,
           palette <span class="op">=</span> <span class="st">"lancet"</span>,
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>,
           legend.labs<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv022-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>A partir de la solución gráfica es posible obtener los datos de supervivencia para ambos grupos, así como la diferencia de supervivencia. El código necesario es</p>
<div class="sourceCode" id="cb941"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Guardamos la información del gráfico</span>
<span class="va">datosgraf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fit</span>, data<span class="op">=</span><span class="va">lung</span>, variable <span class="op">=</span> <span class="st">"sex"</span>, palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span><span class="op">$</span><span class="va">dat</span>
<span class="va">datossurv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/spread.html">spread</a></span><span class="op">(</span><span class="va">datosgraf</span>, key <span class="op">=</span> <span class="va">variable</span>, value <span class="op">=</span><span class="va">surv</span><span class="op">)</span>
<span class="va">datossurv</span> <span class="op">&lt;-</span> <span class="va">datossurv</span> <span class="op"><a href="https://stringr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>dif <span class="op">=</span> <span class="va">Female</span> <span class="op">-</span> <span class="va">Male</span><span class="op">)</span>
<span class="co"># Gráfico</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">datossurv</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time</span>, y <span class="op">=</span> <span class="va">dif</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv023-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se observa que entre los 375 y 500 días la probabilidad de supervivencia es aproximadamente 0.2 superior en las mujeres que en los hombres.</p>
</div>
<div id="diagnóstico-del-modelo-1" class="section level4" number="16.3.2.2">
<h4>
<span class="header-section-number">16.3.2.2</span> Diagnóstico del modelo<a class="anchor" aria-label="anchor" href="#diagn%C3%B3stico-del-modelo-1"><i class="fas fa-link"></i></a>
</h4>
<p>El modelo de Cox hace varias suposiciones. Por lo tanto, es importante evaluar si un modelo de regresión de Cox ajustado describe adecuadamente los datos. En concreto debemos comprobar:</p>
<ul>
<li>Suposición de riesgos proporcionales.</li>
<li>Existen observaciones influyentes (o valores atípicos).</li>
<li>Detectar la no linealidad de los efectos de las variables predictoras en la función hazard.</li>
</ul>
<p>Para verificar estas suposiciones del modelo, se utilizan diferentes tipos de residuos. Los residuos a considerar son:</p>
<ul>
<li>Residuos de Schoenfeld vs time para verificar la suposición de riesgos proporcionales</li>
<li>Residuos de Schoenfeld vs time para cada predictora para evaluar la no linealidad</li>
<li>Desviación residual (transformación simétrica de los residuos de Martingale) para examinar observaciones influyentes</li>
</ul>
<div id="riesgos-porporcionales" class="section level5" number="16.3.2.2.1">
<h5>
<span class="header-section-number">16.3.2.2.1</span> Riesgos porporcionales<a class="anchor" aria-label="anchor" href="#riesgos-porporcionales"><i class="fas fa-link"></i></a>
</h5>
<p>Utilizamos la función <code><a href="https://rdrr.io/pkg/survival/man/cox.zph.html">cox.zph()</a></code> para evaluar mediante tests estadísticos la hipótesis de riesgos proporcionales, y la función <code><a href="https://rdrr.io/pkg/survminer/man/ggcoxzph.html">ggcoxzph()</a></code> para el análisis gráfico.</p>
<div class="sourceCode" id="cb942"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de riesgos proporcionales</span>
<span class="va">ftest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/cox.zph.html">cox.zph</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span>
<span class="va">ftest</span></code></pre></div>
<pre><code>##        chisq df     p
## sex     2.86  1 0.091
## GLOBAL  2.86  1 0.091</code></pre>
<p>Dado que el pvalor asociado del test resulta no significativo no podemos descartar la hipótesis de riesgos proporcionales asociados con la variable sexo.</p>
<div class="sourceCode" id="cb944"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de riesgos proporcionales</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxzph.html">ggcoxzph</a></span><span class="op">(</span><span class="va">ftest</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv025-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>No se observa ningún tipo de tendencia en la curva ajustada (línea continua) entre tiempo y residuos, lo que da indicios de la verificación de la hipótesis de riesgos proporcionales.</p>
</div>
<div id="observaciones-influyentes" class="section level5" number="16.3.2.2.2">
<h5>
<span class="header-section-number">16.3.2.2.2</span> Observaciones influyentes<a class="anchor" aria-label="anchor" href="#observaciones-influyentes"><i class="fas fa-link"></i></a>
</h5>
<p>La detección de observaciones influyentes se realiza mediante métodos gráficos</p>
<div class="sourceCode" id="cb945"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Observaciones influyentes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxdiagnostics.html">ggcoxdiagnostics</a></span><span class="op">(</span><span class="va">fit</span>, type <span class="op">=</span> <span class="st">"deviance"</span>,
                 linear.predictions <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv026-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>El patrón de residuos es bastante simétrico respecto de cero. Además no hay residuos con valores claramente fuera del rango (-3, 3), indicando que no hay ninguna observación que pueda identificarse como anómala. En caso de existir alguna deberíamos eliminarla y ajustar el nuevo modelo.</p>
</div>
<div id="no-linealidad" class="section level5" number="16.3.2.2.3">
<h5>
<span class="header-section-number">16.3.2.2.3</span> No linealidad<a class="anchor" aria-label="anchor" href="#no-linealidad"><i class="fas fa-link"></i></a>
</h5>
<p>El test de no linealidad sólo se puede interpretar para variables de tipo numérico donde se pueden plantear diferentes tendencia en al respuesta en función de diferentes transformaciones numéricas de la predictora. En este caso realizamos el gráfico de análisis pero no lo interpretamos.</p>
<div class="sourceCode" id="cb946"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Observaciones influyentes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxdiagnostics.html">ggcoxdiagnostics</a></span><span class="op">(</span><span class="va">fit</span>, type <span class="op">=</span> <span class="st">"schoenfeld"</span>,
                 ox.scale <span class="op">=</span> <span class="st">"time"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv027-1.png" width="95%" style="display: block; margin: auto;"></div>
</div>
</div>
</div>
<div id="múltiples-predictoras" class="section level3" number="16.3.3">
<h3>
<span class="header-section-number">16.3.3</span> Múltiples predictoras<a class="anchor" aria-label="anchor" href="#m%C3%BAltiples-predictoras"><i class="fas fa-link"></i></a>
</h3>
<p>Pasamos ahora a analizar el modelo con múltiples predictoras. En principio en este tipo de modelos no se consideran interacciones entre las predictoras para determinar el efecto individual que cada una de ellas puede tener en la supervivencia de los sujetos considerados. En nuestro caso consideramos las variables: <code>sex</code> (factor), <code>age</code> (numérica), y <code>wt.loss</code> (numérica). El modelo ajustado viene dado por:</p>
<div class="sourceCode" id="cb947"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fitcom</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">wt.loss</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="co"># Resumen del modelo ajustado</span>
<span class="va">fitcom</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex + age + wt.loss, data = lung)
## 
##                 coef  exp(coef)   se(coef)      z      p
## sexFemale -0.5210319  0.5939074  0.1743541 -2.988 0.0028
## age        0.0200882  1.0202913  0.0096644  2.079 0.0377
## wt.loss    0.0007596  1.0007599  0.0061934  0.123 0.9024
## 
## Likelihood ratio test=14.67  on 3 df, p=0.002122
## n= 214, number of events= 152 
##    (14 observations deleted due to missingness)</code></pre>
<p>A la hora de interpretar los resultados de este modelo hay que tener en cuenta que las estimaciones proporcionadas corresponden al efecto de cada variable cuando el resto se mantienen constantes. Eso quiere decir que el riesgo de 0.59 para la variable sexo se obtiene fijando el resto de variables en su valor medio. En este caso tendríamos que la edad se fijaría en 62.47 y wt.loss en 9.8. Por tanto, el riesgo de muerte se reduce en las mujeres en un 43% (0.57) para una edad de 62 años y una pérdida de peso de 9.8 kg. En cuanto a los pvalores podemos ver que tanto la variable sex como age contribuyen significativamente la supervivencia de los sujetos, pero no así la variable wt.loss Por cada aumento de una unidad de edad el riesgo de morir aumenta en un 2% (1.02). El test global indica que el modelo construido es útil para explicar la supervivencia de los sujetos. Veamos el análisis gráfico de los coeficientes del modelo:</p>
<div class="sourceCode" id="cb949"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de la relevancia de los coeficientes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggforest.html">ggforest</a></span><span class="op">(</span><span class="va">fitcom</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv029-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Representamos ahora las curvas de supervivencia ajustadas. Recordemos que sólo se representan la curvas de supervivencia comparando por variables de tipo factor. En este caso tenemos dos variables de tipo numérico, de forma que si queremos representar la supervivencia asociada con cada una de ellas las deberemos convertir en factores de una forma adecuada. Esta forma de proceder es muy habitual den los modelos de supervivencia donde siempre son preferibles variables de tipo factor a las numéricas. En este caso los gráficos son condicionales a los valores medios de las variables numéricas, tal y como hemos explicado en la interpretación de los parámetros del modelo.</p>
<div class="sourceCode" id="cb950"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de supervivencia para sex</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fitcom</span>, data <span class="op">=</span> <span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"sex"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv030-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb951"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico con intervalos de confianza tomando los valores medios de las numéricas</span>
<span class="va">sex.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">lung</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span>,
                                age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">62.5</span>,<span class="fl">2</span><span class="op">)</span>,
                                wt.loss <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">9.5</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">fit</span>, newdata <span class="op">=</span> <span class="va">sex.df</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span>,
           palette <span class="op">=</span> <span class="st">"lancet"</span>,
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>,
           legend.labs<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv030-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Para representar las curvas de supervivencia para la variable numérica procedemos construyendo una nueva variable categórica artificial a partir de los cuantiles de la variable numérica, y sin necesitad de ajustar el modelo.</p>
<div class="sourceCode" id="cb952"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Edad</span>
<span class="co"># Variable  artificial</span>
<span class="va">lung</span><span class="op">$</span><span class="va">agenew</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">age</span>, <span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">quantile</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="va">lung</span><span class="op">$</span><span class="va">wtnew</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">wt.loss</span>, <span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">quantile</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">wt.loss</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Ajuste del modelo</span>
<span class="va">fitcom</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">agenew</span> <span class="op">+</span> <span class="va">wtnew</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="co"># Gráfico de supervivencia para edad</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fitcom</span>, data <span class="op">=</span> <span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"agenew"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv031-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb953"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Pérdida de peso</span>
<span class="co"># Gráfico de supervivencia para sex</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fitcom</span>, data <span class="op">=</span> <span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"wtnew"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv031-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Podemos ver que los sujetos de mayor edad tienen una supervivencia menor, así como los que han perdido más peso en los último seis meses. Sin embargo, esta forma de proceder no es óptima ya que hay muchas curvas de supervivencia muy similares. Para evitar esto podemos buscar el punto de la variable numérica que separa a los sujeto en dos grupos que podemos considerar que tienen supervivencias distintas. Para realizar esto utilizamos la función <code>surv_cutpoint</code>.</p>
<div class="sourceCode" id="cb954"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Puntos de corte</span>
<span class="va">corte</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survminer/man/surv_cutpoint.html">surv_cutpoint</a></span><span class="op">(</span><span class="va">lung</span>, time <span class="op">=</span> <span class="st">"time"</span>, 
              event <span class="op">=</span> <span class="st">"status"</span>, 
              variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"wt.loss"</span><span class="op">)</span><span class="op">)</span>
<span class="va">corte</span></code></pre></div>
<pre><code>##         cutpoint statistic
## age           70  2.013619
## wt.loss        9  1.756750</code></pre>
<p>El valor para edad se sitúa en los 70 años mientras que para la pérdida de peso es de 9kg. Veamos los gráfico con las variables artificiales</p>
<div class="sourceCode" id="cb956"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Variable  artificial edad</span>
<span class="va">lung</span><span class="op">$</span><span class="va">agenew</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;=</span> <span class="va">corte</span><span class="op">$</span><span class="va">age</span><span class="op">$</span><span class="va">estimate</span>,<span class="st">"+70"</span>,<span class="st">"-70"</span><span class="op">)</span>
<span class="va">lung</span><span class="op">$</span><span class="va">wtnew</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">lung</span><span class="op">$</span><span class="va">wt.loss</span> <span class="op">&gt;=</span> <span class="va">corte</span><span class="op">$</span><span class="va">wt.loss</span><span class="op">$</span><span class="va">estimate</span>,<span class="st">"+9"</span>,<span class="st">"-9"</span><span class="op">)</span>
<span class="co"># Ajuste del modelo</span>
<span class="va">fitcom</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">agenew</span> <span class="op">+</span> <span class="va">wtnew</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="co"># Gráfico de supervivencia para edad</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fitcom</span>, data <span class="op">=</span> <span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"agenew"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv033-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb957"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de supervivencia para pérdida de peso</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggadjustedcurves.html">ggadjustedcurves</a></span><span class="op">(</span><span class="va">fitcom</span>, data <span class="op">=</span> <span class="va">lung</span>, 
                 variable <span class="op">=</span> <span class="st">"wtnew"</span>, 
                 palette <span class="op">=</span> <span class="st">"lancet"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv033-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Para variables numéricas con pocos valores posibles resulta más útil introducir dicha variable en el modelo como un nivel de estratificación son necesidad de estimar el coeficiente asociado. En este caso las variables <code>ph.ecog</code> y <code>ph.karno</code> se pueden tomar como estratos, ya que se tratan de valoraciones sobre los sujetos que no tienen porque tener relación directa con la supervivencia. En este caso el modelo a ajustar viene dado por:</p>
<div class="sourceCode" id="cb958"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">wt.loss</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/strata.html">strata</a></span><span class="op">(</span><span class="va">ph.ecog</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/strata.html">strata</a></span><span class="op">(</span><span class="va">ph.karno</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex + age + wt.loss + strata(ph.ecog) + 
##     strata(ph.karno), data = lung)
## 
##                coef exp(coef)  se(coef)      z        p
## sexFemale -0.632793  0.531106  0.188563 -3.356 0.000791
## age        0.020913  1.021133  0.010562  1.980 0.047702
## wt.loss   -0.009286  0.990757  0.007059 -1.315 0.188359
## 
## Likelihood ratio test=17.16  on 3 df, p=0.0006537
## n= 213, number of events= 151 
##    (15 observations deleted due to missingness)</code></pre>
<p>¿Cómo interpretaríamos este modelo?</p>
<p>También podríamos ajustar el modelo de supervivencia con los nuevos factores creados:</p>
<div class="sourceCode" id="cb960"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fitcomp2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">agenew</span> <span class="op">+</span> <span class="va">wtnew</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fitcomp2</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex + agenew + wtnew, data = lung)
## 
##              coef exp(coef) se(coef)      z       p
## sexFemale -0.5160    0.5969   0.1744 -2.960 0.00308
## agenew+70  0.3754    1.4555   0.1800  2.086 0.03702
## wtnew+9    0.2370    1.2675   0.1628  1.456 0.14549
## 
## Likelihood ratio test=16.34  on 3 df, p=0.0009675
## n= 214, number of events= 152 
##    (14 observations deleted due to missingness)</code></pre>
<p>Se puede ver como el efecto de la edad es mucho más claro en este modelo. ¿Cuáles serían los riesgos asociados con cada una de las variables?</p>
<p>Procedemos con el gráfico de curvas de supervivencia estimadas:</p>
<div class="sourceCode" id="cb962"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico conjunto de todos los fatores</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot_facet.html">ggsurvplot_facet</a></span><span class="op">(</span><span class="va">fitcomp2</span>, <span class="va">lung</span>, facet.by <span class="op">=</span> <span class="st">"wtnew"</span>,
                palette <span class="op">=</span> <span class="st">"lancet"</span>, pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv036-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Con este tipo de gráficos resulta posible estudiar como se modifica la supervivencia cuando tenemos variables que no están en el modelo. Partimos del modelo más simple donde sólo consideramos la variable sexo, y estudiamos las funciones de supervivencia si incluimos las variables edad y pérdida de peso en forma de factores:</p>
<div class="sourceCode" id="cb963"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Eliminamos valores pérdidos</span>
<span class="va">lung</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="va">lung</span><span class="op">)</span>
<span class="co"># Gráfico conjunto de todos los fatores</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot_facet.html">ggsurvplot_facet</a></span><span class="op">(</span><span class="va">fit</span>, <span class="va">lung</span>, facet.by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"agenew"</span>,<span class="st">"wtnew"</span><span class="op">)</span>,
                palette <span class="op">=</span> <span class="st">"lancet"</span>, pval <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv037-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>Este gráfico nos permite comparar el efecto de las combinaciones de los nuevos factores teniendo en cuenta el modelo por sexo. Es casi como un estudio de la interacción o de la inclusión de un factor en el modelo.</p>
</div>
<div id="diagnóstico-del-modelo-2" class="section level3" number="16.3.4">
<h3>
<span class="header-section-number">16.3.4</span> Diagnóstico del modelo<a class="anchor" aria-label="anchor" href="#diagn%C3%B3stico-del-modelo-2"><i class="fas fa-link"></i></a>
</h3>
<p>Comenzamos con el diagnóstico del modelo. En principio trabajamos con le modelo tomando las variables edad y peso perdido como numéricas.</p>
<div class="sourceCode" id="cb964"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fitcomp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">wt.loss</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span></code></pre></div>
<div id="riesgos-porporcionales-1" class="section level4" number="16.3.4.1">
<h4>
<span class="header-section-number">16.3.4.1</span> Riesgos porporcionales<a class="anchor" aria-label="anchor" href="#riesgos-porporcionales-1"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb965"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de riesgos proporcionales</span>
<span class="va">ftest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/cox.zph.html">cox.zph</a></span><span class="op">(</span><span class="va">fitcomp</span><span class="op">)</span>
<span class="va">ftest</span></code></pre></div>
<pre><code>##         chisq df    p
## sex     1.003  1 0.32
## age     0.668  1 0.41
## wt.loss 0.351  1 0.55
## GLOBAL  1.868  3 0.60</code></pre>
<p>Todos los pvalores (tanto los individuales de cada variable como el global para el modelo) son superiores a 0.05 indicando que se verifica la hipótesis de riesgos proporcionales. Veamos el análisis gráfico:</p>
<div class="sourceCode" id="cb967"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Gráfico de riesgos proporcionales</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxzph.html">ggcoxzph</a></span><span class="op">(</span><span class="va">ftest</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv040-1.png" width="95%" style="display: block; margin: auto;"></div>
</div>
<div id="observaciones-influyentes-1" class="section level4" number="16.3.4.2">
<h4>
<span class="header-section-number">16.3.4.2</span> Observaciones influyentes<a class="anchor" aria-label="anchor" href="#observaciones-influyentes-1"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb968"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Observaciones influyentes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxdiagnostics.html">ggcoxdiagnostics</a></span><span class="op">(</span><span class="va">fitcomp</span>, type <span class="op">=</span> <span class="st">"deviance"</span>,
                 linear.predictions <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv041-1.png" width="95%" style="display: block; margin: auto;"></div>
<p>No se aprecian observaciones influyentes.</p>
<p>Podemos ver que se cumplen todas la hipótesis del modelo, pero ¿podemos considerar que los modelos ajustados son iguales en su capacidad explicativa? Para poder verificar esto realizamos el test de comparación de modelos basado en el test Ji-cuadrado. ¿Podríamos prescindir de alguna variable? Comparamos los siguientes modelos para obtener el modelo con menor número de predictoras pero con la misma capacidad explicativa. Construimos modelos anidados para favorecer la comparación:</p>
<div class="sourceCode" id="cb969"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelos</span>
<span class="va">fit1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fit2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">agenew</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fit3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">agenew</span> <span class="op">+</span> <span class="va">wt.loss</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="co"># Comparación</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit3</span><span class="op">)</span></code></pre></div>
<p>Puesto que no hay ningún pvalor significativo podríamos concluir que el mejor modelo es aquel que sólo contiene la variable sexo, pero podríamos llegar a modelos erróneos. En el caso de tener factores que no parecen aportar capacidad explicativa pero que si tienen sentido desde el punto de vista experimental, es necesario introducirlos en el modelo de alguna forma. En este caso utilizamos la denominada estratificación. Ajustamos los nuevos modelos considerando la edad como variable estratificada. Al considerarla de esta forma no podremos evaluar su riesgo de forma directa en la supervivencia, pero si en la supervivencia global.</p>
<p>En este caso podemos ver que el modelo 2 es claramente distinto del modelo 1, pero no es distinto del modelo 3. Por tanto, nuestro modelo para estos datos sería el 2.</p>
<div class="sourceCode" id="cb970"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajuste del modelo</span>
<span class="va">fitcomp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/strata.html">strata</a></span><span class="op">(</span><span class="va">agenew</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span><span class="op">)</span>
<span class="va">fitcomp</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex + strata(agenew), data = lung)
## 
##              coef exp(coef) se(coef)      z      p
## sexFemale -0.4645    0.6285   0.1981 -2.344 0.0191
## 
## Likelihood ratio test=5.75  on 1 df, p=0.01645
## n= 167, number of events= 120</code></pre>
<p>Veamos el diagnóstico</p>
<div class="sourceCode" id="cb972"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tests de riesgos proporcionales</span>
<span class="va">ftest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/cox.zph.html">cox.zph</a></span><span class="op">(</span><span class="va">fitcomp</span><span class="op">)</span>
<span class="va">ftest</span></code></pre></div>
<pre><code>##        chisq df    p
## sex    0.944  1 0.33
## GLOBAL 0.944  1 0.33</code></pre>
<div class="sourceCode" id="cb974"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Observaciones influyentes</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxdiagnostics.html">ggcoxdiagnostics</a></span><span class="op">(</span><span class="va">fitcomp</span>, type <span class="op">=</span> <span class="st">"deviance"</span>,
                 linear.predictions <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv048-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb975"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># No linealidad</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggcoxdiagnostics.html">ggcoxdiagnostics</a></span><span class="op">(</span><span class="va">fitcomp</span>, type <span class="op">=</span> <span class="st">"schoenfeld"</span>,
                 ox.scale <span class="op">=</span> <span class="st">"time"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv048-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se cumplen todas las hipótesis. Representamos las funciones de supervivencia para este modelo</p>
<div class="sourceCode" id="cb976"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Supervivencia para menores de 70 años</span>
<span class="va">sex.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">lung</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span>,
                                agenew <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"-70"</span>,<span class="st">"-70"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">fitcomp</span>,newdata <span class="op">=</span> <span class="va">sex.df</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span>,
           palette <span class="op">=</span> <span class="st">"lancet"</span>,
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>,
           legend.labs<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv049-1.png" width="95%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb977"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Supervivencia para mayores de 70 años</span>
<span class="va">sex.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">lung</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span>,
                                agenew <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"+70"</span>,<span class="st">"+70"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">fitcomp</span>,newdata <span class="op">=</span> <span class="va">sex.df</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lung</span>,
           palette <span class="op">=</span> <span class="st">"lancet"</span>,
           conf.int <span class="op">=</span> <span class="cn">TRUE</span>, 
           conf.int.style <span class="op">=</span> <span class="st">"step"</span>,
           legend.labs<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="15-GLMTSuperv_files/figure-html/superv049-2.png" width="95%" style="display: block; margin: auto;"></div>
<p>Se puede ver como si se aprecian diferencias por sexo para los menores de 70 años, pero no ocurre lo mismo para los mayores de 70 años (el intervalo de confianza de los hombres contiene a la estimación de supervivencia para las mujeres).</p>
<p>Existen más modificaciones de este tipo de modelos que por límite de tiempo no consideramos aquí como son: la posible inclusión de interacciones, modelos doble censurados, incorporación de efectos de grupos o sujetos (camadas, hospitales,…). parte de estas situaciones aparecen en los ejemplos planteados al inicio de este tema y se trataran con lago de detalle en las sesiones prácticas.</p>
</div>
</div>
</div>
<div id="ejercicios-6" class="section level2" number="16.4">
<h2>
<span class="header-section-number">16.4</span> Ejercicios<a class="anchor" aria-label="anchor" href="#ejercicios-6"><i class="fas fa-link"></i></a>
</h2>
<p>Colección de ejercicios sobre modelos de supervivencia.</p>
<p><em>No olvides cargar las librerías para realizar los ejercicios.</em></p>
<p><strong>Ejercicio 1.</strong> Los datos siguientes corresponden a un pequeño experimento en el que 7 de un total de 16 ratones fueron aleatoriamente seleccionados para recibir un nuevo tratamiento médico. Los 9 ratones restantes fueron asignados a un grupo control en el que no se administró ningún tipo de tratamiento. El objetivo del tratamiento era prolongar el tiempo de supervivencia después de una operación quinírgica. El banco de datos contiene los tiempos de supervivencia (en días) tras la operación para los 16 ratones. El objetivo principal es saber si el tratamiento prolongaba la vida de los ratones tras la operación</p>
<div class="sourceCode" id="cb978"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">grupo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Tratado"</span>, <span class="fl">7</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span>
<span class="va">tiempo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">94</span>, <span class="fl">38</span>, <span class="fl">23</span>, <span class="fl">19</span>, <span class="fl">99</span>, <span class="fl">16</span>,<span class="fl">141</span>, <span class="fl">52</span>, <span class="fl">104</span>, <span class="fl">146</span>, <span class="fl">10</span>, <span class="fl">51</span>, <span class="fl">30</span>, <span class="fl">40</span>, <span class="fl">27</span>, <span class="fl">46</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 2.</strong> Los datos de la Tabla siguiente son: ‘tiemsup’, que es el tiempo hasta la muerte (en semanas) desde la diagnosis de leucemia, y ‘logcel’, igual al log 10 del número inicial de células blancas en la sangre. Se dispone de datos de diecisiete pacientes que sufrían de leucemia. ¿Cuáles son tus conclusiones sobre la utilidad de saber el número de células blancas en la sangre para predecir el tiempo de supervivencia? ¿Cuál es la probabilidad de sobrevivir de un paciente con 5000 células blancas en la sangre?</p>
<div class="sourceCode" id="cb979"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tiemsup</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">65</span>, <span class="fl">156</span>, <span class="fl">100</span>, <span class="fl">134</span>, <span class="fl">16</span>, <span class="fl">108</span>, <span class="fl">121</span>, <span class="fl">5</span>, <span class="fl">65</span>, <span class="fl">4</span>, <span class="fl">39</span>, <span class="fl">143</span>, <span class="fl">56</span>, <span class="fl">26</span>, <span class="fl">22</span>, <span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>
<span class="va">logcel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3.36</span>, <span class="fl">2.88</span>, <span class="fl">3.63</span>, <span class="fl">3.41</span>, <span class="fl">3.78</span>, <span class="fl">4.02</span>, <span class="fl">4.00</span>, <span class="fl">4.72</span>, <span class="fl">5.00</span>, <span class="fl">4.23</span>, <span class="fl">3.73</span>, <span class="fl">3.85</span>, <span class="fl">3.97</span>, <span class="fl">4.51</span>, <span class="fl">4.54</span>, <span class="fl">5.00</span>, <span class="fl">5.00</span><span class="op">)</span></code></pre></div>
<p><strong>Ejercicio 3.</strong> Un total de 90 pacientes que sufrían ele cancer gástrico fueron asignados aleatoriamente a dos grupos. Un gupo fue tratado con quimioterapia y radiación, mientras que el otro sólo recibió quimioterapia. Se recoge además el tiempo de superviviencia si dicho datos está censurado (0) o no (1). ¿Existe evidencia para concluir que la radiación prolonga el tiempo de supervivencia?</p>
<div class="sourceCode" id="cb980"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">group</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Q+R"</span>, <span class="fl">45</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Q"</span>, <span class="fl">45</span><span class="op">)</span><span class="op">)</span>
<span class="va">censor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">36</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">9</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">36</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span> 
<span class="va">time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">17</span>, <span class="fl">42</span>, <span class="fl">44</span>, <span class="fl">48</span>, <span class="fl">60</span>, <span class="fl">72</span>, <span class="fl">74</span>, <span class="fl">95</span>, <span class="fl">103</span>, <span class="fl">108</span>, <span class="fl">122</span>, <span class="fl">144</span>, <span class="fl">167</span>, <span class="fl">170</span>, <span class="fl">183</span>, <span class="fl">185</span>, <span class="fl">193</span>, <span class="fl">195</span>, <span class="fl">197</span>, <span class="fl">208</span>, <span class="fl">234</span>, <span class="fl">235</span>, <span class="fl">254</span>, <span class="fl">307</span>, <span class="fl">315</span>, <span class="fl">401</span>, <span class="fl">445</span>, <span class="fl">464</span>, <span class="fl">484</span>, <span class="fl">528</span>, <span class="fl">542</span>, <span class="fl">567</span>, <span class="fl">577</span>, <span class="fl">580</span>, <span class="fl">795</span>, <span class="fl">855</span>, <span class="fl">1174</span>, <span class="fl">1214</span>, <span class="fl">1232</span>, <span class="fl">1366</span>, <span class="fl">1455</span>, <span class="fl">1585</span>, <span class="fl">1622</span>, <span class="fl">1626</span>, <span class="fl">1736</span>, <span class="fl">1</span>, <span class="fl">63</span>, <span class="fl">105</span>, <span class="fl">125</span>, <span class="fl">182</span>, <span class="fl">216</span>, <span class="fl">250</span>, <span class="fl">262</span>, <span class="fl">301</span>, <span class="fl">301</span>, <span class="fl">342</span>, <span class="fl">354</span>, <span class="fl">356</span>, <span class="fl">358</span>, <span class="fl">380</span>, <span class="fl">383</span>, <span class="fl">383</span>, <span class="fl">388</span>, <span class="fl">394</span>, <span class="fl">408</span>, <span class="fl">460</span>, <span class="fl">489</span>, <span class="fl">499</span>, <span class="fl">523</span>, <span class="fl">524</span>, <span class="fl">535</span>, <span class="fl">562</span>, <span class="fl">569</span>, <span class="fl">675</span>, <span class="fl">676</span>, <span class="fl">748</span>, <span class="fl">778</span>, <span class="fl">786</span>, <span class="fl">797</span>, <span class="fl">955</span>, <span class="fl">968</span>, <span class="fl">977</span>, <span class="fl">1245</span>, <span class="fl">1271</span>, <span class="fl">1420</span>, <span class="fl">1460</span>, <span class="fl">1516</span>, <span class="fl">1551</span>, <span class="fl">1690</span>, <span class="fl">1694</span><span class="op">)</span> </code></pre></div>
<p><strong>Ejercicio 4.</strong> Los datos siguientes contienen los tiempos de remisión de pacientes con leucemia para dos grupos de pacientes ¿Existen diferencias en los tiempos de supervivencia para ambos grupos? Realiza un estudio completo del modelo de superviviencia asocaido con estos datos.</p>
<div class="sourceCode" id="cb981"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">glm_surv_01</span><span class="op">=</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/d4YI9g"</span>, col_types <span class="op">=</span> <span class="st">"cid"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">glm_surv_01</span><span class="op">)</span></code></pre></div>
<pre><code>## spec_tbl_df [42 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ group : chr [1:42] "control" "control" "control" "control" ...
##  $ censor: int [1:42] 1 1 1 1 1 1 1 1 1 1 ...
##  $ time  : num [1:42] 1 1 2 2 3 4 4 5 5 8 ...
##  - attr(*, "spec")=
##   .. cols(
##   ..   group = col_character(),
##   ..   censor = col_integer(),
##   ..   time = col_double()
##   .. )
##  - attr(*, "problems")=&lt;externalptr&gt;</code></pre>
<p><strong>Ejercicio 5.</strong> El conjunto de datos siguiente contiene los datos de supervivencia (en meses) de pacientes hepatitis crónica activa y que son dividios en dos grupos. Al grupo tratado se le suministra Prednisona mientras que el otro grupo actúa como control. ¿Existen diferencias en los tiempos de supervivencia para ambos grupos? Realiza un estudio completo del modelo de superviviencia asocaido con estos datos.</p>
<div class="sourceCode" id="cb983"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">glm_surv_02</span><span class="op">=</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://goo.gl/Rzxo3o"</span>, col_types <span class="op">=</span> <span class="st">"dcc"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">glm_surv_02</span><span class="op">)</span></code></pre></div>
<pre><code>## spec_tbl_df [44 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ stime : num [1:44] 2 6 12 54 56 68 89 96 96 125 ...
##  $ censor: chr [1:44] "died" "died" "died" "died" ...
##  $ group : chr [1:44] "prednisolone" "prednisolone" "prednisolone" "prednisolone" ...
##  - attr(*, "spec")=
##   .. cols(
##   ..   stime = col_double(),
##   ..   censor = col_character(),
##   ..   group = col_character()
##   .. )
##  - attr(*, "problems")=&lt;externalptr&gt;</code></pre>
<p><strong>Ejercicio 6.</strong> Los siguientes datos representan la supervivencia en días desde el ingreso al ensayo de pacientes con linfoma histiocítico difuso. Se comparan dos grupos diferentes de pacientes, aquellos con estadio III y aquellos con enfermedad en estadio IV.</p>
<div class="sourceCode" id="cb985"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">group</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"SIII"</span>, <span class="fl">19</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"SIV"</span>, <span class="fl">61</span><span class="op">)</span><span class="op">)</span>
<span class="va">censor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span> 
<span class="va">time</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span>, <span class="fl">19</span>, <span class="fl">32</span>, <span class="fl">42</span>, <span class="fl">42</span>, <span class="fl">43</span>, <span class="fl">94</span>, <span class="fl">126</span>, <span class="fl">169</span>, <span class="fl">207</span>, <span class="fl">211</span>, <span class="fl">227</span>, <span class="fl">253</span>, <span class="fl">255</span>, <span class="fl">270</span>, <span class="fl">310</span>, <span class="fl">316</span>, <span class="fl">335</span>, <span class="fl">346</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">10</span>, <span class="fl">11</span>, <span class="fl">11</span>, <span class="fl">11</span>, <span class="fl">13</span>, <span class="fl">17</span>, <span class="fl">20</span>, <span class="fl">20</span>, <span class="fl">21</span>, <span class="fl">22</span>, <span class="fl">24</span>, <span class="fl">24</span>, <span class="fl">29</span>, <span class="fl">30</span>, <span class="fl">30</span>, <span class="fl">31</span>, <span class="fl">33</span>, <span class="fl">34</span>, <span class="fl">35</span>, <span class="fl">39</span>, <span class="fl">40</span>, <span class="fl">41</span>, <span class="fl">43</span>, <span class="fl">45</span>, <span class="fl">46</span>, <span class="fl">50</span>, <span class="fl">56</span>, <span class="fl">61</span>, <span class="fl">61</span>, <span class="fl">63</span>, <span class="fl">68</span>, <span class="fl">82</span>, <span class="fl">85</span>, <span class="fl">88</span>, <span class="fl">89</span>, <span class="fl">90</span>, <span class="fl">93</span>, <span class="fl">104</span>, <span class="fl">110</span>, <span class="fl">134</span>, <span class="fl">137</span>, <span class="fl">160</span>, <span class="fl">169</span>, <span class="fl">171</span>, <span class="fl">173</span>, <span class="fl">175</span>, <span class="fl">184</span>, <span class="fl">201</span>, <span class="fl">222</span>, <span class="fl">235</span>, <span class="fl">247</span>, <span class="fl">260</span>, <span class="fl">284</span>, <span class="fl">290</span>, <span class="fl">291</span>, <span class="fl">302</span>, <span class="fl">304</span>, <span class="fl">341</span>, <span class="fl">345</span><span class="op">)</span> </code></pre></div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="glmtablascont.html"><span class="header-section-number">15</span> GLM para tablas de contingencia</a></div>
<div class="next"><a href="referencias.html">Referencias</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#glmsuperv"><span class="header-section-number">16</span> GLM para datos de supervivencia</a></li>
<li>
<a class="nav-link" href="#funciones-de-supervivencia"><span class="header-section-number">16.1</span> Funciones de supervivencia</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#supervivencia-completa"><span class="header-section-number">16.1.1</span> Supervivencia completa</a></li>
<li><a class="nav-link" href="#supervivencia-por-un-factor"><span class="header-section-number">16.1.2</span> Supervivencia por un factor</a></li>
<li><a class="nav-link" href="#test-de-comparaci%C3%B3n"><span class="header-section-number">16.1.3</span> Test de comparación</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#an%C3%A1lisis-preliminar-1"><span class="header-section-number">16.2</span> Análisis preliminar</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#leucemia"><span class="header-section-number">16.2.1</span> Leucemia</a></li>
<li><a class="nav-link" href="#veteranos"><span class="header-section-number">16.2.2</span> Veteranos</a></li>
<li><a class="nav-link" href="#c%C3%A1ncer-de-pulm%C3%B3n"><span class="header-section-number">16.2.3</span> Cáncer de pulmón</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#modelos-de-supervivencia"><span class="header-section-number">16.3</span> Modelos de supervivencia</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#hip%C3%B3tesis-del-modelo"><span class="header-section-number">16.3.1</span> Hipótesis del modelo</a></li>
<li><a class="nav-link" href="#an%C3%A1lisis-c%C3%A1ncer-de-pulm%C3%B3n"><span class="header-section-number">16.3.2</span> Análisis Cáncer de pulmón</a></li>
<li><a class="nav-link" href="#m%C3%BAltiples-predictoras"><span class="header-section-number">16.3.3</span> Múltiples predictoras</a></li>
<li><a class="nav-link" href="#diagn%C3%B3stico-del-modelo-2"><span class="header-section-number">16.3.4</span> Diagnóstico del modelo</a></li>
</ul>
</li>
<li><a class="nav-link" href="#ejercicios-6"><span class="header-section-number">16.4</span> Ejercicios</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modelos Estadísticos</strong>" was written by true, true. It was last built on 2022-03-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
