<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Unidad 4 Inferencia básica | Modelos Estadísticos</title>
  <meta name="description" content="Unidad 4 Inferencia básica | Modelos Estadísticos" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Unidad 4 Inferencia básica | Modelos Estadísticos" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Unidad 4 Inferencia básica | Modelos Estadísticos" />
  
  
  



<meta name="date" content="2022-02-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prob.html"/>
<link rel="next" href="modelstats.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>
<li><a href="./">J. Morales y A.M. Mayoral</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html"><i class="fa fa-check"></i>Antes de empezar</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#conceptos-básicos-del-diseño-experimental"><i class="fa fa-check"></i>Conceptos básicos del diseño experimental</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#objetivo-del-diseño-experimental"><i class="fa fa-check"></i>Objetivo del diseño experimental</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#población-y-muestra"><i class="fa fa-check"></i>Población y muestra</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#medidas-y-escalas-de-medida"><i class="fa fa-check"></i>Medidas y escalas de medida</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#parámetros-poblacionales-y-estadísticos"><i class="fa fa-check"></i>Parámetros poblacionales y estadísticos</a></li>
</ul></li>
<li><a href="antes-de-empezar.html#primeros-pasos-con-r-y-rstudio">Primeros pasos con <code>R</code> y <code>RStudio</code></a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#instalación-y-puesta-en-marcha"><i class="fa fa-check"></i>Instalación y puesta en marcha</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#informes-prediseñados"><i class="fa fa-check"></i>Informes prediseñados</a></li>
<li><a href="antes-de-empezar.html#librerías-de-r-necesarías">Librerías de <code>R</code> necesarías</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#conceptos-básicos"><i class="fa fa-check"></i><b>1.1</b> Conceptos básicos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#objetivo-del-diseño-experimental-1"><i class="fa fa-check"></i><b>1.1.1</b> Objetivo del diseño experimental</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#población-y-muestra-1"><i class="fa fa-check"></i><b>1.1.2</b> Población y muestra</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#medidas-y-escalas-de-medida-1"><i class="fa fa-check"></i><b>1.1.3</b> Medidas y escalas de medida</a></li>
<li class="chapter" data-level="1.1.4" data-path="intro.html"><a href="intro.html#parámetros-poblacionales-y-estadísticos-1"><i class="fa fa-check"></i><b>1.1.4</b> Parámetros poblacionales y estadísticos</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>1.2</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="aed.html"><a href="aed.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="aed.html"><a href="aed.html#objetivos"><i class="fa fa-check"></i><b>2.1</b> Objetivos</a></li>
<li class="chapter" data-level="2.2" data-path="aed.html"><a href="aed.html#variabilidad"><i class="fa fa-check"></i><b>2.2</b> Variabilidad</a></li>
<li class="chapter" data-level="2.3" data-path="aed.html"><a href="aed.html#procesado-inicial"><i class="fa fa-check"></i><b>2.3</b> Procesado inicial</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="aed.html"><a href="aed.html#operaciones-con-sujetos"><i class="fa fa-check"></i><b>2.3.1</b> Operaciones con sujetos</a></li>
<li class="chapter" data-level="2.3.2" data-path="aed.html"><a href="aed.html#trabajando-con-variables"><i class="fa fa-check"></i><b>2.3.2</b> Trabajando con variables</a></li>
<li class="chapter" data-level="2.3.3" data-path="aed.html"><a href="aed.html#reuniendo-los-datos"><i class="fa fa-check"></i><b>2.3.3</b> Reuniendo los datos</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="aed.html"><a href="aed.html#análisis-descriptivo-inicial"><i class="fa fa-check"></i><b>2.4</b> Análisis Descriptivo inicial</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="aed.html"><a href="aed.html#una-variable-factor"><i class="fa fa-check"></i><b>2.4.1</b> Una variable factor</a></li>
<li class="chapter" data-level="2.4.2" data-path="aed.html"><a href="aed.html#una-variable-numérica"><i class="fa fa-check"></i><b>2.4.2</b> Una variable numérica</a></li>
<li class="chapter" data-level="2.4.3" data-path="aed.html"><a href="aed.html#dos-variables-categóricas"><i class="fa fa-check"></i><b>2.4.3</b> Dos variables categóricas</a></li>
<li class="chapter" data-level="2.4.4" data-path="aed.html"><a href="aed.html#categórica-vs-numérica"><i class="fa fa-check"></i><b>2.4.4</b> Categórica vs Numérica</a></li>
<li class="chapter" data-level="2.4.5" data-path="aed.html"><a href="aed.html#dos-variables-numéricas"><i class="fa fa-check"></i><b>2.4.5</b> Dos variables numéricas</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="aed.html"><a href="aed.html#análisis-descriptivo-avanzado"><i class="fa fa-check"></i><b>2.5</b> Análisis Descriptivo avanzado</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="aed.html"><a href="aed.html#tres-factores"><i class="fa fa-check"></i><b>2.5.1</b> Tres factores</a></li>
<li class="chapter" data-level="2.5.2" data-path="aed.html"><a href="aed.html#dos-factores-una-numérica"><i class="fa fa-check"></i><b>2.5.2</b> Dos factores, Una numérica</a></li>
<li class="chapter" data-level="2.5.3" data-path="aed.html"><a href="aed.html#un-factor-dos-numéricas"><i class="fa fa-check"></i><b>2.5.3</b> Un factor, Dos numéricas</a></li>
<li class="chapter" data-level="2.5.4" data-path="aed.html"><a href="aed.html#dos-factores-dos-numéricas"><i class="fa fa-check"></i><b>2.5.4</b> Dos factores, Dos numéricas</a></li>
<li class="chapter" data-level="2.5.5" data-path="aed.html"><a href="aed.html#tres-factores-dos-numéricas"><i class="fa fa-check"></i><b>2.5.5</b> Tres factores, Dos numéricas</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="aed.html"><a href="aed.html#librería-de-interés"><i class="fa fa-check"></i><b>2.6</b> Librería de interés</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="prob.html"><a href="prob.html"><i class="fa fa-check"></i><b>3</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="prob.html"><a href="prob.html#prob-intro"><i class="fa fa-check"></i><b>3.1</b> Introducción</a></li>
<li class="chapter" data-level="3.2" data-path="prob.html"><a href="prob.html#distribuciones-modelos"><i class="fa fa-check"></i><b>3.2</b> Distribuciones-Modelos</a></li>
<li class="chapter" data-level="3.3" data-path="prob.html"><a href="prob.html#distribuciones-notables"><i class="fa fa-check"></i><b>3.3</b> Distribuciones notables</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="prob.html"><a href="prob.html#prob-binomial"><i class="fa fa-check"></i><b>3.3.1</b> Distribución Binomial</a></li>
<li class="chapter" data-level="3.3.2" data-path="prob.html"><a href="prob.html#prob-poisson"><i class="fa fa-check"></i><b>3.3.2</b> Distribución Poisson</a></li>
<li class="chapter" data-level="3.3.3" data-path="prob.html"><a href="prob.html#prob-normal"><i class="fa fa-check"></i><b>3.3.3</b> Distribución Normal</a></li>
<li class="chapter" data-level="3.3.4" data-path="prob.html"><a href="prob.html#otras-distribuciones"><i class="fa fa-check"></i><b>3.3.4</b> Otras distribuciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inferencia-básica.html"><a href="inferencia-básica.html"><i class="fa fa-check"></i><b>4</b> Inferencia básica</a>
<ul>
<li class="chapter" data-level="4.1" data-path="inferencia-básica.html"><a href="inferencia-básica.html#estimador-y-estimación"><i class="fa fa-check"></i><b>4.1</b> Estimador y estimación</a></li>
<li class="chapter" data-level="4.2" data-path="inferencia-básica.html"><a href="inferencia-básica.html#información-contenida-en-la-muestra"><i class="fa fa-check"></i><b>4.2</b> Información contenida en la muestra</a></li>
<li class="chapter" data-level="4.3" data-path="inferencia-básica.html"><a href="inferencia-básica.html#procedimientos-de-inferencia-estadística"><i class="fa fa-check"></i><b>4.3</b> Procedimientos de inferencia estadística</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="inferencia-básica.html"><a href="inferencia-básica.html#estimación-puntual"><i class="fa fa-check"></i><b>4.3.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.3.2" data-path="inferencia-básica.html"><a href="inferencia-básica.html#distribución-en-el-muestreo"><i class="fa fa-check"></i><b>4.3.2</b> Distribución en el muestreo</a></li>
<li class="chapter" data-level="4.3.3" data-path="inferencia-básica.html"><a href="inferencia-básica.html#estimación-por-intervalos-de-confianza"><i class="fa fa-check"></i><b>4.3.3</b> Estimación por intervalos de confianza</a></li>
<li class="chapter" data-level="4.3.4" data-path="inferencia-básica.html"><a href="inferencia-básica.html#contraste-de-hipótesis"><i class="fa fa-check"></i><b>4.3.4</b> Contraste de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="inferencia-básica.html"><a href="inferencia-básica.html#inferencia-para-dos-poblaciones"><i class="fa fa-check"></i><b>4.4</b> Inferencia para dos poblaciones</a></li>
<li class="chapter" data-level="4.5" data-path="inferencia-básica.html"><a href="inferencia-básica.html#inferencia-para-dos-proporciones"><i class="fa fa-check"></i><b>4.5</b> Inferencia para dos proporciones</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="inferencia-básica.html"><a href="inferencia-básica.html#estimador-puntual"><i class="fa fa-check"></i><b>4.5.1</b> Estimador puntual</a></li>
<li class="chapter" data-level="4.5.2" data-path="inferencia-básica.html"><a href="inferencia-básica.html#estimador-por-intervalos-de-confianza"><i class="fa fa-check"></i><b>4.5.2</b> Estimador por intervalos de confianza</a></li>
<li class="chapter" data-level="4.5.3" data-path="inferencia-básica.html"><a href="inferencia-básica.html#contraste-de-hipótesis-1"><i class="fa fa-check"></i><b>4.5.3</b> Contraste de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="inferencia-básica.html"><a href="inferencia-básica.html#inferencia-para-dos-medias"><i class="fa fa-check"></i><b>4.6</b> Inferencia para dos medias</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="inferencia-básica.html"><a href="inferencia-básica.html#análisis-de-dos-varianzas-poblacionales"><i class="fa fa-check"></i><b>4.6.1</b> Análisis de dos varianzas poblacionales</a></li>
<li class="chapter" data-level="4.6.2" data-path="inferencia-básica.html"><a href="inferencia-básica.html#dos-medias-para-poblaciones-independientes-con-varianzas-iguales"><i class="fa fa-check"></i><b>4.6.2</b> Dos medias para poblaciones independientes con varianzas iguales</a></li>
<li class="chapter" data-level="4.6.3" data-path="inferencia-básica.html"><a href="inferencia-básica.html#dos-medias-para-poblaciones-independientes-con-varianzas-distintas"><i class="fa fa-check"></i><b>4.6.3</b> Dos medias para poblaciones independientes con varianzas distintas</a></li>
<li class="chapter" data-level="4.6.4" data-path="inferencia-básica.html"><a href="inferencia-básica.html#dos-medias-para-poblaciones-emparejadas"><i class="fa fa-check"></i><b>4.6.4</b> Dos medias para poblaciones emparejadas</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="inferencia-básica.html"><a href="inferencia-básica.html#procedimientos-no-paramétricos"><i class="fa fa-check"></i><b>4.7</b> Procedimientos no paramétricos</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="inferencia-básica.html"><a href="inferencia-básica.html#normalidad"><i class="fa fa-check"></i><b>4.7.1</b> Normalidad</a></li>
<li class="chapter" data-level="4.7.2" data-path="inferencia-básica.html"><a href="inferencia-básica.html#dos-medianas-en-poblaciones-independientes"><i class="fa fa-check"></i><b>4.7.2</b> Dos medianas en poblaciones independientes</a></li>
<li class="chapter" data-level="4.7.3" data-path="inferencia-básica.html"><a href="inferencia-básica.html#dos-medianas-en-poblaciones-dependientes"><i class="fa fa-check"></i><b>4.7.3</b> Dos medianas en poblaciones dependientes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelstats.html"><a href="modelstats.html"><i class="fa fa-check"></i><b>5</b> Modelos estadísticos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelstats.html"><a href="modelstats.html#componentes-del-modelo"><i class="fa fa-check"></i><b>5.1</b> Componentes del modelo</a></li>
<li class="chapter" data-level="5.2" data-path="modelstats.html"><a href="modelstats.html#tipos-de-modelos"><i class="fa fa-check"></i><b>5.2</b> Tipos de modelos</a></li>
<li class="chapter" data-level="5.3" data-path="modelstats.html"><a href="modelstats.html#fases-en-la-construcción-de-un-modelo"><i class="fa fa-check"></i><b>5.3</b> Fases en la construcción de un modelo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rls.html"><a href="rls.html"><i class="fa fa-check"></i><b>6</b> Regresión Lineal Simple (RLS)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="rls.html"><a href="rls.html#bancos-de-datos"><i class="fa fa-check"></i><b>6.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="6.2" data-path="rls.html"><a href="rls.html#modelorls"><i class="fa fa-check"></i><b>6.2</b> El modelo RLS</a></li>
<li class="chapter" data-level="6.3" data-path="rls.html"><a href="rls.html#estimacionrls"><i class="fa fa-check"></i><b>6.3</b> Estimación del modelo</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="rls.html"><a href="rls.html#mincuadrls"><i class="fa fa-check"></i><b>6.3.1</b> Estimación Mínimos Cuadrados</a></li>
<li class="chapter" data-level="6.3.2" data-path="rls.html"><a href="rls.html#emvrls"><i class="fa fa-check"></i><b>6.3.2</b> Estimación Máximo Verosímil</a></li>
<li class="chapter" data-level="6.3.3" data-path="rls.html"><a href="rls.html#emR"><i class="fa fa-check"></i><b>6.3.3</b> Estimación con R</a></li>
<li class="chapter" data-level="6.3.4" data-path="rls.html"><a href="rls.html#ejemplos"><i class="fa fa-check"></i><b>6.3.4</b> Ejemplos</a></li>
<li class="chapter" data-level="6.3.5" data-path="rls.html"><a href="rls.html#propiedades-de-la-recta-de-regresión."><i class="fa fa-check"></i><b>6.3.5</b> Propiedades de la recta de regresión.</a></li>
<li class="chapter" data-level="6.3.6" data-path="rls.html"><a href="rls.html#rls_varmodel"><i class="fa fa-check"></i><b>6.3.6</b> Estimación varianza del modelo.</a></li>
<li class="chapter" data-level="6.3.7" data-path="rls.html"><a href="rls.html#inferencia-sobre-los-coeficientes-del-modelo"><i class="fa fa-check"></i><b>6.3.7</b> Inferencia sobre los coeficientes del modelo</a></li>
<li class="chapter" data-level="6.3.8" data-path="rls.html"><a href="rls.html#ejemplo"><i class="fa fa-check"></i><b>6.3.8</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="rls.html"><a href="rls.html#bondad-del-ajuste"><i class="fa fa-check"></i><b>6.4</b> Bondad del Ajuste</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="rls.html"><a href="rls.html#rls_errorresidual"><i class="fa fa-check"></i><b>6.4.1</b> Error residual</a></li>
<li class="chapter" data-level="6.4.2" data-path="rls.html"><a href="rls.html#rls_tablaanova"><i class="fa fa-check"></i><b>6.4.2</b> Tabla Anova</a></li>
<li class="chapter" data-level="6.4.3" data-path="rls.html"><a href="rls.html#coeficiente-de-determinación"><i class="fa fa-check"></i><b>6.4.3</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="6.4.4" data-path="rls.html"><a href="rls.html#ejemplo-1"><i class="fa fa-check"></i><b>6.4.4</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rls.html"><a href="rls.html#rls_diag"><i class="fa fa-check"></i><b>6.5</b> Diagnóstico del Modelo</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="rls.html"><a href="rls.html#linealidad-y-homocedasticidad."><i class="fa fa-check"></i><b>6.5.1</b> Linealidad y homocedasticidad.</a></li>
<li class="chapter" data-level="6.5.2" data-path="rls.html"><a href="rls.html#ejemplo-2"><i class="fa fa-check"></i><b>6.5.2</b> Ejemplo</a></li>
<li class="chapter" data-level="6.5.3" data-path="rls.html"><a href="rls.html#normalidad-1"><i class="fa fa-check"></i><b>6.5.3</b> Normalidad</a></li>
<li class="chapter" data-level="6.5.4" data-path="rls.html"><a href="rls.html#independencia."><i class="fa fa-check"></i><b>6.5.4</b> Independencia.</a></li>
<li class="chapter" data-level="6.5.5" data-path="rls.html"><a href="rls.html#otros-gráficos-de-diagnóstico"><i class="fa fa-check"></i><b>6.5.5</b> Otros gráficos de diagnóstico</a></li>
<li class="chapter" data-level="6.5.6" data-path="rls.html"><a href="rls.html#incumplimiento-de-hipótesis"><i class="fa fa-check"></i><b>6.5.6</b> Incumplimiento de hipótesis</a></li>
<li class="chapter" data-level="6.5.7" data-path="rls.html"><a href="rls.html#análisis-de-influencia"><i class="fa fa-check"></i><b>6.5.7</b> Análisis de influencia</a></li>
<li class="chapter" data-level="6.5.8" data-path="rls.html"><a href="rls.html#transformaciones"><i class="fa fa-check"></i><b>6.5.8</b> Transformaciones</a></li>
<li class="chapter" data-level="6.5.9" data-path="rls.html"><a href="rls.html#ejemplos-1"><i class="fa fa-check"></i><b>6.5.9</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="rls.html"><a href="rls.html#rls_pred"><i class="fa fa-check"></i><b>6.6</b> Predicción del modelo</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="rls.html"><a href="rls.html#respuesta-media"><i class="fa fa-check"></i><b>6.6.1</b> Respuesta media</a></li>
<li class="chapter" data-level="6.6.2" data-path="rls.html"><a href="rls.html#nueva-observación"><i class="fa fa-check"></i><b>6.6.2</b> Nueva observación</a></li>
<li class="chapter" data-level="6.6.3" data-path="rls.html"><a href="rls.html#ejemplos-2"><i class="fa fa-check"></i><b>6.6.3</b> Ejemplos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rlm.html"><a href="rlm.html"><i class="fa fa-check"></i><b>7</b> Regresión Lineal Múltiple y Polinómica</a>
<ul>
<li class="chapter" data-level="7.1" data-path="rlm.html"><a href="rlm.html#tipos-de-modelos-1"><i class="fa fa-check"></i><b>7.1</b> Tipos de modelos</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="rlm.html"><a href="rlm.html#modelos-de-rlm"><i class="fa fa-check"></i><b>7.1.1</b> Modelos de RLM</a></li>
<li class="chapter" data-level="7.1.2" data-path="rlm.html"><a href="rlm.html#modelos-de-rp"><i class="fa fa-check"></i><b>7.1.2</b> Modelos de RP</a></li>
<li class="chapter" data-level="7.1.3" data-path="rlm.html"><a href="rlm.html#expresión-en-r-de-los-modelos"><i class="fa fa-check"></i><b>7.1.3</b> Expresión en R de los modelos</a></li>
<li class="chapter" data-level="7.1.4" data-path="rlm.html"><a href="rlm.html#modelo-saturado-y-anidado"><i class="fa fa-check"></i><b>7.1.4</b> Modelo saturado y anidado</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="rlm.html"><a href="rlm.html#estimación-e-inferencia"><i class="fa fa-check"></i><b>7.2</b> Estimación e inferencia</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="rlm.html"><a href="rlm.html#mínimos-cuadrados"><i class="fa fa-check"></i><b>7.2.1</b> Mínimos cuadrados</a></li>
<li class="chapter" data-level="7.2.2" data-path="rlm.html"><a href="rlm.html#propiedades"><i class="fa fa-check"></i><b>7.2.2</b> Propiedades</a></li>
<li class="chapter" data-level="7.2.3" data-path="rlm.html"><a href="rlm.html#máxima-verosimilitud"><i class="fa fa-check"></i><b>7.2.3</b> Máxima verosimilitud</a></li>
<li class="chapter" data-level="7.2.4" data-path="rlm.html"><a href="rlm.html#inferencia"><i class="fa fa-check"></i><b>7.2.4</b> Inferencia</a></li>
<li class="chapter" data-level="7.2.5" data-path="rlm.html"><a href="rlm.html#ejemplos-3"><i class="fa fa-check"></i><b>7.2.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="rlm.html"><a href="rlm.html#bondad-del-ajuste-1"><i class="fa fa-check"></i><b>7.3</b> Bondad del ajuste</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="rlm.html"><a href="rlm.html#tabla-anova"><i class="fa fa-check"></i><b>7.3.1</b> Tabla ANOVA</a></li>
<li class="chapter" data-level="7.3.2" data-path="rlm.html"><a href="rlm.html#coeficiente-determinación"><i class="fa fa-check"></i><b>7.3.2</b> Coeficiente determinación</a></li>
<li class="chapter" data-level="7.3.3" data-path="rlm.html"><a href="rlm.html#ejemplos-4"><i class="fa fa-check"></i><b>7.3.3</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="rlm.html"><a href="rlm.html#comparación-y-selección-de-modelos"><i class="fa fa-check"></i><b>7.4</b> Comparación y selección de modelos</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="rlm.html"><a href="rlm.html#significatividad-de-los-predictores"><i class="fa fa-check"></i><b>7.4.1</b> Significatividad de los predictores</a></li>
<li class="chapter" data-level="7.4.2" data-path="rlm.html"><a href="rlm.html#estadísticos-aic-y-bic"><i class="fa fa-check"></i><b>7.4.2</b> Estadísticos AIC y BIC</a></li>
<li class="chapter" data-level="7.4.3" data-path="rlm.html"><a href="rlm.html#selección-automática"><i class="fa fa-check"></i><b>7.4.3</b> Selección automática</a></li>
<li class="chapter" data-level="7.4.4" data-path="rlm.html"><a href="rlm.html#funciones-en-r"><i class="fa fa-check"></i><b>7.4.4</b> Funciones en R</a></li>
<li class="chapter" data-level="7.4.5" data-path="rlm.html"><a href="rlm.html#ejemplos-5"><i class="fa fa-check"></i><b>7.4.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="rlm.html"><a href="rlm.html#multicolinealidad"><i class="fa fa-check"></i><b>7.5</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="rlm.html"><a href="rlm.html#causas"><i class="fa fa-check"></i><b>7.5.1</b> Causas</a></li>
<li class="chapter" data-level="7.5.2" data-path="rlm.html"><a href="rlm.html#efectos"><i class="fa fa-check"></i><b>7.5.2</b> Efectos</a></li>
<li class="chapter" data-level="7.5.3" data-path="rlm.html"><a href="rlm.html#diagnósticos"><i class="fa fa-check"></i><b>7.5.3</b> Diagnósticos</a></li>
<li class="chapter" data-level="7.5.4" data-path="rlm.html"><a href="rlm.html#soluciones"><i class="fa fa-check"></i><b>7.5.4</b> Soluciones</a></li>
<li class="chapter" data-level="7.5.5" data-path="rlm.html"><a href="rlm.html#ejemplos-6"><i class="fa fa-check"></i><b>7.5.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="rlm.html"><a href="rlm.html#diagnóstico"><i class="fa fa-check"></i><b>7.6</b> Diagnóstico</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="rlm.html"><a href="rlm.html#tipos-de-residuos"><i class="fa fa-check"></i><b>7.6.1</b> Tipos de Residuos</a></li>
<li class="chapter" data-level="7.6.2" data-path="rlm.html"><a href="rlm.html#linealidad"><i class="fa fa-check"></i><b>7.6.2</b> Linealidad</a></li>
<li class="chapter" data-level="7.6.3" data-path="rlm.html"><a href="rlm.html#homocedasticidad"><i class="fa fa-check"></i><b>7.6.3</b> Homocedasticidad</a></li>
<li class="chapter" data-level="7.6.4" data-path="rlm.html"><a href="rlm.html#normalidad-2"><i class="fa fa-check"></i><b>7.6.4</b> Normalidad</a></li>
<li class="chapter" data-level="7.6.5" data-path="rlm.html"><a href="rlm.html#incorrelación"><i class="fa fa-check"></i><b>7.6.5</b> Incorrelación</a></li>
<li class="chapter" data-level="7.6.6" data-path="rlm.html"><a href="rlm.html#soluciones-a-problemas-detectados-en-el-diagnóstico-del-modelo"><i class="fa fa-check"></i><b>7.6.6</b> Soluciones a problemas detectados en el diagnóstico del modelo</a></li>
<li class="chapter" data-level="7.6.7" data-path="rlm.html"><a href="rlm.html#análisis-de-influencia-1"><i class="fa fa-check"></i><b>7.6.7</b> Análisis de influencia</a></li>
<li class="chapter" data-level="7.6.8" data-path="rlm.html"><a href="rlm.html#funciones-para-diagnóstico-e-influencia"><i class="fa fa-check"></i><b>7.6.8</b> Funciones para diagnóstico e influencia</a></li>
<li class="chapter" data-level="7.6.9" data-path="rlm.html"><a href="rlm.html#ejemplos-7"><i class="fa fa-check"></i><b>7.6.9</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="rlm.html"><a href="rlm.html#predicción"><i class="fa fa-check"></i><b>7.7</b> Predicción</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="rlm.html"><a href="rlm.html#estimación-de-la-respuesta-media."><i class="fa fa-check"></i><b>7.7.1</b> Estimación de la respuesta media.</a></li>
<li class="chapter" data-level="7.7.2" data-path="rlm.html"><a href="rlm.html#predicción-de-nuevas-observaciones."><i class="fa fa-check"></i><b>7.7.2</b> Predicción de nuevas observaciones.</a></li>
<li class="chapter" data-level="7.7.3" data-path="rlm.html"><a href="rlm.html#ejemplos-8"><i class="fa fa-check"></i><b>7.7.3</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="rlm.html"><a href="rlm.html#ejercicios-1"><i class="fa fa-check"></i><b>7.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>8</b> Modelos ANOVA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="anova.html"><a href="anova.html#bancos-de-datos-1"><i class="fa fa-check"></i><b>8.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="8.2" data-path="anova.html"><a href="anova.html#modelos-anova-1-vía"><i class="fa fa-check"></i><b>8.2</b> Modelos ANOVA 1 vía</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="anova.html"><a href="anova.html#especificacion-del-modelo-en-r"><i class="fa fa-check"></i><b>8.2.1</b> Especificacion del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="anova.html"><a href="anova.html#modelos-anova-dos-vías"><i class="fa fa-check"></i><b>8.3</b> Modelos ANOVA dos vías</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="anova.html"><a href="anova.html#especificacion-del-modelo-en-r-1"><i class="fa fa-check"></i><b>8.3.1</b> Especificacion del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="anova.html"><a href="anova.html#estimación-y-bondad-de-ajuste-del-modelo"><i class="fa fa-check"></i><b>8.4</b> Estimación y bondad de ajuste del modelo</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="anova.html"><a href="anova.html#ejemplos-9"><i class="fa fa-check"></i><b>8.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="anova.html"><a href="anova.html#comparación-y-selección-de-modelos-1"><i class="fa fa-check"></i><b>8.5</b> Comparación y selección de modelos</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="anova.html"><a href="anova.html#ejemplos-10"><i class="fa fa-check"></i><b>8.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="anova.html"><a href="anova.html#diagnóstico-1"><i class="fa fa-check"></i><b>8.6</b> Diagnóstico</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="anova.html"><a href="anova.html#ejemplos-11"><i class="fa fa-check"></i><b>8.6.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="anova.html"><a href="anova.html#predicción-1"><i class="fa fa-check"></i><b>8.7</b> Predicción</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="anova.html"><a href="anova.html#ejemplos-12"><i class="fa fa-check"></i><b>8.7.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="anova.html"><a href="anova.html#ejercicios-2"><i class="fa fa-check"></i><b>8.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>9</b> Modelos ANCOVA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ancova.html"><a href="ancova.html#bancos-de-datos-2"><i class="fa fa-check"></i><b>9.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="9.2" data-path="ancova.html"><a href="ancova.html#modelo-ancova-básico"><i class="fa fa-check"></i><b>9.2</b> Modelo ANCOVA básico</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ancova.html"><a href="ancova.html#i-rectas-de-regresión-perpendiculares"><i class="fa fa-check"></i><b>9.2.1</b> I rectas de regresión perpendiculares</a></li>
<li class="chapter" data-level="9.2.2" data-path="ancova.html"><a href="ancova.html#i-rectas-de-regresión-paralelas"><i class="fa fa-check"></i><b>9.2.2</b> I rectas de regresión paralelas</a></li>
<li class="chapter" data-level="9.2.3" data-path="ancova.html"><a href="ancova.html#una-recta-de-regresión"><i class="fa fa-check"></i><b>9.2.3</b> Una recta de regresión</a></li>
<li class="chapter" data-level="9.2.4" data-path="ancova.html"><a href="ancova.html#anova-de-una-vía"><i class="fa fa-check"></i><b>9.2.4</b> ANOVA de una vía</a></li>
<li class="chapter" data-level="9.2.5" data-path="ancova.html"><a href="ancova.html#modelos-sin-efectos"><i class="fa fa-check"></i><b>9.2.5</b> Modelos sin efectos</a></li>
<li class="chapter" data-level="9.2.6" data-path="ancova.html"><a href="ancova.html#especificación-del-modelo-en-r"><i class="fa fa-check"></i><b>9.2.6</b> Especificación del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ancova.html"><a href="ancova.html#análisis-preliminar"><i class="fa fa-check"></i><b>9.3</b> Análisis preliminar</a></li>
<li class="chapter" data-level="9.4" data-path="ancova.html"><a href="ancova.html#ajuste-y-selección-del-modelo"><i class="fa fa-check"></i><b>9.4</b> Ajuste y Selección del modelo</a></li>
<li class="chapter" data-level="9.5" data-path="ancova.html"><a href="ancova.html#diagnóstico-del-modelo"><i class="fa fa-check"></i><b>9.5</b> Diagnóstico del modelo</a></li>
<li class="chapter" data-level="9.6" data-path="ancova.html"><a href="ancova.html#predicción-2"><i class="fa fa-check"></i><b>9.6</b> Predicción</a></li>
<li class="chapter" data-level="9.7" data-path="ancova.html"><a href="ancova.html#ejercicios-modelos-ancova"><i class="fa fa-check"></i><b>9.7</b> Ejercicios modelos ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="smooth.html"><a href="smooth.html"><i class="fa fa-check"></i><b>10</b> Modelos aditivos lineales</a>
<ul>
<li class="chapter" data-level="10.1" data-path="smooth.html"><a href="smooth.html#bancos-de-datos-3"><i class="fa fa-check"></i><b>10.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="10.2" data-path="smooth.html"><a href="smooth.html#funciones-de-suavizado"><i class="fa fa-check"></i><b>10.2</b> Funciones de suavizado</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="smooth.html"><a href="smooth.html#splines-de-regresión"><i class="fa fa-check"></i><b>10.2.1</b> Splines de regresión</a></li>
<li class="chapter" data-level="10.2.2" data-path="smooth.html"><a href="smooth.html#splines-cúbicos"><i class="fa fa-check"></i><b>10.2.2</b> Splines cúbicos</a></li>
<li class="chapter" data-level="10.2.3" data-path="smooth.html"><a href="smooth.html#splines-penalizados"><i class="fa fa-check"></i><b>10.2.3</b> Splines penalizados</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="smooth.html"><a href="smooth.html#bondad-del-ajuste-y-selección-del-modelo"><i class="fa fa-check"></i><b>10.3</b> Bondad del ajuste y selección del modelo</a></li>
<li class="chapter" data-level="10.4" data-path="smooth.html"><a href="smooth.html#diagnóstico-2"><i class="fa fa-check"></i><b>10.4</b> Diagnóstico</a></li>
<li class="chapter" data-level="10.5" data-path="smooth.html"><a href="smooth.html#predicción-3"><i class="fa fa-check"></i><b>10.5</b> Predicción</a></li>
<li class="chapter" data-level="10.6" data-path="smooth.html"><a href="smooth.html#ejercicios-3"><i class="fa fa-check"></i><b>10.6</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>11</b> Modelos Lineales Generalizados</a>
<ul>
<li class="chapter" data-level="11.1" data-path="glm.html"><a href="glm.html#modelo-teórico"><i class="fa fa-check"></i><b>11.1</b> Modelo Teórico</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="glm.html"><a href="glm.html#distribución-binomial-logit-link"><i class="fa fa-check"></i><b>11.1.1</b> Distribución Binomial (logit link)</a></li>
<li class="chapter" data-level="11.1.2" data-path="glm.html"><a href="glm.html#distribución-poisson-log-link"><i class="fa fa-check"></i><b>11.1.2</b> Distribución Poisson (log link)</a></li>
<li class="chapter" data-level="11.1.3" data-path="glm.html"><a href="glm.html#distribución-normal-link-identidad"><i class="fa fa-check"></i><b>11.1.3</b> Distribución Normal (link identidad)</a></li>
<li class="chapter" data-level="11.1.4" data-path="glm.html"><a href="glm.html#distribución-gamma-link-recíproco"><i class="fa fa-check"></i><b>11.1.4</b> Distribución Gamma (link recíproco)</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="glm.html"><a href="glm.html#estimación-de-los-glm"><i class="fa fa-check"></i><b>11.2</b> Estimación de los GLM</a></li>
<li class="chapter" data-level="11.3" data-path="glm.html"><a href="glm.html#bondad-del-ajuste-2"><i class="fa fa-check"></i><b>11.3</b> Bondad del ajuste</a></li>
<li class="chapter" data-level="11.4" data-path="glm.html"><a href="glm.html#comparación-de-modelos"><i class="fa fa-check"></i><b>11.4</b> Comparación de modelos</a></li>
<li class="chapter" data-level="11.5" data-path="glm.html"><a href="glm.html#diagnóstico-de-los-glm"><i class="fa fa-check"></i><b>11.5</b> Diagnóstico de los GLM</a></li>
<li class="chapter" data-level="11.6" data-path="glm.html"><a href="glm.html#predicción-de-los-glm"><i class="fa fa-check"></i><b>11.6</b> Predicción de los GLM</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="glmbinomial.html"><a href="glmbinomial.html"><i class="fa fa-check"></i><b>12</b> GLM respuesta binomial</a>
<ul>
<li class="chapter" data-level="12.1" data-path="glmbinomial.html"><a href="glmbinomial.html#tipos-de-datos-binomiales"><i class="fa fa-check"></i><b>12.1</b> Tipos de datos binomiales</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="glmbinomial.html"><a href="glmbinomial.html#información-individualizada-por-sujeto"><i class="fa fa-check"></i><b>12.1.1</b> Información individualizada por sujeto</a></li>
<li class="chapter" data-level="12.1.2" data-path="glmbinomial.html"><a href="glmbinomial.html#información-agrupada-por-sujetos"><i class="fa fa-check"></i><b>12.1.2</b> Información agrupada por sujetos</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="glmbinomial.html"><a href="glmbinomial.html#especificación-e-hipótesis-de-modelo"><i class="fa fa-check"></i><b>12.2</b> Especificación e hipótesis de modelo</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="glmbinomial.html"><a href="glmbinomial.html#funciones-link"><i class="fa fa-check"></i><b>12.2.1</b> Funciones link</a></li>
<li class="chapter" data-level="12.2.2" data-path="glmbinomial.html"><a href="glmbinomial.html#representación-de-las-funciones-link"><i class="fa fa-check"></i><b>12.2.2</b> Representación de las funciones link</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="glmbinomial.html"><a href="glmbinomial.html#estimación-y-bondad-de-ajuste"><i class="fa fa-check"></i><b>12.3</b> Estimación y bondad de ajuste</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-13"><i class="fa fa-check"></i><b>12.3.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="glmbinomial.html"><a href="glmbinomial.html#selección-del-modelo"><i class="fa fa-check"></i><b>12.4</b> Selección del modelo</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-14"><i class="fa fa-check"></i><b>12.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="glmbinomial.html"><a href="glmbinomial.html#diagnóstico-3"><i class="fa fa-check"></i><b>12.5</b> Diagnóstico</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-15"><i class="fa fa-check"></i><b>12.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="glmbinomial.html"><a href="glmbinomial.html#predicción-4"><i class="fa fa-check"></i><b>12.6</b> Predicción</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-16"><i class="fa fa-check"></i><b>12.6.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="glmbinomial.html"><a href="glmbinomial.html#ejercicios-4"><i class="fa fa-check"></i><b>12.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="glmpoisson.html"><a href="glmpoisson.html"><i class="fa fa-check"></i><b>13</b> GLM Poisson</a>
<ul>
<li class="chapter" data-level="13.1" data-path="glmpoisson.html"><a href="glmpoisson.html#bancos-de-datos-4"><i class="fa fa-check"></i><b>13.1</b> Bancos de datos</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="glmpoisson.html"><a href="glmpoisson.html#telas"><i class="fa fa-check"></i><b>13.1.1</b> Telas</a></li>
<li class="chapter" data-level="13.1.2" data-path="glmpoisson.html"><a href="glmpoisson.html#barcos"><i class="fa fa-check"></i><b>13.1.2</b> Barcos</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="glmpoisson.html"><a href="glmpoisson.html#modelo-teórico-1"><i class="fa fa-check"></i><b>13.2</b> Modelo Teórico</a></li>
<li class="chapter" data-level="13.3" data-path="glmpoisson.html"><a href="glmpoisson.html#estimación-y-bondad-de-ajuste-del-modelo-1"><i class="fa fa-check"></i><b>13.3</b> Estimación y bondad de ajuste del modelo</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-17"><i class="fa fa-check"></i><b>13.3.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="glmpoisson.html"><a href="glmpoisson.html#selección-del-modelo-1"><i class="fa fa-check"></i><b>13.4</b> Selección del modelo</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-18"><i class="fa fa-check"></i><b>13.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="glmpoisson.html"><a href="glmpoisson.html#diagnóstico-4"><i class="fa fa-check"></i><b>13.5</b> Diagnóstico</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-19"><i class="fa fa-check"></i><b>13.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="glmpoisson.html"><a href="glmpoisson.html#predicción-5"><i class="fa fa-check"></i><b>13.6</b> Predicción</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="glmpoisson.html"><a href="glmpoisson.html#bancos-de-datos-5"><i class="fa fa-check"></i><b>13.6.1</b> Bancos de datos</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="glmpoisson.html"><a href="glmpoisson.html#ejercicios-5"><i class="fa fa-check"></i><b>13.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="glmtablascont.html"><a href="glmtablascont.html"><i class="fa fa-check"></i><b>14</b> GLM para tablas de contingencia</a>
<ul>
<li class="chapter" data-level="14.1" data-path="glmtablascont.html"><a href="glmtablascont.html#bancos-de-datos-6"><i class="fa fa-check"></i><b>14.1</b> Bancos de datos</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="glmtablascont.html"><a href="glmtablascont.html#melanoma"><i class="fa fa-check"></i><b>14.1.1</b> Melanoma</a></li>
<li class="chapter" data-level="14.1.2" data-path="glmtablascont.html"><a href="glmtablascont.html#gripe"><i class="fa fa-check"></i><b>14.1.2</b> Gripe</a></li>
<li class="chapter" data-level="14.1.3" data-path="glmtablascont.html"><a href="glmtablascont.html#aspirina"><i class="fa fa-check"></i><b>14.1.3</b> Aspirina</a></li>
<li class="chapter" data-level="14.1.4" data-path="glmtablascont.html"><a href="glmtablascont.html#aspiraciones"><i class="fa fa-check"></i><b>14.1.4</b> Aspiraciones</a></li>
<li class="chapter" data-level="14.1.5" data-path="glmtablascont.html"><a href="glmtablascont.html#contraceptivos"><i class="fa fa-check"></i><b>14.1.5</b> Contraceptivos</a></li>
<li class="chapter" data-level="14.1.6" data-path="glmtablascont.html"><a href="glmtablascont.html#satisfacción-laboral"><i class="fa fa-check"></i><b>14.1.6</b> Satisfacción laboral</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="glmtablascont.html"><a href="glmtablascont.html#modelos-log-lineales"><i class="fa fa-check"></i><b>14.2</b> Modelos Log-Lineales</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="glmtablascont.html"><a href="glmtablascont.html#especificación-en-r"><i class="fa fa-check"></i><b>14.2.1</b> Especificación en R</a></li>
<li class="chapter" data-level="14.2.2" data-path="glmtablascont.html"><a href="glmtablascont.html#ejemplos-20"><i class="fa fa-check"></i><b>14.2.2</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="glmtablascont.html"><a href="glmtablascont.html#modelos-logit-multinomial"><i class="fa fa-check"></i><b>14.3</b> Modelos Logit-Multinomial</a></li>
<li class="chapter" data-level="14.4" data-path="glmtablascont.html"><a href="glmtablascont.html#estimación"><i class="fa fa-check"></i><b>14.4</b> Estimación</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="glmtablascont.html"><a href="glmtablascont.html#respuesta-binaria-nominal-y-predictora-nominal"><i class="fa fa-check"></i><b>14.4.1</b> Respuesta binaria nominal y predictora nominal</a></li>
<li class="chapter" data-level="14.4.2" data-path="glmtablascont.html"><a href="glmtablascont.html#respuesta-multinomial-nominal-y-predictora-nominal"><i class="fa fa-check"></i><b>14.4.2</b> Respuesta multinomial nominal y predictora nominal</a></li>
<li class="chapter" data-level="14.4.3" data-path="glmtablascont.html"><a href="glmtablascont.html#respuesta-nominal-predictora-ordinal"><i class="fa fa-check"></i><b>14.4.3</b> Respuesta nominal, predictora ordinal</a></li>
<li class="chapter" data-level="14.4.4" data-path="glmtablascont.html"><a href="glmtablascont.html#respuesta-ordinal-predictora-nominal"><i class="fa fa-check"></i><b>14.4.4</b> Respuesta ordinal, predictora nominal</a></li>
<li class="chapter" data-level="14.4.5" data-path="glmtablascont.html"><a href="glmtablascont.html#respuesta-ordinal-predictora-ordinal"><i class="fa fa-check"></i><b>14.4.5</b> Respuesta ordinal, predictora ordinal</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="glmtablascont.html"><a href="glmtablascont.html#diagnóstico-5"><i class="fa fa-check"></i><b>14.5</b> Diagnóstico</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="glmtablascont.html"><a href="glmtablascont.html#ejemplos-21"><i class="fa fa-check"></i><b>14.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="glmtablascont.html"><a href="glmtablascont.html#predicción-6"><i class="fa fa-check"></i><b>14.6</b> Predicción</a></li>
<li class="chapter" data-level="14.7" data-path="glmtablascont.html"><a href="glmtablascont.html#ejercicios-6"><i class="fa fa-check"></i><b>14.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="glmsuperv.html"><a href="glmsuperv.html"><i class="fa fa-check"></i><b>15</b> GLM para datos de supervivencia</a>
<ul>
<li class="chapter" data-level="15.1" data-path="glmsuperv.html"><a href="glmsuperv.html#funciones-de-supervivencia"><i class="fa fa-check"></i><b>15.1</b> Funciones de supervivencia</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="glmsuperv.html"><a href="glmsuperv.html#supervivencia-completa"><i class="fa fa-check"></i><b>15.1.1</b> Supervivencia completa</a></li>
<li class="chapter" data-level="15.1.2" data-path="glmsuperv.html"><a href="glmsuperv.html#supervivencia-por-un-factor"><i class="fa fa-check"></i><b>15.1.2</b> Supervivencia por un factor</a></li>
<li class="chapter" data-level="15.1.3" data-path="glmsuperv.html"><a href="glmsuperv.html#test-de-comparación"><i class="fa fa-check"></i><b>15.1.3</b> Test de comparación</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="glmsuperv.html"><a href="glmsuperv.html#análisis-preliminar-1"><i class="fa fa-check"></i><b>15.2</b> Análisis preliminar</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="glmsuperv.html"><a href="glmsuperv.html#leucemia"><i class="fa fa-check"></i><b>15.2.1</b> Leucemia</a></li>
<li class="chapter" data-level="15.2.2" data-path="glmsuperv.html"><a href="glmsuperv.html#veteranos"><i class="fa fa-check"></i><b>15.2.2</b> Veteranos</a></li>
<li class="chapter" data-level="15.2.3" data-path="glmsuperv.html"><a href="glmsuperv.html#cáncer-de-pulmón"><i class="fa fa-check"></i><b>15.2.3</b> Cáncer de pulmón</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="glmsuperv.html"><a href="glmsuperv.html#modelos-de-supervivencia"><i class="fa fa-check"></i><b>15.3</b> Modelos de supervivencia</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="glmsuperv.html"><a href="glmsuperv.html#hipótesis-del-modelo"><i class="fa fa-check"></i><b>15.3.1</b> Hipótesis del modelo</a></li>
<li class="chapter" data-level="15.3.2" data-path="glmsuperv.html"><a href="glmsuperv.html#análisis-cáncer-de-pulmón"><i class="fa fa-check"></i><b>15.3.2</b> Análisis Cáncer de pulmón</a></li>
<li class="chapter" data-level="15.3.3" data-path="glmsuperv.html"><a href="glmsuperv.html#múltiples-predictoras"><i class="fa fa-check"></i><b>15.3.3</b> Múltiples predictoras</a></li>
<li class="chapter" data-level="15.3.4" data-path="glmsuperv.html"><a href="glmsuperv.html#diagnóstico-del-modelo-2"><i class="fa fa-check"></i><b>15.3.4</b> Diagnóstico del modelo</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="glmsuperv.html"><a href="glmsuperv.html#ejercicios-7"><i class="fa fa-check"></i><b>15.4</b> Ejercicios</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferencia-básica" class="section level1" number="4">
<h1><span class="header-section-number">Unidad 4</span> Inferencia básica</h1>
<p>En la unidad anterior se han expuesto brevemente la teoría y los métodos de la probabilidad. En este unidad se expondrán la teoría y los métodos de la inferencia estadística que servirán como base para los modelos estadísticos que estudiaremos en la unidad siguiente. Un problema de inferencia estadística es un problema en el cual se han de analizar datos que han sido generados de acuerdo con una distribución de probabilidad desconocida y en la que se debe realizar algún tipo de inferencia (“conocer su comportamiento”) acerca de tal distribución. En la mayoría de situaciones reales, existe un número infinito de distribuciones posibles distintas que podrían haber generado los datos. En la práctica, dado el tipo de variable aleatoria considerada, se suele asumir un modelo de distribución de probabilidad que es completamente conocida salvo excepto por los valores de los parámetros que la especifican completamente. Utilizamos los datos de la muestra para obtener información sobre dichos parámetros desconocidos y poder asumir de esta forma una distribución de probabilidad completa para todos los datos de la población.</p>
<p>Por ejemplo, se podría saber que la duración de cierto tipo de marcapasos tiene una distribución exponencial con parámetro <span class="math inline">\(\lambda\)</span> pero desconocer el valor exacto de dicho parámetro. Si se puede observar la duración de varios marcapasos de este tipo, entonces, a partir de estos valores observados y de cualquier otra información relevante de la que se pudiera disponer, es posible producir una inferencia acerca de ese valor desconocido <span class="math inline">\(\lambda\)</span>. Podría interesar producir la mejor estimación del valor de dicho parámetro o especificar un intervalo en el cual se piensa que pueda estar incluido el verdadero valor de <span class="math inline">\(\lambda\)</span>, o decidir si dicho parámetro es menor que un valor específico, ya que en ningún caso es posible obtener el verdadero valor de <span class="math inline">\(\lambda\)</span> ya que sería necesario obtener la información de todos los sujetos de la población y no sólo los de la muestra.</p>
<p>En un problema de inferencia estadística, cualquier característica de la distribución que genera los datos experimentales que tenga un valor desconocido, como <span class="math inline">\(\lambda\)</span> en el ejemplo anterior, se llama parámetro de la distribución. El conjunto <span class="math inline">\(\Omega\)</span> de todos los valores posibles de dicho parámetro se llama espacio parámetrico. Cuando nuestra distribución de probabilidad tiene dos parámetros (por ejemplo la distribución Normal) el espacio paramétrico vendrá dado por todo el conjunto de parejas de valores de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma^2\)</span>.</p>
<div id="estimador-y-estimación" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Estimador y estimación</h2>
<p>Si tenemos una variable aleatoria <span class="math inline">\(X\)</span> cuya función de distribución viene caracterizada por un parámetro o conjunto de parámetros <span class="math inline">\(\delta\)</span>, y una muestra aleatoria de tamaño <span class="math inline">\(n\)</span>, <span class="math inline">\(X_1,...,X_n\)</span>, a partir de la cual se observan el conjunto de datos muestrales <span class="math inline">\(x_1,...,x_n\)</span> vamos a definir dos conceptos relevantes en todo proceso de inferencia: <code>estimador</code> y <code>estimación</code>.</p>
<p>Un <strong>estimador</strong> del parámetro <span class="math inline">\(\delta\)</span>, basado en las variables aleatorias <span class="math inline">\(X_1,...,X_n\)</span>, es una función <span class="math inline">\(\delta(X_1,...,X_n)\)</span> que especifica una valor para <span class="math inline">\(\delta\)</span>. Se trata de una función matemática que tiene la misma forma independientemente de la muestra utilizada. Por ejemplo, los estimadores para la media, varianza (y cuasivarainza), y proporción poblacionales vienen dados por:</p>
<ol style="list-style-type: decimal">
<li>Media muestral</li>
</ol>
<p><span class="math display">\[\delta_1(X_1,...,X_n) = \bar{X} = \frac{X_1+X_2+...+X_n}{n}\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Varianza muestral</li>
</ol>
<p><span class="math display">\[\delta_2(X_1,...,X_n) = S^2 = \frac{\sum_{i=1}^n (X_i-\bar{X})^2}{n}\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Cuasi-Varianza muestral</li>
</ol>
<p><span class="math display">\[\delta_3(X_1,...,X_n) = S_q^2 = \frac{n}{n-1} S^2\]</span></p>
<p>Para una variable de tipo discreto se aplican las mismas definiciones si consideramos cada <span class="math inline">\(X_i\)</span> como una realización de dicha variable. Para una variable que mide “éxito” o “fracaso” los valores de <span class="math inline">\(X_i\)</span> serán 1 o 0 respectivamente, de forma que la media muestral coincide con la proporción muestral ya que tendríamos la suma de 1 en el numerador dividido por el tamaño de muestra en el denominador.</p>
<p>Una <strong>estimación</strong> es el valor numérico del estimador para unos datos dados (<span class="math inline">\(x_1,...,x_n\)</span>), es decir, sustituimos en <span class="math inline">\(\delta(X_1,...,X_n)\)</span> por sus valores observados y obtendríamos la estimación del parámetro. De forma habitual se identifica con el “gorro” encima del parámetro indica la estimación de un parámetro:
<span class="math display">\[\hat{\mu} = \delta_1(x_1,...,x_n) =\bar{x}\]</span>
<span class="math display">\[\hat{\sigma}^2 = \delta_2(x_1,...,x_n)= s^2\]</span></p>
</div>
<div id="información-contenida-en-la-muestra" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Información contenida en la muestra</h2>
<p>Antes de comenzar a describir los procesos de inferencia estadística es necesario conocer como podemos relacionar la información contenida en una muestra con la distribución de probabilidad de la variable aleatoria de interés. Para ello una vez fijada la población del estudio y el objetivo principal es necesario:</p>
<ul>
<li>Establecer la variable de interés, <span class="math inline">\(X\)</span> (y su tipo), en función del objetivo principal</li>
<li>Establecer una distribución de probabilidad para la variable aleatoria, <span class="math inline">\(f(X | \theta)\)</span>, acorde con el tipo de dicha variable y lo más sencilla posible, donde <span class="math inline">\(\theta\)</span> representa el parámetro o parámetros que especifican dicha distribución.</li>
<li>Muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de la variable de interés, <span class="math inline">\(X_1, X_2,...,X_n\)</span> de forma que cada observación tiene probabilidad <span class="math inline">\(f(X_1 | \theta), f(X_2 | \theta),...,f(X_n | \theta)\)</span> respectivamente y sus valores observados vienen dados por <span class="math inline">\(x_1,...,x_n\)</span>.</li>
<li>Obtener los descriptivos muestrales habituales: media, varianza, desviación típica, o proporción.</li>
</ul>
<p>Se define entonces la <code>función de verosimilitud</code> <span class="math inline">\(L(X|\theta)\)</span> como:
<span class="math display">\[L(X|\theta) = \prod_{i=1}^n f(X_i|\theta) = f(X_1|\theta)f(X_2|\theta)\cdots f(X_n|\theta)\]</span></p>
<p>La función de verosimilitud contiene toda la información sobre la muestra y la relaciona con el parámetro o parámetros de interés a través de la distribución de probabilidad establecida. Se convierte por tanto en la herramienta más importante, desde el punto de vista de la estadística frecuentista, para los procesos de inferencia estadística que estudiaremos a continuación. Además, se utiliza como base para la caracterización de la distribución en el muestreo de los diferentes estimadores, aproximaciones numéricas del verdadero valor del parámetro o parámetros de la distribución de probabilidad asumida, que se utilizan en los procesos inferenciales.</p>
<p>Para evitar la complejidad matemática que supone trabajar con productos se suele definir el logaritmo de la función de verosimilitud, <code>log-verosimilitud</code>, <span class="math inline">\(LL(X|\theta)\)</span> como:
<span class="math display">\[LL(X|\theta) = log\left(\prod_{i=1}^n f(X_i|\theta)\right) = \sum_{i=1}^n log(f(X_i|\theta)) = log(f(X_1|\theta))+log(f(X_2|\theta))+\cdots +log(f(X_n|\theta))\]</span></p>
</div>
<div id="procedimientos-de-inferencia-estadística" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Procedimientos de inferencia estadística</h2>
<p>Estudiamos en este punto los distintos procedimientos de inferencia que tratamos en esta unidad. Realizamos una pequeña introducción de cada uno de ellos y ejemplificaremos su uso en el análisis de una población.</p>
<div id="estimación-puntual" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Estimación puntual</h3>
<p>Es el procedimiento de inferencia estadística más sencillo y consiste en obtener un único valor aproximado del parámetro de interés a partir de un estimador de dicho parámetro y de los datos observados de una muestra. Aunque en las situaciones más sencillas (media, varianza y proporción) tanto el estimador como la estimación son fáciles de obtener, hay que establecer un procedimiento general para obtener dichas estimaciones.</p>
<p>Dicho procedimiento consiste en encontrar el máximo de la función de verosimilitud (o más concretamente de la log-verosimilitud) para el parámetro o parámetros involucrados en dicha función, es decir, el valor o valores que se obtienen al igualar a cero la derivada de la función de log-verosimilitud:
<span class="math display">\[\frac{d}{d\theta} LL(X | \theta) = 0\]</span></p>
<div id="estimador-de-una-proporción" class="section level4" number="4.3.1.1">
<h4><span class="header-section-number">4.3.1.1</span> Estimador de una proporción</h4>
<p>La estimación de proporciones surge de forma natural en poblaciones Bernouilli cuya función de log-verosimilitud viene dada por:
<span class="math display">\[LL(X |\theta) = s*log(\theta) + (n-s)*log(1-\theta)\]</span>
Derivando e igualando a cero:
<span class="math display">\[\frac{d}{d\theta} LL(X | \theta) = \frac{s}{\theta}+\frac{-(n-s)}{1-\theta} = 0\]</span>
Despejando obtenemos:
<span class="math display">\[\hat{\theta} = \frac{s}{n}\]</span>
que es el estimador habitual para obtener la proporción muestral.</p>
</div>
<div id="estimador-de-una-media" class="section level4" number="4.3.1.2">
<h4><span class="header-section-number">4.3.1.2</span> Estimador de una media</h4>
<p>Si asumimos que la variable aleatoria es <span class="math inline">\(N(\mu,\sigma^2)\)</span> la función de log verosimilitud viene dada por:</p>
<p><span class="math display">\[LL(X |\mu,\sigma^2) = -\frac{n}{2}*log(2\pi\sigma^2)+\frac{nS^2 + n(\mu-\bar{X})^2}{2\sigma^2}\]</span></p>
<p>Si derivamos respecto de <span class="math inline">\(\mu\)</span> e igualamos a cero:</p>
<p><span class="math display">\[\frac{d}{d\mu}LL(X |\mu,\sigma^2) = -\frac{2n(\mu-\bar{X})}{2\sigma^2} = 0\]</span>
Despejando obtenemos el estimador para la media:
<span class="math display">\[\hat\mu = \bar X\]</span></p>
</div>
<div id="estimador-de-una-varianza" class="section level4" number="4.3.1.3">
<h4><span class="header-section-number">4.3.1.3</span> Estimador de una varianza</h4>
<p>De forma similar, derivando respecto de <span class="math inline">\(\sigma^2\)</span> e igualando a cero la función de log-verosimilitud tenemos que el estimador para la varianza viene dado por:
<span class="math display">\[\hat \sigma^2 = S^2\]</span></p>
<p>Podemos ver que en las situaciones habituales los estimadores de los parámetros poblacionales coinciden con las funciones que nos permiten obtener las medidas de localización y dispersión muestrales.</p>
<p>El problema con la estimación puntual es que únicamente nos da un valor posible para el parámetro poblacional pero sin ninguna medida del posible error que estamos cometiendo, dado que la estimación obtenida depende de la muestra seleccionada. Dos muestras distintas podrían dar dos estimaciones distintas y por tanto dos valores para el parámetro poblacional. Para introducir una medida del error cometido con la muestra seleccionada se utiliza los procedimiento de inferencia basados en intervalos de confianza, pero antes de pasar con ellos es necesario describir un poco más el comportamiento aleatorio de los estimadores que acabamos de obtener.</p>
</div>
</div>
<div id="distribución-en-el-muestreo" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Distribución en el muestreo</h3>
<p>Dado que todos los estimadores se construyen a partir de una colección de realizaciones aleatorias <span class="math inline">\(X_1,...X_n\)</span> de la variable aleatoria <span class="math inline">\(X\)</span>, resulta que dicho estimador es una nueva variable aleatoria (que toma valores según los datos observados de la muestra) y por tanto su distribución puede ser deducida a partir de las distribuciones de cada una de las <span class="math inline">\(X_i\)</span>, utilizando la función de verosimilitud. En algunos casos (variables discretas) será necesario utilizar el Teorema Central del Límite para determinar una forma aproximada de dicha distribución de probabilidad que nos permita realizar los procesos inferenciales sin demasiada complejidad matemática. La distribución de los estimadores se conoce con el nombre de <code>distribución en el muestreo</code></p>
<p>En este punto siguiente se muestran las distribuciones en el muestro para los estimadores obtenidos en este apartado. Se eliminan todos los desarrollos matemáticos y simplemente se muestran las distribuciones obtenidas.</p>
<div id="distribución-en-el-muestreo-de-una-media-poblacional-con-varianza-poblacional-conocida" class="section level4" number="4.3.2.1">
<h4><span class="header-section-number">4.3.2.1</span> Distribución en el muestreo de una media poblacional con varianza poblacional conocida</h4>
<p>Tenemos una población de <span class="math inline">\(N\)</span> sujetos sobre la que se desea estudiar una variable aleatoria de tipo continuo (<span class="math inline">\(X\)</span>) que sigue una distribución <span class="math inline">\(N(\mu,\sigma^2)\)</span> y cuyo parámetro de interés es la media (<span class="math inline">\(\mu\)</span>) pero donde conocemos el valor de <span class="math inline">\(\sigma^2\)</span>. Por la aplicación directa del Teorema Central del Límite la distribución en el muestreo de <span class="math inline">\(\bar X\)</span> viene dada por:
<span class="math display">\[\bar X \sim N\left(\mu,\frac{\sigma^2}{n}\right)\]</span>
y por tanto la variable tipificada tiene distribución Normal estándar, es decir:
<span class="math display">\[\frac{\bar X - \mu}{\sigma/\sqrt n} \sim N(0,1)\]</span></p>
</div>
<div id="distribución-en-el-muestreo-de-una-media-poblacional-con-varianza-poblacional-desconocida" class="section level4" number="4.3.2.2">
<h4><span class="header-section-number">4.3.2.2</span> Distribución en el muestreo de una media poblacional con varianza poblacional desconocida</h4>
<p>Cuando la varianza es desconocida también se puede obtener la distribución en el muestreo de la media muestral sin más que sustituir la varianza poblacional por un estimador. Tipificando tenemos que:
<span class="math display">\[T = \frac{\bar{X} - \mu}{S/\sqrt{n-1}} = \frac{\bar{X} - \mu}{S_q/\sqrt{n}}\]</span>
se distribuye según una distribución <span class="math inline">\(t\)</span> de Student con <span class="math inline">\(n-1\)</span> grados de libertad,
<span class="math display">\[ T \sim t_{n-1}\]</span></p>
</div>
<div id="distribución-en-el-muestreo-de-una-varianza-poblacional" class="section level4" number="4.3.2.3">
<h4><span class="header-section-number">4.3.2.3</span> Distribución en el muestreo de una varianza poblacional</h4>
<p>En la situación poblacional anterior la distribución en el muestreo de la varianza si consideramos la variable aleatoria:
<span class="math display">\[\chi^2 = \frac{nS^2}{\sigma^2} = \frac{(n-1)S_q^2}{\sigma^2}\]</span> que se distribuye según una distribución Chi cuadrado con <span class="math inline">\(n-1\)</span> grados de libertad,
<span class="math display">\[ \chi^2 \sim \chi^2_{n-1}\]</span></p>
<p>La obtención de esta distribución se hace a partir de la forma de la función de verosimilitud para una población Normal con ambos parámetros desconocidos.</p>
</div>
<div id="distribución-en-el-muestreo-de-una-proporción-poblacional" class="section level4" number="4.3.2.4">
<h4><span class="header-section-number">4.3.2.4</span> Distribución en el muestreo de una proporción poblacional</h4>
<p>Tenemos una población de <span class="math inline">\(N\)</span> sujetos sobre la que se desea estudiar una variable aleatoria de tipo discreto (<span class="math inline">\(X\)</span>) cuyo parámetro de interés es la proporción de sujetos (<span class="math inline">\(\theta\)</span>) que cumplen con cierta condición. En esta situación si obtenemos una muestra de tamaño <span class="math inline">\(n\)</span> de dicha variable <span class="math inline">\(X_1,...,X_n\)</span> (donde cada uno de ellos toma el valor 1 si cumple con la condición y = si no cumple), la proporción de éxito muestral (<span class="math inline">\(\hat{\theta}\)</span>) viene dada por:
<span class="math display">\[\hat{\theta} = \frac{\sum_{i=1}^n X_i}{n}\]</span></p>
<p>En esta situación la distribución en el muestreo para <span class="math inline">\(\hat{\theta}\)</span>, cuando <span class="math inline">\(n\)</span> es grande (<span class="math inline">\(n \geq 30\)</span>), viene dada por:
<span class="math display">\[\hat{\theta} \sim N \left(\theta, \frac{\theta (1-\theta)}{n}\right) \]</span>
de forma que la variable aleatoria tipificada <span class="math inline">\(Z\)</span> cumple que:</p>
<p><span class="math display">\[Z = \frac{\hat{\theta}-\theta}{\sqrt{\frac{\theta (1-\theta)}{n}}} \sim N(0,1)\]</span></p>
<p>La obtención de dichas distribuciones en el muestreo nos permite realizar cálculos de probabilidades sobre dichas cantidades aleatorias, con lo que resulta posible conocer cuál es la probabilidad de que la media muestral supere cierto valor, y por tanto, podamos tener una mayor certeza del verdadero valor del parámetro poblacional.</p>
</div>
<div id="error-estándar" class="section level4" number="4.3.2.5">
<h4><span class="header-section-number">4.3.2.5</span> Error estándar</h4>
<p>Para cuantificar la bondad de la estimación obtenida se define el <code>error estándar</code> (<span class="math inline">\(es()\)</span>) como la desviación típica de la distribución en el muestreo del estimador. De esta forma:</p>
<ul>
<li>Error estándar de la media en una población Normal con varianza conocida</li>
</ul>
<p><span class="math display">\[es(\bar X) = \frac{\sigma}{\sqrt n}\]</span></p>
<ul>
<li>Error estándar de la media en una población Normal con varianza desconocida</li>
</ul>
<p><span class="math display">\[es(\bar X) = \frac{S}{\sqrt{n-1}}\]</span></p>
<ul>
<li>Error estándar de una proporción en una población Bernouilli</li>
</ul>
<p><span class="math display">\[es(\hat{\theta}) = \sqrt{\frac{\hat{\theta} (1-\hat{\theta}))}{n}}\]</span></p>
</div>
</div>
<div id="estimación-por-intervalos-de-confianza" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Estimación por intervalos de confianza</h3>
<p>Un <code>intervalo de confianza</code> al nivel <span class="math inline">\(100*(1 - \alpha)\%\)</span> representa la confianza que tenemos en que el verdadero valor del parámetro de la población se encuentre contenido entre los limites de dicho intervalo, que se construye a partir de la información muestral y la distribución en el muestreo del estimador. Si tenemos un intervalo de confianza al 95%, es decir <span class="math inline">\(\alpha = 0.05\)</span>, lo que estamos indicando es que si obtuviéramos 100 muestras y calculáramos los 100 intervalos asociados, solo en 95 de ellos contendrían al verdadero valor del parámetro poblacional. Dado que habitualmente tomamos una única muestra debemos confiar en que el intervalo producido sea uno de los 95 que contiene al verdadero valor del parámetro poblacional. El valor de <span class="math inline">\(\alpha\)</span> se conoce como <code>significatividad</code>.</p>
<p>Supongamos que tenemos una población sobre la deseamos estudiar una variable aleatoria <span class="math inline">\(X\)</span> cuya función de distribución es conocida y viene caracterizada por el parámetro <span class="math inline">\(\theta\)</span>, <span class="math inline">\(f(X|\theta)\)</span>. Vamos a obtener una muestra de tamaño <span class="math inline">\(n\)</span>, <span class="math inline">\(X_1,...,X_n\)</span> y consideramos el estimador <span class="math inline">\(\hat\theta\)</span> de <span class="math inline">\(\theta\)</span> del que conocemos su distribución en el muestreo, <span class="math inline">\(f_n\)</span>,y podemos especificar su error estándar, <span class="math inline">\(es(\hat{\theta})\)</span>. Si fijamos el valor de <span class="math inline">\(\alpha\)</span> el intervalo de confianza para el parámetro poblacional viene dado por la expresión:</p>
<p><span class="math display">\[IC_{1-\alpha}(\theta) = (\hat{\theta} - q_{\alpha/2}*es(\hat{\theta}),\hat{\theta} + q_{1-\alpha/2}*es(\hat{\theta}))\]</span>
donde <span class="math inline">\(q_{\alpha/2}\)</span> y <span class="math inline">\(q_{1-\alpha/2}\)</span> son los cuantiles <span class="math inline">\(\alpha/2\)</span> y <span class="math inline">\(1-\alpha/2\)</span> de la distribución en el muestreo, es decir,
<span class="math display">\[P(\hat{\theta} \leq q_{\alpha/2}) = \alpha/2\]</span>
<span class="math display">\[P(\hat{\theta} \leq q_{1-\alpha/2}) = 1-\alpha/2\]</span></p>
<p>Si la distribución en el muestreo es simétrica <span class="math inline">\(q_{1-\alpha/2} = - q_{\alpha/2}\)</span></p>
<p>Antes de estudiar la forma explicita de los intervalos de confianza para una proporción, una media, y una varianza vamos a ver una herramienta de simulación que nos permite comprobar el funcionamiento de dichos intervalos. El funcionamiento de la aplicación es:</p>
<ul>
<li>Fijar valor del parámetro poblacional</li>
<li>Fijar el tamaño de la muestra</li>
<li>Establecer el límite de confianza</li>
<li>Establecer el número de muestras de trabajo y simularlas representando los intervalos de confianza obtenidos.</li>
<li>Podemos ver entonces cuantos de esos intervalos contienen al verdadero valor del parámetro.</li>
</ul>
<p><a href="https://istats.shinyapps.io/ExploreCoverage/">Acceder a la aplicación</a></p>
<div id="ic-para-una-proporción" class="section level4" number="4.3.3.1">
<h4><span class="header-section-number">4.3.3.1</span> IC para una proporción</h4>
<p>El intervalo de confianza al nivel <span class="math inline">\(100*(1 - \alpha)\%\)</span> para una proporción poblacional viene dado por:
<span class="math display">\[IC_{1-\alpha}(\theta) = \left(\hat{\theta} - q_{1-\alpha/2}*\sqrt{\frac{\hat{\theta} (1-\hat{\theta}))}{n}},\hat{\theta} + q_{1-\alpha/2}*\sqrt{\frac{\hat{\theta} (1-\hat{\theta}))}{n}}\right)\]</span>
donde <span class="math inline">\(q_{1-\alpha/2}\)</span> es el cuantil <span class="math inline">\(1-\alpha/2\)</span> de una distribución Normal estándar, <span class="math inline">\(\hat{\theta}\)</span> es la proporción muestral y <span class="math inline">\(n\)</span> es el tamaño muestral.</p>
</div>
<div id="ic-para-la-media" class="section level4" number="4.3.3.2">
<h4><span class="header-section-number">4.3.3.2</span> IC para la media</h4>
<p>El intervalo de confianza al nivel <span class="math inline">\(100*(1 - \alpha)\%\)</span> para la media de una población Normal con varianza desconocida viene dado por:</p>
<p><span class="math display">\[IC_{1-\alpha}(\mu) = \left(\bar{x} - q_{1-\alpha/2}*\frac{s}{\sqrt{n-1}},\bar{x} + q_{1-\alpha/2}*\frac{s}{\sqrt{n-1}}\right)\]</span>
donde <span class="math inline">\(q_{1-\alpha/2}\)</span> es el cuantil <span class="math inline">\(1-\alpha/2\)</span> de una distribución <span class="math inline">\(t\)</span> se Student con <span class="math inline">\(n-1\)</span> grados de libertad, <span class="math inline">\(\bar x\)</span> es la media muestral, <span class="math inline">\(s\)</span> es la desviación típica muestral, y <span class="math inline">\(n\)</span> es el tamaño de muestra.</p>
</div>
<div id="intervalo-de-confianza-para-la-varianza" class="section level4" number="4.3.3.3">
<h4><span class="header-section-number">4.3.3.3</span> Intervalo de confianza para la varianza</h4>
<p>El intervalo de confianza al nivel <span class="math inline">\(100*(1 - \alpha)\%\)</span> para la varianza de una población Normal viene dado por:</p>
<p><span class="math display">\[IC_{1-\alpha}(\sigma^2) = \left(\frac{(n-1)s^2}{q_{1-\alpha/2}}, \frac{(n-1)s^2}{q_{\alpha/2}}\right)\]</span>
donde <span class="math inline">\(q_{1-\alpha/2}\)</span> y <span class="math inline">\(q_{\alpha/2}\)</span> son los cuantiles <span class="math inline">\(1-\alpha/2\)</span> y <span class="math inline">\(\alpha/2\)</span> de una distribución <span class="math inline">\(Chi^2\)</span> con <span class="math inline">\(n-1\)</span> grados de libertad, <span class="math inline">\(s^2\)</span> es la varianza muestral, y <span class="math inline">\(n\)</span> es el tamaño de muestra.</p>
</div>
</div>
<div id="contraste-de-hipótesis" class="section level3" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Contraste de hipótesis</h3>
<p>Un procedimiento de contraste de hipótesis tiene por objetivo valorar la evidencia proporcionada por los datos a favor de alguna hipótesis planteada sobre el parámetro o parámetros que identifican a la población bajo estudio. En el caso más sencillo, imaginemos que tenemos un parámetro poblacional <span class="math inline">\(\theta\)</span> que puede tomar valores en el conjunto <span class="math inline">\(\Theta\)</span></p>
<p><em>Ejemplo: Estamos interesados en conocer si la proporción de alumnos que superan la asignatura de Estadística en la convocatoria de junio es mayor o igual al 50%. El parámetro de interés, <span class="math inline">\(\theta\)</span>, es entonces la proporción de aprobados en la convocatoria de junio, y el conjunto de posibles valores de dicho parámetro puede tomar valores entre 0 y 100. El contraste de interés viene dado por:</em></p>
<p><span class="math display">\[\theta \geq 0.5\]</span></p>
<p>Para resolver cualquier procedimiento de contraste debemos establecer dos subconjuntos disjuntos del espacio paramétrico, <span class="math inline">\(\Theta_0\)</span> y <span class="math inline">\(\Theta_1\)</span> cumpliendo que <span class="math inline">\(\Theta = \Theta_0 \cup \Theta_1\)</span>, con los posibles valores del parámetro de interés que denominamos hipótesis:</p>
<ul>
<li><strong>Hipótesis nula</strong>, que se denota por <span class="math inline">\(H_0\)</span>, y que generalmente expresa el valor o conjunto de valores del parámetro,<span class="math inline">\(\Theta_0\)</span>, que corresponde con la idea que deseamos verificar.</li>
<li><strong>Hipótesis alternativa</strong>, que se denota por <span class="math inline">\(H_a\)</span>, y que generalmente expresa el valor o conjunto de valores complementarios, <span class="math inline">\(\Theta_1\)</span>, a los dados en la hipótesis nula. Formalmente, el problema de contraste de hipótesis se plantea como:
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \in \Theta_0\\ H_a: &amp; \theta \in \Theta_1\end{array}\right.\]</span></li>
</ul>
<p>Estas hipótesis se deben establecer antes de obtener la información muestral ya que deben reflejar conocimiento previo sobre el parámetro poblacional de interés. La muestra recogida aportará las evidencias suficientes para rechazar o no rechazar la hipótesis nula planteada.</p>
<p><em>En nuestro ejemplo</em></p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \geq 0.5\\ H_a: &amp; \theta &lt; 0.5\end{array}\right.\]</span></p>
<div id="posibles-contrastes" class="section level4" number="4.3.4.1">
<h4><span class="header-section-number">4.3.4.1</span> Posibles contrastes</h4>
<p>Dada la estructura del procedimiento de contraste se plantean únicamente dos tipos de posibilidades:</p>
<ul>
<li><p><strong>Contraste bilateral:</strong> El conjunto de posibles valores del parámetro de interés establecidos en la hipótesis nula se concentra en un único valor, <span class="math inline">\(\theta_0\)</span>, es decir,
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta = \theta_0\\ H_a: &amp; \text{ no } \theta_0 \end{array}\right.\]</span></p></li>
<li><p><strong>Contraste unilateral:</strong> El conjunto de posibles valores del parámetro de interés establecidos en la hipótesis nula se concentra en un conjunto de valores dado por una desigualdad con respecto a <span class="math inline">\(\theta_0\)</span>, es decir,</p></li>
</ul>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \geq \theta_0\\ H_a: &amp; \text{ no } \theta_0 \end{array}\right.\]</span>
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \leq \theta_0\\ H_a: &amp; \text{ no } \theta_0 \end{array}\right.\]</span></p>
</div>
<div id="resolución-de-contraste" class="section level4" number="4.3.4.2">
<h4><span class="header-section-number">4.3.4.2</span> Resolución de contraste</h4>
<p>Para establecer evidencias a favor de una hipótesis u otra se debe:</p>
<ol style="list-style-type: decimal">
<li>Elegir un nivel de significación, <span class="math inline">\(\alpha\)</span>, que refleja el riesgo que tomamos cuando rechazamos la hipótesis nula o probabilidad de rechazar la hipótesis nula cuando es cierta, es decir:
<span class="math display">\[\alpha = P(\text{ Rechazar } H_0 | H_0 \text{ cierta})\]</span></li>
</ol>
<p>Normalmente se eligen valores pequeños, <span class="math inline">\(\alpha=0,1, 0.05, y 0.01\)</span> que resultan los equivalentes del 90%, 95%, y 99% al nivel de confianza en el proceso de estimación.</p>
<p><em>Ejemplo. Si tomamos una significación del 5%, tendremos una probabilidad de 0.05 de rechazar la hipótesis nula cuando en realidad es cierta.</em></p>
<ol start="2" style="list-style-type: decimal">
<li>Establecer estadístico de contraste (<span class="math inline">\(EC\)</span>) que nos permita, utilizando la información muestral, estudiar la compatibilidad de dicha información con la hipótesis nula planteada. La forma habitual suele ser:</li>
</ol>
<p><span class="math display">\[EC = \frac{\theta - \hat{\theta}}{es(\hat{\theta})}\]</span>
donde <span class="math inline">\(\hat{\theta}\)</span> es un estimador puntual del parámetro poblacional y <span class="math inline">\(es(\hat{\theta})\)</span> es una medida del error estándar que cometemos con el estimador utilizado.</p>
<ol start="3" style="list-style-type: decimal">
<li>Para decidir sobre el contraste planteado utilizaremos el <span class="math inline">\(p-valor\)</span>, que representa la probabilidad de que el valor del EC sea superior al valor de dicho estadístico evaluado en los datos muestrales, <span class="math inline">\(EC_{obs}\)</span>,atendiendo a la distribución en el muestreo, es decir,</li>
</ol>
<p><span class="math display">\[p-valor = P(EC \geq EC_{obs})\]</span>
Para tomar una decisión sobre el contraste miramos si el p-valor obtenido y concluimos que:</p>
<ul>
<li>Si <span class="math inline">\(p-valor &lt; \alpha\)</span>, tenemos evidencias estadísticas suficientes para rechazar la hipótesis nula a favor de la hipótesis alternativa.</li>
<li>Si <span class="math inline">\(p-valor &gt; \alpha\)</span>, no tenemos evidencias estadísticas suficientes para rechazar la hipótesis nula.</li>
</ul>
<p>A continuación vemos como ampliar el procedimiento de contraste para una proporción y una media. El proceso de contraste sobre una varianza no suele tener interés práctico ya que resulta más habitual obtener un intervalo de confianza. Como veremos en el tema siguiente, si que resulta relevante el proceso de contraste cuando se involucran dos poblaciones y estamos interesados en comparar la variabilidad de ambas.</p>
</div>
<div id="una-proporción" class="section level4" number="4.3.4.3">
<h4><span class="header-section-number">4.3.4.3</span> Una proporción</h4>
<p>Tenemos una población de tipo Bernouilli que viene especificada a partir de la proporción de sujetos que alcanzan el “éxito,” <span class="math inline">\(\theta\)</span>, y una estimación de dicho parámetro dada por <span class="math inline">\(\hat{\theta}\)</span>. Anteriormente ya hemos visto que para una muestra de tamaño <span class="math inline">\(n\)</span> el error estándar viene dado por:</p>
<p><span class="math display">\[es(\hat{\theta}) = \sqrt{\frac{\hat{\theta} (1-\hat{\theta}))}{n}}.\]</span></p>
<p>Tanto para el contraste unilateral como el bilateral el estadístico de contraste viene dado por:
<span class="math display">\[EC = \frac{\theta - \hat{\theta}}{\sqrt{\frac{\hat{\theta} (1-\hat{\theta}))}{n}}}\]</span>
cuya distribución en el muestreo es <span class="math inline">\(N(0,1)\)</span>. Dicho estadístico valora lo cerca que queda el estimador respecto del valor poblacional teniendo en cuenta el error cometido en el proceso de estimación.</p>
<p><em>Ejemplo. Se está estudiando el efecto de los rayos X sobre la viabilidad huevo-larva en Tribolium casteneum. Se plantean tres situaciones: a) la proporción de viabilidad es del 50%, b) la proporción de viabilidad es superior al 60%, c) la proporción de viabilidad es inferior al 55%. Los contrastes asociados con cada situación son:</em>
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta = 0.5\\ H_a: &amp;  \theta \neq 0,5 \end{array}\right.\]</span>
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \geq 0.6\\ H_a: &amp; \theta &lt; 0.6 \end{array}\right.\]</span>
<span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta \leq 0.55\\ H_a: &amp; \theta &gt; 0.55 \end{array}\right.\]</span></p>
<p><em>Para verificar dichios contarstes se irradiaron 1000 huevos de los que resultaron 572 larvas.</em></p>
<blockquote>
<p>Para resolver contrastes en estas situaciones utiliamos la función <code>prop.test()</code></p>
</blockquote>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="inferencia-básica.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Situación 1</span></span>
<span id="cb147-2"><a href="inferencia-básica.html#cb147-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb147-3"><a href="inferencia-básica.html#cb147-3" aria-hidden="true" tabindex="-1"></a>larvas <span class="ot">&lt;-</span> <span class="dv">572</span></span>
<span id="cb147-4"><a href="inferencia-básica.html#cb147-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos fijar el valor del contraste, el tipo (two.sided), y el nivel de significación o su análogo como el nivel de confianza</span></span>
<span id="cb147-5"><a href="inferencia-básica.html#cb147-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(larvas, n, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  larvas out of n
## X-squared = 20.449, df = 1, p-value = 6.124e-06
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.5406126 0.6028273
## sample estimates:
##     p 
## 0.572</code></pre>
<p><em>El p-valor resultante es 6.124e-06 que resulta inferior al nivel de significación prefijado de 0.05. Por lo tanto hay evidencias para rechazar la hipótesis nula y concluir que la proporción de viabilidad una vez irradiamos los huevos con rayos X es distinta del 50%. </em></p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="inferencia-básica.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Situación 2</span></span>
<span id="cb149-2"><a href="inferencia-básica.html#cb149-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb149-3"><a href="inferencia-básica.html#cb149-3" aria-hidden="true" tabindex="-1"></a>larvas <span class="ot">&lt;-</span> <span class="dv">572</span></span>
<span id="cb149-4"><a href="inferencia-básica.html#cb149-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos fijar el valor del contraste, el tipo (two.sided), y el nivel de significación o su análogo como el nivel de confianza</span></span>
<span id="cb149-5"><a href="inferencia-básica.html#cb149-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(larvas, n, <span class="at">p =</span> <span class="fl">0.6</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  larvas out of n
## X-squared = 3.151, df = 1, p-value = 0.03794
## alternative hypothesis: true p is less than 0.6
## 95 percent confidence interval:
##  0.0000000 0.5980029
## sample estimates:
##     p 
## 0.572</code></pre>
<p><em>El p-valor resultante es 0.03794 que resulta inferior al nivel de significación prefijado de 0.05. Por lo tanto hay evidencias para rechazar la hipótesis nula y concluir que la proporción de viabilidad una vez irradiamos los huevos es mayor o igual al 60%. </em></p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="inferencia-básica.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Situación 2</span></span>
<span id="cb151-2"><a href="inferencia-básica.html#cb151-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb151-3"><a href="inferencia-básica.html#cb151-3" aria-hidden="true" tabindex="-1"></a>larvas <span class="ot">&lt;-</span> <span class="dv">572</span></span>
<span id="cb151-4"><a href="inferencia-básica.html#cb151-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos fijar el valor del contraste, el tipo (two.sided), y el nivel de significación o su análogo como el nivel de confianza</span></span>
<span id="cb151-5"><a href="inferencia-básica.html#cb151-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(larvas, n, <span class="at">p =</span> <span class="fl">0.55</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  larvas out of n
## X-squared = 1.8677, df = 1, p-value = 0.08587
## alternative hypothesis: true p is greater than 0.55
## 95 percent confidence interval:
##  0.545601 1.000000
## sample estimates:
##     p 
## 0.572</code></pre>
<p><em>El p-valor resultante es 0.08587 que resulta superior al nivel de significación prefijado de 0.05. Por lo tanto hay evidencias para no rechazar la hipótesis nula y concluir que la proporción de viabilidad una vez irradiamos los huevos puede ser menor o igual al 55%. </em></p>
</div>
<div id="una-media" class="section level4" number="4.3.4.4">
<h4><span class="header-section-number">4.3.4.4</span> Una media</h4>
<p>Tenemos una población Normal que viene especificada a partir de la media (<span class="math inline">\(\mu\)</span>) y varianza (<span class="math inline">\(\sigma^2\)</span>). Por el momento estamos interesados en los procedimientos de contraste sobre la media cuando desconocemos el valor de la varianza poblacional. Tomamos los estimadores habituales <span class="math inline">\(\bar X\)</span>, <span class="math inline">\(S^2\)</span>, y consideramos el error estándar:
<span class="math display">\[es(\bar X) = \frac{s}{\sqrt{n-1}}.\]</span>
Tanto para el contraste unilateral como el bilateral el estadístico de contraste viene dado por:
<span class="math display">\[EC = \frac{\mu - \bar X}{\frac{s}{\sqrt{n-1}}}\]</span>
cuya distribución en el muestreo es una <span class="math inline">\(t\)</span> de Student con n-1 grados de libertad.</p>
<p><em>Ejemplo. La concentración media de dióxido de carbono en el aire en una cierta zona no es habitualmente mayor que 335 ppmv (partes por millon en volumen). Se sospecha que esta concentración es mayor en la capa de aire más próxima a la superficie. Los investigadores quieren comprobar si la concentración en la superficie es mayor o igual a dicho valor con una significación de 0.05. Se plantea el contraste:</em></p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \mu \geq 335\\ H_a: &amp; \mu &lt; 335 \end{array}\right.\]</span>
<em>Para tratar de ratificar su hipótesis Se ha analizado el aire en 20 puntos elegidos aleatoriamente a una misma altura cerca del suelo, resultando los siguientes datos: 332, 320, 312, 270, 330, 354, 356, 310, 341, 313, 223, 224, 305, 321, 325, 333, 332, 345, 312, 331.</em></p>
<blockquote>
<p>Para resolver este contraste utilizamos la función <code>t.test()</code></p>
</blockquote>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="inferencia-básica.html#cb153-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">332</span>, <span class="dv">320</span>, <span class="dv">312</span>, <span class="dv">270</span>, <span class="dv">330</span>, <span class="dv">354</span>, <span class="dv">356</span>, <span class="dv">310</span>, <span class="dv">341</span>, <span class="dv">313</span>, <span class="dv">223</span>, <span class="dv">224</span>, <span class="dv">305</span>, <span class="dv">321</span>, <span class="dv">325</span>, <span class="dv">333</span>, <span class="dv">332</span>, <span class="dv">345</span>, <span class="dv">312</span>, <span class="dv">331</span>)</span>
<span id="cb153-2"><a href="inferencia-básica.html#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos fijar el valor del contraste, el tipo (two.sided), y el nivel de significación o su análogo como el nivel de confianza</span></span>
<span id="cb153-3"><a href="inferencia-básica.html#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(datos, <span class="at">mu =</span> <span class="dv">335</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  datos
## t = -2.5219, df = 19, p-value = 0.01038
## alternative hypothesis: true mean is less than 335
## 95 percent confidence interval:
##      -Inf 328.5403
## sample estimates:
## mean of x 
##    314.45</code></pre>
<p><em>El p-valor resultante es 0.01038 que resulta inferior al nivel de significación prefijado de 0.05. Por lo tanto hay evidencias para rechazar la hipótesis nula y concluir que la media del nivel de dióxido de carbono en la capa de aire más cercana a la superficie es menor a 335 ppmv.</em></p>
</div>
</div>
</div>
<div id="inferencia-para-dos-poblaciones" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Inferencia para dos poblaciones</h2>
<p>En este sección completamos el estudio inferencial visto en los puntos anteriores. Más concretamente se muestra el análisis inferencial para la comparación de dos proporciones o dos medias. En la situación de la comparación de dos medias veremos también la influencia que tiene el estudio de las varianzas de ambas poblaciones. No se presentan todas las formulaciones y distribuciones asociadas con estos análisis sino que se presenta directamente la forma de resolverlos. se pueden consultar los desarrollos estadísticos en cualquier libro de estadística básica.</p>
<p><strong>Poblaciones Binomiales</strong> Sean dos poblaciones sobre las que se desea estudiar una misma característica de interés de tipo discreto (1 = éxito; 0 = fracaso), que identificamos por <span class="math inline">\(X_{P1}\)</span> y <span class="math inline">\(X_{P2}\)</span> respectivamente. El parámetro de interés en cada población es la proporción de éxito, <span class="math inline">\(\theta_1\)</span> y <span class="math inline">\(\theta_2\)</span> respectivamente, pero el interés inferencial principal es la comparación de <span class="math inline">\(\theta_1\)</span> y <span class="math inline">\(\theta_2\)</span>, es decir, comprobar si la proporción de éxito en la población 1 es comparable con la proporción de éxito en la población 2. Para realizar dicha comparación se utiliza el parámetro que viene dado por la diferencia de proporciones de éxito:
<span class="math display">\[\theta_1 - \theta_2\]</span></p>
<p>Si las proporciones son iguales la diferencia debería estar próximo a cero, mientras que si son distintas la diferencia sería estadísticamente diferente a cero.</p>
<p><strong>Poblaciones Normales</strong> Sean dos poblaciones normales sobre las que se desea estudiar una misma característica de interés de tipo continuo que identificamos por <span class="math inline">\(X_{P1}\)</span> y <span class="math inline">\(X_{P2}\)</span> respectivamente. Cada población viene caracterizada por su media y varianza, es decir,
<span class="math display">\[X_{P1} \sim N(\mu_1,\sigma^2_1) \text{    ;  }  X_{P2} \sim N(\mu_2,\sigma^2_2)\]</span>
En este caso el proceso inferencial se centras en todos los parámetros, medias y varianzas, pero habitualmente el objetivo inferencial principal se centra en comprobar si las medias de ambas poblaciones pueden considerarse iguales o diferentes. Por tanto, el parámetro de interés es la diferencia de medias poblacionales:
<span class="math display">\[\mu_1 - \mu_2\]</span>
Como ocurre con las proporciones, se considera que las medias son iguales cuando la diferencia de las medias es estadísticamente cero. Sin embargo, para poder realizar dicho estudio es necesario conocer en primer lugar si las varianzas de ambas poblaciones pueden considerarse iguales o distintas. En función del resultado de dicha comparación se deberá utilizar un proceso inferencial diferente para la comparación de medias. Dado que las varianzas siempre son positivas el parámetro de interés para la comparación de varianzas viene dado por su cociente:
<span class="math display">\[\frac{\sigma^2_1}{\sigma^2_1}\]</span></p>
</div>
<div id="inferencia-para-dos-proporciones" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Inferencia para dos proporciones</h2>
<p>Dada una muestra aleatoria en cada una de las poblaciones de interés de tamaños <span class="math inline">\(n_1\)</span> y <span class="math inline">\(n_2\)</span>, utilizamos los estimadores habituales de la proporción poblacional dados por las proporciones muestrales <span class="math inline">\(\hat{\theta}_1\)</span> y <span class="math inline">\(\hat{\theta}_2\)</span>. Como ya hemos dicho el parámetro objetivo en esta situación es la diferencia de proporciones poblacionales.</p>
<p><strong>Ejemplo</strong>. La angina de pecho es una afección cardíaca en la que el paciente sufre ataque períodicos de dolor. En un estudio para analizar la efectividad de una nueva droga para prevenir dichos ataques se han seleccionado dos grupos de sujetos. Al primero de ellos se les dará la nueva droga mientras que al otro se les dará el tratamiento estándar. Los resultados obtenidos después de un periodo de 28 semanas viene dados en la tabla siguiente:</p>
<table>
<thead>
<tr class="header">
<th>Estado / Tratamiento</th>
<th>Droga nueva</th>
<th>Droga antigua</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sin angina</td>
<td>44</td>
<td>19</td>
</tr>
<tr class="even">
<td>Con angina</td>
<td>116</td>
<td>128</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>160</td>
<td>147</td>
</tr>
</tbody>
</table>
<p>Se está interesado en conocer con una confianza del 90% (significación de 0.1) si la porporción de pacientes mejorados con la nueva droga es diferente con respecto a la droga antigua.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="inferencia-básica.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># carga de datos </span></span>
<span id="cb155-2"><a href="inferencia-básica.html#cb155-2" aria-hidden="true" tabindex="-1"></a>muestra <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">160</span>,<span class="dv">147</span>) </span>
<span id="cb155-3"><a href="inferencia-básica.html#cb155-3" aria-hidden="true" tabindex="-1"></a>mejoras <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">44</span>,<span class="dv">19</span>) </span>
<span id="cb155-4"><a href="inferencia-básica.html#cb155-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla </span></span>
<span id="cb155-5"><a href="inferencia-básica.html#cb155-5" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mejoras, muestra)</span>
<span id="cb155-6"><a href="inferencia-básica.html#cb155-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;mejoras&quot;</span>,<span class="st">&quot;muestra&quot;</span>)</span>
<span id="cb155-7"><a href="inferencia-básica.html#cb155-7" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-6">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-6">Tabla 4.1: </span> </caption><col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">mejoras</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">muestra</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">44</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">160</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">19</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">147</td></tr>
</table>

<div id="estimador-puntual" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Estimador puntual</h3>
<p>El estimador puntual de la diferencia de proporciones poblacionales se consigue partir de los estimadores puntuales de cada una de las proporciones de éxito muestrales.</p>
<p>Para los datos de nuestro ejemplo, si la población 1 identifica a los usjetos que toman la nueva droga y la pobalción 2 a los que toman la droga antigua, tendríamos:
<span class="math inline">\(\widehat{\theta_1 - \theta_2} = \widehat{\theta_1} - \widehat{\theta_2} = \frac{44}{160} - \frac{19}{147} = 0.1457\)</span></p>
<p>Se observa una diferencia en la mejora de los sujetos del 14.57% de los que toman la droga nueva frente a los que toman la droga estándar.</p>
</div>
<div id="estimador-por-intervalos-de-confianza" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Estimador por intervalos de confianza</h3>
<p>Para obtener el intervalo de confianza para la diferencia de proporciones utilizamos la función <code>prop.test()</code>. Esta función también nos permite realizar el correspondiente contarte pero por le momento solo pediremos los resultados referidos al intervalo de confianza.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="inferencia-básica.html#cb156-1" aria-hidden="true" tabindex="-1"></a>analisis <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(mejoras,muestra,<span class="at">conf.level =</span> <span class="fl">0.90</span>)</span>
<span id="cb156-2"><a href="inferencia-básica.html#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confianza</span></span>
<span id="cb156-3"><a href="inferencia-básica.html#cb156-3" aria-hidden="true" tabindex="-1"></a>analisis<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.0654468 0.2260498
## attr(,&quot;conf.level&quot;)
## [1] 0.9</code></pre>
<p>Para los datos de nuestro ejemplo el intervalo de confianza al 90% indica que la diferencia de proporciones de mejora entre los que usan la droga nueva frente a os que usan la droga estándar se sitúa entre el 6.5% y el 22.6%.</p>
</div>
<div id="contraste-de-hipótesis-1" class="section level3" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Contraste de hipótesis</h3>
<p>El contraste habitual en esta situación viene dado por:</p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \theta_1 = \theta_2\\ H_a: &amp; \theta_1 \neq \theta_2 \end{array}\right.\]</span>
donde estamos interesados en verificar si las proporciones de éxito poblacionales pueden considerarse iguales o distintas.</p>
<p>Para los datos de nuestro ejemplo tenemos:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="inferencia-básica.html#cb158-1" aria-hidden="true" tabindex="-1"></a>analisis <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(mejoras,muestra,<span class="at">conf.level =</span> <span class="fl">0.90</span>)</span>
<span id="cb158-2"><a href="inferencia-básica.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultados completos</span></span>
<span id="cb158-3"><a href="inferencia-básica.html#cb158-3" aria-hidden="true" tabindex="-1"></a>analisis</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  mejoras out of muestra
## X-squared = 9.1046, df = 1, p-value = 0.00255
## alternative hypothesis: two.sided
## 90 percent confidence interval:
##  0.0654468 0.2260498
## sample estimates:
##    prop 1    prop 2 
## 0.2750000 0.1292517</code></pre>
<p>Dado que el pvalor obtenido (0.00255) es inferior al nivel de siginificación prefijado (0.1) hay eviedencias estadísticas para rechazar la hipótesis nula, es decir, hay evidendaicas para concluir que las proporciones de mejora con mabsa drogas son distintas. Además el intervalo de confianza ya nos indicaba qye dicha mejoría era a favor de la droga nueva con los valores obtenidos en el aprtado anterior</p>
</div>
</div>
<div id="inferencia-para-dos-medias" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Inferencia para dos medias</h2>
<p>Los problemas de inferencia asociados con la comparación de dos medias poblacionales para variables Normales presentan diferentes situaciones:</p>
<ul>
<li>Estudio de dos poblaciones independientes con variabilidades iguales</li>
<li>Estudio de dos poblaciones independientes con variabilidades distintas</li>
<li>Estudio de la evolución de una población (medidas antes - después)</li>
</ul>
<p>A continuación se detalla como realizar el análisis de cada uno de ellos, pero antes de pasar con ellos debemos estudiar el problema de como comparar las variabilidades en dos poblaciones independientes. Presentamos en primer lugar los diferentes ejemplos de trabajo.</p>
<p><strong>Ejemplo 1</strong>. Para realizar un estudio de la concentración de una hormona en una solución vamos a utilizar dos métodos. Disponemos de 10 dosis preparadas en el laboratorio y medimos la concentración de cada una con los dos métodos. Se obtienen los siguientes resultados:</p>
<table>
<thead>
<tr class="header">
<th>Dosis</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Método A</td>
<td>10.7</td>
<td>11.2</td>
<td>15.3</td>
<td>14.9</td>
<td>13.9</td>
<td>15</td>
<td>15.6</td>
<td>15.7</td>
<td>14.3</td>
<td>10.8</td>
</tr>
<tr class="even">
<td>Método B</td>
<td>11.1</td>
<td>11.4</td>
<td>15</td>
<td>15.1</td>
<td>14.3</td>
<td>15.4</td>
<td>15.4</td>
<td>16</td>
<td>14.3</td>
<td>11.2</td>
</tr>
</tbody>
</table>
<p>Se desea realizar el estudio inferencial con una confianza del 95%.</p>
<p><strong>Ejemplo 2</strong>. Una compañía contrata 10 tubos con filamentos del tipo A y 12 tubos con filamentos del tipo B. Las duraciones medias observadas se muestran en la siguiente tabla:</p>
<table>
<thead>
<tr class="header">
<th>Tipo/Duración</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
<th>11</th>
<th>12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>1614</td>
<td>1094</td>
<td>1293</td>
<td>1643</td>
<td>1466</td>
<td>1270</td>
<td>1340</td>
<td>1380</td>
<td>1081</td>
<td>1497</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>B</td>
<td>1383</td>
<td>1138</td>
<td>920</td>
<td>1143</td>
<td>1017</td>
<td>961</td>
<td>1627</td>
<td>821</td>
<td>1711</td>
<td>865</td>
<td>1662</td>
<td>1698</td>
</tr>
</tbody>
</table>
<p>Se desea realizar el estudio inferencial con una confianza del 90%.</p>
<p><strong>Ejemplo 3</strong>. En una unidad del sueño se está probando con un nuevo somnífero. Para comprobar su eficacia se toman 10 individuos al azar. Un día no se les suministra el somnífero y se les anota el número de horas de sueño, al día siguiente se les suministra y se vuelve a comprobar las horas de sueño. Los resultados entes y después del tratamiento han sido los siguientes:</p>
<table>
<thead>
<tr class="header">
<th>Instante/Sujeto</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Antes</td>
<td>7.3</td>
<td>8.2</td>
<td>6.3</td>
<td>5.2</td>
<td>6.9</td>
<td>5.8</td>
<td>5.3</td>
<td>7.1</td>
<td>6.9</td>
<td>8.1</td>
</tr>
<tr class="even">
<td>Después</td>
<td>8.2</td>
<td>7.9</td>
<td>6.4</td>
<td>5.1</td>
<td>7.1</td>
<td>6.3</td>
<td>5.9</td>
<td>8.2</td>
<td>7.1</td>
<td>7.7</td>
</tr>
</tbody>
</table>
<p>Se desea realizar el estudio inferencial con una confianza del 90%.</p>
<div id="análisis-de-dos-varianzas-poblacionales" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Análisis de dos varianzas poblacionales</h3>
<p>Supongamos que tenemos dos poblaciones Normales y que deseamos comprobar si la variabilidad en ambas poblaciones pueden considerarse estadísticamente iguales o distintas. Como ya vimos en la introducción este problema se reduce a la comparación de ambas varianzas a través del cociente de ambas. Para resolver este problema utilizamos la función <code>var.test()</code>. El contraste utilizado es:</p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \frac{\sigma^2_1}{\sigma^2_2} = 1\\ H_a: &amp; \frac{\sigma^2_1}{\sigma^2_2} \neq 1 \end{array}\right.\]</span></p>
<p>Para los datos del ejemplo 1</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="inferencia-básica.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb160-2"><a href="inferencia-básica.html#cb160-2" aria-hidden="true" tabindex="-1"></a>MetodoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.7</span>, <span class="fl">11.2</span>, <span class="fl">15.3</span>, <span class="fl">14.9</span>, <span class="fl">13.9</span>, <span class="dv">15</span>, <span class="fl">15.6</span>, <span class="fl">15.7</span>, <span class="fl">14.3</span>, <span class="fl">10.8</span>)</span>
<span id="cb160-3"><a href="inferencia-básica.html#cb160-3" aria-hidden="true" tabindex="-1"></a>MetodoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">11.1</span>, <span class="fl">11.4</span>, <span class="dv">15</span>, <span class="fl">15.1</span>, <span class="fl">14.3</span>, <span class="fl">15.4</span>, <span class="fl">15.4</span>, <span class="dv">16</span>, <span class="fl">14.3</span>, <span class="fl">11.2</span>)</span>
<span id="cb160-4"><a href="inferencia-básica.html#cb160-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(MetodoA, MetodoB, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  MetodoA and MetodoB
## F = 1.1229, num df = 9, denom df = 9, p-value = 0.8657
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2789187 4.5208902
## sample estimates:
## ratio of variances 
##           1.122925</code></pre>
<p>Dado que el pvalor resultante es superior a la significatividad prefijada, tenemos evidencias estadísticas para no rechazar la hipótesis nula, y por tanto concluir que ambas varianzas no pueden considerarse distintas.</p>
<p>Para los datos del ejemplo 2</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="inferencia-básica.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb162-2"><a href="inferencia-básica.html#cb162-2" aria-hidden="true" tabindex="-1"></a>TipoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1614</span>,<span class="dv">1094</span>,<span class="dv">1293</span>,<span class="dv">1643</span>,<span class="dv">1466</span>,<span class="dv">1270</span>,<span class="dv">1340</span>,<span class="dv">1380</span>,<span class="dv">1081</span>,<span class="dv">1497</span>)</span>
<span id="cb162-3"><a href="inferencia-básica.html#cb162-3" aria-hidden="true" tabindex="-1"></a>TipoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1383</span>,<span class="dv">1138</span>,<span class="dv">920</span>,<span class="dv">1143</span>,<span class="dv">1017</span>,<span class="dv">961</span>,<span class="dv">1627</span>,<span class="dv">821</span>,<span class="dv">1711</span>,<span class="dv">865</span>,<span class="dv">1662</span>,<span class="dv">1698</span>)</span>
<span id="cb162-4"><a href="inferencia-básica.html#cb162-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(TipoA, TipoB, <span class="at">conf.level =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  TipoA and TipoB
## F = 0.3052, num df = 9, denom df = 11, p-value = 0.08543
## alternative hypothesis: true ratio of variances is not equal to 1
## 90 percent confidence interval:
##  0.1053789 0.9468807
## sample estimates:
## ratio of variances 
##          0.3052007</code></pre>
<p>Puesto que el pvalor es inferior a la significatividad prefijada podemos concluir que hya evidencias estad´sitivas apra concluir que las varaibilidades en ambas poblaciones pueden considerarse distintas.</p>
<blockquote>
<p>En todos los análisis inferenciales asociados con la comparación de dos medias utilizamos la función <code>t.test()</code>, aunque con difrentes opciones en función de que las varianzas sean iguales o no, o de que las muestras sean independientes o no.*</p>
</blockquote>
</div>
<div id="dos-medias-para-poblaciones-independientes-con-varianzas-iguales" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Dos medias para poblaciones independientes con varianzas iguales</h3>
<p>El contraste de hipótesis para esta situación viene dado por:</p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \mu_1 = \mu_2\\ H_a: &amp; \mu_1 \neq \mu_2 \end{array}\right.\]</span></p>
<p>Utilizamos los datos del ejemplo 1, ya que como hemos visto anteriormente las varianzas de ambas pobalciones puden considerarse iguales</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="inferencia-básica.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb164-2"><a href="inferencia-básica.html#cb164-2" aria-hidden="true" tabindex="-1"></a>MetodoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.7</span>, <span class="fl">11.2</span>, <span class="fl">15.3</span>, <span class="fl">14.9</span>, <span class="fl">13.9</span>, <span class="dv">15</span>, <span class="fl">15.6</span>, <span class="fl">15.7</span>, <span class="fl">14.3</span>, <span class="fl">10.8</span>)</span>
<span id="cb164-3"><a href="inferencia-básica.html#cb164-3" aria-hidden="true" tabindex="-1"></a>MetodoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">11.1</span>, <span class="fl">11.4</span>, <span class="dv">15</span>, <span class="fl">15.1</span>, <span class="fl">14.3</span>, <span class="fl">15.4</span>, <span class="fl">15.4</span>, <span class="dv">16</span>, <span class="fl">14.3</span>, <span class="fl">11.2</span>)</span>
<span id="cb164-4"><a href="inferencia-básica.html#cb164-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(MetodoA, MetodoB, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  MetodoA and MetodoB
## t = -0.20323, df = 18, p-value = 0.8412
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.040763  1.680763
## sample estimates:
## mean of x mean of y 
##     13.74     13.92</code></pre>
<p>Dado que el pavalor es superior a la significatividad prefijada, hay evidencias estadísticas para concluir que las medias de concentración con ambos métodos pueden considerarse iguales.</p>
</div>
<div id="dos-medias-para-poblaciones-independientes-con-varianzas-distintas" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> Dos medias para poblaciones independientes con varianzas distintas</h3>
<p>El constaste de hipótesis en esta situación es el mismo que en el punto anterior.</p>
<p>Utilizamos los datos del ejemplo 2, ya que como hemos visto anteriormente las varianzas de ambas pobalciones puden considerarse distintas</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="inferencia-básica.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb166-2"><a href="inferencia-básica.html#cb166-2" aria-hidden="true" tabindex="-1"></a>TipoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1614</span>,<span class="dv">1094</span>,<span class="dv">1293</span>,<span class="dv">1643</span>,<span class="dv">1466</span>,<span class="dv">1270</span>,<span class="dv">1340</span>,<span class="dv">1380</span>,<span class="dv">1081</span>,<span class="dv">1497</span>)</span>
<span id="cb166-3"><a href="inferencia-básica.html#cb166-3" aria-hidden="true" tabindex="-1"></a>TipoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1383</span>,<span class="dv">1138</span>,<span class="dv">920</span>,<span class="dv">1143</span>,<span class="dv">1017</span>,<span class="dv">961</span>,<span class="dv">1627</span>,<span class="dv">821</span>,<span class="dv">1711</span>,<span class="dv">865</span>,<span class="dv">1662</span>,<span class="dv">1698</span>)</span>
<span id="cb166-4"><a href="inferencia-básica.html#cb166-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(TipoA, TipoB, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  TipoA and TipoB
## t = 0.98508, df = 20, p-value = 0.3364
## alternative hypothesis: true difference in means is not equal to 0
## 90 percent confidence interval:
##  -91.82747 336.42747
## sample estimates:
## mean of x mean of y 
##    1367.8    1245.5</code></pre>
<p>Dado que el pvalor es superior a la significatividad prefijada, hay evidencias estadísticas para concluir que las medias de duración de los filamentos en ambos tipos pueden considerarse iguales.</p>
</div>
<div id="dos-medias-para-poblaciones-emparejadas" class="section level3" number="4.6.4">
<h3><span class="header-section-number">4.6.4</span> Dos medias para poblaciones emparejadas</h3>
<p>Es muy habitual que en ciertas situaciones experimentales nos encontramos que queremos estudiar la evolución (medidas antes -después) de un grupo de sujetos después de ser sometidos a cierta prueba experimental. En esta caso no tenemos dos poblaciones independientes sino sólo una que medimos en dos ocasiones. Por tanto, los procedimientos anteriores tienen que ser modificados para tener en cuenta esta situación. El constaste de hipótesis para esta situación viene dado por:</p>
<p><span class="math display">\[\left\{\begin{array}{ll} H_0: &amp; \mu_{antes} = \mu_{despues}\\ H_a: &amp; \mu_{antes} \neq \mu_{despues} \end{array}\right.\]</span></p>
<p>De nuevo podemos utilizar la función <code>t.test()</code> con el parámetro <code>paired</code>.</p>
<p>Utilizamos los datos del ejemplo 3, donde tenemos una única muestra de sujetos</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="inferencia-básica.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb168-2"><a href="inferencia-básica.html#cb168-2" aria-hidden="true" tabindex="-1"></a>antes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">7.3</span>,<span class="fl">8.2</span>,<span class="fl">6.3</span>,<span class="fl">5.2</span>,<span class="fl">6.9</span>,<span class="fl">5.8</span>,<span class="fl">5.3</span>,<span class="fl">7.1</span>,<span class="fl">6.9</span>,<span class="fl">8.1</span>)</span>
<span id="cb168-3"><a href="inferencia-básica.html#cb168-3" aria-hidden="true" tabindex="-1"></a>despues <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">8.2</span>,<span class="fl">7.9</span>,<span class="fl">6.4</span>,<span class="fl">5.1</span>,<span class="fl">7.1</span>,<span class="fl">6.3</span>,<span class="fl">5.9</span>,<span class="fl">8.2</span>,<span class="fl">7.1</span>,<span class="fl">7.7</span>)</span>
<span id="cb168-4"><a href="inferencia-básica.html#cb168-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(antes, despues, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  antes and despues
## t = -1.7925, df = 9, p-value = 0.1066
## alternative hypothesis: true difference in means is not equal to 0
## 90 percent confidence interval:
##  -0.566341394  0.006341394
## sample estimates:
## mean of the differences 
##                   -0.28</code></pre>
<p>Dado que el pvalor es superior a la significatividad prefijada, hay evidencias estadísticas para concluir que las horas medias de sueño antes y después de tomar el somnifero no pueden considerarse estadísticamente distintas.</p>
</div>
</div>
<div id="procedimientos-no-paramétricos" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Procedimientos no paramétricos</h2>
<p>Todos los procedimientos de inferencia sobre dos medias se basan en la suposición de que las variables sobre las que estamos trabajando se puede considerar que se distribuyen normalmente. Sin embargo, cuando tenemos tamaños muestrales pequeños o simplemente por el tipo de variable que estamos midiendo, dicha suposición no resulta creible y es necesario comporbarla antes de poder aplicar estos procedimientos. SI la distribución no resulta Normal podemos utilizar los procedimientos denominados no parámetricos para la comparación de dos medias. A continuación presentamso el test de normalidad y los contrastes no paramétricos.</p>
<div id="normalidad" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Normalidad</h3>
<p>Este requisito implica que la variable objetivo tiene que distribuirse según una normal para cualquiera de las pobalciones donde se pueda medir. El test utilizado para resolver este problema es el de Shapiro-Wilks. En R utilizamos la función <code>shapiro.test()</code> para concluir estadísticamente sobre este contraste. Siempre utilizamos significatividad de 0.05 en estas situaciones.</p>
<p>Para los datos del ejemplo 1 comprobamos si los datos muestrales en cada población pueden considerarse que se distribuyen según una normal.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="inferencia-básica.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb170-2"><a href="inferencia-básica.html#cb170-2" aria-hidden="true" tabindex="-1"></a>MetodoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.7</span>, <span class="fl">11.2</span>, <span class="fl">15.3</span>, <span class="fl">14.9</span>, <span class="fl">13.9</span>, <span class="dv">15</span>, <span class="fl">15.6</span>, <span class="fl">15.7</span>, <span class="fl">14.3</span>, <span class="fl">10.8</span>)</span>
<span id="cb170-3"><a href="inferencia-básica.html#cb170-3" aria-hidden="true" tabindex="-1"></a>MetodoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">11.1</span>, <span class="fl">11.4</span>, <span class="dv">15</span>, <span class="fl">15.1</span>, <span class="fl">14.3</span>, <span class="fl">15.4</span>, <span class="fl">15.4</span>, <span class="dv">16</span>, <span class="fl">14.3</span>, <span class="fl">11.2</span>)</span>
<span id="cb170-4"><a href="inferencia-básica.html#cb170-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(MetodoA)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  MetodoA
## W = 0.8058, p-value = 0.01705</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="inferencia-básica.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(MetodoB)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  MetodoB
## W = 0.80577, p-value = 0.01704</code></pre>
<p>En ambos casos las conclusión es que rechazamos que los datos se distribuyan según una normal, ya que el pvalor es inferior a la significatividad prefijada.</p>
<p>Para los datos del ejemplo 2:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="inferencia-básica.html#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb174-2"><a href="inferencia-básica.html#cb174-2" aria-hidden="true" tabindex="-1"></a>TipoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1614</span>,<span class="dv">1094</span>,<span class="dv">1293</span>,<span class="dv">1643</span>,<span class="dv">1466</span>,<span class="dv">1270</span>,<span class="dv">1340</span>,<span class="dv">1380</span>,<span class="dv">1081</span>,<span class="dv">1497</span>)</span>
<span id="cb174-3"><a href="inferencia-básica.html#cb174-3" aria-hidden="true" tabindex="-1"></a>TipoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1383</span>,<span class="dv">1138</span>,<span class="dv">920</span>,<span class="dv">1143</span>,<span class="dv">1017</span>,<span class="dv">961</span>,<span class="dv">1627</span>,<span class="dv">821</span>,<span class="dv">1711</span>,<span class="dv">865</span>,<span class="dv">1662</span>,<span class="dv">1698</span>)</span>
<span id="cb174-4"><a href="inferencia-básica.html#cb174-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(TipoA)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  TipoA
## W = 0.95009, p-value = 0.6696</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="inferencia-básica.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(TipoB)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  TipoB
## W = 0.86377, p-value = 0.05451</code></pre>
<p>En ambos casos no podemos rechzar que los datos sean normales, ya que el pvalor es superior a la significatividad.</p>
</div>
<div id="dos-medianas-en-poblaciones-independientes" class="section level3" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Dos medianas en poblaciones independientes</h3>
<p>El test no paramétrico no se centra en la comparación de medias sino en la comparación de las medianas. Esto es así porque uno de los incumplimientos más habituales de la normalidad es porque los datos no son simétricos, es decir, la media coincide con la mediana. Para resolver este contraste utilizamos el test de Wilcoxon y su función en R <code>wilcox.test()</code>.</p>
<p>Dado que los datos del ejmplo 1 no pueden considerarse normales, utilizamos el test no paramétrico apra concluir si las medianas de ambas poblaciones pueden considerarse iguales o distintas. Fijamos la significatividad en 0.05.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="inferencia-básica.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb178-2"><a href="inferencia-básica.html#cb178-2" aria-hidden="true" tabindex="-1"></a>MetodoA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.7</span>, <span class="fl">11.2</span>, <span class="fl">15.3</span>, <span class="fl">14.9</span>, <span class="fl">13.9</span>, <span class="dv">15</span>, <span class="fl">15.6</span>, <span class="fl">15.7</span>, <span class="fl">14.3</span>, <span class="fl">10.8</span>)</span>
<span id="cb178-3"><a href="inferencia-básica.html#cb178-3" aria-hidden="true" tabindex="-1"></a>MetodoB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">11.1</span>, <span class="fl">11.4</span>, <span class="dv">15</span>, <span class="fl">15.1</span>, <span class="fl">14.3</span>, <span class="fl">15.4</span>, <span class="fl">15.4</span>, <span class="dv">16</span>, <span class="fl">14.3</span>, <span class="fl">11.2</span>)</span>
<span id="cb178-4"><a href="inferencia-básica.html#cb178-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(MetodoA,MetodoB)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  MetodoA and MetodoB
## W = 44, p-value = 0.6768
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Dado que el pvalor es superior a la significatividad, tenemos evidencias para concluir que no podemos considerar que las medianas de ambas poblaciones sean distintas.</p>
</div>
<div id="dos-medianas-en-poblaciones-dependientes" class="section level3" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> Dos medianas en poblaciones dependientes</h3>
<p>También existe una versión del test de wilcoxon para la comparación en poblaciones dependientes. Este es muy habitual ya que en este tipo de situaciones lo nomral es tener pocos sujetos, y por tanto la hipótesis de normalidad es muy difícil de verificar.</p>
<p>Para los datos del ejemplo 3 tenemos:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="inferencia-básica.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos los datos</span></span>
<span id="cb180-2"><a href="inferencia-básica.html#cb180-2" aria-hidden="true" tabindex="-1"></a>antes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">7.3</span>,<span class="fl">8.2</span>,<span class="fl">6.3</span>,<span class="fl">5.2</span>,<span class="fl">6.9</span>,<span class="fl">5.8</span>,<span class="fl">5.3</span>,<span class="fl">7.1</span>,<span class="fl">6.9</span>,<span class="fl">8.1</span>)</span>
<span id="cb180-3"><a href="inferencia-básica.html#cb180-3" aria-hidden="true" tabindex="-1"></a>despues <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">8.2</span>,<span class="fl">7.9</span>,<span class="fl">6.4</span>,<span class="fl">5.1</span>,<span class="fl">7.1</span>,<span class="fl">6.3</span>,<span class="fl">5.9</span>,<span class="fl">8.2</span>,<span class="fl">7.1</span>,<span class="fl">7.7</span>)</span>
<span id="cb180-4"><a href="inferencia-básica.html#cb180-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(antes, despues,<span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  antes and despues
## V = 12.5, p-value = 0.1389
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Dado que el pvalor es superior a la significatividad, podemos conluir que la mediana antes y después no pueden considerarse distintas.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prob.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelstats.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["libroSTAT.pdf", "libroSTAT.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
