title: Modelos estadísticos con R y RStudio
description: Una visión práctica de la construcción y análisis de modelos estadísticos con R y RStudio.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
markdown: kramdown
