<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Unidad 14 Estimación | Modelos Estadísticos</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Unidad 14 Estimación | Modelos Estadísticos" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Unidad 14 Estimación | Modelos Estadísticos" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Javier Morales (Universidad Miguel Hernández de Elche)" />
<meta name="author" content="Mª Asunción Martínez (Universidad Miguel Hernández de Elche)" />


<meta name="date" content="2021-05-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelos-logit-multinomial.html"/>
<link rel="next" href="diagnóstico-5.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>
<li><a href="./">J. Morales y A.M. Mayoral</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html"><i class="fa fa-check"></i>Antes de empezar</a><ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#conceptos-básicos-del-diseño-experimental"><i class="fa fa-check"></i>Conceptos básicos del diseño experimental</a><ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#objetivo-del-diseño-experimental"><i class="fa fa-check"></i>Objetivo del diseño experimental</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#población-y-muestra"><i class="fa fa-check"></i>Población y muestra</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#medidas-y-escalas-de-medida"><i class="fa fa-check"></i>Medidas y escalas de medida</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#parámetros-poblacionales-y-estadísticos"><i class="fa fa-check"></i>Parámetros poblacionales y estadísticos</a></li>
</ul></li>
<li><a href="antes-de-empezar.html#primeros-pasos-con-r-y-rstudio">Primeros pasos con <code>R</code> y <code>RStudio</code></a><ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#instalación-y-puesta-en-marcha"><i class="fa fa-check"></i>Instalación y puesta en marcha</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#informes-prediseñados"><i class="fa fa-check"></i>Informes prediseñados</a></li>
<li><a href="antes-de-empezar.html#librerías-de-r-necesarías">Librerías de <code>R</code> necesarías</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="modelstats.html"><a href="modelstats.html"><i class="fa fa-check"></i><b>1</b> Modelos estadísticos</a><ul>
<li class="chapter" data-level="1.1" data-path="modelstats.html"><a href="modelstats.html#componentes-del-modelo"><i class="fa fa-check"></i><b>1.1</b> Componentes del modelo</a></li>
<li class="chapter" data-level="1.2" data-path="modelstats.html"><a href="modelstats.html#tipos-de-modelos"><i class="fa fa-check"></i><b>1.2</b> Tipos de modelos</a></li>
<li class="chapter" data-level="1.3" data-path="modelstats.html"><a href="modelstats.html#fases-en-la-construcción-de-un-modelo"><i class="fa fa-check"></i><b>1.3</b> Fases en la construcción de un modelo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rls.html"><a href="rls.html"><i class="fa fa-check"></i><b>2</b> Regresión Lineal Simple (RLS)</a><ul>
<li class="chapter" data-level="2.1" data-path="rls.html"><a href="rls.html#bancos-de-datos"><i class="fa fa-check"></i><b>2.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="2.2" data-path="rls.html"><a href="rls.html#modelorls"><i class="fa fa-check"></i><b>2.2</b> El modelo RLS</a></li>
<li class="chapter" data-level="2.3" data-path="rls.html"><a href="rls.html#estimacionrls"><i class="fa fa-check"></i><b>2.3</b> Estimación del modelo</a><ul>
<li class="chapter" data-level="2.3.1" data-path="rls.html"><a href="rls.html#mincuadrls"><i class="fa fa-check"></i><b>2.3.1</b> Estimación Mínimos Cuadrados</a></li>
<li class="chapter" data-level="2.3.2" data-path="rls.html"><a href="rls.html#emvrls"><i class="fa fa-check"></i><b>2.3.2</b> Estimación Máximo Verosímil</a></li>
<li class="chapter" data-level="2.3.3" data-path="rls.html"><a href="rls.html#emR"><i class="fa fa-check"></i><b>2.3.3</b> Estimación con R</a></li>
<li class="chapter" data-level="2.3.4" data-path="rls.html"><a href="rls.html#ejemplos"><i class="fa fa-check"></i><b>2.3.4</b> Ejemplos</a></li>
<li class="chapter" data-level="2.3.5" data-path="rls.html"><a href="rls.html#propiedades-de-la-recta-de-regresión."><i class="fa fa-check"></i><b>2.3.5</b> Propiedades de la recta de regresión.</a></li>
<li class="chapter" data-level="2.3.6" data-path="rls.html"><a href="rls.html#rls_varmodel"><i class="fa fa-check"></i><b>2.3.6</b> Estimación varianza del modelo.</a></li>
<li class="chapter" data-level="2.3.7" data-path="rls.html"><a href="rls.html#inferencia-sobre-los-coeficientes-del-modelo"><i class="fa fa-check"></i><b>2.3.7</b> Inferencia sobre los coeficientes del modelo</a></li>
<li class="chapter" data-level="2.3.8" data-path="rls.html"><a href="rls.html#ejemplo"><i class="fa fa-check"></i><b>2.3.8</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rls.html"><a href="rls.html#bondad-del-ajuste"><i class="fa fa-check"></i><b>2.4</b> Bondad del Ajuste</a><ul>
<li class="chapter" data-level="2.4.1" data-path="rls.html"><a href="rls.html#rls_errorresidual"><i class="fa fa-check"></i><b>2.4.1</b> Error residual</a></li>
<li class="chapter" data-level="2.4.2" data-path="rls.html"><a href="rls.html#rls_tablaanova"><i class="fa fa-check"></i><b>2.4.2</b> Tabla Anova</a></li>
<li class="chapter" data-level="2.4.3" data-path="rls.html"><a href="rls.html#coeficiente-de-determinación"><i class="fa fa-check"></i><b>2.4.3</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="2.4.4" data-path="rls.html"><a href="rls.html#ejemplo-1"><i class="fa fa-check"></i><b>2.4.4</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rls.html"><a href="rls.html#rls_diag"><i class="fa fa-check"></i><b>2.5</b> Diagnóstico del Modelo</a><ul>
<li class="chapter" data-level="2.5.1" data-path="rls.html"><a href="rls.html#linealidad-y-homocedasticidad."><i class="fa fa-check"></i><b>2.5.1</b> Linealidad y homocedasticidad.</a></li>
<li class="chapter" data-level="2.5.2" data-path="rls.html"><a href="rls.html#ejemplo-2"><i class="fa fa-check"></i><b>2.5.2</b> Ejemplo</a></li>
<li class="chapter" data-level="2.5.3" data-path="rls.html"><a href="rls.html#normalidad"><i class="fa fa-check"></i><b>2.5.3</b> Normalidad</a></li>
<li class="chapter" data-level="2.5.4" data-path="rls.html"><a href="rls.html#independencia."><i class="fa fa-check"></i><b>2.5.4</b> Independencia.</a></li>
<li class="chapter" data-level="2.5.5" data-path="rls.html"><a href="rls.html#otros-gráficos-de-diagnóstico"><i class="fa fa-check"></i><b>2.5.5</b> Otros gráficos de diagnóstico</a></li>
<li class="chapter" data-level="2.5.6" data-path="rls.html"><a href="rls.html#incumplimiento-de-hipótesis"><i class="fa fa-check"></i><b>2.5.6</b> Incumplimiento de hipótesis</a></li>
<li class="chapter" data-level="2.5.7" data-path="rls.html"><a href="rls.html#análisis-de-influencia"><i class="fa fa-check"></i><b>2.5.7</b> Análisis de influencia</a></li>
<li class="chapter" data-level="2.5.8" data-path="rls.html"><a href="rls.html#transformaciones"><i class="fa fa-check"></i><b>2.5.8</b> Transformaciones</a></li>
<li class="chapter" data-level="2.5.9" data-path="rls.html"><a href="rls.html#ejemplos-1"><i class="fa fa-check"></i><b>2.5.9</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rls.html"><a href="rls.html#rls_pred"><i class="fa fa-check"></i><b>2.6</b> Predicción del modelo</a><ul>
<li class="chapter" data-level="2.6.1" data-path="rls.html"><a href="rls.html#respuesta-media"><i class="fa fa-check"></i><b>2.6.1</b> Respuesta media</a></li>
<li class="chapter" data-level="2.6.2" data-path="rls.html"><a href="rls.html#nueva-observación"><i class="fa fa-check"></i><b>2.6.2</b> Nueva observación</a></li>
<li class="chapter" data-level="2.6.3" data-path="rls.html"><a href="rls.html#ejemplos-2"><i class="fa fa-check"></i><b>2.6.3</b> Ejemplos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rlm.html"><a href="rlm.html"><i class="fa fa-check"></i><b>3</b> Regresión Lineal Múltiple y Polinómica</a><ul>
<li class="chapter" data-level="3.1" data-path="rlm.html"><a href="rlm.html#tipos-de-modelos-1"><i class="fa fa-check"></i><b>3.1</b> Tipos de modelos</a><ul>
<li class="chapter" data-level="3.1.1" data-path="rlm.html"><a href="rlm.html#modelos-de-rlm"><i class="fa fa-check"></i><b>3.1.1</b> Modelos de RLM</a></li>
<li class="chapter" data-level="3.1.2" data-path="rlm.html"><a href="rlm.html#modelos-de-rp"><i class="fa fa-check"></i><b>3.1.2</b> Modelos de RP</a></li>
<li class="chapter" data-level="3.1.3" data-path="rlm.html"><a href="rlm.html#expresión-en-r-de-los-modelos"><i class="fa fa-check"></i><b>3.1.3</b> Expresión en R de los modelos</a></li>
<li class="chapter" data-level="3.1.4" data-path="rlm.html"><a href="rlm.html#modelo-saturado-y-anidado"><i class="fa fa-check"></i><b>3.1.4</b> Modelo saturado y anidado</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="rlm.html"><a href="rlm.html#estimación-e-inferencia"><i class="fa fa-check"></i><b>3.2</b> Estimación e inferencia</a><ul>
<li class="chapter" data-level="3.2.1" data-path="rlm.html"><a href="rlm.html#mínimos-cuadrados"><i class="fa fa-check"></i><b>3.2.1</b> Mínimos cuadrados</a></li>
<li class="chapter" data-level="3.2.2" data-path="rlm.html"><a href="rlm.html#propiedades"><i class="fa fa-check"></i><b>3.2.2</b> Propiedades</a></li>
<li class="chapter" data-level="3.2.3" data-path="rlm.html"><a href="rlm.html#máxima-verosimilitud"><i class="fa fa-check"></i><b>3.2.3</b> Máxima verosimilitud</a></li>
<li class="chapter" data-level="3.2.4" data-path="rlm.html"><a href="rlm.html#inferencia"><i class="fa fa-check"></i><b>3.2.4</b> Inferencia</a></li>
<li class="chapter" data-level="3.2.5" data-path="rlm.html"><a href="rlm.html#ejemplos-3"><i class="fa fa-check"></i><b>3.2.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="rlm.html"><a href="rlm.html#bondad-del-ajuste-1"><i class="fa fa-check"></i><b>3.3</b> Bondad del ajuste</a><ul>
<li class="chapter" data-level="3.3.1" data-path="rlm.html"><a href="rlm.html#tabla-anova"><i class="fa fa-check"></i><b>3.3.1</b> Tabla ANOVA</a></li>
<li class="chapter" data-level="3.3.2" data-path="rlm.html"><a href="rlm.html#coeficiente-determinación"><i class="fa fa-check"></i><b>3.3.2</b> Coeficiente determinación</a></li>
<li class="chapter" data-level="3.3.3" data-path="rlm.html"><a href="rlm.html#ejemplos-4"><i class="fa fa-check"></i><b>3.3.3</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="rlm.html"><a href="rlm.html#comparación-y-selección-de-modelos"><i class="fa fa-check"></i><b>3.4</b> Comparación y selección de modelos</a><ul>
<li class="chapter" data-level="3.4.1" data-path="rlm.html"><a href="rlm.html#significatividad-de-los-predictores"><i class="fa fa-check"></i><b>3.4.1</b> Significatividad de los predictores</a></li>
<li class="chapter" data-level="3.4.2" data-path="rlm.html"><a href="rlm.html#estadísticos-aic-y-bic"><i class="fa fa-check"></i><b>3.4.2</b> Estadísticos AIC y BIC</a></li>
<li class="chapter" data-level="3.4.3" data-path="rlm.html"><a href="rlm.html#selección-automática"><i class="fa fa-check"></i><b>3.4.3</b> Selección automática</a></li>
<li class="chapter" data-level="3.4.4" data-path="rlm.html"><a href="rlm.html#funciones-en-r"><i class="fa fa-check"></i><b>3.4.4</b> Funciones en R</a></li>
<li class="chapter" data-level="3.4.5" data-path="rlm.html"><a href="rlm.html#ejemplos-5"><i class="fa fa-check"></i><b>3.4.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="rlm.html"><a href="rlm.html#multicolinealidad"><i class="fa fa-check"></i><b>3.5</b> Multicolinealidad</a><ul>
<li class="chapter" data-level="3.5.1" data-path="rlm.html"><a href="rlm.html#causas"><i class="fa fa-check"></i><b>3.5.1</b> Causas</a></li>
<li class="chapter" data-level="3.5.2" data-path="rlm.html"><a href="rlm.html#efectos"><i class="fa fa-check"></i><b>3.5.2</b> Efectos</a></li>
<li class="chapter" data-level="3.5.3" data-path="rlm.html"><a href="rlm.html#diagnósticos"><i class="fa fa-check"></i><b>3.5.3</b> Diagnósticos</a></li>
<li class="chapter" data-level="3.5.4" data-path="rlm.html"><a href="rlm.html#soluciones"><i class="fa fa-check"></i><b>3.5.4</b> Soluciones</a></li>
<li class="chapter" data-level="3.5.5" data-path="rlm.html"><a href="rlm.html#ejemplos-6"><i class="fa fa-check"></i><b>3.5.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="rlm.html"><a href="rlm.html#diagnóstico"><i class="fa fa-check"></i><b>3.6</b> Diagnóstico</a><ul>
<li class="chapter" data-level="3.6.1" data-path="rlm.html"><a href="rlm.html#tipos-de-residuos"><i class="fa fa-check"></i><b>3.6.1</b> Tipos de Residuos</a></li>
<li class="chapter" data-level="3.6.2" data-path="rlm.html"><a href="rlm.html#linealidad"><i class="fa fa-check"></i><b>3.6.2</b> Linealidad</a></li>
<li class="chapter" data-level="3.6.3" data-path="rlm.html"><a href="rlm.html#homocedasticidad"><i class="fa fa-check"></i><b>3.6.3</b> Homocedasticidad</a></li>
<li class="chapter" data-level="3.6.4" data-path="rlm.html"><a href="rlm.html#normalidad-1"><i class="fa fa-check"></i><b>3.6.4</b> Normalidad</a></li>
<li class="chapter" data-level="3.6.5" data-path="rlm.html"><a href="rlm.html#incorrelación"><i class="fa fa-check"></i><b>3.6.5</b> Incorrelación</a></li>
<li class="chapter" data-level="3.6.6" data-path="rlm.html"><a href="rlm.html#soluciones-a-problemas-detectados-en-el-diagnóstico-del-modelo"><i class="fa fa-check"></i><b>3.6.6</b> Soluciones a problemas detectados en el diagnóstico del modelo</a></li>
<li class="chapter" data-level="3.6.7" data-path="rlm.html"><a href="rlm.html#análisis-de-influencia-1"><i class="fa fa-check"></i><b>3.6.7</b> Análisis de influencia</a></li>
<li class="chapter" data-level="3.6.8" data-path="rlm.html"><a href="rlm.html#funciones-para-diagnóstico-e-influencia"><i class="fa fa-check"></i><b>3.6.8</b> Funciones para diagnóstico e influencia</a></li>
<li class="chapter" data-level="3.6.9" data-path="rlm.html"><a href="rlm.html#ejemplos-7"><i class="fa fa-check"></i><b>3.6.9</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="rlm.html"><a href="rlm.html#predicción"><i class="fa fa-check"></i><b>3.7</b> Predicción</a><ul>
<li class="chapter" data-level="3.7.1" data-path="rlm.html"><a href="rlm.html#estimación-de-la-respuesta-media."><i class="fa fa-check"></i><b>3.7.1</b> Estimación de la respuesta media.</a></li>
<li class="chapter" data-level="3.7.2" data-path="rlm.html"><a href="rlm.html#predicción-de-nuevas-observaciones."><i class="fa fa-check"></i><b>3.7.2</b> Predicción de nuevas observaciones.</a></li>
<li class="chapter" data-level="3.7.3" data-path="rlm.html"><a href="rlm.html#ejemplos-8"><i class="fa fa-check"></i><b>3.7.3</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="rlm.html"><a href="rlm.html#ejercicios"><i class="fa fa-check"></i><b>3.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>4</b> Modelos ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="anova.html"><a href="anova.html#bancos-de-datos-1"><i class="fa fa-check"></i><b>4.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="4.2" data-path="anova.html"><a href="anova.html#modelos-anova-1-vía"><i class="fa fa-check"></i><b>4.2</b> Modelos ANOVA 1 vía</a><ul>
<li class="chapter" data-level="4.2.1" data-path="anova.html"><a href="anova.html#especificacion-del-modelo-en-r"><i class="fa fa-check"></i><b>4.2.1</b> Especificacion del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="anova.html"><a href="anova.html#modelos-anova-dos-vías"><i class="fa fa-check"></i><b>4.3</b> Modelos ANOVA dos vías</a><ul>
<li class="chapter" data-level="4.3.1" data-path="anova.html"><a href="anova.html#especificacion-del-modelo-en-r-1"><i class="fa fa-check"></i><b>4.3.1</b> Especificacion del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="anova.html"><a href="anova.html#estimación-y-bondad-de-ajuste-del-modelo"><i class="fa fa-check"></i><b>4.4</b> Estimación y bondad de ajuste del modelo</a><ul>
<li class="chapter" data-level="4.4.1" data-path="anova.html"><a href="anova.html#ejemplos-9"><i class="fa fa-check"></i><b>4.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="anova.html"><a href="anova.html#comparación-y-selección-de-modelos-1"><i class="fa fa-check"></i><b>4.5</b> Comparación y selección de modelos</a><ul>
<li class="chapter" data-level="4.5.1" data-path="anova.html"><a href="anova.html#ejemplos-10"><i class="fa fa-check"></i><b>4.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="anova.html"><a href="anova.html#diagnóstico-1"><i class="fa fa-check"></i><b>4.6</b> Diagnóstico</a><ul>
<li class="chapter" data-level="4.6.1" data-path="anova.html"><a href="anova.html#ejemplos-11"><i class="fa fa-check"></i><b>4.6.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="anova.html"><a href="anova.html#predicción-1"><i class="fa fa-check"></i><b>4.7</b> Predicción</a><ul>
<li class="chapter" data-level="4.7.1" data-path="anova.html"><a href="anova.html#ejemplos-12"><i class="fa fa-check"></i><b>4.7.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="anova.html"><a href="anova.html#ejercicios-1"><i class="fa fa-check"></i><b>4.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>5</b> Modelos ANCOVA</a><ul>
<li class="chapter" data-level="5.1" data-path="ancova.html"><a href="ancova.html#bancos-de-datos-2"><i class="fa fa-check"></i><b>5.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="5.2" data-path="ancova.html"><a href="ancova.html#modelo-ancova-básico"><i class="fa fa-check"></i><b>5.2</b> Modelo ANCOVA básico</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ancova.html"><a href="ancova.html#i-rectas-de-regresión-perpendiculares"><i class="fa fa-check"></i><b>5.2.1</b> I rectas de regresión perpendiculares</a></li>
<li class="chapter" data-level="5.2.2" data-path="ancova.html"><a href="ancova.html#i-rectas-de-regresión-paralelas"><i class="fa fa-check"></i><b>5.2.2</b> I rectas de regresión paralelas</a></li>
<li class="chapter" data-level="5.2.3" data-path="ancova.html"><a href="ancova.html#una-recta-de-regresión"><i class="fa fa-check"></i><b>5.2.3</b> Una recta de regresión</a></li>
<li class="chapter" data-level="5.2.4" data-path="ancova.html"><a href="ancova.html#anova-de-una-vía"><i class="fa fa-check"></i><b>5.2.4</b> ANOVA de una vía</a></li>
<li class="chapter" data-level="5.2.5" data-path="ancova.html"><a href="ancova.html#modelos-sin-efectos"><i class="fa fa-check"></i><b>5.2.5</b> Modelos sin efectos</a></li>
<li class="chapter" data-level="5.2.6" data-path="ancova.html"><a href="ancova.html#especificación-del-modelo-en-r"><i class="fa fa-check"></i><b>5.2.6</b> Especificación del modelo en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ancova.html"><a href="ancova.html#análisis-preliminar"><i class="fa fa-check"></i><b>5.3</b> Análisis preliminar</a></li>
<li class="chapter" data-level="5.4" data-path="ancova.html"><a href="ancova.html#ajuste-y-selección-del-modelo"><i class="fa fa-check"></i><b>5.4</b> Ajuste y Selección del modelo</a></li>
<li class="chapter" data-level="5.5" data-path="ancova.html"><a href="ancova.html#diagnóstico-del-modelo"><i class="fa fa-check"></i><b>5.5</b> Diagnóstico del modelo</a></li>
<li class="chapter" data-level="5.6" data-path="ancova.html"><a href="ancova.html#predicción-2"><i class="fa fa-check"></i><b>5.6</b> Predicción</a></li>
<li class="chapter" data-level="5.7" data-path="ancova.html"><a href="ancova.html#ejercicios-modelos-ancova"><i class="fa fa-check"></i><b>5.7</b> Ejercicios modelos ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="smooth.html"><a href="smooth.html"><i class="fa fa-check"></i><b>6</b> Modelos aditivos lineales</a><ul>
<li class="chapter" data-level="6.1" data-path="smooth.html"><a href="smooth.html#bancos-de-datos-3"><i class="fa fa-check"></i><b>6.1</b> Bancos de datos</a></li>
<li class="chapter" data-level="6.2" data-path="smooth.html"><a href="smooth.html#funciones-de-suavizado"><i class="fa fa-check"></i><b>6.2</b> Funciones de suavizado</a><ul>
<li class="chapter" data-level="6.2.1" data-path="smooth.html"><a href="smooth.html#splines-de-regresión"><i class="fa fa-check"></i><b>6.2.1</b> Splines de regresión</a></li>
<li class="chapter" data-level="6.2.2" data-path="smooth.html"><a href="smooth.html#splines-cúbicos"><i class="fa fa-check"></i><b>6.2.2</b> Splines cúbicos</a></li>
<li class="chapter" data-level="6.2.3" data-path="smooth.html"><a href="smooth.html#splines-penalizados"><i class="fa fa-check"></i><b>6.2.3</b> Splines penalizados</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="smooth.html"><a href="smooth.html#bondad-del-ajuste-y-selección-del-modelo"><i class="fa fa-check"></i><b>6.3</b> Bondad del ajuste y selección del modelo</a></li>
<li class="chapter" data-level="6.4" data-path="smooth.html"><a href="smooth.html#diagnóstico-2"><i class="fa fa-check"></i><b>6.4</b> Diagnóstico</a></li>
<li class="chapter" data-level="6.5" data-path="smooth.html"><a href="smooth.html#predicción-3"><i class="fa fa-check"></i><b>6.5</b> Predicción</a></li>
<li class="chapter" data-level="6.6" data-path="smooth.html"><a href="smooth.html#ejercicios-2"><i class="fa fa-check"></i><b>6.6</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>7</b> Modelos Lineales Generalizados</a><ul>
<li class="chapter" data-level="7.1" data-path="glm.html"><a href="glm.html#modelo-teórico"><i class="fa fa-check"></i><b>7.1</b> Modelo Teórico</a><ul>
<li class="chapter" data-level="7.1.1" data-path="glm.html"><a href="glm.html#distribución-binomial-logit-link"><i class="fa fa-check"></i><b>7.1.1</b> Distribución Binomial (logit link)</a></li>
<li class="chapter" data-level="7.1.2" data-path="glm.html"><a href="glm.html#distribución-poisson-log-link"><i class="fa fa-check"></i><b>7.1.2</b> Distribución Poisson (log link)</a></li>
<li class="chapter" data-level="7.1.3" data-path="glm.html"><a href="glm.html#distribución-normal-link-identidad"><i class="fa fa-check"></i><b>7.1.3</b> Distribución Normal (link identidad)</a></li>
<li class="chapter" data-level="7.1.4" data-path="glm.html"><a href="glm.html#distribución-gamma-link-recíproco"><i class="fa fa-check"></i><b>7.1.4</b> Distribución Gamma (link recíproco)</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="glm.html"><a href="glm.html#estimación-de-los-glm"><i class="fa fa-check"></i><b>7.2</b> Estimación de los GLM</a></li>
<li class="chapter" data-level="7.3" data-path="glm.html"><a href="glm.html#bondad-del-ajuste-2"><i class="fa fa-check"></i><b>7.3</b> Bondad del ajuste</a></li>
<li class="chapter" data-level="7.4" data-path="glm.html"><a href="glm.html#comparación-de-modelos"><i class="fa fa-check"></i><b>7.4</b> Comparación de modelos</a></li>
<li class="chapter" data-level="7.5" data-path="glm.html"><a href="glm.html#diagnóstico-de-los-glm"><i class="fa fa-check"></i><b>7.5</b> Diagnóstico de los GLM</a></li>
<li class="chapter" data-level="7.6" data-path="glm.html"><a href="glm.html#predicción-de-los-glm"><i class="fa fa-check"></i><b>7.6</b> Predicción de los GLM</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="glmbinomial.html"><a href="glmbinomial.html"><i class="fa fa-check"></i><b>8</b> GLM respuesta binomial</a><ul>
<li class="chapter" data-level="8.1" data-path="glmbinomial.html"><a href="glmbinomial.html#tipos-de-datos-binomiales"><i class="fa fa-check"></i><b>8.1</b> Tipos de datos binomiales</a><ul>
<li class="chapter" data-level="8.1.1" data-path="glmbinomial.html"><a href="glmbinomial.html#información-individualizada-por-sujeto"><i class="fa fa-check"></i><b>8.1.1</b> Información individualizada por sujeto</a></li>
<li class="chapter" data-level="8.1.2" data-path="glmbinomial.html"><a href="glmbinomial.html#información-agrupada-por-sujetos"><i class="fa fa-check"></i><b>8.1.2</b> Información agrupada por sujetos</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="glmbinomial.html"><a href="glmbinomial.html#especificación-e-hipótesis-de-modelo"><i class="fa fa-check"></i><b>8.2</b> Especificación e hipótesis de modelo</a><ul>
<li class="chapter" data-level="8.2.1" data-path="glmbinomial.html"><a href="glmbinomial.html#funciones-link"><i class="fa fa-check"></i><b>8.2.1</b> Funciones link</a></li>
<li class="chapter" data-level="8.2.2" data-path="glmbinomial.html"><a href="glmbinomial.html#representación-de-las-funciones-link"><i class="fa fa-check"></i><b>8.2.2</b> Representación de las funciones link</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="glmbinomial.html"><a href="glmbinomial.html#estimación-y-bondad-de-ajuste"><i class="fa fa-check"></i><b>8.3</b> Estimación y bondad de ajuste</a><ul>
<li class="chapter" data-level="8.3.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-13"><i class="fa fa-check"></i><b>8.3.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="glmbinomial.html"><a href="glmbinomial.html#selección-del-modelo"><i class="fa fa-check"></i><b>8.4</b> Selección del modelo</a><ul>
<li class="chapter" data-level="8.4.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-14"><i class="fa fa-check"></i><b>8.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="glmbinomial.html"><a href="glmbinomial.html#diagnóstico-3"><i class="fa fa-check"></i><b>8.5</b> Diagnóstico</a><ul>
<li class="chapter" data-level="8.5.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-15"><i class="fa fa-check"></i><b>8.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="glmbinomial.html"><a href="glmbinomial.html#predicción-4"><i class="fa fa-check"></i><b>8.6</b> Predicción</a><ul>
<li class="chapter" data-level="8.6.1" data-path="glmbinomial.html"><a href="glmbinomial.html#ejemplos-16"><i class="fa fa-check"></i><b>8.6.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="glmbinomial.html"><a href="glmbinomial.html#ejercicios-3"><i class="fa fa-check"></i><b>8.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="glmpoisson.html"><a href="glmpoisson.html"><i class="fa fa-check"></i><b>9</b> GLM Poisson</a><ul>
<li class="chapter" data-level="9.1" data-path="glmpoisson.html"><a href="glmpoisson.html#bancos-de-datos-4"><i class="fa fa-check"></i><b>9.1</b> Bancos de datos</a><ul>
<li class="chapter" data-level="9.1.1" data-path="glmpoisson.html"><a href="glmpoisson.html#telas"><i class="fa fa-check"></i><b>9.1.1</b> Telas</a></li>
<li class="chapter" data-level="9.1.2" data-path="glmpoisson.html"><a href="glmpoisson.html#barcos"><i class="fa fa-check"></i><b>9.1.2</b> Barcos</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="glmpoisson.html"><a href="glmpoisson.html#modelo-teórico-1"><i class="fa fa-check"></i><b>9.2</b> Modelo Teórico</a></li>
<li class="chapter" data-level="9.3" data-path="glmpoisson.html"><a href="glmpoisson.html#estimación-y-bondad-de-ajuste-del-modelo-1"><i class="fa fa-check"></i><b>9.3</b> Estimación y bondad de ajuste del modelo</a><ul>
<li class="chapter" data-level="9.3.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-17"><i class="fa fa-check"></i><b>9.3.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="glmpoisson.html"><a href="glmpoisson.html#selección-del-modelo-1"><i class="fa fa-check"></i><b>9.4</b> Selección del modelo</a><ul>
<li class="chapter" data-level="9.4.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-18"><i class="fa fa-check"></i><b>9.4.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="glmpoisson.html"><a href="glmpoisson.html#diagnóstico-4"><i class="fa fa-check"></i><b>9.5</b> Diagnóstico</a><ul>
<li class="chapter" data-level="9.5.1" data-path="glmpoisson.html"><a href="glmpoisson.html#ejemplos-19"><i class="fa fa-check"></i><b>9.5.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="glmpoisson.html"><a href="glmpoisson.html#predicción-5"><i class="fa fa-check"></i><b>9.6</b> Predicción</a><ul>
<li class="chapter" data-level="9.6.1" data-path="glmpoisson.html"><a href="glmpoisson.html#bancos-de-datos-5"><i class="fa fa-check"></i><b>9.6.1</b> Bancos de datos</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="glmpoisson.html"><a href="glmpoisson.html#ejercicios-4"><i class="fa fa-check"></i><b>9.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="glmtablascont.html"><a href="glmtablascont.html"><i class="fa fa-check"></i><b>10</b> GLM para tablas de contingencia</a></li>
<li class="chapter" data-level="11" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html"><i class="fa fa-check"></i><b>11</b> Bancos de datos</a><ul>
<li class="chapter" data-level="11.1" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#melanoma"><i class="fa fa-check"></i><b>11.1</b> Melanoma</a></li>
<li class="chapter" data-level="11.2" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#gripe"><i class="fa fa-check"></i><b>11.2</b> Gripe</a></li>
<li class="chapter" data-level="11.3" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#aspirina"><i class="fa fa-check"></i><b>11.3</b> Aspirina</a></li>
<li class="chapter" data-level="11.4" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#aspiraciones"><i class="fa fa-check"></i><b>11.4</b> Aspiraciones</a></li>
<li class="chapter" data-level="11.5" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#contraceptivos"><i class="fa fa-check"></i><b>11.5</b> Contraceptivos</a></li>
<li class="chapter" data-level="11.6" data-path="bancos-de-datos-6.html"><a href="bancos-de-datos-6.html#satisfacción-laboral"><i class="fa fa-check"></i><b>11.6</b> Satisfacción laboral</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html"><i class="fa fa-check"></i><b>12</b> Modelos Log-Lineales</a><ul>
<li class="chapter" data-level="12.1" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#especificación-en-r"><i class="fa fa-check"></i><b>12.1</b> Especificación en R</a></li>
<li class="chapter" data-level="12.2" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#ejemplos-20"><i class="fa fa-check"></i><b>12.2</b> Ejemplos</a><ul>
<li class="chapter" data-level="12.2.1" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#melanoma-1"><i class="fa fa-check"></i><b>12.2.1</b> Melanoma</a></li>
<li class="chapter" data-level="12.2.2" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#aspirina-1"><i class="fa fa-check"></i><b>12.2.2</b> Aspirina</a></li>
<li class="chapter" data-level="12.2.3" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#gripe-1"><i class="fa fa-check"></i><b>12.2.3</b> Gripe</a></li>
<li class="chapter" data-level="12.2.4" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html#aspiraciones-1"><i class="fa fa-check"></i><b>12.2.4</b> Aspiraciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="modelos-logit-multinomial.html"><a href="modelos-logit-multinomial.html"><i class="fa fa-check"></i><b>13</b> Modelos Logit-Multinomial</a></li>
<li class="chapter" data-level="14" data-path="estimación.html"><a href="estimación.html"><i class="fa fa-check"></i><b>14</b> Estimación</a><ul>
<li class="chapter" data-level="14.1" data-path="estimación.html"><a href="estimación.html#respuesta-binaria-nominal-y-predictora-nominal"><i class="fa fa-check"></i><b>14.1</b> Respuesta binaria nominal y predictora nominal</a><ul>
<li class="chapter" data-level="14.1.1" data-path="estimación.html"><a href="estimación.html#datos-aspirina"><i class="fa fa-check"></i><b>14.1.1</b> Datos Aspirina</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="estimación.html"><a href="estimación.html#respuesta-multinomial-nominal-y-predictora-nominal"><i class="fa fa-check"></i><b>14.2</b> Respuesta multinomial nominal y predictora nominal</a></li>
<li class="chapter" data-level="14.3" data-path="estimación.html"><a href="estimación.html#respuesta-nominal-predictora-ordinal"><i class="fa fa-check"></i><b>14.3</b> Respuesta nominal, predictora ordinal</a><ul>
<li class="chapter" data-level="14.3.1" data-path="estimación.html"><a href="estimación.html#datos-aspiraciones-universitarias"><i class="fa fa-check"></i><b>14.3.1</b> Datos Aspiraciones universitarias</a></li>
<li class="chapter" data-level="14.3.2" data-path="estimación.html"><a href="estimación.html#datos-de-contraceptivos"><i class="fa fa-check"></i><b>14.3.2</b> Datos de Contraceptivos</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="estimación.html"><a href="estimación.html#respuesta-ordinal-predictora-nominal"><i class="fa fa-check"></i><b>14.4</b> Respuesta ordinal, predictora nominal</a><ul>
<li class="chapter" data-level="14.4.1" data-path="estimación.html"><a href="estimación.html#datos-de-gripe"><i class="fa fa-check"></i><b>14.4.1</b> Datos de gripe</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="estimación.html"><a href="estimación.html#respuesta-ordinal-predictora-ordinal"><i class="fa fa-check"></i><b>14.5</b> Respuesta ordinal, predictora ordinal</a><ul>
<li class="chapter" data-level="14.5.1" data-path="estimación.html"><a href="estimación.html#datos-satisfacción-laboral"><i class="fa fa-check"></i><b>14.5.1</b> Datos Satisfacción laboral</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html"><i class="fa fa-check"></i><b>15</b> Diagnóstico</a><ul>
<li class="chapter" data-level="15.1" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#ejemplos-21"><i class="fa fa-check"></i><b>15.1</b> Ejemplos</a><ul>
<li class="chapter" data-level="15.1.1" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#aspirina-2"><i class="fa fa-check"></i><b>15.1.1</b> Aspirina</a></li>
<li class="chapter" data-level="15.1.2" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#aspiraciones-2"><i class="fa fa-check"></i><b>15.1.2</b> Aspiraciones</a></li>
<li class="chapter" data-level="15.1.3" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#contraceptivos-1"><i class="fa fa-check"></i><b>15.1.3</b> Contraceptivos</a></li>
<li class="chapter" data-level="15.1.4" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#gripe-2"><i class="fa fa-check"></i><b>15.1.4</b> Gripe</a></li>
<li class="chapter" data-level="15.1.5" data-path="diagnóstico-5.html"><a href="diagnóstico-5.html#satisfacción-laboral-1"><i class="fa fa-check"></i><b>15.1.5</b> Satisfacción laboral</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="predicción-6.html"><a href="predicción-6.html"><i class="fa fa-check"></i><b>16</b> Predicción</a></li>
<li class="chapter" data-level="17" data-path="ejercicios-5.html"><a href="ejercicios-5.html"><i class="fa fa-check"></i><b>17</b> Ejercicios</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>
<li><a href="https://sites.google.com/umh.es/statistical-models" target="blank">Modelos Estadísticos</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimación" class="section level1">
<h1><span class="header-section-number">Unidad 14</span> Estimación</h1>
<p>A continuación se presenta el proceso de estimación de los diferentes modelos logit-multinomial que pueden surgir en función de las características de la varaible respuesta y las predictoras. Se detalla cada caso siguiendo las pautas del punto anterior y se analizan los ejemplos correspondientes.</p>
<div id="respuesta-binaria-nominal-y-predictora-nominal" class="section level2">
<h2><span class="header-section-number">14.1</span> Respuesta binaria nominal y predictora nominal</h2>
<p>Imaginemos que la variable respuesta esta compuesta por dos categorías de carácter nominal (<span class="math inline">\(i=1, 2\)</span>=. Con la estructura de estimación definida en el punto anterior si la respuesta tiene únicamente dos categorías tendríamos que <span class="math inline">\(\pi_{1|j} = 1 - \pi_{2|j}\)</span>, de forma que tendríamos un único log-odds que se puede expresar como:</p>
<p><span class="math display">\[log\left(\frac{\pi_{2|j}}{\pi_{1|j}}\right) = log\left(\frac{\pi_{2|j}}{1-\pi_{2|j}}\right) = (\alpha_2 -\alpha_1) + (\alpha\beta_{2j} - \alpha\beta_{1j})\]</span></p>
<p>donde los <span class="math inline">\(\alpha\)</span> y los <span class="math inline">\(\alpha\beta\)</span> son los definidos en el punto anterior. Si denotamos por <span class="math inline">\(\eta_{2|j}\)</span> al <span class="math inline">\(log\left(\pi_{2|j}/\pi_{1|j}\right)\)</span>, a partir de la expresión anterior resulta posible obtener la probabilidad de cada nivel de la respuesta mediante la ecuación:</p>
<p><span class="math display">\[\pi_{2|j} = \frac{exp(\eta_{2|j})}{1+exp(\eta_{2|j})}\]</span></p>
<div id="datos-aspirina" class="section level3">
<h3><span class="header-section-number">14.1.1</span> Datos Aspirina</h3>
<p>En primer lugar calculamos y evaluamos los logits empíricos asociados y más tarde realizamos el ajuste y estimación delm modelo. Tomamos como variable respuesta el consumo de aspirina, y usamos como referencia la categroria <code>No</code> podemos obtener los log-odds como:</p>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb567-1" title="1"><span class="co"># Creamos variable con valores de referencia y obtenemos los log-odds asociados</span></a>
<a class="sourceLine" id="cb567-2" title="2">referencia.val &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Aspirina, aspirina <span class="op">==</span><span class="st"> &quot;No&quot;</span>),</a>
<a class="sourceLine" id="cb567-3" title="3">                                       frecuencia))</a>
<a class="sourceLine" id="cb567-4" title="4"><span class="co"># Log-odds</span></a>
<a class="sourceLine" id="cb567-5" title="5">Aspirina &lt;-<span class="st"> </span>Aspirina <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb567-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">referencia =</span> <span class="kw">rep</span>(referencia.val, <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb567-7" title="7">         <span class="dt">lodds =</span> <span class="kw">log</span>(frecuencia <span class="op">/</span><span class="st"> </span>referencia))</a>
<a class="sourceLine" id="cb567-8" title="8"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb567-9" title="9"><span class="co"># Seleccionamos las categorías a representar eliminando la de referencia</span></a>
<a class="sourceLine" id="cb567-10" title="10"><span class="co"># Como la respuesta sólo tiene una categoría no hace falta utilizarla en el gráfico</span></a>
<a class="sourceLine" id="cb567-11" title="11">datos &lt;-<span class="st"> </span><span class="kw">filter</span>(Aspirina, aspirina <span class="op">!=</span><span class="st"> &quot;No&quot;</span>)</a>
<a class="sourceLine" id="cb567-12" title="12"><span class="kw">ggplot</span>(datos,<span class="kw">aes</span>(<span class="dt">x =</span> locali, <span class="dt">y =</span> lodds, <span class="dt">group =</span> ulcera, <span class="dt">color =</span> ulcera)) <span class="op">+</span></a>
<a class="sourceLine" id="cb567-13" title="13"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb567-14" title="14"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb567-15" title="15"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Localización&quot;,</span></a>
<a class="sourceLine" id="cb567-16" title="16"><span class="st">       y = &quot;</span>log<span class="op">-</span><span class="kw">odds</span> (Aspirina <span class="op">==</span><span class="st"> </span>Si<span class="op">/</span>No)<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb567-17" title="17"><span class="st">       col = &quot;</span>Desarrollo de úlcera<span class="st">&quot;) </span></a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont014-1.png" width="672" /></p>
<p>Ajustamos un modelo con todas las interacciones dobles, ya que en este caso resulta imposible plantear el modelo con las interacción triple. Este modelo el que ya se planteo en el estudio de independencia.</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb568-1" title="1"><span class="co"># Ajuste del modelo sin interacción</span></a>
<a class="sourceLine" id="cb568-2" title="2">fit.aspirina &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>(locali <span class="op">+</span><span class="st"> </span>ulcera <span class="op">+</span><span class="st"> </span>aspirina)<span class="op">^</span><span class="dv">2</span>, </a>
<a class="sourceLine" id="cb568-3" title="3">              <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb568-4" title="4">              <span class="dt">data =</span> Aspirina)</a></code></pre></div>
<p>Para obtener los logits y probabilidades asociadas a cada categoría de la respuesta extraemos los coeficientes del modelo ajustado. Dado que solo nos interesan los efectos que están relaciondos directamente con la variable respuesta vamos a presentar únicamente dichos valores. Para saber los nombres de los coeficientes del modelo podemos utilizar el código siguiente identificando todos los efectos que están realcionados con la respuesta (efecto principal e interacciones).</p>
<p>En estos modelos utilizamos la función La función <code>tidy</code> para presentar la estimación del modelo selecionando las columnas necesarias.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb569-1" title="1">tabla &lt;-<span class="st"> </span><span class="kw">tidy</span>(fit.aspirina)[,<span class="kw">c</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;estimate&quot;</span>)]</a>
<a class="sourceLine" id="cb569-2" title="2">tabla</a></code></pre></div>
<pre><code>## # A tibble: 7 x 2
##   term                      estimate
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 (Intercept)                 3.75  
## 2 localiDuodenal              0.0698
## 3 ulceraNo                    0.321 
## 4 aspirinaSi                 -0.679 
## 5 localiDuodenal:ulceraNo    -0.106 
## 6 localiDuodenal:aspirinaSi  -0.700 
## 7 ulceraNo:aspirinaSi        -1.14</code></pre>
<p>Seleccionamos los efectos necesarios para el ajuste de los logits y la estimación de probabilidades. Estos efectos son los relacionados (principales e interacciones) con la variable <code>aspirina</code>.</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb571-1" title="1"><span class="co"># Filas de la tabla de estimaciones relacionados con metodo</span></a>
<a class="sourceLine" id="cb571-2" title="2">selefect&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>)</a>
<a class="sourceLine" id="cb571-3" title="3">tabla[selefect,]</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   term                      estimate
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 aspirinaSi                  -0.679
## 2 localiDuodenal:aspirinaSi   -0.700
## 3 ulceraNo:aspirinaSi         -1.14</code></pre>
<p>Dado que ambas variables son de tipo nominal y tomando como referencia la categoría “No” de consumo de aspirina, podemos obtener el logit del consumo de aspirina versus la categoria de referencia para cualquier combinación der categorias de las predictoras mediante:</p>
<p><span class="math display">\[log\left(\frac{\pi_{SI|jk}}{\pi_{No|jk}}\right) = (\alpha_{Si} - \alpha_{No}) + (\theta_{Si,jk} - \theta_{No,jk})\]</span></p>
<p>donde <span class="math inline">\(\alpha\)</span> hace referencia al efecto principal asociado con la respuesta (<code>aspirina</code>), y <span class="math inline">\(\theta\)</span> hace referencia al coeficiente de interacción entre la respuesta y los niveles <span class="math inline">\(j\)</span> y <span class="math inline">\(k\)</span> de localización de la úlcera (<code>locali</code>) y tener úlcera (<code>ulcera</code>) respectivamente. Si denotamos por <span class="math inline">\(A\)</span> al consumo de aspirina, <span class="math inline">\(L\)</span> la localización de la úlcera, y <span class="math inline">\(U\)</span> tener o no tener úlcera, para obtener el logit para un sujeto con <span class="math inline">\(U = No\)</span> y <span class="math inline">\(L = Duodenal\)</span> tendríamos que:</p>
<p><span class="math display">\[\eta_\text{Si| U = NO; L = Duodenal} = (\alpha_{Si} - \alpha_{No}) + (\theta_{Si,No,Duodenal} - \theta_{No,No,Duodenal})\]</span></p>
<p>donde <span class="math inline">\(\alpha_{Si} = -0.679\)</span>, <span class="math inline">\(\alpha_{No} = 0\)</span>, y <span class="math inline">\(\theta_{Si,No,Duodenal}\)</span>, <span class="math inline">\(\theta_{No,No,Duodenal}\)</span> representan las interacciones de la respuesta y predictoras para dicha combinación que vienen dadas por:</p>
<p><span class="math display">\[\begin{array}{ll}
\theta_{Si,No,Duodenal} &amp;= \theta_{Si,No} + \theta_{Si,Duodenal} = - 1.14 - 0.70 = - 1.84\\
\theta_{No,No,Duodenal} &amp;= \theta_{No,No} + \theta_{No,Duodenal} = 0 + 0 = 0\\
\end{array}\]</span></p>
<p>Para la estimación de los logits hya que tener en cuenta las restricciones de identificabilidad <span class="math inline">\(\alpha_{No} = 0\)</span> y <span class="math inline">\(\theta_{No,jk} = 0\)</span> para cualquier combinación de <span class="math inline">\(j\)</span> y <span class="math inline">\(k\)</span>, de forma que:</p>
<p><span class="math display">\[\begin{array}{lll}
\eta_\text{[Si| U = No; L = Duodenal]} &amp;= \alpha_{Si} + \theta_{Si,No} + \theta_{Si,Duodenal} &amp;= - 0.679 - 1.84 &amp;= -2.519\\
\eta_\text{[Si| U = No; L = Gástrica]} &amp; = \alpha_{Si} + \theta_{Si,No} + \theta_{Si,Gástrica} &amp;= - 0.679 - 1.14 + 0 &amp;= -1.819\\
\eta_\text{[Si| U = Si; L = Duodenal]} &amp; = \alpha_{Si} + \theta_{Si,Si} + \theta_{Si,Duodenal}&amp;= - 0.679 + 0 - 0.70 &amp;= -1.379\\
\eta_\text{[Si| U = Si; L = Gástrica]} &amp; = \alpha_{Si} + \theta_{Si,Si} + \theta_{Si,Gástrica}&amp;= - 0.679 + 0 + 0 &amp;= - 0.679\\
\end{array}\]</span></p>
<p>Podemos obtener ahora las probabilidades de consumo de aspirina para cada combinación de las predictoras:</p>
<p><span class="math display">\[\begin{array}{lll}
\pi_\text{[Si| U = NO; L = Duodenal]} &amp; =  exp(-2.519)/(1+exp(-2.519)) &amp;= 0.0745\\
\pi_\text{[Si| U = NO; L = Gástrica]} &amp; =  exp(-1.819)/(1+exp(-1.819)) &amp;= 0.1396\\
\pi_\text{[Si| U = Si; L = Duodenal]} &amp; =  exp(-1.379)/(1+exp(-1.379)) &amp;= 0.2012\\
\pi_\text{[Si| U = Si; L = Gástrica]} &amp; =  exp(-0.679)/(1+exp(-0.679)) &amp;= 0.3365\\
\end{array}\]</span></p>
<p>A la vista de estos resultados podemos concluir que la probabilidad de consumir aspirina dado un enfermo de úlcera duodenal es de 0.2012, mientras que para un enfermo de úlcera gástrica dicha probabilidad es de 0.3365. Podemos concluir que la probabilidad del consumo de aspirina es superior en los enfermos con úlcera gástrica que en la duodenal, y mayor en los sujetos enfermos que en los controles.</p>
<p>Las probabilidades anteriores se puden obtener de forma un poco más directa a partir de los valores predichos del modelo.</p>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb573-1" title="1"><span class="co"># Calculamos los conteos predichos del modelo</span></a>
<a class="sourceLine" id="cb573-2" title="2">conteos &lt;-<span class="st"> </span><span class="kw">predict</span>(fit.aspirina, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb573-3" title="3"><span class="co"># Combinamos los datos originales con los predichos</span></a>
<a class="sourceLine" id="cb573-4" title="4">newdata &lt;-<span class="st"> </span><span class="kw">cbind</span>(Aspirina, conteos)</a>
<a class="sourceLine" id="cb573-5" title="5"><span class="co"># Calculamos el conteo total por las predictoras</span></a>
<a class="sourceLine" id="cb573-6" title="6">newdata.sum &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(locali, ulcera) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb573-7" title="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">suma =</span> <span class="kw">sum</span>(conteos))</a>
<a class="sourceLine" id="cb573-8" title="8"><span class="co"># Calculamos las probabilidades asociadas a cada combinación</span></a>
<a class="sourceLine" id="cb573-9" title="9">newdata &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb573-10" title="10"><span class="st">  </span><span class="kw">left_join</span>(newdata.sum, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;locali&quot;</span>,<span class="st">&quot;ulcera&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb573-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">round</span>(conteos<span class="op">/</span>suma,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb573-12" title="12"><span class="co"># Vemos las probabiliddes obtenidas</span></a>
<a class="sourceLine" id="cb573-13" title="13">dplyr<span class="op">::</span><span class="kw">select</span>(newdata,<span class="kw">c</span>(locali, ulcera, aspirina, prob))</a></code></pre></div>
<pre><code>##     locali ulcera aspirina   prob
## 1 Gástrica     Si       No 0.6635
## 2 Gástrica     No       No 0.8608
## 3 Duodenal     Si       No 0.7988
## 4 Duodenal     No       No 0.9257
## 5 Gástrica     Si       Si 0.3365
## 6 Gástrica     No       Si 0.1392
## 7 Duodenal     Si       Si 0.2012
## 8 Duodenal     No       Si 0.0743</code></pre>
<p>Podemos representar las probabilidades obtenidas para ver los efectos de la combinacion de predictoras en la respuesta.</p>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb575-1" title="1"><span class="kw">ggplot</span>(newdata, <span class="kw">aes</span>(<span class="dt">x =</span> locali, <span class="dt">y =</span> prob, <span class="dt">group =</span> ulcera, <span class="dt">color =</span> ulcera)) <span class="op">+</span></a>
<a class="sourceLine" id="cb575-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb575-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb575-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>aspirina) <span class="op">+</span></a>
<a class="sourceLine" id="cb575-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Consumo de aspirina&quot;</span>,</a>
<a class="sourceLine" id="cb575-6" title="6">       <span class="dt">x =</span> <span class="st">&quot;Localización de la úlcera&quot;</span>,</a>
<a class="sourceLine" id="cb575-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Probabilidad&quot;</span>,</a>
<a class="sourceLine" id="cb575-8" title="8">       <span class="dt">col =</span> <span class="st">&quot;Úlcera&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb575-9" title="9"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>), <span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont019-1.png" width="672" /></p>
</div>
</div>
<div id="respuesta-multinomial-nominal-y-predictora-nominal" class="section level2">
<h2><span class="header-section-number">14.2</span> Respuesta multinomial nominal y predictora nominal</h2>
<p>Cuando tenemos más de dos categorías el procedimiento es bastante similar. En este caso tomamos la última categoria <span class="math inline">\(I\)</span> como referencia, de forma que los log-odds se pueden expresar como:</p>
<p><span class="math display">\[log\left(\frac{\pi_{i|j}}{\pi_{I|j}}\right) = \eta_{i|j} = (\alpha_i -\alpha_I) + (\alpha\beta_{ij} - \alpha\beta_{Ij})\]</span></p>
<p>A partir del logit anterior para cada categoría <span class="math inline">\(i\)</span>,podemos obtener la probabilidad condicionada de dicha categoría <span class="math inline">\(i\)</span> como:</p>
<p><span class="math display">\[\pi_{i|j} = \frac{exp(\eta_{i|j})}{\sum_{l=1}^I exp(\eta_{l|j})}\]</span></p>
<p>Puesto que <span class="math inline">\(exp(\eta_{I|j}) = 1\)</span> dicha probabilidad se puede expresar como:</p>
<p><span class="math display">\[\pi_{i|j} = \frac{exp(\eta_{i|j})}{1 + \sum_{l \neq I} exp(\eta_{l|j})}\]</span></p>
<p>Esta expresión es similar a la de dos categorías salvo por la modificación del denominador, donde se incluyen los predictores, <span class="math inline">\(\eta\)</span>, asociados a todas las categorías de la respuesta.</p>
</div>
<div id="respuesta-nominal-predictora-ordinal" class="section level2">
<h2><span class="header-section-number">14.3</span> Respuesta nominal, predictora ordinal</h2>
<p>Esta situación es miliar a la anterior salvo por el carácter ordinal de la predictora. Para estimar dichos modelos debemos incluir una variable ficticia (<span class="math inline">\(S\)</span>) que contendrá los scores asociados con las categorías de la predictora. Si <span class="math inline">\(v_1=1, v_2=2,...,v_J=J\)</span> denota a los scores asociados con la varaible ordinal, el logit asociado a esta situación se puede expresar mediante:</p>
<p><span class="math display">\[log\left(\frac{\pi_{i|j}}{\pi_{I|j}}\right) = \eta_{i|j} = (\alpha_i -\alpha_I) + (\alpha\beta_{ij} - \alpha\beta_{Ij})v_j\]</span></p>
<p>donde las interacciones entre la respuesta y la predictora se modifican a través del score definido, para introducir el efecto ordinal entre las comninaciones, de forma que los cocientes de probabilidades se obtienen como</p>
<p><span class="math display">\[\frac{\pi_{i|j}}{\pi_{I|j}} = exp(\eta_{i|j}) = exp\{(\alpha_i -\alpha_I) + (\alpha\beta_{ij} - \alpha\beta_{Ij})v_j\}\]</span></p>
<p>de forma que la probabilidad de una categoría <span class="math inline">\(i\)</span> viene dada por:</p>
<p><span class="math display">\[\pi_{i|j} = \frac{exp(\eta_{i|j})}{1 + \sum_{l \neq I} exp(\eta_{l|j})}\]</span></p>
<div id="datos-aspiraciones-universitarias" class="section level3">
<h3><span class="header-section-number">14.3.1</span> Datos Aspiraciones universitarias</h3>
<p>Si tomamos como variable respuesta las aspiraciones universitarias en función del estatus económico y de la motivación familiar, y usamos como referencia la categoría <code>No</code> podemos obtener el log-odd de la categoría <code>Si</code> mediante:</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb576-1" title="1"><span class="co"># Creamos variable con valores de referencia y obtenemos los log-odds asociados</span></a>
<a class="sourceLine" id="cb576-2" title="2">referencia.val &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Aspiraciones, aspiraciones <span class="op">==</span><span class="st"> &quot;No&quot;</span>),</a>
<a class="sourceLine" id="cb576-3" title="3">                                       frecuencia))</a>
<a class="sourceLine" id="cb576-4" title="4">Aspiraciones &lt;-<span class="st"> </span>Aspiraciones <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb576-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">referencia =</span> <span class="kw">rep</span>(referencia.val, <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb576-6" title="6">         <span class="dt">lodds =</span> <span class="kw">log</span>(frecuencia <span class="op">/</span><span class="st"> </span>referencia))</a>
<a class="sourceLine" id="cb576-7" title="7"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb576-8" title="8"><span class="co"># Seleccionamos las categorías a representar eliminando la de referencia</span></a>
<a class="sourceLine" id="cb576-9" title="9"><span class="co"># Como la respuesta sólo tiene una categoría no hace falta utilizarla en el gráfico</span></a>
<a class="sourceLine" id="cb576-10" title="10">datos &lt;-<span class="st"> </span><span class="kw">filter</span>(Aspiraciones, aspiraciones <span class="op">!=</span><span class="st"> &quot;No&quot;</span>)</a>
<a class="sourceLine" id="cb576-11" title="11"><span class="kw">ggplot</span>(datos,<span class="kw">aes</span>(<span class="dt">x =</span> estatus, <span class="dt">y =</span> lodds, <span class="dt">group =</span> motivacion, <span class="dt">color =</span> motivacion)) <span class="op">+</span></a>
<a class="sourceLine" id="cb576-12" title="12"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb576-13" title="13"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb576-14" title="14"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Estatus Socioeconómico&quot;,</span></a>
<a class="sourceLine" id="cb576-15" title="15"><span class="st">       y = &quot;</span>log<span class="op">-</span><span class="kw">odds</span> (Aspiraciones <span class="op">==</span><span class="st"> </span>Si <span class="op">/</span><span class="st"> </span>No)<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb576-16" title="16"><span class="st">       col = &quot;</span>Motivacion<span class="st">&quot;)</span></a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont020-1.png" width="672" /></p>
<p>Se observa una tendencia creciente (puede incluso que no lineal) conforme aumenta el estatus económico, que va relacionada directamente con una motivación más alta en el entorno familiar (comportamiento casi paralelo para ambas motivaciones).</p>
<p>Para el ajuste de este modelo debemos considerar los scores asociados a cada una de las predictoras ordinales (<code>estatus.num</code> y <code>motivacion.num</code>) tal y como los definimos al presentar este banco de datos. En primer lugar ajustamos el modelo para estudiar asociación eliminando la interacción de orden 3.</p>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb577-1" title="1"><span class="co"># Ajuste del modelo sin interacción triple</span></a>
<a class="sourceLine" id="cb577-2" title="2">fit.aspiraciones.aso &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>(estatus <span class="op">+</span><span class="st"> </span>motivacion <span class="op">+</span><span class="st"> </span>aspiraciones)<span class="op">^</span><span class="dv">2</span>, </a>
<a class="sourceLine" id="cb577-3" title="3">                          <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb577-4" title="4">                          <span class="dt">data =</span> Aspiraciones)</a>
<a class="sourceLine" id="cb577-5" title="5"><span class="co"># Bondad del asjute del modelo</span></a>
<a class="sourceLine" id="cb577-6" title="6"><span class="dv">1</span><span class="op">-</span><span class="kw">pchisq</span>(fit.aspiraciones.aso<span class="op">$</span>deviance, fit.aspiraciones.aso<span class="op">$</span>df.residual)</a></code></pre></div>
<pre><code>## [1] 0.664965</code></pre>
<p>No podemos rechazar la interacción triple. Ajustamos un nuevo modelo eliminando la interacción doble entre <code>estatus</code> y <code>motivacion</code> dado que los prefiles de los logits parecían paralelos.</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb579-1" title="1"><span class="co"># Ajuste del modelo sin interacción triple</span></a>
<a class="sourceLine" id="cb579-2" title="2">fit.aspiraciones.aso2 &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>estatus <span class="op">+</span><span class="st"> </span>motivacion <span class="op">+</span><span class="st"> </span>aspiraciones <span class="op">+</span><span class="st"> </span>estatus<span class="op">:</span>aspiraciones <span class="op">+</span><span class="st"> </span>motivacion<span class="op">:</span>aspiraciones, </a>
<a class="sourceLine" id="cb579-3" title="3">                          <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb579-4" title="4">                          <span class="dt">data =</span> Aspiraciones)</a>
<a class="sourceLine" id="cb579-5" title="5"><span class="co"># Bondad del ajuste</span></a>
<a class="sourceLine" id="cb579-6" title="6"><span class="dv">1</span><span class="op">-</span><span class="kw">pchisq</span>(fit.aspiraciones.aso2<span class="op">$</span>deviance, fit.aspiraciones.aso2<span class="op">$</span>df.residual)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb581-1" title="1"><span class="co"># Comapramos con el modelo anterior</span></a>
<a class="sourceLine" id="cb581-2" title="2"><span class="kw">anova</span>(fit.aspiraciones.aso2, fit.aspiraciones.aso, <span class="dt">test =</span><span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: frecuencia ~ estatus + motivacion + aspiraciones + estatus:aspiraciones + 
##     motivacion:aspiraciones
## Model 2: frecuencia ~ (estatus + motivacion + aspiraciones)^2
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1         6    298.485                          
## 2         3      1.575  3   296.91 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>El p-valor resulta significativo dando indicaciones de que la interacción <code>estatus:motivacion</code> no es relevante pero este modelo si que es distinto del modelo saturado. Ajustamos este modelo teniendo en cuenta los scores:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb583-1" title="1"><span class="co"># Debemos incluir el efecto de las predictoras como factor principal </span></a>
<a class="sourceLine" id="cb583-2" title="2"><span class="co"># para mantener la estructura del modelo</span></a>
<a class="sourceLine" id="cb583-3" title="3">fit.aspiraciones &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>estatus <span class="op">+</span><span class="st"> </span>motivacion <span class="op">+</span><span class="st"> </span>aspiraciones <span class="op">+</span><span class="st"> </span>aspiraciones<span class="op">*</span>(estatus.num <span class="op">+</span><span class="st"> </span>motivacion.num), </a>
<a class="sourceLine" id="cb583-4" title="4">                          <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb583-5" title="5">                          <span class="dt">data =</span> Aspiraciones)</a></code></pre></div>
<p>Obtenemos la tabla de estimación para el modelo:</p>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb584-1" title="1">tabla &lt;-<span class="st"> </span><span class="kw">tidy</span>(fit.aspiraciones)[,<span class="kw">c</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;estimate&quot;</span>)]</a>
<a class="sourceLine" id="cb584-2" title="2">tabla</a></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##    term                          estimate
##    &lt;chr&gt;                            &lt;dbl&gt;
##  1 (Intercept)                     6.42  
##  2 estatusMedia-Baja              -0.0318
##  3 estatusMedia-Alta              -0.307 
##  4 estatusAlta                    -0.780 
##  5 motivacionAlta                 -0.482 
##  6 aspiracionesSi                 -7.81  
##  7 estatus.num                    NA     
##  8 motivacion.num                 NA     
##  9 aspiracionesSi:estatus.num      0.806 
## 10 aspiracionesSi:motivacion.num   3.01</code></pre>
<p>Seleccionamos los efectos necesarios para el ajuste de los logits y la estimación de probabilidades. Estos efectos son los relacionados (principales e interacciones) con la variable <code>aspiraciones</code>.</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb586-1" title="1"><span class="co"># Filas de la tabla de estimaciones relacionados con metodo</span></a>
<a class="sourceLine" id="cb586-2" title="2">tabla[<span class="dv">6</span><span class="op">:</span><span class="dv">8</span>,]</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   term           estimate
##   &lt;chr&gt;             &lt;dbl&gt;
## 1 aspiracionesSi    -7.81
## 2 estatus.num       NA   
## 3 motivacion.num    NA</code></pre>
<p>Con una variable respuesta nominal y una predictora ordinal la ecuació del logit (tomando la categoría <code>No</code> como referencia) se pueden obtener de forma sencilla a partir de las ecuaciones descritas anteriormente. La expresión del logit en función de los niveles de las predictoras viene dada por:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{Si,jk}}}{\pi_{\text{No,jk}}}\right) = (\alpha_{\text{Si}} - \alpha_{\text{No}}) + (\theta_{Si,j} - \theta_{No,j}) v_j + (\gamma_{Si,k} - \gamma_{No,k}) w_k \\ = \alpha_{\text{Si}} + \theta_{Si,j} v_j + \gamma_{Si,k} w_k\]</span></p>
<p>donde los <span class="math inline">\(\alpha\)</span> representan los efectos principales de <code>aspiraciones</code>, <span class="math inline">\(\theta\)</span> los efectos de las interacciones entre <code>aspiraciones</code> y <code>estatus</code>, <span class="math inline">\(\gamma\)</span> los efectos de las interacciones entre <code>aspiraciones</code> y <code>motivacion</code>, los <span class="math inline">\(v_j\)</span> son los scores de <code>estatus</code>, y los <span class="math inline">\(\gamma_k\)</span> son los scores de <code>motivacion</code>. Sustituyendo tendríamos:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{Si,jk}}}{\pi_{\text{No,jk}}}\right) = - 7.81 + 0.806 v_j + 3.01 w_k\]</span></p>
<p>Dando valores a <span class="math inline">\(v_j\)</span> (de 1 a 4) y a <span class="math inline">\(w_k\)</span> (de 1 a 2) podemos obtener el logit asociado con la variable respuesta. En este caso pasamos directamente a estimar las probabilidades de cada combinación.</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb588-1" title="1"><span class="co"># Calculamos los conteos predichos del modelo</span></a>
<a class="sourceLine" id="cb588-2" title="2">conteos &lt;-<span class="st"> </span><span class="kw">predict</span>(fit.aspiraciones, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb588-3" title="3"><span class="co"># Combinamos los datos originales con los predichos</span></a>
<a class="sourceLine" id="cb588-4" title="4">newdata &lt;-<span class="st"> </span><span class="kw">cbind</span>(Aspiraciones, conteos)</a>
<a class="sourceLine" id="cb588-5" title="5"><span class="co"># Calculamos el conteo total por las predictoras</span></a>
<a class="sourceLine" id="cb588-6" title="6">newdata.sum &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(estatus, motivacion) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb588-7" title="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">suma =</span> <span class="kw">sum</span>(conteos))</a>
<a class="sourceLine" id="cb588-8" title="8"><span class="co"># Calculamos las probabilidades asociadas a cada combinación</span></a>
<a class="sourceLine" id="cb588-9" title="9">newdata &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb588-10" title="10"><span class="st">  </span><span class="kw">left_join</span>(newdata.sum, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;estatus&quot;</span>, <span class="st">&quot;motivacion&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb588-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">round</span>(conteos<span class="op">/</span>suma,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb588-12" title="12"><span class="co"># Vemos las probabiliddes obtenidas</span></a>
<a class="sourceLine" id="cb588-13" title="13">dplyr<span class="op">::</span><span class="kw">select</span>(newdata,<span class="kw">c</span>(estatus, motivacion, aspiraciones, prob))</a></code></pre></div>
<pre><code>##       estatus motivacion aspiraciones   prob
## 1        Baja       Baja           No 0.9819
## 2        Baja       Alta           No 0.7282
## 3  Media-Baja       Baja           No 0.9604
## 4  Media-Baja       Alta           No 0.5448
## 5  Media-Alta       Baja           No 0.9156
## 6  Media-Alta       Alta           No 0.3484
## 7        Alta       Baja           No 0.8289
## 8        Alta       Alta           No 0.1928
## 9        Baja       Baja           Si 0.0181
## 10       Baja       Alta           Si 0.2718
## 11 Media-Baja       Baja           Si 0.0396
## 12 Media-Baja       Alta           Si 0.4552
## 13 Media-Alta       Baja           Si 0.0844
## 14 Media-Alta       Alta           Si 0.6516
## 15       Alta       Baja           Si 0.1711
## 16       Alta       Alta           Si 0.8072</code></pre>
<p>Podemos representar las probabilidades obtenidas para ver los efectos de la combinacion de predictoras en la respuesta.</p>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb590-1" title="1"><span class="kw">ggplot</span>(newdata, <span class="kw">aes</span>(<span class="dt">x =</span> estatus, <span class="dt">y =</span> prob, <span class="dt">group =</span> aspiraciones, <span class="dt">color =</span> aspiraciones)) <span class="op">+</span></a>
<a class="sourceLine" id="cb590-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb590-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb590-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>motivacion) <span class="op">+</span></a>
<a class="sourceLine" id="cb590-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probabilidades estimadas por motivacion&quot;</span>,</a>
<a class="sourceLine" id="cb590-6" title="6">       <span class="dt">x =</span> <span class="st">&quot;Edad&quot;</span>,</a>
<a class="sourceLine" id="cb590-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Probabilidad&quot;</span>,</a>
<a class="sourceLine" id="cb590-8" title="8">       <span class="dt">col =</span> <span class="st">&quot;Método anticonceptivo&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb590-9" title="9"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>), <span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont027-1.png" width="672" /></p>
</div>
<div id="datos-de-contraceptivos" class="section level3">
<h3><span class="header-section-number">14.3.2</span> Datos de Contraceptivos</h3>
<p>Si tomamos como variable respuesta el método anticonceptivo utilizado, y usamos como referencia la categroria <code>Ninguno</code> podemos obtener los log-odds de la otras dos categorías como:</p>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb591-1" title="1"><span class="co"># Creamos variable con valores de referencia y obtenemos los log-odds asociados</span></a>
<a class="sourceLine" id="cb591-2" title="2">referencia.val &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Contraceptivos, metodo <span class="op">==</span><span class="st"> &quot;Ninguno&quot;</span>), frecuencia))</a>
<a class="sourceLine" id="cb591-3" title="3">Contraceptivos &lt;-<span class="st"> </span>Contraceptivos <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb591-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">referencia =</span> <span class="kw">rep</span>(referencia.val, <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb591-5" title="5">         <span class="dt">lodds =</span> <span class="kw">log</span>(frecuencia <span class="op">/</span><span class="st"> </span>referencia))</a>
<a class="sourceLine" id="cb591-6" title="6"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb591-7" title="7"><span class="co"># Seleccionamos las categorías a representar eliminando la de referencia</span></a>
<a class="sourceLine" id="cb591-8" title="8"><span class="co"># Como la respuesta sólo tiene una categoría no hace falta utilizarla en el gráfico</span></a>
<a class="sourceLine" id="cb591-9" title="9">datos &lt;-<span class="st"> </span><span class="kw">filter</span>(Contraceptivos, metodo <span class="op">!=</span><span class="st"> &quot;Ninguno&quot;</span>)</a>
<a class="sourceLine" id="cb591-10" title="10"><span class="kw">ggplot</span>(datos,<span class="kw">aes</span>(<span class="dt">x =</span> edad, <span class="dt">y =</span> lodds, <span class="dt">group =</span> metodo, <span class="dt">color =</span> metodo)) <span class="op">+</span></a>
<a class="sourceLine" id="cb591-11" title="11"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb591-12" title="12"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb591-13" title="13"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Grupo de edad&quot;</span>,</a>
<a class="sourceLine" id="cb591-14" title="14">       <span class="dt">y =</span> <span class="st">&quot;log-odds (Ref: Método == Ninguno)&quot;</span>,</a>
<a class="sourceLine" id="cb591-15" title="15">       <span class="dt">col =</span> <span class="st">&quot;Método anticonceptivo&quot;</span>) </a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont028-1.png" width="672" /></p>
<p>Se observan claramente tendencias cuadráticas distintas para cada método asociadas con el grupo de edad considerado. Aprovecharemos el carácter ordinal de dicha variable para incluir una nueva variable que contenga la marca de clase de cada grupo de edad (score), que nos permita ajustar el modelo cuadrático con edad.</p>
<p>Dado que sólo tenemos una predictora vamos a ajustar un modelo sólo con efectos principales. Estudiamos la bondad del ajuste de dicho modelo para conocer el patrón de asociación entre las variables. Si desechamos la interacción doble concluiríamos que no existe asociación entre edad y método contraceptivo. En caso contrario deberíamos establecer el modelo de asociación entre ambas variables. El gráfico de log-odds muestra cierto grado de asociación de tipo cuadrático con la edad. Se debe explorar la posibilidd de un modelo de interacción con la variable de scores de edad asumiendo un modelo cuadrático.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb592-1" title="1"><span class="co"># Ajuste del modelo sin interacción</span></a>
<a class="sourceLine" id="cb592-2" title="2">fit.contraceptivos.aso &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>edad <span class="op">+</span><span class="st"> </span>metodo, </a>
<a class="sourceLine" id="cb592-3" title="3">                          <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb592-4" title="4">                          <span class="dt">data =</span> Contraceptivos)</a>
<a class="sourceLine" id="cb592-5" title="5"><span class="co"># Bondad del asjute del modelo</span></a>
<a class="sourceLine" id="cb592-6" title="6"><span class="dv">1</span><span class="op">-</span><span class="kw">pchisq</span>(fit.contraceptivos.aso<span class="op">$</span>deviance, fit.contraceptivos.aso<span class="op">$</span>df.residual)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Rechazamos la hipótesis de independencia. Ajustamos el modelo de interacción cuadrático con los scores de la variable edad que ya fijamos en la presentación del banco de datos (punto medio de los intervalos de edad). En este modelo incluimos la edad como factor principal, y los scores de la edad en interacción con la variable método anticonceptivo.</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb594-1" title="1"><span class="co"># Ajuste del modelo con efecto cuadrático en edad</span></a>
<a class="sourceLine" id="cb594-2" title="2"><span class="co"># Debemos incluir el efecto edad como factor principal </span></a>
<a class="sourceLine" id="cb594-3" title="3"><span class="co"># para mantener la estructura del modelo</span></a>
<a class="sourceLine" id="cb594-4" title="4">fit.contraceptivos &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>edad <span class="op">+</span><span class="st"> </span>metodo<span class="op">*</span>(edad.num <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(edad.num<span class="op">^</span><span class="dv">2</span>)), </a>
<a class="sourceLine" id="cb594-5" title="5">                          <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb594-6" title="6">                          <span class="dt">data =</span> Contraceptivos)</a></code></pre></div>
<p>Comparamos los dos modelos obtenidos para validar la inclusión de la variable de scores de edad</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb595-1" title="1"><span class="kw">anova</span>(fit.contraceptivos.aso, fit.contraceptivos, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: frecuencia ~ edad + metodo
## Model 2: frecuencia ~ edad + metodo * (edad.num + I(edad.num^2))
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1        12     521.10                          
## 2         8      20.47  4   500.63 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Dado que el p-valor resulta significativo podemos conluir que ambos modelos son distintos.</p>
<p>Obtenemos la tabla de estimación para el modelo:</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb597-1" title="1">tabla &lt;-<span class="st"> </span><span class="kw">tidy</span>(fit.contraceptivos)[,<span class="kw">c</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;estimate&quot;</span>)]</a>
<a class="sourceLine" id="cb597-2" title="2">tabla</a></code></pre></div>
<pre><code>## # A tibble: 15 x 2
##    term                        estimate
##    &lt;chr&gt;                          &lt;dbl&gt;
##  1 (Intercept)                  2.26   
##  2 edad20-24                    2.14   
##  3 edad25-29                    3.04   
##  4 edad30-34                    3.28   
##  5 edad35-39                    3.16   
##  6 edad40-44                    2.78   
##  7 edad45-49                    2.13   
##  8 metodoOtros                  7.85   
##  9 metodoNinguno               12.3    
## 10 edad.num                    NA      
## 11 I(edad.num^2)               NA      
## 12 metodoOtros:edad.num        -0.441  
## 13 metodoNinguno:edad.num      -0.700  
## 14 metodoOtros:I(edad.num^2)    0.00497
## 15 metodoNinguno:I(edad.num^2)  0.00973</code></pre>
<p>Seleccionamos los efectos necesarios para el ajuste de los logits y la estimación de probabilidades. Estos efectos son los relacionados (principales e interacciones) con la variable <code>metodo</code>.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb599-1" title="1"><span class="co"># Filas de la tabla de estimaciones relacionados con metodo</span></a>
<a class="sourceLine" id="cb599-2" title="2">tabla[<span class="dv">8</span><span class="op">:</span><span class="dv">13</span>,]</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   term                   estimate
##   &lt;chr&gt;                     &lt;dbl&gt;
## 1 metodoOtros               7.85 
## 2 metodoNinguno            12.3  
## 3 edad.num                 NA    
## 4 I(edad.num^2)            NA    
## 5 metodoOtros:edad.num     -0.441
## 6 metodoNinguno:edad.num   -0.700</code></pre>
<p>Con una variable respuesta nominal y una predictora ordinal la ecuació del logit (tomando la categoría <code>Ninguno</code> como referencia) se pueden obtener de forma sencilla a partir de las ecuaciones descritas anteriormente. Para simplificar las expresiones utilizamos la codificación de categorias de la variable <code>metodo</code>: <code>Esterilizacion = E</code>, <code>Ninguno = N</code>, y <code>Otros = O</code>. Las expresiones de los logits en función de la edad son:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{E,j}}}{\pi_{\text{N,j}}}\right) = (\alpha_{\text{E}} - \alpha_{\text{N}}) + (\theta_{E,j} - \theta_{N,j}) v_j + (\theta^2_{E,j} - \theta^2_{N,j}) v^2_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{O,j}}}{\pi_{\text{N,j}}}\right) = (\alpha_{\text{O}} - \alpha_{\text{N}}) + (\theta_{O,j} - \theta_{N,j}) v_j + (\theta^2_{O,j} - \theta^2_{N,j}) v^2_j\]</span></p>
<p>donde los <span class="math inline">\(\alpha\)</span> representan los efectos principales, <span class="math inline">\(\theta\)</span> los efectos de las interacciones con el efecto lineal del score, <span class="math inline">\(\theta^2\)</span> los efectos de las interacciones con el efecto cuadrático del score, y los <span class="math inline">\(v_j\)</span> son los scores de la edad. Sustituyendo tendríamos:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{E,j}}}{\pi_{\text{N,j}}}\right) = (0 - 12.30) + (0 + 0.70) v_j + (0 - 0.00973) v^2_j \\ = - 12.30 + 0.70 v_j - 0.00973 v^2_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{O,j}}}{\pi_{\text{N,j}}}\right) = (7.85 - 12.30) + (-0.441 + 0.70) v_j + (0.00497 - 0.00973) v^2_j \\ = - 4.45 + 0.259 v_j - 0.00476 v^2_j\]</span></p>
<p>Podemos representar los logits obtenidos en función de la edad:</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb601-1" title="1"><span class="co"># Secuencia de edad</span></a>
<a class="sourceLine" id="cb601-2" title="2">edadsec &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">15</span>,<span class="dv">49</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb601-3" title="3"><span class="co"># Valores logit comparada con la de referencia</span></a>
<a class="sourceLine" id="cb601-4" title="4">EvsN &lt;-<span class="st"> </span><span class="op">-</span><span class="st"> </span><span class="fl">12.30</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.70</span><span class="op">*</span>edadsec <span class="op">-</span><span class="st"> </span><span class="fl">0.00973</span><span class="op">*</span>edadsec<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb601-5" title="5">OvsN &lt;-<span class="st"> </span><span class="op">-</span><span class="st"> </span><span class="fl">4.45</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.259</span><span class="op">*</span>edadsec <span class="op">-</span><span class="st"> </span><span class="fl">0.00476</span><span class="op">*</span>edadsec<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb601-6" title="6"><span class="co"># Configuración de datos para logits</span></a>
<a class="sourceLine" id="cb601-7" title="7">edad &lt;-<span class="st"> </span><span class="kw">rep</span>(edadsec,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb601-8" title="8">combinacion &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;E versus N&quot;</span>,<span class="kw">length</span>(edadsec)), <span class="kw">rep</span>(<span class="st">&quot;O versus N&quot;</span>,<span class="kw">length</span>(edadsec)))</a>
<a class="sourceLine" id="cb601-9" title="9">logits &lt;-<span class="st"> </span><span class="kw">c</span>(EvsN, OvsN)</a>
<a class="sourceLine" id="cb601-10" title="10">datoscom &lt;-<span class="st"> </span><span class="kw">data.frame</span>(edad, combinacion, logits)</a>
<a class="sourceLine" id="cb601-11" title="11"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb601-12" title="12"><span class="kw">ggplot</span>(datoscom, <span class="kw">aes</span>(<span class="dt">x =</span> edad, <span class="dt">y =</span> logits, <span class="dt">group =</span> combinacion, <span class="dt">color =</span> combinacion)) <span class="op">+</span></a>
<a class="sourceLine" id="cb601-13" title="13"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb601-14" title="14"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Logits por edad&quot;</span>, </a>
<a class="sourceLine" id="cb601-15" title="15">       <span class="dt">y =</span> <span class="st">&quot;Logits&quot;</span>, </a>
<a class="sourceLine" id="cb601-16" title="16">       <span class="dt">x =</span> <span class="st">&quot;Edad&quot;</span>,</a>
<a class="sourceLine" id="cb601-17" title="17">       <span class="dt">col =</span> <span class="st">&quot;Comparación&quot;) </span></a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont034-1.png" width="672" /></p>
<p>Los logits estimados reproducen el comportamiento observado en los logits empíricos.</p>
<p>Por último obtnemos las probabilidades de cada combinación, que en este caso su evolución como función de la edad. En lugar de evaluar los logits utilizaremos la función predict para evaluar dichas probabildiades y representarlas gráficamente.</p>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb602-1" title="1"><span class="co"># Calculamos los conteos predichos del modelo</span></a>
<a class="sourceLine" id="cb602-2" title="2">conteos &lt;-<span class="st"> </span><span class="kw">predict</span>(fit.contraceptivos, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb602-3" title="3"><span class="co"># Combinamos los datos originales con los predichos</span></a>
<a class="sourceLine" id="cb602-4" title="4">newdata &lt;-<span class="st"> </span><span class="kw">cbind</span>(Contraceptivos, conteos)</a>
<a class="sourceLine" id="cb602-5" title="5"><span class="co"># Calculamos el conteo total por las predictoras</span></a>
<a class="sourceLine" id="cb602-6" title="6">newdata.sum &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(edad) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb602-7" title="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">suma =</span> <span class="kw">sum</span>(conteos))</a>
<a class="sourceLine" id="cb602-8" title="8"><span class="co"># Calculamos las probabilidades asociadas a cada combinación</span></a>
<a class="sourceLine" id="cb602-9" title="9">newdata &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb602-10" title="10"><span class="st">  </span><span class="kw">left_join</span>(newdata.sum, <span class="dt">by =</span> <span class="st">&quot;edad&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb602-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">round</span>(conteos<span class="op">/</span>suma,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb602-12" title="12"><span class="co"># Vemos las probabiliddes obtenidas</span></a>
<a class="sourceLine" id="cb602-13" title="13">dplyr<span class="op">::</span><span class="kw">select</span>(newdata,<span class="kw">c</span>(edad, metodo, prob))</a></code></pre></div>
<pre><code>##     edad         metodo   prob
## 1  15-19 Esterilización 0.0322
## 2  20-24 Esterilización 0.1318
## 3  25-29 Esterilización 0.3086
## 4  30-34 Esterilización 0.4632
## 5  35-39 Esterilización 0.5192
## 6  40-44 Esterilización 0.4572
## 7  45-49 Esterilización 0.2832
## 8  15-19          Otros 0.1936
## 9  20-24          Otros 0.2306
## 10 25-29          Otros 0.2018
## 11 30-34          Otros 0.1451
## 12 35-39          Otros 0.0999
## 13 40-44          Otros 0.0693
## 14 45-49          Otros 0.0434
## 15 15-19        Ninguno 0.7741
## 16 20-24        Ninguno 0.6376
## 17 25-29        Ninguno 0.4895
## 18 30-34        Ninguno 0.3917
## 19 35-39        Ninguno 0.3809
## 20 40-44        Ninguno 0.4734
## 21 45-49        Ninguno 0.6734</code></pre>
<p>Podemos representar las probabilidades obtenidas para ver los efectos de la combinacion de predictoras en la respuesta.</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb604-1" title="1"><span class="kw">ggplot</span>(newdata, <span class="kw">aes</span>(<span class="dt">x =</span> edad, <span class="dt">y =</span> prob, <span class="dt">group =</span> metodo, <span class="dt">color =</span> metodo)) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb604-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb604-4" title="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probabilidades estimadas&quot;</span>,</a>
<a class="sourceLine" id="cb604-5" title="5">       <span class="dt">x =</span> <span class="st">&quot;Edad&quot;</span>,</a>
<a class="sourceLine" id="cb604-6" title="6">       <span class="dt">y =</span> <span class="st">&quot;Probabilidad&quot;</span>,</a>
<a class="sourceLine" id="cb604-7" title="7">       <span class="dt">col =</span> <span class="st">&quot;Método anticonceptivo&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-8" title="8"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>), <span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont036-1.png" width="672" /></p>
<p>¿Qué conclusiones podemos extraer de este gráfico? ¿qué método predomina en el grupo de 20 a 24 años? ¿y en l grupo 40 a 44?</p>
</div>
</div>
<div id="respuesta-ordinal-predictora-nominal" class="section level2">
<h2><span class="header-section-number">14.4</span> Respuesta ordinal, predictora nominal</h2>
<p>Cuando la variable respuesta tiene carácter ordinal el proceso de estimación debe variar para tener en cuenta dicho carácter. En esta situación no obtenemos los logit de una categoría con respecto a la de referencia sino que procedemos construyendo los logit de dos categorías consecutivas</p>
<p><span class="math display">\[log\left(\frac{\pi_{i+1|j}}{\pi_{i|j}}\right)\]</span></p>
<p>para valorar el incremento que sufre la probabilidad de un categoría con respecto a su categoría superior.</p>
<p>Para estimar dichos modelos debemos incluir una variable ficticia (<span class="math inline">\(S\)</span>) que contendrá los scores asociados con las categorías de la respuesta. Si <span class="math inline">\(u_1=1, u_2=2,...,u_n=n\)</span> denotan dichos scores y sólo tenemos una variable predictora, el logit anterior se puede obtener fácilmente mediante:</p>
<p><span class="math display">\[log(E(Y_{ij})) = \mu +\alpha_i + \beta_j + \theta_j S_i\]</span></p>
<p>donde <span class="math inline">\(\mu\)</span> es la interceptación del modelo, <span class="math inline">\(\alpha_i\)</span> es el efecto asociado con el nivel <span class="math inline">\(i\)</span> de la respuesta, <span class="math inline">\(\beta_j\)</span> es el efecto asociado con el nivel <span class="math inline">\(j\)</span> de la predictora, y <span class="math inline">\(\theta\)</span> es el efecto asociado con la variable de scores. En la práctica el logit para dos categorías consecutivas de la respuesta dependen únicamente de los coeficientes del modelo que afectaban a la respuesta y a la interacción entre respuesta y predictora, es decir:</p>
<p><span class="math display">\[log\left(\frac{\pi_{i+1|j}}{\pi_{i|j}}\right) = \eta_{i+1|j} =(\alpha_{i+1} - \alpha_i)+ \theta_j (u_{i+1} - u_i)\ \]</span></p>
<p>de forma que la relación entre ambas probabilidades viene dada por:</p>
<p><span class="math display">\[\frac{\pi_{i+1|j}}{\pi_{i|j}} = exp(\eta_{i+1|j}) = exp\{(\alpha_{i+1} - \alpha_i) + \theta_j (u_{i+1} - u_i)\}\]</span></p>
<p>Si queremos obtener la relación entre las probabilidades de las categorías <span class="math inline">\(i+2\)</span> e <span class="math inline">\(i\)</span> basta con considerar que:</p>
<p><span class="math display">\[\frac{\pi_{i+2|j}}{\pi_{i|j}} = \frac{\pi_{i+2|j}}{\pi_{i+1|j}}\frac{\pi_{i+1|j}}{\pi_{i|j}}\]</span>
que se puede calcular como:</p>
<p><span class="math display">\[\frac{\pi_{i+2|j}}{\pi_{i|j}} = exp(\eta_{i+2|j}) = exp\{(\alpha_{i+2} - \alpha_i) + \theta_j (u_{i+2} - u_i)\}\]</span></p>
<p>De esta forma podemos obtener la relación entre cualquier para de categorías de la respuesta.</p>
<div id="datos-de-gripe" class="section level3">
<h3><span class="header-section-number">14.4.1</span> Datos de gripe</h3>
<p>En primer lugar calculamos y evaluamos los logits empíricos asociados y más tarde realizamos el ajuste y estimación del modelo. Dado que la respuesta es ordinal debemos calcular los logits referenciados a la categoría inferior tomando como referencia inicial la categoría <code>small</code>. Obtenemos los log-odds y los representamos mediante:</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb605-1" title="1"><span class="co"># Creamos referencias de comparación consecutivas</span></a>
<a class="sourceLine" id="cb605-2" title="2">ref.val1 &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Gripe, response <span class="op">==</span><span class="st"> &quot;small&quot;</span>), frequency))</a>
<a class="sourceLine" id="cb605-3" title="3">ref.val2 &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Gripe, response <span class="op">==</span><span class="st"> &quot;moderate&quot;</span>), frequency))</a>
<a class="sourceLine" id="cb605-4" title="4"><span class="co"># Log-odds</span></a>
<a class="sourceLine" id="cb605-5" title="5">Gripe &lt;-<span class="st"> </span>Gripe <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb605-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">referencia =</span> <span class="kw">c</span>(<span class="kw">rep</span>(ref.val1, <span class="dv">2</span>), ref.val2),</a>
<a class="sourceLine" id="cb605-7" title="7">         <span class="dt">lodds =</span> <span class="kw">log</span>(frequency <span class="op">/</span><span class="st"> </span>referencia))</a>
<a class="sourceLine" id="cb605-8" title="8"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb605-9" title="9"><span class="co"># Seleccionamos las categorías a representar eliminando la de referencia</span></a>
<a class="sourceLine" id="cb605-10" title="10"><span class="co"># Como la respuesta sólo tiene una categoría no hace falta utilizarla en el gráfico</span></a>
<a class="sourceLine" id="cb605-11" title="11">datos &lt;-<span class="st"> </span><span class="kw">filter</span>(Gripe, response <span class="op">!=</span><span class="st"> &quot;small&quot;</span>)</a>
<a class="sourceLine" id="cb605-12" title="12"><span class="kw">ggplot</span>(datos,<span class="kw">aes</span>(<span class="dt">x =</span> treatment, <span class="dt">y =</span> lodds, <span class="dt">group =</span> response, <span class="dt">color =</span> response)) <span class="op">+</span></a>
<a class="sourceLine" id="cb605-13" title="13"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb605-14" title="14"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb605-15" title="15"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Tratamiento&quot;</span>,</a>
<a class="sourceLine" id="cb605-16" title="16">       <span class="dt">y =</span> <span class="st">&quot;log-odds condicionados&quot;</span>,</a>
<a class="sourceLine" id="cb605-17" title="17">       <span class="dt">col =</span> <span class="st">&quot;Respuesta&quot;</span>) </a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont037-1.png" width="672" /></p>
<p>Se observa casi un comportamiento paralelo entre los logits obtenidos. En este caso queremos estudiar un posible modelo de asociación entre la respuesta a la vacuna y el tipo de tratamiento seguido. La variable respuesta es de tipo ordinal y asignamos la variable de scores de 1 a 3, donde 1 refleja efecto pequeño y 3 refleja un efecto grande. En este caso modelizaremos los logits de categorías consecutivas: Moderado vs Pequeño, y Grande vs Moderado. Planteamos el análisis de independencia (sin interacción entre el tratamiento y la variable de scores) frente al de asociación (interacción entre tratamiento y scores) dado los logits observados.</p>
<p>En primer lugar creamos los scores asociados:</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb606-1" title="1"><span class="co"># Creamos variable de scores</span></a>
<a class="sourceLine" id="cb606-2" title="2">Gripe<span class="op">$</span>efecto.s &lt;-<span class="kw">c</span>() </a>
<a class="sourceLine" id="cb606-3" title="3">Gripe<span class="op">$</span>efecto.s[Gripe<span class="op">$</span>response <span class="op">==</span><span class="st"> &quot;small&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb606-4" title="4">Gripe<span class="op">$</span>efecto.s[Gripe<span class="op">$</span>response <span class="op">==</span><span class="st"> &quot;moderate&quot;</span>] &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb606-5" title="5">Gripe<span class="op">$</span>efecto.s[Gripe<span class="op">$</span>response <span class="op">==</span><span class="st"> &quot;large&quot;</span>] &lt;-<span class="st"> </span><span class="dv">3</span></a></code></pre></div>
<p>Ajustamos los modelos sin (independencia) y con interacción (dependencia) de los scores con la predictora y valoramos sin ambos modleos son iguales:</p>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb607-1" title="1"><span class="co"># Ajuste del modelo de independencia</span></a>
<a class="sourceLine" id="cb607-2" title="2">fit.gripe.ind &lt;-<span class="st"> </span><span class="kw">glm</span>(frequency <span class="op">~</span><span class="st"> </span>treatment <span class="op">+</span><span class="st"> </span>response <span class="op">+</span><span class="st"> </span>efecto.s, </a>
<a class="sourceLine" id="cb607-3" title="3">              <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb607-4" title="4">              <span class="dt">data =</span> Gripe)</a>
<a class="sourceLine" id="cb607-5" title="5"><span class="co"># Ajuste del modelo de asociación</span></a>
<a class="sourceLine" id="cb607-6" title="6">fit.gripe &lt;-<span class="st"> </span><span class="kw">glm</span>(frequency <span class="op">~</span><span class="st"> </span>treatment <span class="op">+</span><span class="st"> </span>response <span class="op">+</span><span class="st"> </span>treatment<span class="op">:</span>efecto.s, </a>
<a class="sourceLine" id="cb607-7" title="7">               <span class="dt">family =</span> <span class="kw">poisson</span>(), </a>
<a class="sourceLine" id="cb607-8" title="8">               <span class="dt">data =</span> Gripe)</a>
<a class="sourceLine" id="cb607-9" title="9"><span class="co"># Comparamos ambos modelos</span></a>
<a class="sourceLine" id="cb607-10" title="10"><span class="kw">anova</span>(fit.gripe.ind, fit.gripe, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: frequency ~ treatment + response + efecto.s
## Model 2: frequency ~ treatment + response + treatment:efecto.s
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1         2    18.6425                          
## 2         1     4.3106  1   14.332 0.0001532 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Rechazamos el modelo de independencia a favor del modelo de asociación. Veamos las estimaciones del modelo.</p>
<p>Obtenemos la tabla de estimación para el modelo:</p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb609-1" title="1">tabla &lt;-<span class="st"> </span><span class="kw">tidy</span>(fit.gripe)[,<span class="kw">c</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;estimate&quot;</span>)]</a>
<a class="sourceLine" id="cb609-2" title="2">tabla</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   term                      estimate
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 (Intercept)                 4.88  
## 2 treatmentvaccine           -2.32  
## 3 responsemoderate            0.0928
## 4 responsesmall              -0.490 
## 5 treatmentplacebo:efecto.s  -1.25  
## 6 treatmentvaccine:efecto.s  NA</code></pre>
<p>Seleccionamos los efectos necesarios para el ajuste de los logits y la estimación de probabilidades. Estos efectos son los relacionados (principales e interacciones) con la variable <code>response</code>.</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb611-1" title="1"><span class="co"># Filas de la tabla de estimaciones relacionados con metodo</span></a>
<a class="sourceLine" id="cb611-2" title="2">tabla[<span class="dv">3</span><span class="op">:</span><span class="dv">5</span>,]</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   term                      estimate
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 responsemoderate            0.0928
## 2 responsesmall              -0.490 
## 3 treatmentplacebo:efecto.s  -1.25</code></pre>
<p>Para este modelo Los logits consecutivos asociados vienen dados por las expresiones siguientes donde utilizamos la codificación <code>S = small</code>, <code>M = moderate</code>, y <code>L = large</code> para la variable response:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{M,j}}}{\pi_{\text{S,j}}}\right) = (\alpha_{\text{M}} - \alpha_{\text{S}}) + \theta_j(u_{M} - u_{S})\]</span>
<span class="math display">\[log\left(\frac{\pi_{\text{L,j}}}{\pi_{\text{M,j}}}\right) = (\alpha_{\text{L}} - \alpha_{\text{M}}) + \theta_j(u_{L} - u_{M})\]</span></p>
<p>donde los <span class="math inline">\(\alpha_i\)</span> son los efectos asociados con el nivel <span class="math inline">\(i\)</span> de la respuesta, <span class="math inline">\(\theta\)</span> es el efecto de intereacción entre predictora y scores, y los <span class="math inline">\(u_i\)</span> son los scores asociados con la variable respuesta. Al sustituir por las correspondientes estimaciones y scores proporciona:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{M,j}}}{\pi_{\text{S,j}}}\right) = (0.0928 + 0.490) + \theta_j (2 -1) = 0.5828 + \theta_j \]</span>
<span class="math display">\[log\left(\frac{\pi_{\text{L,j}}}{\pi_{\text{M,j}}}\right) = (0 - 0.0928) + \theta_j (3 - 2) = -0.0928 + \theta_j\]</span></p>
<p>con <span class="math inline">\(\theta_1 = -1.25\)</span> para el placebo y <span class="math inline">\(\theta_2 = 0\)</span> para el tratamiento. Si asignamos la codificación <code>T = treatment</code> y <code>P = placebo</code> los losgits obtenidos son:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{M,T}}}{\pi_{\text{S,T}}}\right) = 0.5828; \quad log\left(\frac{\pi_{\text{M,P}}}{\pi_{\text{S,P}}}\right) = - 0.6672\]</span>
<span class="math display">\[log\left(\frac{\pi_{\text{L,T}}}{\pi_{\text{M,T}}}\right)= - 0.0928; \quad log\left(\frac{\pi_{\text{L,P}}}{\pi_{\text{M,P}}}\right)= - 1.3428\]</span></p>
<p>A partir de estos logits podemos obtner las probabiliddes asociadas a cada combinación de respuesta y predictora. Calculamos y representamos dichas probabilidades:</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb613-1" title="1"><span class="co"># Calculamos los conteos predichos del modelo</span></a>
<a class="sourceLine" id="cb613-2" title="2">conteos &lt;-<span class="st"> </span><span class="kw">predict</span>(fit.gripe, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb613-3" title="3"><span class="co"># Combinamos los datos originales con los predichos</span></a>
<a class="sourceLine" id="cb613-4" title="4">newdata &lt;-<span class="st"> </span><span class="kw">cbind</span>(Gripe, conteos)</a>
<a class="sourceLine" id="cb613-5" title="5"><span class="co"># Calculamos el conteo total por las predictoras</span></a>
<a class="sourceLine" id="cb613-6" title="6">newdata.sum &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(treatment) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb613-7" title="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">suma =</span> <span class="kw">sum</span>(conteos))</a>
<a class="sourceLine" id="cb613-8" title="8"><span class="co"># Calculamos las probabilidades asociadas a cada combinación</span></a>
<a class="sourceLine" id="cb613-9" title="9">newdata &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb613-10" title="10"><span class="st">  </span><span class="kw">left_join</span>(newdata.sum, <span class="dt">by =</span> <span class="st">&quot;treatment&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb613-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">round</span>(conteos<span class="op">/</span>suma,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb613-12" title="12"><span class="co"># Vemos las probabiliddes obtenidas</span></a>
<a class="sourceLine" id="cb613-13" title="13">dplyr<span class="op">::</span><span class="kw">select</span>(newdata,<span class="kw">c</span>(treatment, response, prob))</a></code></pre></div>
<pre><code>##   treatment response   prob
## 1   placebo    small 0.6075
## 2   placebo moderate 0.3113
## 3   placebo    large 0.0812
## 4   vaccine    small 0.2261
## 5   vaccine moderate 0.4049
## 6   vaccine    large 0.3690</code></pre>
<p>Podemos representar las probabilidades obtenidas para ver los efectos de la combinacion de predictoras en la respuesta.</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb615-1" title="1"><span class="kw">ggplot</span>(newdata, <span class="kw">aes</span>(<span class="dt">x =</span> treatment, <span class="dt">y =</span> prob, <span class="dt">group =</span> response, <span class="dt">color =</span> response)) <span class="op">+</span></a>
<a class="sourceLine" id="cb615-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb615-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb615-4" title="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probabilidades estimadas&quot;</span>,</a>
<a class="sourceLine" id="cb615-5" title="5">       <span class="dt">x =</span> <span class="st">&quot;Tratamiento&quot;</span>,</a>
<a class="sourceLine" id="cb615-6" title="6">       <span class="dt">y =</span> <span class="st">&quot;Probabilidad&quot;</span>,</a>
<a class="sourceLine" id="cb615-7" title="7">       <span class="dt">col =</span> <span class="st">&quot;Respuesta&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb615-8" title="8"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>), <span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont043-1.png" width="672" /></p>
<p>¿Cómo varían las probabilidades de la respuesta en función del tratamiento?</p>
</div>
</div>
<div id="respuesta-ordinal-predictora-ordinal" class="section level2">
<h2><span class="header-section-number">14.5</span> Respuesta ordinal, predictora ordinal</h2>
<p>Imaginemos que tenemos una variable respuesta y otra predictora (ambas de carácter ordinal). La modelización en esta situación pasa por definir variables ficticias de scores tanto para la predictora como la respuesta. Denotamos por <span class="math inline">\(S\)</span> y <span class="math inline">\(U\)</span> a las variables de scores para la respuesta y la predictora respectivamente. Calculamos la variable producto <span class="math inline">\(P\)</span> en ambos scores que será introducida en el modelo para reflejar el posible efecto de interacción entre respuesta y predictora. En esta situación tenemos que:</p>
<p><span class="math display">\[log(E(Y_{ij})) = \mu +\alpha_i + \beta_j + \theta P_{ij} = \mu +\alpha_i + \beta_j + \theta S_iU_j\]</span>
donde <span class="math inline">\(\mu\)</span> es la interceptación del modelo, <span class="math inline">\(\alpha_i\)</span> es el efecto asociado con el nivel <span class="math inline">\(i\)</span> de la respuesta, <span class="math inline">\(\beta_j\)</span> es el efecto asociado con el nivel <span class="math inline">\(j\)</span> de la predictora, y <span class="math inline">\(\theta\)</span> es el efecto asociado con la variable <span class="math inline">\(P_{ij} = S_iU_j\)</span>. En la práctica se puede demostrar que el logit para dos categorías consecutivas de la respuesta dependen únicamente de los coeficientes del modelo que afectan a la respuesta y a la interacción entre respuesta y predictora, es decir:</p>
<p><span class="math display">\[log\left(\frac{\pi_{i+1|j}}{\pi_{i|j}}\right) = \eta_{i+1|j} = (\alpha_{i+1} - \alpha_i) + \theta (u_{i+1} - u_i)v_j\]</span></p>
<p>de forma que la relación entre ambas probabilidades viene dada por:</p>
<p><span class="math display">\[\frac{\pi_{i+1|j}}{\pi_{i|j}} = exp(\eta_{i+1|j}) = exp\{(\alpha_{i+1} - \alpha_i) + \theta (u_{i+1} - u_i)v_j\}\]</span></p>
<p>Si queremos obtener la relación entre las probabilidades de las categorías <span class="math inline">\(i+2\)</span> e <span class="math inline">\(i\)</span> basta con considerar que:</p>
<p><span class="math display">\[\frac{\pi_{i+2|j}}{\pi_{i|j}} = \frac{\pi_{i+2|j}}{\pi_{i+1|j}}\frac{\pi_{i+1|j}}{\pi_{i|j}}\]</span></p>
<p>que se puede calcular como:</p>
<p><span class="math display">\[\frac{\pi_{i+2|j}}{\pi_{i|j}} = exp(\eta_{i+2|j}) = exp\{(\alpha_{i+2} - \alpha_i) + \theta (u_{i+2} - u_i)v_j\}\]</span></p>
<p>De esta forma podemos obtener la relación entre cualquier par de categorías de la respuesta. Actuado de esta forma resulta posible calcular la probabilidad de cada categoría de la respuesta sin más que fijar una categoría de referencia, y obtener todas las probabilidades asociadas con la de referencia. Procederíamos entonces como en el caso multinomial.</p>
<p>Todas estas ecuaciones de estimación se pueden generalizar sin problemas cuando existe más de una variable predictora, sin más que considerar las posibles interacciones entre la respuesta y las predictoras. En caso de tratarse de variables de tipo ordinal construiremos los scores correspondientes para analizar dichos efectos de interacción.</p>
<div id="datos-satisfacción-laboral" class="section level3">
<h3><span class="header-section-number">14.5.1</span> Datos Satisfacción laboral</h3>
<p>Si tomamos como variable respuesta el grado de satisfacción, y usamos como referencia la categroria <code>Muy Insatisfecho</code> podemos obtener los log-odds condicionales mediante:</p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb616-1" title="1"><span class="co"># Creamos referencias de comparación consecutivas</span></a>
<a class="sourceLine" id="cb616-2" title="2">ref.val1 &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Satisfaccion, Estado <span class="op">==</span><span class="st"> &quot;Muy insatisfecho&quot;</span>),frecuencia))</a>
<a class="sourceLine" id="cb616-3" title="3">ref.val2 &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Satisfaccion, Estado <span class="op">==</span><span class="st"> &quot;Poco insatisfecho&quot;</span>),frecuencia))</a>
<a class="sourceLine" id="cb616-4" title="4">ref.val3 &lt;-<span class="st"> </span><span class="kw">unlist</span>(dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">filter</span>(Satisfaccion, Estado <span class="op">==</span><span class="st"> &quot;Moderadamente satisfecho&quot;</span>), frecuencia))</a>
<a class="sourceLine" id="cb616-5" title="5"><span class="co"># Log-odds</span></a>
<a class="sourceLine" id="cb616-6" title="6">Satisfaccion &lt;-<span class="st"> </span>Satisfaccion <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb616-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">referencia =</span> <span class="kw">c</span>(<span class="kw">rep</span>(ref.val1, <span class="dv">2</span>), ref.val2, ref.val3),</a>
<a class="sourceLine" id="cb616-8" title="8">         <span class="dt">lodds =</span> <span class="kw">log</span>(frecuencia <span class="op">/</span><span class="st"> </span>referencia))</a>
<a class="sourceLine" id="cb616-9" title="9"><span class="co"># Gráfico</span></a>
<a class="sourceLine" id="cb616-10" title="10"><span class="co"># Seleccionamos las categorías a representar eliminando la de referencia</span></a>
<a class="sourceLine" id="cb616-11" title="11"><span class="co"># Como la respuesta sólo tiene una categoría no hace falta utilizarla en el gráfico</span></a>
<a class="sourceLine" id="cb616-12" title="12">datos &lt;-<span class="st"> </span><span class="kw">filter</span>(Satisfaccion, Estado <span class="op">!=</span><span class="st"> &quot;Muy insatisfecho&quot;</span>)</a>
<a class="sourceLine" id="cb616-13" title="13">ords &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;&lt; 6000&quot;</span>, <span class="st">&quot;6000 - 15000&quot;</span>, <span class="st">&quot;15000 - 25000&quot;</span>, <span class="st">&quot;&gt; 25000&quot;</span>)</a>
<a class="sourceLine" id="cb616-14" title="14"><span class="kw">ggplot</span>(datos,<span class="kw">aes</span>(<span class="dt">x =</span> Ingresos, <span class="dt">y =</span> lodds, <span class="dt">group =</span> Estado, <span class="dt">color =</span> Estado)) <span class="op">+</span></a>
<a class="sourceLine" id="cb616-15" title="15"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb616-16" title="16"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb616-17" title="17"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">limits =</span> ords) <span class="op">+</span></a>
<a class="sourceLine" id="cb616-18" title="18"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Ingresos&quot;</span>,</a>
<a class="sourceLine" id="cb616-19" title="19">       <span class="dt">y =</span> <span class="st">&quot;log-odds condicionados&quot;</span>,</a>
<a class="sourceLine" id="cb616-20" title="20">       <span class="dt">col =</span> <span class="st">&quot;Grado de satisfacción&quot;) </span></a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont044-1.png" width="672" /></p>
<p>¿Cómo interpretamos los log-odds condicionales entre categorías consecutivas obtenidos? Recuerda que en este caso cada perfil se debe comparar con la categoria inmediatamente inferior.</p>
<p>En este caso queremos estudiar un posible modelo de asociación entre la satisfacción laboral en función de los ingresos percibidos. Tanto la variable respuesta como la predictora se encuentran en escala ordinal. Debemos introducir los scores asociados a ambas variables para poder considerarlos en el modelo de asociación. Creamos scores en escala continua de 1 a 4 para la satisfacción (<span class="math inline">\(u_i\)</span>), y de 1 a 4 para los ingresos (<span class="math inline">\(v_j\)</span>), ya que los intervalos considerados no tienen la misma amplitud en este caso y no podmeos utilizar el punto medio. La interacción entre ambas variables se reflejará mediante el producto de las variables de scores creadas.</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb617-1" title="1"><span class="co"># Generamos la variable de interacción</span></a>
<a class="sourceLine" id="cb617-2" title="2">Satisfaccion &lt;-<span class="st"> </span>Satisfaccion <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb617-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">asociacion =</span> Ingresos.num <span class="op">*</span><span class="st"> </span>Estado.num)</a>
<a class="sourceLine" id="cb617-4" title="4"><span class="co"># Ajuste del modelo de independencia</span></a>
<a class="sourceLine" id="cb617-5" title="5">fit.satisfaccion.ind &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>Ingresos <span class="op">+</span><span class="st"> </span>Estado, </a>
<a class="sourceLine" id="cb617-6" title="6">              <span class="dt">family =</span> <span class="kw">poisson</span>(), <span class="dt">data =</span> Satisfaccion)</a>
<a class="sourceLine" id="cb617-7" title="7"><span class="co"># Ajuste del modelo de asociación</span></a>
<a class="sourceLine" id="cb617-8" title="8">fit.satisfaccion &lt;-<span class="st"> </span><span class="kw">glm</span>(frecuencia <span class="op">~</span><span class="st"> </span>Ingresos <span class="op">+</span><span class="st"> </span>Estado <span class="op">+</span><span class="st"> </span>asociacion, </a>
<a class="sourceLine" id="cb617-9" title="9">               <span class="dt">family =</span> <span class="kw">poisson</span>(), <span class="dt">data =</span> Satisfaccion)</a>
<a class="sourceLine" id="cb617-10" title="10"><span class="co"># Comparamos ambos modelos</span></a>
<a class="sourceLine" id="cb617-11" title="11"><span class="kw">anova</span>(fit.satisfaccion.ind, fit.satisfaccion, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: frecuencia ~ Ingresos + Estado
## Model 2: frecuencia ~ Ingresos + Estado + asociacion
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
## 1         9    12.0369                        
## 2         8     2.3859  1   9.6509 0.001893 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Rechazamos el modelo de independencia a favor del modelo de asociación que obtenemos con los scores. Veamos el resumen del modelo:</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb619-1" title="1">tabla &lt;-<span class="st"> </span><span class="kw">tidy</span>(fit.satisfaccion)[,<span class="kw">c</span>(<span class="st">&quot;term&quot;</span>, <span class="st">&quot;estimate&quot;</span>)]</a>
<a class="sourceLine" id="cb619-2" title="2">tabla</a></code></pre></div>
<pre><code>## # A tibble: 8 x 2
##   term                    estimate
##   &lt;chr&gt;                      &lt;dbl&gt;
## 1 (Intercept)               3.98  
## 2 Ingresos&gt; 25000          -1.26  
## 3 Ingresos15000 - 25000    -0.577 
## 4 Ingresos6000 - 15000     -0.0105
## 5 EstadoMuy insatisfecho   -1.13  
## 6 EstadoMuy satisfecho     -0.0181
## 7 EstadoPoco insatisfecho  -0.823 
## 8 asociacion                0.112</code></pre>
<p>Seleccionamos los efectos necesarios para el ajuste de los logits y la estimación de probabilidades. Estos efectos son los relacionados (principales e interacciones) con la variable <code>Estado</code>.</p>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb621-1" title="1"><span class="co"># Filas de la tabla de estimaciones relacionados con metodo</span></a>
<a class="sourceLine" id="cb621-2" title="2">tabla[<span class="dv">5</span><span class="op">:</span><span class="dv">8</span>,]</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   term                    estimate
##   &lt;chr&gt;                      &lt;dbl&gt;
## 1 EstadoMuy insatisfecho   -1.13  
## 2 EstadoMuy satisfecho     -0.0181
## 3 EstadoPoco insatisfecho  -0.823 
## 4 asociacion                0.112</code></pre>
<p>Para la obtención de los logits vinculados con este modelo usamos la codificación <code>Muy Insatisfecho = S1</code>, <code>Poco Insatisfecho = S2</code>, <code>Moderadamente Satisfecho = S3</code>, y <code>Muy Satisfecho = S4</code> para la variable Estado, y <code>&lt; 6000 = I1</code>, <code>6000 - 15000 = I2</code>, <code>15000 - 25000 = I3</code>, y <code>&gt; 25000 = I4</code> para la variable ingresos, de forma que las ecuaciones de los logit para este modelo vienen dadas por:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S4|j}}}{\pi_{\text{S3|j}}}\right) = (\alpha_{\text{S4|j}} - \alpha_{\text{S3|j}} ) + \theta (u_{\text{S4|j}} - u_{\text{S3|j}})v_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S3|j}}}{\pi_{\text{S2|j}}}\right) = (\alpha_{\text{S3|j}} - \alpha_{\text{S2|j}} ) + \theta (u_{\text{S3|j}} - u_{\text{S2|j}})v_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S2|j}}}{\pi_{\text{S1|j}}}\right) = (\alpha_{\text{S2|j}} - \alpha_{\text{S1|j}} ) + \theta (u_{\text{S2|j}} - u_{\text{S1|j}})v_j\]</span></p>
<p>donde los <span class="math inline">\(\alpha_i\)</span> son los efectos asociados con el nivel <span class="math inline">\(i\)</span> de la respuesta, <span class="math inline">\(\theta\)</span> es el efecto de intereacción entre scores (<code>asociacion</code>), los <span class="math inline">\(u_i\)</span> son los scores asociados con <code>Estado</code>, y los <span class="math inline">\(u_i\)</span> son los scores asociados con <code>Ingresos</code>. Al sustituir por las correspondientes estimaciones y scores proporciona:</p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S4|j}}}{\pi_{\text{S3|j}}}\right) = (-0.0181 - 0) + 0.112*(4-3)* v_j = -0.0181 + 0.112 * v_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S3|j}}}{\pi_{\text{S2|j}}}\right) = (0 + 0.823) + 0.112*(3-2)* v_j = 0.823 + 0.112 * v_j\]</span></p>
<p><span class="math display">\[log\left(\frac{\pi_{\text{S2|j}}}{\pi_{\text{S1|j}}}\right) = (-0.823 + 1.13) + 0.112*(2-1)* v_j = 0.307 + 0.112 * v_j\]</span></p>
<p>Sustiyuendo los <span class="math inline">\(v_j\)</span> podemos establecer la relación entre las probabildiades de dos categorias consecutivas de la respuesta. Finalmente obtnemos las probabilidades asociadas al modelo ajustado.</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb623-1" title="1"><span class="co"># Calculamos los conteos predichos del modelo</span></a>
<a class="sourceLine" id="cb623-2" title="2">conteos &lt;-<span class="st"> </span><span class="kw">predict</span>(fit.satisfaccion, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb623-3" title="3"><span class="co"># Combinamos los datos originales con los predichos</span></a>
<a class="sourceLine" id="cb623-4" title="4">newdata &lt;-<span class="st"> </span><span class="kw">cbind</span>(Satisfaccion, conteos)</a>
<a class="sourceLine" id="cb623-5" title="5"><span class="co"># Calculamos el conteo total por las predictoras</span></a>
<a class="sourceLine" id="cb623-6" title="6">newdata.sum &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Ingresos) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb623-7" title="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">suma =</span> <span class="kw">sum</span>(conteos))</a>
<a class="sourceLine" id="cb623-8" title="8"><span class="co"># Calculamos las probabilidades asociadas a cada combinación</span></a>
<a class="sourceLine" id="cb623-9" title="9">newdata &lt;-<span class="st"> </span>newdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb623-10" title="10"><span class="st">  </span><span class="kw">left_join</span>(newdata.sum, <span class="dt">by =</span> <span class="st">&quot;Ingresos&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb623-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">round</span>(conteos<span class="op">/</span>suma,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb623-12" title="12"><span class="co"># Vemos las probabiliddes obtenidas</span></a>
<a class="sourceLine" id="cb623-13" title="13">dplyr<span class="op">::</span><span class="kw">select</span>(newdata,<span class="kw">c</span>(Ingresos, Estado, prob))</a></code></pre></div>
<pre><code>##         Ingresos                   Estado   prob
## 1         &lt; 6000         Muy insatisfecho 0.0939
## 2   6000 - 15000         Muy insatisfecho 0.0741
## 3  15000 - 25000         Muy insatisfecho 0.0578
## 4        &gt; 25000         Muy insatisfecho 0.0447
## 5         &lt; 6000        Poco insatisfecho 0.1429
## 6   6000 - 15000        Poco insatisfecho 0.1261
## 7  15000 - 25000        Poco insatisfecho 0.1101
## 8        &gt; 25000        Poco insatisfecho 0.0952
## 9         &lt; 6000 Moderadamente satisfecho 0.3637
## 10  6000 - 15000 Moderadamente satisfecho 0.3589
## 11 15000 - 25000 Moderadamente satisfecho 0.3505
## 12       &gt; 25000 Moderadamente satisfecho 0.3390
## 13        &lt; 6000           Muy satisfecho 0.3995
## 14  6000 - 15000           Muy satisfecho 0.4409
## 15 15000 - 25000           Muy satisfecho 0.4816
## 16       &gt; 25000           Muy satisfecho 0.5210</code></pre>
<p>Podemos representar las probabilidades obtenidas para ver los efectos de la combinacion de predictoras en la respuesta.</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb625-1" title="1">ords &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;&lt; 6000&quot;</span>, <span class="st">&quot;6000 - 15000&quot;</span>, <span class="st">&quot;15000 - 25000&quot;</span>, <span class="st">&quot;&gt; 25000&quot;</span>)</a>
<a class="sourceLine" id="cb625-2" title="2"><span class="kw">ggplot</span>(newdata, <span class="kw">aes</span>(<span class="dt">x =</span> Ingresos, <span class="dt">y =</span> prob, <span class="dt">group =</span> Estado, <span class="dt">color =</span> Estado)) <span class="op">+</span></a>
<a class="sourceLine" id="cb625-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb625-4" title="4"><span class="st">  </span><span class="kw">geom_line</span>()  <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb625-5" title="5"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">limits =</span> ords) <span class="op">+</span></a>
<a class="sourceLine" id="cb625-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probabilidades estimadas&quot;</span>,</a>
<a class="sourceLine" id="cb625-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Ingresos&quot;</span>,</a>
<a class="sourceLine" id="cb625-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Probabilidad&quot;</span>,</a>
<a class="sourceLine" id="cb625-9" title="9">       <span class="dt">col =</span> <span class="st">&quot;Nivel de satisfacción&quot;) +</span></a>
<a class="sourceLine" id="cb625-10" title="10"><span class="st">  scale_y_continuous(breaks = seq(0, 1, by = 0.1), limits = c(0, 1))</span></a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/tcont049-1.png" width="672" /></p>
<p>¿Cómo evolucionan las probabilidades del nivel de satisfacción en función de los ingresos percibidos?</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelos-logit-multinomial.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diagnóstico-5.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["libroSTAT.pdf", "libroSTAT.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
