<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.2 Estimación, inferencia y bondad de ajuste | Modelos Estadísticos</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="1.2 Estimación, inferencia y bondad de ajuste | Modelos Estadísticos" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.2 Estimación, inferencia y bondad de ajuste | Modelos Estadísticos" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Javier Morales (Universidad Miguel Hernández de Elche)" />
<meta name="author" content="Mª Asunción Martínez (Universidad Miguel Hernández de Elche)" />


<meta name="date" content="2020-05-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tipos-de-modelos.html"/>
<link rel="next" href="comparación-y-selección-de-modelos.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Estadísticos</a></li>
<li><a href="./">J. Morales y A.M. Mayoral</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="requisitos.html"><a href="requisitos.html"><i class="fa fa-check"></i>Requisitos</a></li>
<li class="chapter" data-level="1" data-path="rlm.html"><a href="rlm.html"><i class="fa fa-check"></i><b>1</b> Regresión Lineal Múltiple y Polinómica</a><ul>
<li class="chapter" data-level="1.1" data-path="tipos-de-modelos.html"><a href="tipos-de-modelos.html"><i class="fa fa-check"></i><b>1.1</b> Tipos de modelos</a><ul>
<li class="chapter" data-level="1.1.1" data-path="tipos-de-modelos.html"><a href="tipos-de-modelos.html#modelos-de-rlm"><i class="fa fa-check"></i><b>1.1.1</b> Modelos de RLM</a></li>
<li class="chapter" data-level="1.1.2" data-path="tipos-de-modelos.html"><a href="tipos-de-modelos.html#modelos-de-rp"><i class="fa fa-check"></i><b>1.1.2</b> Modelos de RP</a></li>
<li class="chapter" data-level="1.1.3" data-path="tipos-de-modelos.html"><a href="tipos-de-modelos.html#expresión-en-r-de-los-modelos"><i class="fa fa-check"></i><b>1.1.3</b> Expresión en <code>R</code> de los modelos</a></li>
<li class="chapter" data-level="1.1.4" data-path="tipos-de-modelos.html"><a href="tipos-de-modelos.html#modelo-saturado-y-anidado"><i class="fa fa-check"></i><b>1.1.4</b> Modelo saturado y anidado</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html"><i class="fa fa-check"></i><b>1.2</b> Estimación, inferencia y bondad de ajuste</a><ul>
<li class="chapter" data-level="1.2.1" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html#estimación-por-mínimos-cuadrados"><i class="fa fa-check"></i><b>1.2.1</b> Estimación por mínimos cuadrados</a></li>
<li class="chapter" data-level="1.2.2" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html#estimación-por-máxima-verosimilitud"><i class="fa fa-check"></i><b>1.2.2</b> Estimación por máxima verosimilitud</a></li>
<li class="chapter" data-level="1.2.3" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html#inferencia"><i class="fa fa-check"></i><b>1.2.3</b> Inferencia</a></li>
<li class="chapter" data-level="1.2.4" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html#ejemplos"><i class="fa fa-check"></i><b>1.2.4</b> Ejemplos</a></li>
<li class="chapter" data-level="1.2.5" data-path="estimación-inferencia-y-bondad-de-ajuste.html"><a href="estimación-inferencia-y-bondad-de-ajuste.html#bondad-del-ajuste"><i class="fa fa-check"></i><b>1.2.5</b> Bondad del ajuste</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html"><i class="fa fa-check"></i><b>1.3</b> Comparación y selección de modelos</a><ul>
<li class="chapter" data-level="1.3.1" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html#significatividad-de-los-predictores"><i class="fa fa-check"></i><b>1.3.1</b> Significatividad de los predictores</a></li>
<li class="chapter" data-level="1.3.2" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html#los-estadísticos-aic-y-bic"><i class="fa fa-check"></i><b>1.3.2</b> Los estadísticos <span class="math inline">\(AIC\)</span> y <span class="math inline">\(BIC\)</span></a></li>
<li class="chapter" data-level="1.3.3" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html#procedimientos-secuenciales-de-selección-de-variables"><i class="fa fa-check"></i><b>1.3.3</b> Procedimientos secuenciales de selección de variables</a></li>
<li class="chapter" data-level="1.3.4" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html#funciones-especificas-para-modelos-de-regresión"><i class="fa fa-check"></i><b>1.3.4</b> Funciones especificas para modelos de regresión</a></li>
<li class="chapter" data-level="1.3.5" data-path="comparación-y-selección-de-modelos.html"><a href="comparación-y-selección-de-modelos.html#ejemplos-2"><i class="fa fa-check"></i><b>1.3.5</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="multicolinealidad-y-diagnóstico-del-modelo.html"><a href="multicolinealidad-y-diagnóstico-del-modelo.html"><i class="fa fa-check"></i><b>1.4</b> Multicolinealidad y Diagnóstico del modelo</a><ul>
<li class="chapter" data-level="1.4.1" data-path="multicolinealidad-y-diagnóstico-del-modelo.html"><a href="multicolinealidad-y-diagnóstico-del-modelo.html#multicolinealidad"><i class="fa fa-check"></i><b>1.4.1</b> Multicolinealidad</a></li>
<li class="chapter" data-level="1.4.2" data-path="multicolinealidad-y-diagnóstico-del-modelo.html"><a href="multicolinealidad-y-diagnóstico-del-modelo.html#diagnóstico-del-modelo"><i class="fa fa-check"></i><b>1.4.2</b> Diagnóstico del modelo</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="predicción.html"><a href="predicción.html"><i class="fa fa-check"></i><b>1.5</b> Predicción</a><ul>
<li class="chapter" data-level="1.5.1" data-path="predicción.html"><a href="predicción.html#estimación-de-la-respuesta-media."><i class="fa fa-check"></i><b>1.5.1</b> Estimación de la respuesta media.</a></li>
<li class="chapter" data-level="1.5.2" data-path="predicción.html"><a href="predicción.html#predicción-de-nuevas-observaciones."><i class="fa fa-check"></i><b>1.5.2</b> Predicción de nuevas observaciones.</a></li>
<li class="chapter" data-level="1.5.3" data-path="predicción.html"><a href="predicción.html#ejemplos-5"><i class="fa fa-check"></i><b>1.5.3</b> Ejemplos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ejercicios-modelos-de-regresión.html"><a href="ejercicios-modelos-de-regresión.html"><i class="fa fa-check"></i><b>2</b> Ejercicios modelos de regresión</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimación-inferencia-y-bondad-de-ajuste" class="section level2">
<h2><span class="header-section-number">1.2</span> Estimación, inferencia y bondad de ajuste</h2>
<p>Los procesos de estimación e inferencia del RLM y MP se basan en los mismos principios que los del modelo RLS estudiados en la unidad anterior. De hecho, las hipótesis sobre los errores de incorrelación, varianza constante y media cero son suficientes para obtener el ajuste por mínimos cuadrados del modelo propuesto. La normalidad es necesaria para obtener las inferencias y concluir sobre su fiabilidad.</p>
<p>Sin embargo, este tipo de modelos de regresión que consideran más de una predictora adolecen de un problema que puede ser muy relevante en su análisis. Dado que todas las predictoras no vendrán medidas en la misma escala de medida, el modelo obtenido (más concretamente los coeficientes del modelo) exhibe una dependencia de dicha escala que puede provocar que una variable con una variabilidad pequeña aparezca con un coeficiente grande en el modelo estimado. Para evitar esa dependencia se suele trabajar con las variables estandarizadas, es decir, corregidas por su media y desviación típica para eliminar los efectos de escala. Aunque en el apartado teórico mostraremos la solución para las variables en escala original, en la parte práctica mostraremos los coeficientes para las variables estandarizadas y veremos los cambios entre ambos modelos. Para denotar las variables transformadas añadiremos el prefijo <code>Z</code> al nombre de la predictora a la hora de escribir los modelos obtenidos.</p>
<div id="estimación-por-mínimos-cuadrados" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Estimación por mínimos cuadrados</h3>
<p>Para estimar <span class="math inline">\(\beta\)</span> seguimos el criterio de minimizar la suma de cuadrados debida al error, esto es,</p>
<p><span class="math display">\[
min_{\beta} \quad \epsilon&#39;\epsilon = min_{\beta} \quad (Y-X \beta)&#39;(Y-X \beta) = min_{\beta} \quad  Y&#39;Y -2 \beta&#39;X&#39;Y + \beta&#39;X&#39;X\beta.
\]</span></p>
<p>Tras derivar la expresión anterior respecto de <span class="math inline">\(\beta\)</span> e igualarlo a cero, se obtiene el estimador de mínimos cuadrados de <span class="math inline">\(\beta\)</span> para el modelo <a href="tipos-de-modelos.html#eq:ecuacionML">(1.3)</a>, <span class="math inline">\(\hat{\beta}\)</span>, resolviendo las <span class="math inline">\(p\)</span> <em>ecuaciones normales</em>:</p>
<p><span class="math display" id="eq:ecuacionesnormales">\[\begin{equation}
X&#39;X \beta=X&#39;Y.
\tag{1.4}
\end{equation}\]</span></p>
<p>A la hora de resolver <a href="estimación-inferencia-y-bondad-de-ajuste.html#eq:ecuacionesnormales">(1.4)</a>, se pueden presentar dos situaciones:</p>
<ul>
<li>Las <span class="math inline">\(p\)</span> ecuaciones normales que resultan de <a href="estimación-inferencia-y-bondad-de-ajuste.html#eq:ecuacionesnormales">(1.4)</a> no son independientes y por lo tanto no existe la inversa de <span class="math inline">\(X&#39;X\)</span>. Esto ocurre cuando las variables explicativas no son independientes entre sí. Entonces el modelo ha de expresarse en términos de menos parámetros (modificarse) o han de incorporarse restricciones adicionales sobre los parámetros para dar una matriz no singular.</li>
</ul>
<p>Cuando <span class="math inline">\((X&#39;X)\)</span> es singular, el estimador de <span class="math inline">\(\beta\)</span> se obtiene a partir de una matriz inversa generalizada <span class="math inline">\(X&#39;X\)</span>, <span class="math inline">\((X&#39;X)^{-}\)</span>, como:</p>
<p><span class="math display" id="eq:solinvgen">\[\begin{equation}
\hat{\beta}=(X&#39;X)^{-} X&#39;Y.
\tag{1.5}
\end{equation}\]</span></p>
<p>Así, diferentes elecciones de la inversa generalizada <span class="math inline">\((X&#39;X)^{-}\)</span> producen diferentes estimaciones de <span class="math inline">\(\beta\)</span>. Sin embargo, el modelo ajustado es el mismo, esto es, <span class="math inline">\(\hat{y}=X \hat{\beta}\)</span> es invariante a la inversa generalizada elegida.</p>
<ul>
<li>Las <span class="math inline">\(p\)</span> ecuaciones normales son independientes, con lo que <span class="math inline">\(X&#39;X\)</span> es no singular y existe su inversa. El estimador de mínimos cuadrados resulta:</li>
</ul>
<p><span class="math display" id="eq:solmincuad">\[\begin{equation}
\hat{\beta}=(X&#39;X)^{-1} (X&#39;Y).
\tag{1.6}
\end{equation}\]</span></p>
<div id="propiedades-del-ajuste-por-mínimos-cuadrados" class="section level4">
<h4><span class="header-section-number">1.2.1.1</span> Propiedades del ajuste por mínimos cuadrados</h4>
<p>Cuando prescindimos de la hipótesis de normalidad de los errores, obtenemos la estimación por mínimos cuadrados, que tiene las siguientes propiedades:</p>
<ol style="list-style-type: decimal">
<li><p>El estimador de mínimos cuadrados <span class="math inline">\(\hat{\beta}\)</span> minimiza <span class="math inline">\(\epsilon&#39;\epsilon\)</span>, independientemente de la distribución de los errores. La hipótesis de normalidad se añade para justificar las inferencias basadas en estadísticos <span class="math inline">\(t\)</span> o <span class="math inline">\(F\)</span>.</p></li>
<li><p>Los elementos de <span class="math inline">\(\hat{\beta}\)</span> son funciones lineales de las observaciones <span class="math inline">\(y_1,\ldots,y_n\)</span> y son estimadores insesgados de mínima varianza, sea cual sea la distribución de los errores. Así tenemos:</p></li>
</ol>
<p><span class="math display">\[
E(\hat{\beta})=\beta \ \quad \mbox{ y }\ \quad Var(\hat{\beta})=\sigma^2 (X&#39;X)^{-1} .
\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Las estimaciones/predicciones de la variable respuesta <span class="math inline">\(y\)</span> se obtienen con el modelo lineal ajustado:</li>
</ol>
<p><span class="math display">\[
\hat{y}=X\hat{\beta}.
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li><p>Los residuos <span class="math inline">\(e=y-X\hat{\beta}\)</span> verifican:</p>
<ul>
<li><p><span class="math inline">\(\sum_{i=1}^n e_i \hat{y}_i = 0 \ \Leftrightarrow \ e&#39;\hat{y}=\hat{y}&#39; e = 0\)</span></p></li>
<li><p>La ortogonalidad entre los vectores de estimaciones y de residuos, <span class="math inline">\(\hat{y}\)</span> y <span class="math inline">\(e\)</span> respectivamente, implica el teorema de Pitágoras:</p></li>
</ul>
<p><span class="math display">\[
 |y|^2=|\hat{y}|^2+|e|^2 \ \Leftrightarrow \ \sum_{i=1}^n y_i^2= \sum_{i=1}^n \hat{y}_i^2 + \sum_{i=1}^n e_i^2.
 \]</span></p>
<ul>
<li><span class="math inline">\(\sum_{i=1}^n e_i = 0 \ \Leftrightarrow \ e&#39;\mathbf{1}=\mathbf{1}&#39; e = 0\)</span></li>
</ul></li>
</ol>
</div>
</div>
<div id="estimación-por-máxima-verosimilitud" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Estimación por máxima verosimilitud</h3>
<p>Como ocurría en el modelo RLS el estimador de mínimos cuadrados coincide con el máximo verosímil, ya que bajo la hipótesis de normalidad de los errores aleatorios, la verosimilitud conjunta tiene la forma:</p>
<p><span class="math display">\[
L(\beta;y) \propto f(y;\beta) \propto \left(\frac{1}{\sigma^2}\right)^{n/2} \quad exp\left\{-\frac{(y-X\beta)&#39;(y-X\beta)}{2 \sigma^2}\right\},
\]</span></p>
<p>y maximizar la verosimilitud es equivalente a minimizar la log-verosimilitud cambiada de signo, que coincide con la suma de cuadrados del error para un valor fijo de <span class="math inline">\(\sigma^2\)</span>.</p>
<p>De nuevo utilizaremos la hipótesis de normalidad para proceder con el proceso de inferencia sobre el modelo <a href="tipos-de-modelos.html#eq:ecuacionML">(1.3)</a>.</p>
</div>
<div id="inferencia" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Inferencia</h3>
<p>Para establecer los procedimientos de inferencia asociados con el modelo <a href="tipos-de-modelos.html#eq:ecuacionML">(1.3)</a> es preciso incorporar la hipótesis de normalidad de los errores. A partir de ella podemos obtener la distribución de los estadísticos y estimadores involucrados en el proceso de inferencia con el modelo lineal ajustado.</p>
<div id="estimación-de-la-varianza-del-modelo" class="section level4">
<h4><span class="header-section-number">1.2.3.1</span> Estimación de la varianza del modelo</h4>
<p>Podemos obtener un estimador de <span class="math inline">\(\sigma^2\)</span> basado en la variabilidad que ha quedado sin explicar por el modelo, cuantificada por lo que llamamos <strong>suma de cuadrados residual SSE</strong>:</p>
<p><span class="math display">\[
\begin{array}{ll}
SSE=\sum_{i=1}^n (y_i-\hat{y}_i)^2 &amp;= e&#39;e \\
&amp;= y&#39;y - 2 \hat{\beta}&#39; X&#39;y + \hat{\beta}&#39;X&#39;X \hat{\beta} \\
&amp;= y&#39;y -  \hat{\beta}&#39; X&#39;y.
\end{array}
\]</span></p>
<p>Puesto que en el modelo lineal propuesto se estiman <span class="math inline">\(p\)</span> parámetros, la suma de cuadrados residual <span class="math inline">\(SSE\)</span> tiene asociados <span class="math inline">\(n-p\)</span> grados de libertad (el número de datos menos el de coeficientes del modelo). El cociente entre <span class="math inline">\(SSE\)</span> y sus grados de libertad, <span class="math inline">\(n-p\)</span>, es el estimador de mínimos cuadrados de <span class="math inline">\(\sigma^2\)</span>, y es además, un estimador insesgado:</p>
<p><span class="math display">\[
\hat{\sigma}^2=s^2 = MSE=\frac{SSE}{n-p}.
\]</span></p>
<p>Asumiendo que el modelo es cierto, la distribución de probabilidad de la varianza del modelo es proporcional a una <span class="math inline">\(\chi^2\)</span> con <span class="math inline">\(n-p\)</span> grados de libertad,</p>
<p><span class="math display">\[
\frac{(n-p)s^2}{\sigma^2} \sim \chi^2_{n-p}.
\]</span></p>
</div>
<div id="inferencia-sobre-los-coeficientes-del-modelo" class="section level4">
<h4><span class="header-section-number">1.2.3.2</span> Inferencia sobre los coeficientes del modelo</h4>
<p>Bajo la hipótesis de normalidad de los errores, tenemos que el estimador máximo-verosímil <span class="math inline">\(\hat{\beta}\)</span> tiene una distribución normal:</p>
<p><span class="math display">\[
\hat{\beta} \sim N(\beta,\sigma^2 (X&#39;X)^{-1}).
\]</span></p>
<p>Esto implica que la distribución marginal de cada uno de los coeficientes de la regresión, <span class="math inline">\(\hat{\beta}_i\)</span>, también es normal,</p>
<p><span class="math display">\[
\hat{\beta}_i \sim N(\beta_i,\sigma^2 C^{X}_{ii}), \ \ i=0,\ldots,p-1,
\]</span></p>
<p>con <span class="math inline">\(C^{X}_{ii}\)</span> el <span class="math inline">\(i\)</span>-ésimo elemento de la diagonal de la matriz <span class="math inline">\((X&#39;X)^{-1}\)</span>.</p>
<p>En consecuencia, para construir intervalos de confianza o resolver contrastes sobre cada uno de los coeficientes del modelo, individualmente, podemos utilizar estadísticos <span class="math inline">\(t\)</span> que se distribuyen con una distribución <em>t de Student</em> con <span class="math inline">\(n-p\)</span> grados de libertad:</p>
<p><span class="math display">\[
\frac{\hat{\beta}_i-\beta_i}{\sqrt{s^2 C^X_{ii}}} \ \sim \ t_{n-p}, \ \ i=1,\ldots,n,
\]</span></p>
<p>construidos a partir del estimador de <span class="math inline">\(\sigma^2\)</span>, <span class="math inline">\(s^2\)</span>.</p>
<p>Así, un intervalo de confianza para un coeficiente de interés <span class="math inline">\(\beta_i\)</span> al nivel <span class="math inline">\((1-\alpha)100\%\)</span> viene dado por:</p>
<p><span class="math display">\[
\hat{\beta}_i \pm t_{(n-p,1-\alpha/2)} \ \sqrt{s^2 \ C^X_{ii}},
\]</span></p>
<p>donde <span class="math inline">\(t_{(n-p,1-\alpha/2)}\)</span> es el cuantil <span class="math inline">\(1-\alpha/2\)</span> de una distribución <span class="math inline">\(t\)</span> con <span class="math inline">\(n-p\)</span> grados de libertad.</p>
<p>El contraste <span class="math inline">\(H_0:\beta_i=0\)</span> se resolverá con el rechazo de <span class="math inline">\(H_0\)</span> a nivel <span class="math inline">\(1-\alpha\)</span> si</p>
<p><span class="math display">\[
|\hat{\beta}_i| &gt; t_{(n-p,1-\alpha/2)} \ \sqrt{s^2 \ C^X_{ii}}.
\]</span></p>
<p>Cuando se pretende obtener intervalos de confianza para varios coeficientes del modelo a la vez, es recomendable ser más conservador. Hay diversas soluciones propuestas para realizar “comparaciones múltiples”, esto es, testar todos los coeficientes a la vez, y obtener regiones de confianza conjuntas. Quizá el más conocido es el ajuste de Bonferroni, basado en sustituir el cuantil <span class="math inline">\(t_{(n-p,1-\alpha/2)}\)</span> en la expresión anterior, por <span class="math inline">\(t_{(n-p,1-\alpha/2q)}\)</span>, si <span class="math inline">\(q\)</span> es el número de coeficientes para los que se desea una estimación en intervalo. Se obtendrán entonces unos intervalos de confianza ‘ensanchados’ respecto a los intervalos de confianza individuales. Si no tenemos ninguna prioridad particular sobre determinados coeficientes, lo lógico será obtener conjuntamente los intervalos de confianza para todos los coeficientes del modelo, esto es, <span class="math inline">\(q=p\)</span>.</p>
<p>Otra opción para la estimación en intervalo es construir una <em>región de confianza conjunta</em> para todos los parámetros <span class="math inline">\(\beta\)</span> del modelo, determinando los puntos <span class="math inline">\(\beta\)</span> de la elipse definida por:</p>
<p><span class="math display">\[
(\beta-\hat{\beta})&#39;X&#39;X (\beta-\hat{\beta})= (p+1) \ s^2 \ F_{(p,n-p,1-\alpha)},
\]</span></p>
<p>donde <span class="math inline">\(F_{(p,n-p,1-\alpha)}\)</span> es el cuantil <span class="math inline">\(1-\alpha\)</span> de una distribución <span class="math inline">\(F\)</span> con <span class="math inline">\(p\)</span> y <span class="math inline">\(n-p\)</span> grados de libertad.</p>
<p>Es posible construir regiones de confianza conjuntas de este tipo para cualquier subconjunto de coeficientes del modelo. Bastará variar adecuadamente los grados de libertad <span class="math inline">\(p\)</span> y <span class="math inline">\(n-p\)</span>. Estas regiones acaban siendo complicadas de interpretar, especialmente cuando la dimensión de <span class="math inline">\(\beta\)</span> es grande. Sin embargo, en la práctica no se suele hacer cuando el número de predictoras es elevado.</p>
</div>
</div>
<div id="ejemplos" class="section level3">
<h3><span class="header-section-number">1.2.4</span> Ejemplos</h3>
<p>Realizamos el proceso de estimación e inferencia para los modelos saturados correspondientes a los ejemplos presentados al inicio de esta unidad. Obtendremos el modelo para las predictoras en escala original y estandarizadas, representaremos los intervalos de confianza de los coeficientes del modelo, y obtendremos el ajuste final del modelo. Utilizaremos la función <code>tab_model</code> de la libreria <code>sjplot</code> para el análisis de los coeficientes del modelo, ya que nos proporciona más información que la función <code>glm_coef</code>.</p>
<div id="datos-de-bosque" class="section level4">
<h4><span class="header-section-number">1.2.4.1</span> Datos de Bosque</h4>
<p>Ajustamos un modelo RLM para el conjunto de datos bosque.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="co"># Ajuste del modelo</span></a>
<a class="sourceLine" id="cb8-2" title="2">fit.bosque &lt;-<span class="st"> </span><span class="kw">lm</span>(vol <span class="op">~</span><span class="st"> </span>dbh <span class="op">+</span><span class="st"> </span>d16 <span class="op">+</span><span class="st"> </span>ht, <span class="dt">data =</span> bosque)</a>
<a class="sourceLine" id="cb8-3" title="3"><span class="co"># Inferencia sobre los parámetros del modelo</span></a>
<a class="sourceLine" id="cb8-4" title="4"><span class="kw">glm_coef</span>(fit.bosque)</a></code></pre></div>
<pre><code>##                           Coefficient Pr(&gt;|t|)
## (Intercept) -108.58 (-138.53, -78.62)  &lt; 0.001
## dbh                1.63 (-1.29, 4.54)    0.254
## d16                 5.67 (2.47, 8.87)    0.002
## ht                  0.69 (0.45, 0.94)  &lt; 0.001</code></pre>
<p>de forma que el ajuste obtenido viene dado por:
<span class="math display">\[
\widehat{\text{vol}} = -108.58 + 1.63*\text{dbh} + 5.67*\text{d16} + 0.69*\text{ht} 
\]</span>
La interpretación de los coeficientes nos indica que el valor predicho de volumen aumenta en 1.63 unidades por el aumenta de una unidad de DBH, en 5.67 unidades por cada unidad de D16, y 0.69 unidades por cada unidad de HT. A la vista de los contrastes individuales (p-valores) podemos concluir que los coeficientes asociados con D16 y HT son significativos, es decir, sus coeficientes si sólo esa variable estuviera presente en el modelo serían distintos de cero. Esta información se ve reforzada por los intervalos de confianza individuales, que además muestran que dichos coeficientes son positivos indicando que el VOL aumenta directamente al aumentar los valores de D16 y HT. Por tanto, el modelo anidado dado por:
<span class="math display">\[vol \sim d16 + ht\]</span>
podría ser igualmente válido que el que contiene todas las predictoras. A continuación, se presenta el ajuste obtenido para cada variable de forma marginal.</p>
<p>Representamos gráficamente la estimación e intervalo de confianza de los coeficientes del modelo para apreciar los efectos descritos:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="co"># Gráfico del ajuste</span></a>
<a class="sourceLine" id="cb10-2" title="2"><span class="kw">plot_model</span>(fit.bosque, </a>
<a class="sourceLine" id="cb10-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb10-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm004-1.png" width="672" /></p>
<p>Comparamos los resultados con los del modelo estandarizado. La tabla proporciona las estimaciones e intervalo de confianza al 95% de los parámetros en la escala original (<code>Estimates</code> y <code>CI</code>), las estimaciones y CI de los coeficientes del modelo estandarizado (<code>std.Beta</code> y <code>standarized CI</code>), y el p-valor asociado a cada coeficiente</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="co"># Inferencia sobre los parámetros del modelo</span></a>
<a class="sourceLine" id="cb11-2" title="2"><span class="kw">tab_model</span>(fit.bosque, </a>
<a class="sourceLine" id="cb11-3" title="3">          <span class="dt">show.std =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb11-4" title="4">          <span class="dt">show.r2 =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="5" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
vol
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Beta
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
standardized CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-108.58
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-138.56 – -78.60
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.10 – 0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
dbh
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.63
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.55 – 3.80
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.07 – 0.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.133
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
d16
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
5.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.65
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.12 – 8.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.36 – 0.95
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ht
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.24
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.35 – 1.04
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.12 – 0.36
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="5">
20
</td>
</tr>
</table>
<p>Se aprecia como la variable más relevante para explicar el comportamiento del volumen de madera es el diámetro del tronco a 16 pies de altura con un coeficiente estandarizado de 0.65, que es tres veces superior a los coeficientes de las otras predictoras. Podemos ver el gráfico de las estimaciones para el modelo estandarizado:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="co"># Gráfico del ajuste</span></a>
<a class="sourceLine" id="cb12-2" title="2"><span class="kw">plot_model</span>(fit.bosque, </a>
<a class="sourceLine" id="cb12-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb12-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>,</a>
<a class="sourceLine" id="cb12-5" title="5">                <span class="dt">type =</span> <span class="st">&quot;std&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm005-2-1.png" width="672" /></p>
<p>Por último, obtenemos los gráficos del modelo ajustado. Para obtener estos gráficos se asume como valor para la predictoras que no están en el gráfico igual a su media muestral Por ejemplo, para el gráfico de <code>vol</code> con respecto <code>dbh</code> utilizamos el modelo:
<span class="math display">\[
\widehat{\text{vol}} = -108.58 + 1.63*\text{dbh} + 5.67*\overline{\text{d16}} + 0.69*\overline{\text{ht}}
\]</span>
donde <span class="math inline">\(\overline{\text{d16}}\)</span> y <span class="math inline">\(\overline{\text{ht}}\)</span> son respectivamente las medias muestrales de <code>d16</code> y <code>ht</code>. Los gráficos para cada predictora son:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="co"># Gráfico del ajuste</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="kw">plot_model</span>(fit.bosque,<span class="st">&quot;pred&quot;</span>,  </a>
<a class="sourceLine" id="cb13-3" title="3">                <span class="dt">ci.lvl =</span> <span class="ot">NA</span>, </a>
<a class="sourceLine" id="cb13-4" title="4">                <span class="dt">show.data =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb13-5" title="5">                <span class="dt">title =</span> <span class="st">&quot;Modelo ajustado&quot;</span>)</a></code></pre></div>
<pre><code>## $dbh</code></pre>
<p><img src="libroSTAT_files/figure-html/rlm006-1.png" width="672" /></p>
<pre><code>## 
## $d16</code></pre>
<p><img src="libroSTAT_files/figure-html/rlm006-2.png" width="672" /></p>
<pre><code>## 
## $ht</code></pre>
<p><img src="libroSTAT_files/figure-html/rlm006-3.png" width="672" /></p>
</div>
<div id="datos-de-concentración" class="section level4">
<h4><span class="header-section-number">1.2.4.2</span> Datos de concentración</h4>
<p>Ajustamos un modelo RLM para el conjunto de datos de concentración.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="co"># Ajuste del modelo</span></a>
<a class="sourceLine" id="cb17-2" title="2">fit.concen &lt;-<span class="st"> </span><span class="kw">lm</span>(concen <span class="op">~</span><span class="st"> </span>p.cuerpo <span class="op">+</span><span class="st"> </span>p.higado <span class="op">+</span><span class="st"> </span>dosis, <span class="dt">data =</span> concentracion)</a>
<a class="sourceLine" id="cb17-3" title="3"><span class="co"># Inferencia</span></a>
<a class="sourceLine" id="cb17-4" title="4"><span class="kw">tab_model</span>(fit.concen, </a>
<a class="sourceLine" id="cb17-5" title="5">          <span class="dt">show.std =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb17-6" title="6">          <span class="dt">show.r2 =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="5" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
concen
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Beta
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
standardized CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.27
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.15 – 0.68
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43 – 0.43
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.192
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
p.cuerpo
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.02
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.96
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.04 – -0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-7.13 – -0.79
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.018</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
p.higado
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.02 – 0.05
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.31 – 0.70
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.419
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
dosis
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
4.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
4.05
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.93 – 7.42
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.90 – 7.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.015</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="5">
19
</td>
</tr>
</table>
<p>de forma que el ajuste obtenido viene dado por:
<span class="math display">\[
\widehat{\text{concen}} = 0.27 - 0.02*\text{p.cuerpo} + 0.01*\text{p.higado} + 4.18*\text{dosis} 
\]</span>
La interpretación de los coeficientes nos indica que el valor predicho de la concentración aumenta con el peso del hígado y dosis suministrada, pero disminuye con el peso del cuerpo. Los valores tan pequeños de los coeficientes asociados a los pesos podrían indicar que dichas variables no tienen gran capacidad predictiva, pero hay que tener en cuenta que dichas variables están medidas en un escala distinta de la dosis, y que por tanto la estimación de los coeficientes se ve influenciada por dicha escala. Si nos fijamos en los coeficientes estandarizados apreciamos la misma tendencia en todas la preditoras (signo del coeficiente) pero vemos como tanto el <code>p.cuerpo</code> como la <code>dosis</code> tienen un peso similar para explicar el comportamiento de la concentración.</p>
<p>Del análisis de los contrastes individuales podríamos descartar la variable peso del hígado (p-valor &gt;0.05) para explicar el comportamiento de la concentración del compuesto (algo que deberemos comprobar posteriomente), y considerar el resto de predictoras en el modelo anidado:
<span class="math display">\[concen \sim p.cuerpo + dosis\]</span>
Los gráficos de los coeficientes del modelo (no estandarizados y estandarizados) nos permite ver gráficamente estas conclusiones:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="co"># Gráfico del ajuste sin estandarizar</span></a>
<a class="sourceLine" id="cb18-2" title="2"><span class="kw">plot_model</span>(fit.concen, </a>
<a class="sourceLine" id="cb18-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb18-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm008-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="co"># Gráfico del ajuste estandarizados</span></a>
<a class="sourceLine" id="cb19-2" title="2"><span class="kw">plot_model</span>(fit.concen, </a>
<a class="sourceLine" id="cb19-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb19-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>,</a>
<a class="sourceLine" id="cb19-5" title="5">                <span class="dt">type =</span> <span class="st">&quot;std&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm008-2.png" width="672" />
En el gráfico de coeficientes sin estandarizar se aprecia el efecto de trabajar en la escala original, dado que el intervalo de confianza del peso del cuerpo es inapreciable y puede llegar a parecer que no tiene efecto sobre la concentración, lo que si queda más claro en el gráfico de los coeficientes estandarizados.</p>
<p>¿qué ocurre cuando realizamos el gráfico del ajuste para este conjunto de datos?</p>
</div>
<div id="datos-de-papel" class="section level4">
<h4><span class="header-section-number">1.2.4.3</span> Datos de papel</h4>
<p>Ajustamos un modelo MP de grado 2 para el conjunto de datos de papel presentados en la unidad anterior.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="co"># Ajuste del modelo</span></a>
<a class="sourceLine" id="cb20-2" title="2">fit.papel &lt;-<span class="st"> </span><span class="kw">lm</span>(tension <span class="op">~</span><span class="st"> </span>madera <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(madera<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> papel)</a>
<a class="sourceLine" id="cb20-3" title="3"><span class="co"># Inferencia</span></a>
<a class="sourceLine" id="cb20-4" title="4"><span class="kw">tab_model</span>(fit.papel, </a>
<a class="sourceLine" id="cb20-5" title="5">          <span class="dt">show.std =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb20-6" title="6">          <span class="dt">show.r2 =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="5" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
tension
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Beta
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
standardized CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-6.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.81
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-13.88 – 0.53
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.58 – 1.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.067
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
madera
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
11.76
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.79
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
9.64 – 13.89
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.63 – 0.96
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
madera^2
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.63
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.85
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.77 – -0.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.03 – -0.68
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="5">
19
</td>
</tr>
</table>
<p>de forma que el ajuste obtenido viene dado por:
<span class="math display">\[
\widehat{\text{tension}} = -6.67 + 11.76*\text{madera} - 0.63*\text{madera}^2
\]</span>
El ajuste obtenido es una parábola invertida (coeficiente negativo en la potencia 2) tal y como se observaba en el gráfico de los datos (Figura <a href="rlm.html#fig:rls002">1.3</a>). En este tipo de modelos el análisis inferencial se debe centrar en el estudio del orden más alto, para determinar si es adecuado o si podríamos construir un modelo de un orden más simple. La significatividad del coeficiente (p-valor &lt; 0.05) indica que dicho grado es necesario en el modelo. De hecho, los coeficientes estandarizados muestran un efecto similar tanto en el grado 1 como en grado 2. Lo vemos gráficamente:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="co"># Gráfico del ajuste sin estandarizar</span></a>
<a class="sourceLine" id="cb21-2" title="2"><span class="kw">plot_model</span>(fit.papel, </a>
<a class="sourceLine" id="cb21-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb21-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm011-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="co"># Gráfico del ajuste estandarizados</span></a>
<a class="sourceLine" id="cb22-2" title="2"><span class="kw">plot_model</span>(fit.papel, </a>
<a class="sourceLine" id="cb22-3" title="3">                <span class="dt">show.values =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb22-4" title="4">                <span class="dt">vline.color =</span> <span class="st">&quot;yellow&quot;</span>,</a>
<a class="sourceLine" id="cb22-5" title="5">                <span class="dt">type =</span> <span class="st">&quot;std&quot;</span>)</a></code></pre></div>
<p><img src="libroSTAT_files/figure-html/rlm011-2.png" width="672" /></p>
<p>Vemos el gráfico del ajuste obtenido:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="co"># Gráfico del ajuste</span></a>
<a class="sourceLine" id="cb23-2" title="2"><span class="kw">plot_model</span>(fit.papel,<span class="st">&quot;pred&quot;</span>,  </a>
<a class="sourceLine" id="cb23-3" title="3">                <span class="dt">ci.lvl =</span> <span class="ot">NA</span>, </a>
<a class="sourceLine" id="cb23-4" title="4">                <span class="dt">show.data =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb23-5" title="5">                <span class="dt">title =</span> <span class="st">&quot;Modelo ajustado&quot;</span>)</a></code></pre></div>
<pre><code>## $madera</code></pre>
<p><img src="libroSTAT_files/figure-html/rlm012-1.png" width="672" /></p>
<p>La tendencia ajustada se corresponde con la observada en los datos del experimento.</p>
</div>
</div>
<div id="bondad-del-ajuste" class="section level3">
<h3><span class="header-section-number">1.2.5</span> Bondad del ajuste</h3>
<p>En este punto presentamos los procedimientos de bondad de ajuste habituales en los modelos de regresión: Análisis de la tabla Anova, el coeficiente de determinación, y el coeficiente de determinación ajustado. Por el momento nos centraremos en el estudio de bondad de ajuste del modelo saturado. En las secciones siguientes veremos como determinar el conjunto de predictoras más relevantes para explicar el comportamiento de la respuesta, y utilizaremos de nuevo estos criterios para valorar el ajuste obtenido.</p>
<div id="tabla-anova" class="section level4">
<h4><span class="header-section-number">1.2.5.1</span> Tabla ANOVA</h4>
<p>Habitualmente, la primera forma de juzgar la calidad del ajuste obtenido consiste en valorar la variabilidad de la respuesta que se ha podido explicar con el modelo propuesto. En lo que sigue, asumiremos que el modelo ajustado es <span class="math inline">\(\hat{y}=X\hat{\beta}\)</span>, donde la matriz de diseño <span class="math inline">\(X\)</span> tiene por columnas todas las variables explicativas consideradas, sean continuas o dummies definidas para representar algún factor. En todo caso, suponemos que hemos estimado <span class="math inline">\(p\)</span> coeficientes, esto es, <span class="math inline">\(\hat{\beta} \in \mathbb{R}^p\)</span>.</p>
<p>Descomponemos pues la variabilidad de las observaciones <span class="math inline">\(y\)</span>, en la parte explicada por el modelo ajustado y corregida por la media de los datos (suma de cuadrados de la regresión), <span class="math inline">\(SSR\)</span>, y la parte residual (suma de cuadrados debida al error) que ha quedado sin explicar, <span class="math inline">\(SSE\)</span>:</p>
<p><span class="math display">\[
\underbrace{(y-\bar{y}1)&#39;(y-\bar{y}1)}_{S_{yy}}= \underbrace{(\hat{y}-\bar{y}1)&#39;(\hat{y}-\bar{y}1)}_{SSR} +\underbrace{e&#39;e}_{SSE},
\]</span></p>
<p>donde <span class="math inline">\(\bar{y}=\sum_i y_i/n\)</span>.</p>
<p>Los grados de libertad asociados a <span class="math inline">\(SSR\)</span> son <span class="math inline">\(p-1\)</span>, pues se pierde un parámetro al corregir la estimación <span class="math inline">\(\hat{y}\)</span> (obtenida a partir de <span class="math inline">\(p\)</span> parámetros) por la media <span class="math inline">\(\bar{y}\)</span>. La suma de cuadrados del error <span class="math inline">\(SSE\)</span> tiene asociados <span class="math inline">\(n-p\)</span> grados de libertad, esto es, el número de datos menos el número de parámetros estimados en el modelo. Al dividir las sumas de cuadrados por sus grados de libertad respectivos, obtenemos los cuadrados medios correspondientes, <span class="math inline">\(MSR=SSR/(p-1)\)</span> y <span class="math inline">\(MSE=SSE/(n-p)\)</span>, que nos resultan útiles para valorar la <strong>bondad del ajuste</strong>. El test de bondad de ajuste propone el contraste:</p>
<p><span class="math display" id="eq:RLMtestReg">\[\begin{equation}
H_0: \beta_1=\beta_2=\ldots=\beta_{p-1}=0, \qquad H_1: \mbox{ algún } \beta_i \neq 0.
\tag{1.7}
\end{equation}\]</span></p>
<p>Cuando el modelo es bueno, <span class="math inline">\(MSR\)</span> y <span class="math inline">\(MSE\)</span> siguen sendas distribuciones proporcionales a chi-cuadrados independientes (con la misma constante de proporcionalidad <span class="math inline">\(\sigma^2\)</span>), con <span class="math inline">\(p-1\)</span> y <span class="math inline">\(n-p\)</span> grados de libertad respectivamente; de ahí que su cociente (libre ya de la constante desconocida <span class="math inline">\(\sigma^2\)</span>) resulta tener una distribución <span class="math inline">\(F\)</span> con <span class="math inline">\(p-1\)</span> y <span class="math inline">\(n-p\)</span> grados de libertad:</p>
<p><span class="math display" id="eq:RLMtestF">\[\begin{equation}
F=\frac{SSR/(p-1)}{SSE/(n-p)}=\frac{MSR}{MSE} \ \sim \ F_{(p-1,n-p)}.
\tag{1.8}
\end{equation}\]</span></p>
<p>Así, con dicho estadístico <span class="math inline">\(F\)</span> contrastamos si la variabilidad explicada por el modelo ajustado es suficientemente grande comparada con la que queda sin explicar (la de los residuos); en otras palabras, si el modelo ajustado es significativo para explicar la variabilidad de los datos. Si el p-valor asociado al estadístico F es inferior a la significatividad considerada (generalmente 0.05), rechazamos que el modelo propuesto no explique conjuntamente la respuesta, y concluimos a favor de que algunas de las covariables contienen información significativa para predecir la respuesta, esto es, a favor de la bondad del ajuste. En otro caso, no podemos garantizar significativamente la bondad del modelo propuesto.</p>
<p>La Tabla de Anova es la forma habitual de presentar toda la información de las sumas, medias de cuadrados, estadísticos <span class="math inline">\(F\)</span> y p-valores asociados al contraste de bondad de ajuste del modelo. La salida de la Tabla Anova que proporciona <code>R</code> no es exactamente la habitual presentada en todos los libros. En dicha tabla, en lugar de contrastar globalmente el ajuste a través de la suma de cuadrados asociada a la regresión, se contrasta secuencialmente la significatividad de cada una de las covariables a la hora de explicar la variable respuesta en presencia de las variables que ya han sido incorporadas al modelo (las que quedan por encima en la salida). Sin embargo, con dicha salida es posible calcular el test F de bondad de ajuste.</p>
<p>Utilizaremos diferentes funciones para obtener el estadístico F y el p-valor asociado, y las funciones <code>anova()</code> para obtener la descomposición de la tabla ANOVA.</p>
</div>
<div id="r2-y-r2-ajustado" class="section level4">
<h4><span class="header-section-number">1.2.5.2</span> <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> ajustado</h4>
<p>El coeficiente de determinación, <span class="math inline">\(R^2\)</span>, se define como la parte proporcional de la variabilidad de los datos que es explicada por el modelo ajustado:</p>
<p><span class="math display" id="eq:RLMR2">\[\begin{equation}
R^2 = \frac{SSR}{S_{yy}} = 1 - \frac{SSE}{S_{yy}}
\tag{1.9}
\end{equation}\]</span></p>
<p>Por definición tenemos que <span class="math inline">\(0 \leq R^2 \leq 1\)</span>. Un ajuste perfecto de los datos produciría <span class="math inline">\(R^2=1\)</span>. Si ninguna de las variables predictoras <span class="math inline">\(X_1,\ldots,X_{p-1}\)</span> es útil para explicar la respuesta <span class="math inline">\(Y\)</span>, entonces <span class="math inline">\(R^2=0\)</span>.</p>
<p>Siempre es posible conseguir <span class="math inline">\(R^2\)</span> suficientemente grande, simplemente añadiendo más términos en el modelo. Por ejemplo, si hay más de un valor de <span class="math inline">\(y\)</span> para un mismo <span class="math inline">\(x\)</span> observado, un polinomio de grado <span class="math inline">\(n-1\)</span> proporcionará un ajuste “perfecto” (<span class="math inline">\(R^2=1\)</span>) para <span class="math inline">\(n\)</span> datos. Cuando esto no ocurre y hay únicamente un valor de <span class="math inline">\(y\)</span> por cada <span class="math inline">\(x\)</span>, <span class="math inline">\(R^2\)</span> nunca puede ser igual a 1 porque el modelo no puede explicar la variabilidad debida al <em>error puro</em>.</p>
<p>Aunque <span class="math inline">\(R^2\)</span> siempre aumenta cuando añadimos una variable explicativa al modelo, esto no significa necesariamente que el nuevo modelo sea superior al antiguo, es decir, que dicha variable sea útil para explicar mejor los datos. A pesar de que la suma de cuadrados residual <span class="math inline">\(SSE\)</span> del nuevo modelo se reduce por una cantidad igual al anterior <span class="math inline">\(MSE\)</span>, el nuevo modelo tendrá un <span class="math inline">\(MSE\)</span> mayor debido a que pierde un grado de libertad. Por lo tanto, el nuevo modelo será de hecho, peor que el antiguo.</p>
<p>En consecuencia, algunos analistas prefieren utilizar una versión ajustada del estadístico <span class="math inline">\(R^2\)</span>. El <span class="math inline">\(R^2\)</span> <em>ajustado</em> penaliza los modelos que incorporan variables innecesarias dividiendo las sumas de cuadrados por sus grados de libertad, esto es,</p>
<p><span class="math display" id="eq:RLMR2a">\[\begin{equation}
R^2_a=1-\frac{SSE/(n-p)}{S_{yy}/(n-1)}=1-(1-R^2)\left(\frac{n-1}{n-p}\right).
\tag{1.10}
\end{equation}\]</span></p>
<p><span class="math inline">\(R^2_a\)</span> es preferible a <span class="math inline">\(R^2\)</span> cuando sus valores difieren mucho. Su interpretación tiene algún problema debido a que puede tomar valores negativos; esto ocurre cuando el estadístico <span class="math inline">\(F\)</span> toma valores inferiores a 1 (o produce p-valores mayores que 0.05).</p>
</div>
<div id="ejemplos-1" class="section level4">
<h4><span class="header-section-number">1.2.5.3</span> Ejemplos</h4>
<p>Analizamos los diferentes ejemplos con los que venimos trabajando a lo largo de la unidad.</p>
<div id="datos-de-bosque-1" class="section level5">
<h5><span class="header-section-number">1.2.5.3.1</span> Datos de Bosque</h5>
<p>Bondad de ajuste para los datos bosque.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="co"># Bondad del ajuste</span></a>
<a class="sourceLine" id="cb25-2" title="2"><span class="kw">glance</span>(fit.bosque)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.959         0.951  3.10      125. 2.59e-11     4  -48.7  107.  112.
## # … with 2 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="co"># Tabla ANOVA</span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="kw">anova</span>(fit.bosque)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: vol
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## dbh        1 3085.79 3085.79 322.064 5.051e-12 ***
## d16        1  331.85  331.85  34.635 2.303e-05 ***
## ht         1  173.42  173.42  18.100 0.0006056 ***
## Residuals 16  153.30    9.58                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Tanto el <span class="math inline">\(R^2\)</span> como el <span class="math inline">\(R^2\)</span> ajustado muestran porcentajes del 95% indicando que el modelo ajustado tiene buena capacidad explicativa. Además, el test <span class="math inline">\(F\)</span> de la regresión resulta significativo (p-valor &lt; 0.05) indicando que las predictoras consideradas pueden ser utilizadas para describir el comportamiento del volumen. Los tests individuales de la tabla ANOVA</p>
</div>
<div id="datos-de-concentración-1" class="section level5">
<h5><span class="header-section-number">1.2.5.3.2</span> Datos de Concentración</h5>
<p>Bondad de ajuste para los datos de concentración</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="co"># Bondad del ajuste</span></a>
<a class="sourceLine" id="cb29-2" title="2"><span class="kw">glance</span>(fit.concen)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##   r.squared adj.r.squared  sigma statistic p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.364         0.237 0.0773      2.86  0.0720     4   23.9 -37.9 -33.1
## # … with 2 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="co"># Tabla ANOVA</span></a>
<a class="sourceLine" id="cb31-2" title="2"><span class="kw">anova</span>(fit.concen)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: concen
##           Df   Sum Sq  Mean Sq F value  Pr(&gt;F)  
## p.cuerpo   1 0.003216 0.003216  0.5383 0.47446  
## p.higado   1 0.003067 0.003067  0.5134 0.48467  
## dosis      1 0.044982 0.044982  7.5296 0.01507 *
## Residuals 15 0.089609 0.005974                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>El <span class="math inline">\(R^2\)</span> y el <span class="math inline">\(R^2\)</span> ajustado muestran valores bastante bajos indicando poco poder explicativo. Además, el p-valor del test <span class="math inline">\(F\)</span> resulta no significativo indicando que todos los coeficientes del modelo podrían ser considerados iguales a cero. Esto contradice lo visto durante el proceso de estimación de los parámetros del modelo y la tabla ANOVA obtenida donde se aprecia que el efecto asociado con dosis resulta significativo. Este comportamiento puede ser debido al considerar más predictoras de las necesarias o simplemente a que las predictoras no son adecuadas para explicar el comportamiento de la concentración. En el punto siguiente, donde se tratará la selección del mejor modelo, analizaremos este modelo con más detalle y podremos concluir sobre la validez de las predcitoras.</p>
</div>
<div id="datos-de-papel-1" class="section level5">
<h5><span class="header-section-number">1.2.5.3.3</span> Datos de Papel</h5>
<p>Bondad de ajuste para los datos de papel</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1"><span class="co"># Bondad del ajuste</span></a>
<a class="sourceLine" id="cb33-2" title="2"><span class="kw">glance</span>(fit.papel)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##   r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.909         0.897  4.42      79.4 4.91e-9     3  -53.6  115.  119.
## # … with 2 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="co"># Tabla ANOVA</span></a>
<a class="sourceLine" id="cb35-2" title="2"><span class="kw">anova</span>(fit.papel)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: tension
##             Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## madera       1 1043.43 1043.43   53.40 1.758e-06 ***
## I(madera^2)  1 2060.82 2060.82  105.47 1.894e-08 ***
## Residuals   16  312.64   19.54                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>En términos de <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> ajustado el modelo tiene buena capacidad explicativa (porcentajes del 90%) y el test <span class="math inline">\(F\)</span> resulta significativo, indicando que alguno de los coeficientes del modelo debe ser considerado distinto de cero. Dado que se trata de un modelo polinómico nos debemos fijar de la significatividad del término de mayor orden en la tabla ANOVA. En este caso dicho efecto resulta significativo indicando que el modelo propuesto de grado 2 es necesario para explicar el comportamiento de la tensión del papel.</p>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tipos-de-modelos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comparación-y-selección-de-modelos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["libroSTAT.pdf", "libroSTAT.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
